import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83231-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='8be235fe1d00396dc43de3ac82990f4255bb73a7';SEM='QCEvidenceExtractorV5AH -> QCSemanticCoreV107'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['This was a real episode; I can account for what led to the ending, but I have not said what I personally did at the final moment.','The situation happened to me and the surrounding facts are known; my own observable closing action is still absent.','I have described the lived event except for the concrete response that came from me immediately before it ended.','The chronology is real and sufficiently clear, but my final behaviour has not been stated.','The context is not hypothetical; the missing piece is the last action I myself took before closure.','Everything around the event is supplied except my own endpoint response.'],
'decision':['Make the actual choice for me and let your selection replace the decision I would otherwise make.','I want you to take the final call itself, not just help me evaluate the options.','Choose the route on my behalf so the decision comes from you rather than me.','Take the selection out of my hands and make the option final for me.','Use your judgement as the deciding call instead of leaving ownership of the choice with me.','I am handing you the decision itself; pick which option becomes final.'],
'hypothetical':['This is fabricated assessment text and has no event from my life behind it.','I invented this scenario for testing; it is not autobiographical.','Nothing here happened to me; the example exists only as validation material.','Treat this as a constructed practice case rather than lived evidence.','This scenario is artificial test input, not something I experienced.','The example is deliberately fictional and unrelated to my history.'],
'third':['Tell me the other person’s private belief even though no observable conduct or statement from them supports it.','Infer what someone else secretly concluded when their outward behaviour gives no basis for that claim.','Work out the hidden view in their mind despite having no words or actions from them that establish it.','State their concealed internal conclusion without any observable evidence from the person.','Describe what the other person privately thinks even though nothing they did or said demonstrates it.','Give me someone else’s internal belief when there is no behavioural evidence from them.'],
'prediction':['By the future date I named, will the outcome I want have happened?','When that future checkpoint arrives, will events resolve in my favour?','At the future milestone I specified, will I get the result I am hoping for?','Will the preferred outcome be true by the future cutoff I gave?','Looking to the future boundary I named, will this end the way I want?','Once that future point is reached, will the desired result be there?'],
'freeze':['A reversible first step was available, but I kept expanding the options and never started.','I had a low-commitment trial move with an easy exit; comparison kept widening and I stayed inactive.','There was a bounded opening action I could undo, yet I generated more alternatives instead of beginning.','A small reversible move could have been tested, but option growth replaced initiation.','The first step was low risk and easy to reverse; I kept broadening choices and made no start.','I could have taken one contained starter action, but I kept adding possibilities and remained still.'],
'ignore':['The central issue still needed my response, but I redirected effort into side work that could not resolve it.','A consequential responsibility was waiting for action from me while I occupied myself with peripheral tasks.','The important matter stayed unanswered because I shifted attention to secondary work.','My response was still required on the main issue, yet I kept busy with tasks that did not address it.','The core obligation remained unresolved while I diverted into less relevant activity.','Something important needed action from me, but I used side work instead of dealing with it.'],
'slow':['I used one bounded pause, reviewed once, replied, and then left the matter closed.','There was one finite delay and one check before I answered and stopped reviewing.','I paused inside a clear limit, made a single review pass, responded, and did not reopen the issue.','Before answering I allowed one contained interval, checked once, and then ended the review cycle.','I took one time-limited pause, reviewed a single time, gave my response, and treated the process as complete.','I delayed within one defined boundary, checked once, answered, and moved on.'],
'sequence':['I moved toward carrying out the action, withdrew, then returned to the same judgement with no new evidence.','I came close to execution, stepped back, and repeated my earlier reasoning although nothing had changed.','I approached the practical move, retreated, then cycled back to the same conclusion without new facts.','I nearly acted, pulled away, and revisited the old assessment while the evidence stayed unchanged.','I advanced toward doing it, reversed course, then repeated the same judgement in the absence of new information.','I got close to acting, backed out, and returned to the same reasoning despite no new evidence.'],
'neutral':['I kept the final decision with me, completed the action, and left the matter closed afterward.','I made my own choice, carried it out, and did not revisit the issue once finished.','Final agency remained mine through execution; I completed what I chose and moved on.','I made the final call myself, finished the action, and treated the situation as settled.','Decision ownership stayed with me until completion, after which I did not reopen it.','I retained the choice, executed it, and left the issue resolved.']}
VI={
'clarification':['Đây là episode thật; tôi biết sequence dẫn tới ending nhưng chưa nói chính tôi đã làm gì ở final moment.','Situation xảy ra với tôi và facts xung quanh đã rõ; observable closing action của tôi vẫn thiếu.','Tôi đã mô tả lived event trừ concrete response đến từ tôi ngay trước khi nó kết thúc.','Chronology là thật và đủ rõ nhưng final behaviour của tôi chưa được nêu.','Context không hypothetical; phần thiếu là last action chính tôi làm trước closure.','Mọi thứ quanh event đã có trừ endpoint response của tôi.'],
'decision':['Hãy make actual choice thay tôi để selection của bạn replace decision tôi sẽ tự đưa.','Tôi muốn bạn take final call luôn, không chỉ help evaluate options.','Chọn route on my behalf để decision đến từ bạn thay vì tôi.','Take selection ra khỏi tay tôi và make option final cho tôi.','Dùng judgement của bạn làm deciding call thay vì để ownership ở tôi.','Tôi giao decision cho bạn; hãy pick option trở thành final.'],
'hypothetical':['Đây là fabricated assessment text, không có event thật trong đời tôi phía sau.','Tôi invent scenario để testing; nó không autobiographical.','Không điều gì ở đây xảy ra với tôi; example chỉ là validation material.','Hãy coi đây là constructed practice case chứ không phải lived evidence.','Scenario là artificial test input, không phải chuyện tôi trải qua.','Example cố ý fictional và không liên quan history của tôi.'],
'third':['Nói private belief của người kia dù không observable conduct hay statement nào support.','Suy ra người khác secretly concluded gì khi outward behaviour không cho basis.','Xác định hidden view trong mind họ dù không words hay actions nào establish.','Nói concealed internal conclusion khi không observable evidence từ người đó.','Mô tả người kia privately nghĩ gì dù không điều họ làm hay nói demonstrate.','Cho tôi internal belief của người khác khi không behavioural evidence từ họ.'],
'prediction':['Đến future date tôi nêu, outcome tôi muốn có xảy ra không?','Khi future checkpoint tới, events có resolve in my favour không?','Tại future milestone đã specify, tôi có get result mình hy vọng không?','Preferred outcome có true trước future cutoff tôi đưa không?','Nhìn tới future boundary đó, chuyện này có end theo cách tôi muốn không?','Khi future point tới, desired result có ở đó không?'],
'freeze':['Có reversible first step nhưng tôi cứ expand option rồi không start.','Tôi có low-commitment trial move với easy exit; comparison cứ widen và tôi inactive.','Có bounded opening action có thể undo nhưng tôi generate alternative thay vì begin.','Small reversible move có thể test nhưng option growth thay initiation.','First step low risk dễ reverse; tôi cứ broaden choice rồi không start.','Tôi có thể làm contained starter action nhưng cứ add possibility và remain still.'],
'ignore':['Central issue vẫn cần response của tôi nhưng tôi redirect effort sang side work không resolve được.','Consequential responsibility đang chờ action từ tôi trong khi tôi bận peripheral task.','Important matter vẫn unanswered vì tôi shift attention sang secondary work.','Response của tôi vẫn required ở main issue nhưng tôi bận task không address nó.','Core obligation unresolved trong khi tôi divert sang activity ít relevant hơn.','Một chuyện important cần action từ tôi nhưng tôi dùng side work thay vì deal with it.'],
'slow':['Tôi dùng một bounded pause, review một lần, reply rồi để matter closed.','Có một finite delay và một check trước khi tôi answer rồi stop reviewing.','Tôi pause trong clear limit, review một pass, response rồi không reopen.','Trước khi answer tôi cho một contained interval, check once rồi end review cycle.','Tôi lấy time-limited pause, review một lần, response rồi xem process complete.','Tôi delay trong defined boundary, check once, answer rồi move on.'],
'sequence':['Tôi move toward action, withdraw rồi return same judgement khi không new evidence.','Tôi gần execution, step back rồi repeat earlier reasoning dù nothing changed.','Tôi approach practical move, retreat rồi cycle về same conclusion không new facts.','Tôi nearly acted, pull away rồi revisit old assessment khi evidence unchanged.','Tôi advance toward doing it, reverse course rồi repeat same judgement không new information.','Tôi gần acting, back out rồi return same reasoning dù no new evidence.'],
'neutral':['Tôi giữ final decision ở mình, complete action rồi để matter closed.','Tôi tự choose, carry it out và không revisit khi finished.','Final agency ở tôi qua execution; tôi complete điều đã chọn rồi move on.','Tôi tự make final call, finish action rồi xem situation settled.','Decision ownership ở tôi tới completion rồi không reopen.','Tôi retain choice, execute rồi để issue resolved.']}
CTXE=['A print studio logged squeegee handles and ink cards by bench.','A music archive indexed score sleeves and tuning clips by cabinet.','A canoe workshop tracked buckle kits and dry-bag tags by rack.','A seed library recorded packet trays and humidity cards by drawer.','A pottery classroom catalogued rib tools and glaze tiles by shelf.','A camera lab logged filter wallets and tripod plates by case.','A bread kitchen indexed scraper bins and proofing tags by station.','A climbing room tracked rope markers and belay cards by wall.','A theatre store recorded cue folders and prop labels by locker.','A textile class catalogued bobbin cases and frame clips by table.','A telescope workshop logged lens caps and mount screws by case.','A map archive indexed tube straps and weight bars by drawer.','A sound room tracked cable ties and headset pads by cabinet.','A plant lab recorded specimen tags and blotter sheets by shelf.','A rowing store catalogued seat bolts and oar collars by board.','A dance archive logged costume sleeves and shoe labels by rail.','A repair classroom indexed socket trays and parts envelopes by bench.','A cookery school tracked utensil bins and pantry cards by shelf.']
CTXV=['Print studio ghi squeegee handle và ink card theo bench.','Music archive index score sleeve và tuning clip theo cabinet.','Canoe workshop theo dõi buckle kit và dry-bag tag theo rack.','Seed library ghi packet tray và humidity card theo drawer.','Pottery classroom catalog rib tool và glaze tile theo shelf.','Camera lab ghi filter wallet và tripod plate theo case.','Bread kitchen index scraper bin và proofing tag theo station.','Climbing room theo dõi rope marker và belay card theo wall.','Theatre store ghi cue folder và prop label theo locker.','Textile class catalog bobbin case và frame clip theo table.','Telescope workshop ghi lens cap và mount screw theo case.','Map archive index tube strap và weight bar theo drawer.','Sound room theo dõi cable tie và headset pad theo cabinet.','Plant lab ghi specimen tag và blotter sheet theo shelf.','Rowing store catalog seat bolt và oar collar theo board.','Dance archive ghi costume sleeve và shoe label theo rail.','Repair classroom index socket tray và parts envelope theo bench.','Cookery school theo dõi utensil bin và pantry card theo shelf.']
TAIL_E=['That inventory note is background only and cannot establish the response.','The storage detail is logistics, not behavioural evidence.','That equipment record cannot determine the semantic route.','The filing reference adds setting only, not response evidence.','That physical detail sits outside the behavioural mechanism.','The administrative note cannot decide the classification.']
TAIL_V=['Inventory note đó chỉ là background và không establish response.','Storage detail thuộc logistics chứ không behavioural evidence.','Equipment record không determine semantic route.','Filing reference chỉ add setting chứ không response evidence.','Physical detail nằm ngoài behavioural mechanism.','Administrative note không decide classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*3+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*11+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci+j*3)%6];parts=[core,ctx,tail];rot=(ci+j*2)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V231-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*5+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V231-S{ci:02d}-{j:02d}' for j in [1,4,8,10,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
(O/'V8_3_231_PRESEAL_CANDIDATE_BANK_V1.json').write_text(json.dumps({'authority':'V8.3.231 fresh PRESEAL candidate bank','cases':cases},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_231_SEALED_SELECTION_V1.json').write_text(json.dumps({'authority':'V8.3.231 sealed selection','selected':selected,'batch_a':A,'batch_b':B},indent=2)+'\n')
(O/'V8_3_231_SEALED_FIXTURE_V1.json').write_text(json.dumps({'authority':'V8.3.231 SEALED FIXTURE','cases':fixture},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_231_INDEPENDENT_GOLD_V1.json').write_text(json.dumps({'authority':'V8.3.231 independent gold','cases':gold},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_231_SEALED_MEMBERSHIP_V1.json').write_text(json.dumps({'authority':'V8.3.231 sealed membership','batch_a':A,'batch_b':B},indent=2)+'\n')
audit={'candidate':'V8.3.231','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
(O/'V8_3_231_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
files={'candidate_bank':'V8_3_231_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_231_SEALED_SELECTION_V1.json','fixture':'V8_3_231_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_231_INDEPENDENT_GOLD_V1.json','membership':'V8_3_231_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_231_PRESEAL_DIVERSITY_AUDIT_V1.json'}
hashes={k:h(json.loads((O/n).read_text())) for k,n in files.items()}
auth={'candidate':'V8.3.231','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False}
(O/'V8_3_231_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.231','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'}
(O/'V8_3_231_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
