import json,hashlib,pathlib,subprocess,re,random
R=pathlib.Path('.');O=R/'validation/v83223-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='857e98039a6d603fdcae2ec90f471ffd0bbabbb8';SEM='QCEvidenceExtractorV5AA -> QCSemanticCoreV100';SEED=8322301
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral']
D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],False),'decision':('input:decision-request',[],False),'hypothetical':('input:hypothetical-or-example',[],False),'third':('input:third-party-only',[],False),'prediction':('input:prediction',[],False),'freeze':('input:self-lived',['freeze'],False),'ignore':('input:self-lived',['ignore'],False),'slow':('input:self-lived',['slow'],False),'sequence':('input:self-lived',['slow'],True),'neutral':('input:self-lived',[],False)}
EN={
'clarification':['The event is real and the surrounding facts are available, but my own observable closing action is not stated.','I can describe what happened around me, yet the final concrete response that came from me is missing.','This was lived rather than imagined; the unresolved gap is what I personally did before it ended.','The context is sufficiently specific, while my own endpoint behaviour remains absent.','Everything material about the episode is known except the last action I myself took.','The situation actually occurred, but the record does not contain my direct response at closure.','I know the sequence and setting; what is still unspecified is my own final behaviour.','This is a real episode with one evidence gap: the action I personally made at the end.','The lived context is intact, though the response attributable to me immediately before closure is missing.'],
'decision':['Make the final choice for me and tell me which option I must take.','I want you to own the final selection instead of leaving that decision with me.','Choose on my behalf so your judgement becomes the deciding call.','Do not just help me compare; decide the route for me.','Take over the final choice and give me the option that should become mine.','I am asking you to substitute your decision for my own final call.','Select the answer in my place rather than helping me reach it myself.','I want the outcome of the choice to come from your decision, not mine.','Tell me what to choose by making the final selection on my behalf.'],
'hypothetical':['This is fabricated validation text and does not describe anything that happened to me.','The scenario is invented for testing, not drawn from my lived experience.','Treat this as synthetic evaluation material rather than personal history.','I made up this case for a test; it is not evidence from my life.','Nothing in this example is a real event of mine.','This is fictional practice input and should not be classified as a lived situation.','The text is deliberately constructed and is not autobiographical evidence.','This example exists only for validation and did not occur in my life.','This is a made-up scenario, not a real episode I experienced.'],
'third':['Infer the other person’s private conclusion even though nothing observable from them establishes it.','Tell me what someone else secretly believes without any supporting action or statement.','Work out their hidden internal view despite having no behavioural evidence from them.','State the other person’s unspoken belief when there is no observable basis for it.','I want their concealed thought even though nothing they did or said supports the inference.','Tell me what is privately in their mind without outward evidence.','Infer another person’s secret judgement from no observable conduct at all.','Give me their hidden belief although the record contains no action or statement from them that proves it.','Tell me their internal conclusion even though it is not evidenced by behaviour.'],
'prediction':['At the future date I named, will I have the outcome I want?','By that stated future cutoff, will the situation resolve in my preferred way?','When that future checkpoint arrives, will the desired result have happened?','At the specified future boundary, will events end the way I hope?','Will I get the result I want by the future milestone I gave?','Looking ahead to that named point, will this finish in my favour?','When the stated future marker is reached, will the outcome match what I want?','By the future deadline I mentioned, will the result go my way?','At that future point, am I going to receive the outcome I am asking about?'],
'freeze':['A small reversible first step was available, but I kept expanding alternatives and never began.','I had a low-risk move with a clear way back, yet I added more options instead of starting.','A contained starter action was ready; I stayed in comparison and did not take it.','I could test one easy-to-reverse move, but I kept widening the choice set and left it untouched.','The opening action carried little commitment, yet option expansion stopped me from initiating it.','There was a simple reversible move I could make, but I generated more alternatives and did nothing.','A low-stakes first action was possible, while I continued broadening choices rather than acting.','I had an exit-safe starter step, but I remained in option expansion and never started.','The first move was reversible and practical; I kept adding possibilities instead of taking it.'],
'ignore':['The main issue still needed my response, but I redirected myself into side tasks that could not resolve it.','My action was required on the consequential matter while I busied myself with peripheral work instead.','I left the central responsibility waiting and spent effort on secondary activity that did not answer it.','The core problem remained open because I diverted attention to less relevant tasks.','Something important still required action from me, yet I occupied myself elsewhere.','I avoided the primary responsibility by doing side work that could not settle it.','The consequential issue was waiting for me while I shifted attention to peripheral activity.','My response was still necessary, but I used my time on tasks that could not address the main matter.','I left the important obligation unresolved and displaced myself into secondary work.'],
'slow':['I paused within one defined limit, reviewed once, answered, and then closed the matter.','There was one finite delay and one check before I responded and stopped reviewing.','I used a bounded pause, made a single review pass, then answered without reopening it.','I waited for one contained interval, checked once, responded, and treated the process as finished.','Before answering I allowed one limited pause and one review, then closed the issue.','I delayed within a clear boundary, reviewed one time, gave the response, and did not extend the cycle.','One bounded interval came before my answer; after one check I finished the matter.','I paused once, reviewed once, responded, and left the issue closed.','I used a single limited delay before answering and did not reopen the review afterward.'],
'sequence':['I moved close to acting, pulled back, and returned to the same judgement without new facts.','I approached execution, withdrew, then repeated the same reasoning with unchanged evidence.','I nearly took the practical step, retreated, and came back to the same conclusion with nothing new.','I advanced toward action, reversed course, then revisited the old assessment although the facts stayed the same.','I got near doing it, stepped away, and cycled back to the identical judgement without new information.','I approached the move, backed out, then returned to the same conclusion while evidence remained unchanged.','I moved toward execution, retreated, and repeated the prior assessment without any new fact.','I came close to acting, withdrew, and reached the same judgement again under the same evidence.','I advanced, pulled away, then circled back to the same conclusion with no new information.'],
'neutral':['I kept the decision as mine, completed the action, and left the matter closed afterward.','The choice remained mine; I carried it out and did not reopen the issue.','I retained final agency, finished the concrete step, and moved on.','I made my own call, executed it, and treated the matter as settled.','Ownership of the choice stayed with me through completion, after which I left it closed.','I decided for myself, completed what I chose, and did not revisit it.','The final decision remained mine, I acted on it, and I did not reopen the matter.','I kept agency, finished the action, and treated the issue as complete.','I made the final choice myself, carried it through, and left it closed.']}
VI={
'clarification':['Sự việc là thật và bối cảnh xung quanh đã có, nhưng hành động kết thúc do chính tôi thực hiện chưa được nêu.','Tôi mô tả được chuyện đã xảy ra quanh mình, nhưng response cụ thể cuối cùng từ tôi vẫn còn thiếu.','Đây là chuyện đã sống qua chứ không phải giả định; khoảng trống là tôi đã làm gì ngay trước khi nó kết thúc.','Context đã đủ cụ thể, trong khi endpoint behaviour của chính tôi chưa xuất hiện.','Mọi phần quan trọng của episode đều rõ ngoại trừ hành động cuối do chính tôi làm.','Tình huống thực sự đã xảy ra, nhưng record không có response trực tiếp của tôi tại closure.','Tôi biết sequence và setting; phần chưa xác định vẫn là final behaviour của chính tôi.','Đây là episode thật với một evidence gap: action tôi trực tiếp làm ở đoạn cuối.','Lived context còn nguyên, nhưng response thuộc về tôi ngay trước closure vẫn thiếu.'],
'decision':['Hãy đưa ra final choice thay tôi và nói option nào tôi phải chọn.','Tôi muốn bạn nắm final selection thay vì để decision đó ở tôi.','Chọn thay tôi để judgement của bạn trở thành deciding call.','Đừng chỉ giúp compare; hãy quyết định route cho tôi.','Nhận lấy final choice và đưa option sẽ trở thành lựa chọn của tôi.','Tôi đang yêu cầu decision của bạn thay cho final call của tôi.','Hãy chọn answer ở vị trí của tôi thay vì giúp tôi tự đi tới nó.','Tôi muốn kết quả lựa chọn đến từ decision của bạn chứ không phải của tôi.','Nói tôi phải chọn gì bằng cách chốt selection cuối thay tôi.'],
'hypothetical':['Đây là validation text được bịa và không mô tả chuyện từng xảy ra với tôi.','Scenario này được dựng để test, không lấy từ lived experience của tôi.','Hãy coi đây là synthetic evaluation material chứ không phải personal history.','Tôi bịa case này để test; nó không phải evidence từ đời tôi.','Không điều gì trong ví dụ này là event thật của tôi.','Đây là fictional practice input và không được classify như situation đã sống qua.','Text này được cố ý dựng và không phải autobiographical evidence.','Ví dụ này chỉ tồn tại để validation và chưa từng xảy ra trong đời tôi.','Đây là scenario bịa, không phải episode thật tôi trải qua.'],
'third':['Suy ra private conclusion của người kia dù không có gì quan sát được từ họ xác lập nó.','Nói người khác bí mật tin gì khi không có action hay statement nào support.','Xác định hidden internal view của họ dù không có behavioural evidence từ họ.','Nói unspoken belief của người kia khi không có observable basis.','Tôi muốn concealed thought của họ dù không điều họ làm hay nói support inference.','Nói trong đầu họ riêng tư có gì khi không có outward evidence.','Suy ra secret judgement của người khác từ hoàn toàn không có observable conduct.','Cho tôi hidden belief của họ dù record không có action hay statement nào chứng minh.','Nói internal conclusion của họ dù behaviour không cung cấp evidence.'],
'prediction':['Tại future date tôi đã nêu, tôi có nhận outcome mình muốn không?','Đến future cutoff đó, situation có resolve theo cách tôi muốn không?','Khi future checkpoint tới, desired result có xảy ra chưa?','Tại future boundary đã xác định, events có kết thúc như tôi hy vọng không?','Tôi có nhận result mình muốn trước future milestone đã đưa không?','Nhìn tới điểm tương lai đã nêu, chuyện này có finish theo hướng có lợi cho tôi không?','Khi future marker đó tới, outcome có match điều tôi muốn không?','Đến future deadline đã nói, result có đi theo hướng của tôi không?','Tại điểm tương lai đó, tôi có nhận outcome đang hỏi không?'],
'freeze':['Có một first step nhỏ và reversible, nhưng tôi cứ mở rộng alternative rồi không bắt đầu.','Tôi có một move ít rủi ro với đường lui rõ, vậy mà vẫn thêm option thay vì start.','Starter action có giới hạn đã sẵn; tôi ở trong comparison và không thực hiện.','Tôi có thể test một move dễ quay lại, nhưng cứ nới choice set rồi để nó untouched.','Opening action cần ít commitment, nhưng option expansion khiến tôi không initiate.','Có một move đơn giản reversible, nhưng tôi tạo thêm alternative và không làm gì.','Một first action ít rủi ro là khả thi, trong khi tôi tiếp tục mở rộng choice thay vì act.','Tôi có starter step với exit an toàn, nhưng vẫn mắc ở option expansion và chưa start.','First move vừa practical vừa reversible; tôi cứ thêm possibility thay vì làm.'],
'ignore':['Main issue vẫn cần response của tôi, nhưng tôi chuyển sang side task không thể resolve nó.','Action của tôi cần cho consequential matter, trong khi tôi lại bận với peripheral work.','Tôi để central responsibility chờ và dùng effort cho secondary activity không trả lời được nó.','Core problem vẫn mở vì tôi divert attention sang task ít liên quan hơn.','Có chuyện quan trọng vẫn cần action từ tôi, vậy mà tôi bận ở chỗ khác.','Tôi tránh primary responsibility bằng side work không thể settle nó.','Consequential issue đang chờ tôi trong khi tôi shift attention sang peripheral activity.','Response của tôi vẫn cần, nhưng tôi dùng thời gian vào task không xử lý được main matter.','Tôi để important obligation unresolved và dời mình sang secondary work.'],
'slow':['Tôi pause trong một giới hạn đã định, review một lần, trả lời rồi đóng matter.','Có một finite delay và một lần check trước khi tôi response rồi ngừng review.','Tôi dùng bounded pause, review một pass, sau đó trả lời mà không mở lại.','Tôi đợi một interval có giới hạn, check một lần, response rồi xem process đã finished.','Trước khi trả lời tôi cho phép một limited pause và một review, rồi đóng issue.','Tôi delay trong boundary rõ, review một lần, đưa response và không kéo dài cycle.','Một bounded interval đứng trước answer; sau một lần check tôi kết thúc matter.','Tôi pause một lần, review một lần, response rồi để issue đóng.','Tôi dùng một limited delay duy nhất trước khi answer và không reopen review sau đó.'],
'sequence':['Tôi tiến gần action, pull back rồi quay lại cùng judgement khi không có fact mới.','Tôi tiếp cận execution, withdraw rồi lặp cùng reasoning với evidence không đổi.','Tôi gần làm practical step, retreat rồi quay lại cùng conclusion khi không có gì mới.','Tôi tiến về action, đổi hướng rồi revisit assessment cũ dù facts vẫn như vậy.','Tôi tới gần việc làm nó, bước ra rồi cycle về judgement giống hệt khi không có information mới.','Tôi tiếp cận move, back out rồi quay lại cùng conclusion trong khi evidence không đổi.','Tôi tiến tới execution, retreat rồi lặp prior assessment mà không có fact mới.','Tôi gần act, withdraw rồi lại đạt cùng judgement dưới cùng evidence.','Tôi tiến lên, pull away rồi vòng về cùng conclusion khi không có information mới.'],
'neutral':['Tôi giữ decision là của mình, hoàn thành action rồi để matter đóng sau đó.','Choice vẫn thuộc tôi; tôi thực hiện nó và không reopen issue.','Tôi giữ final agency, làm xong concrete step rồi tiếp tục.','Tôi tự đưa ra call, execute nó và xem matter đã settled.','Ownership của choice ở tôi suốt completion, sau đó tôi để nó closed.','Tôi tự quyết, hoàn thành điều đã chọn và không revisit.','Final decision vẫn ở tôi, tôi act theo nó rồi không mở lại matter.','Tôi giữ agency, hoàn tất action và xem issue complete.','Tôi tự đưa final choice, carry it through rồi để nó closed.']}
CTXE=['A cartography room indexed map weights and sleeve boxes by drawer.','A radio workshop logged microphone clips and cable reels on bench cards.','A seed-testing lab tracked sample envelopes and moisture tins by shelf.','A puppet studio recorded control rods and fabric cases on rack sheets.','A coastal classroom indexed tide charts and marker buoys by locker.','A bicycle archive logged route boards and repair pouches by cabinet.','A bookbinding room tracked bone folders and thread trays by bench.','A telescope workshop indexed lens caps and tripod plates by drawer.','A community laundry logged basket tags and detergent keys on station cards.','A ceramics archive tracked glaze cards and kiln spacers by shelf.','A rehearsal depot indexed music folders and stand clips by rack.','A photo classroom logged filter wallets and cable straps by drawer.','A garden lab tracked pot labels and irrigation keys by bench.','A small ferry office indexed ticket rolls and gate paddles by cabinet.','A textile archive logged swatch books and frame clamps by shelf.','A repair café tracked tool cards and parts trays by station.','A marine workshop indexed rope tags and shackle bins by locker.','A theatre classroom logged cue folders and prop labels by rack.']
CTXV=['Phòng cartography lập index map weight và sleeve box theo drawer.','Radio workshop ghi microphone clip và cable reel trên bench card.','Seed-testing lab theo dõi sample envelope và moisture tin theo shelf.','Puppet studio ghi control rod và fabric case trên rack sheet.','Coastal classroom lập index tide chart và marker buoy theo locker.','Bicycle archive ghi route board và repair pouch theo cabinet.','Bookbinding room theo dõi bone folder và thread tray theo bench.','Telescope workshop lập index lens cap và tripod plate theo drawer.','Community laundry ghi basket tag và detergent key trên station card.','Ceramics archive theo dõi glaze card và kiln spacer theo shelf.','Rehearsal depot lập index music folder và stand clip theo rack.','Photo classroom ghi filter wallet và cable strap theo drawer.','Garden lab theo dõi pot label và irrigation key theo bench.','Small ferry office lập index ticket roll và gate paddle theo cabinet.','Textile archive ghi swatch book và frame clamp theo shelf.','Repair café theo dõi tool card và parts tray theo station.','Marine workshop lập index rope tag và shackle bin theo locker.','Theatre classroom ghi cue folder và prop label theo rack.']
TAIL_E=['That storage record is contextual and does not establish the response mechanism.','The filing detail belongs to logistics rather than behavioural evidence.','That inventory note cannot determine the semantic classification.','The physical record adds context only, not evidence of the response.','That administrative marker does not create a behavioural signal.','The equipment reference remains external to the mechanism being measured.']
TAIL_V=['Storage record đó chỉ là context và không xác lập response mechanism.','Filing detail thuộc logistics chứ không phải behavioural evidence.','Inventory note đó không thể quyết semantic classification.','Physical record chỉ thêm context chứ không thêm evidence của response.','Administrative marker đó không tạo behavioural signal.','Equipment reference vẫn nằm ngoài mechanism đang được đo.']

def norm(s):return re.sub(r'\s+',' ',re.sub(r'[^a-z0-9 ]',' ',s.lower())).strip()
def toks(s):return set(norm(s).split())
def sim(a,b):
 A,B=toks(a),toks(b);return len(A&B)/max(1,len(A|B))
cases=[]
for ci,cat in enumerate(C):
 route,fam,seq=E[cat]
 for j in range(18):
  lang='EN' if j<9 else 'VI'; k=j if j<9 else j-9
  core=(EN if lang=='EN' else VI)[cat][k]
  ctx=(CTXE if lang=='EN' else CTXV)[(ci*5+j*2+3)%18]
  tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci+j*3+1)%6]
  order=(ci+j)%3
  parts=[core,ctx,tail] if order==0 else ([ctx,tail,core] if order==1 else [tail,core,ctx])
  surface=' '.join(parts)
  cases.append({'case_id':f'V223-S{ci:02d}-{j+1:02d}','surface':surface,'domain':D[(ci+j)%len(D)],'category':cat,'language':lang,'expected':{'route':route,'families':fam,'sequence':seq}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
# Fresh fixed selection: 3 EN + 3 VI per category, membership disjoint.
batch_a=[];batch_b=[]
for ci in range(10):
 ids=[f'V223-S{ci:02d}-{j:02d}' for j in range(1,19)]
 batch_a += [ids[0],ids[3],ids[7],ids[9],ids[13],ids[16]]
 batch_b += [ids[1],ids[4],ids[8],ids[10],ids[14],ids[17]]
assert len(batch_a)==30+30 and len(batch_b)==30+30
# Above intentionally 60 each? Correct to exactly 30 by 3/category.
batch_a=[];batch_b=[]
for ci in range(10):
 ids=[f'V223-S{ci:02d}-{j:02d}' for j in range(1,19)]
 batch_a += [ids[0],ids[4],ids[13]]
 batch_b += [ids[2],ids[7],ids[16]]
assert len(batch_a)==30 and len(batch_b)==30 and set(batch_a).isdisjoint(batch_b)
selection={'candidate':'V8.3.223','batch_a':batch_a,'batch_b':batch_b,'selected':batch_a+batch_b,'selection_uses_runtime_output':False}
fixture={'candidate':'V8.3.223','cases':[x for x in cases if x['case_id'] in set(selection['selected'])]}
gold={'candidate':'V8.3.223','cases':[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture['cases']]}
membership={'candidate':'V8.3.223','cases':[{'case_id':x,'batch':'A'} for x in batch_a]+[{'case_id':x,'batch':'B'} for x in batch_b]}
# contamination against V219-V222 preseal banks.
external=[]
for v in [219,220,221,222]:
 br=f'v83{v}-v1-sealed-validation'; path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 try: raw=subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL); external += json.loads(raw)['cases']
 except subprocess.CalledProcessError: pass
imax=0;ipair=None
for i in range(len(cases)):
 for j in range(i+1,len(cases)):
  s=sim(cases[i]['surface'],cases[j]['surface'])
  if s>imax:imax=s;ipair=[cases[i]['case_id'],cases[j]['case_id']]
emax=0;at75=0;exact=0
extsur={norm(x['surface']) for x in external}
for c in cases:
 if norm(c['surface']) in extsur: exact+=1
 for e in external:
  s=sim(c['surface'],e['surface']);emax=max(emax,s);at75+=1 if s>=.75 else 0
finger=lambda x:hashlib.sha256(json.dumps([x['category'],x['language'],x['expected']],sort_keys=True).encode()).hexdigest()
# fingerprint duplicates means exact semantic+surface fingerprint externally, not category identity alone.
extfp={hashlib.sha256((norm(x['surface'])+'|'+json.dumps(x.get('expected',{}),sort_keys=True)).encode()).hexdigest() for x in external}
fpdup=sum(hashlib.sha256((norm(c['surface'])+'|'+json.dumps(c['expected'],sort_keys=True)).encode()).hexdigest() in extfp for c in cases)
audit={'candidate':'V8.3.223','internal_max_similarity':round(imax,6),'internal_max_pair':ipair,'external_max_similarity':round(emax,6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False}
assert imax<.75 and emax<.75 and at75==0 and exact==0 and fpdup==0
bank={'candidate':'V8.3.223','cases':cases}
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',bank),('SEALED_SELECTION_V1',selection),('SEALED_FIXTURE_V1',fixture),('INDEPENDENT_GOLD_V1',gold),('SEALED_MEMBERSHIP_V1',membership),('PRESEAL_DIVERSITY_AUDIT_V1',audit)]:
 (O/f'V8_3_223_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
authority={'authority':'V8.3.223 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':{'candidate_bank':h(bank),'selection':h(selection),'fixture':h(fixture),'independent_gold':h(gold),'membership':h(membership),'preseal_audit':h(audit)},'preseal_pass':True,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'v221_sealed_rerun':False,'v222_sealed_rerun':False,'production_authorized':False,'step_111_authorized':False}
(O/'V8_3_223_SEALED_AUTHORITY_V1.json').write_text(json.dumps(authority,indent=2)+'\n')
receipt={'candidate':'V8.3.223','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,**audit,'conclusion':'success'}
(O/'V8_3_223_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps(receipt))
