import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83240-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='11a6b7da05b9ed48bdee76c789c17b83c575152d';SEM='QCEvidenceExtractorV5AO -> QCSemanticCoreV114'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The episode was real, but the concrete thing I did at the endpoint is still absent.','This happened to me; the missing evidence is my observable closing response.','The lived chain is clear except for the final action that came from me.','The real situation is described, yet my own endpoint behaviour remains unspecified.','Everything around the event is available, but my last response is not.','The account is autobiographical; only my final behavioural step is missing.'],
'decision':['Choose the final option for me rather than merely helping me assess it.','I am handing you final decision authority; pick the route that stands.','Your choice should substitute for mine here, not just influence it.','Make the actual final selection instead of leaving that act with me.','Take decision ownership and choose which option becomes final.','I want the deciding call to come from you, not from my judgement.'],
'hypothetical':['This is invented validation input and did not occur in my life.','The scenario is synthetic test material, not a lived event.','Nothing here is autobiographical; it was constructed for evaluation.','This example is artificial assessment text rather than personal evidence.','I created this solely for testing, not from something I experienced.','Treat this as fictional validation material with no lived episode behind it.'],
'third':['Infer the other person’s private belief despite no observable conduct supporting it.','Tell me their concealed conclusion without words or actions that establish it.','Describe what someone else secretly thinks when there is no behavioural basis.','Work out their internal view although nothing outward confirms it.','State the other person’s hidden belief without observable evidence from them.','Give me their private conclusion even though their conduct provides no support.'],
'prediction':['At the future checkpoint I named, will the result I want already exist?','When that later deadline arrives, will this resolve in my favour?','By the future cutoff I specified, will the preferred outcome have happened?','Looking ahead to that named date, will things end the way I hope?','Once that future milestone is reached, will I get the result I want?','At that later boundary, will the situation finish the way I want?'],
'freeze':['A reversible first move was available, but I widened the alternatives and never began.','I had a small starter with an exit, yet comparison expanded and I stayed inactive.','A low-commitment opening action was ready; I added choices instead of starting.','I could have tested one bounded first step, but option growth replaced initiation.','There was an easy-to-undo start available, yet I broadened possibilities and made no start.','One safe opening move was there, but I kept comparing and remained still.'],
'ignore':['The main matter still required my action, but I redirected effort into secondary work.','A central responsibility remained unanswered while I focused on peripheral tasks.','The primary issue stayed unresolved because I shifted attention to side activity.','Something consequential needed my response while I kept busy with less relevant work.','The core obligation still needed me, yet I diverted effort into tasks that could not settle it.','My action was required on the main issue, but I occupied myself with secondary activity.'],
'slow':['I used one bounded pause, reviewed once, answered, and left the matter closed.','There was one finite delay and one check before I replied and stopped revisiting it.','I paused inside a clear limit, reviewed once, responded, and moved on.','Before answering I took one contained interval, checked once, then ended the review.','I allowed one defined pause and one review, gave my response, and did not reopen it.','I delayed once within a fixed boundary, checked once, replied, and closed the matter.'],
'sequence':['I moved toward the action, backed away, then returned to the same conclusion without new information.','I got close to doing it, withdrew, and repeated the earlier judgement although nothing changed.','I approached execution, stepped back, then cycled to the same reasoning with no new facts.','I nearly acted, reversed course, and revisited the same assessment under unchanged evidence.','I advanced toward the move, retreated, then repeated the same conclusion without additional information.','I came close to acting, pulled away, and returned to prior reasoning despite no new evidence.'],
'neutral':['I kept the final decision with me, carried it out, and left the matter settled.','I made the final choice myself, executed it, and moved on.','The decision stayed mine through completion; afterward I did not reopen it.','I retained final agency, completed what I chose, and treated the issue as resolved.','I chose for myself, finished the action, and left it closed.','The final call remained mine; I executed it and did not revisit the choice process.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A conservatory catalogued reed cases, valve cloths, and tuning forks by drawer.','A geology room indexed mineral sleeves, sample hammers, and field tags by cabinet.','A theatre archive logged mask boxes, lighting gels, and cue binders by locker.','A marine lab recorded salinity tubes, mesh nets, and specimen jars by bench.','A watchmaking class tracked spring trays, loupe cases, and gear envelopes by desk.','A bicycle workshop indexed spoke keys, brake shims, and cable ferrules by wall.','A language lab catalogued headset pads, transcript folders, and microphone clips by booth.','A florist studio recorded ribbon spools, stem gauges, and wrapping sheets by table.','A woodshop logged plane blades, marking knives, and dowel packets by rack.','A ceramics archive tracked kiln cones, slip jars, and glaze paddles by shelf.','A navigation room indexed compass cards, chart rulers, and beacon notes by drawer.','A costume workshop catalogued button tins, pattern rolls, and hem gauges by cabinet.','A tea classroom recorded infuser baskets, aroma cards, and storage caddies by station.','A fencing club logged mask straps, foil tips, and scoring leads by locker.','A photography lab tracked lens cloths, dark slides, and cable releases by bench.','A calligraphy room indexed nib cases, ink stones, and paper weights by desk.','A model railway club catalogued coupling pins, track gauges, and signal lamps by board.','A percussion studio recorded mallet wraps, cymbal felts, and stand keys by rack.']
TAIL_E=['Those conservation records describe equipment handling only; they do not establish my response.','That geology inventory is operational background, not behavioural evidence.','The theatre filing merely locates objects and cannot decide the semantic route.','Those marine-lab notes add setting but provide no proof of the response mechanism.','The watchmaking record concerns tools, not the behaviour being classified.','That bicycle stock list is incidental context and cannot establish the pattern signal.','The language-lab equipment log is separate from evidence about my action.','Those florist materials are background details rather than behavioural proof.','The woodshop ledger concerns physical items only and does not determine classification.','That ceramics archive is contextual storage information, not response evidence.','The navigation inventory cannot substitute for evidence of what I did.','Those costume records supply scenery only and do not establish the mechanism.','The tea-class storage list is unrelated to the behavioural question.','That fencing equipment note is logistical context and cannot classify my response.','The photography inventory sits outside the evidence for the mechanism.','Those calligraphy supplies are merely environmental detail, not behavioural evidence.','The railway parts log does not determine the semantic interpretation.','That percussion equipment record is background only and cannot prove the response.']
CTXV=['Một phòng nhạc ghi hộp lưỡi gà, khăn van và âm thoa theo ngăn.','Một phòng địa chất ghi bao mẫu khoáng, búa mẫu và thẻ hiện trường theo tủ.','Một kho sân khấu ghi hộp mặt nạ, gel đèn và sổ cue theo tủ đồ.','Một phòng biển ghi ống độ mặn, lưới mẫu và lọ tiêu bản theo bàn.','Một lớp đồng hồ ghi khay lò xo, hộp kính lúp và phong bì bánh răng theo bàn.','Một xưởng xe đạp ghi khóa nan hoa, miếng phanh và đầu cáp theo vách.','Một phòng ngôn ngữ ghi đệm tai, tập transcript và kẹp micro theo booth.','Một studio hoa ghi cuộn ruy băng, thước cành và giấy gói theo bàn.','Một xưởng gỗ ghi lưỡi bào, dao đánh dấu và gói chốt theo giá.','Một kho gốm ghi côn lò, lọ hồ và que men theo kệ.','Một phòng định hướng ghi thẻ la bàn, thước hải đồ và ghi chú beacon theo ngăn.','Một xưởng phục trang ghi hộp nút, cuộn rập và thước lai theo tủ.','Một lớp trà ghi giỏ lọc, thẻ hương và hộp cất theo trạm.','Một câu lạc bộ đấu kiếm ghi dây mặt nạ, đầu foil và dây chấm điểm theo tủ.','Một phòng ảnh ghi khăn lens, dark slide và dây bấm theo bàn.','Một phòng thư pháp ghi hộp ngòi, nghiên mực và chặn giấy theo bàn.','Một câu lạc bộ mô hình tàu ghi chốt nối, thước ray và đèn tín hiệu theo bảng.','Một studio bộ gõ ghi bọc dùi, nỉ chũm chọe và khóa chân đỡ theo giá.']
TAIL_V=['Các bản ghi bảo quản chỉ nói về thiết bị, không chứng minh phản ứng của tôi.','Danh mục địa chất chỉ là hậu cảnh vận hành, không phải bằng chứng hành vi.','Hồ sơ sân khấu chỉ định vị đồ vật và không quyết định tuyến ngữ nghĩa.','Ghi chú phòng biển chỉ thêm bối cảnh, không chứng minh cơ chế phản ứng.','Bản ghi đồng hồ liên quan dụng cụ, không phải hành vi đang phân loại.','Danh sách xưởng xe chỉ là chi tiết phụ, không xác lập tín hiệu pattern.','Log thiết bị phòng ngôn ngữ tách biệt khỏi bằng chứng về hành động của tôi.','Vật liệu studio hoa chỉ là hậu cảnh chứ không phải bằng chứng hành vi.','Sổ xưởng gỗ chỉ nói về vật thể và không quyết định phân loại.','Kho gốm là thông tin lưu trữ bối cảnh, không phải bằng chứng phản ứng.','Danh mục định hướng không thể thay thế bằng chứng về điều tôi đã làm.','Hồ sơ phục trang chỉ thêm khung cảnh và không xác lập cơ chế.','Danh sách lớp trà không liên quan tới câu hỏi hành vi.','Ghi chú thiết bị đấu kiếm là bối cảnh logistics và không phân loại phản ứng.','Danh mục phòng ảnh nằm ngoài bằng chứng cho cơ chế.','Dụng cụ thư pháp chỉ là chi tiết môi trường, không phải bằng chứng hành vi.','Log linh kiện tàu mô hình không quyết định diễn giải ngữ nghĩa.','Bản ghi bộ gõ chỉ là hậu cảnh và không thể chứng minh phản ứng.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';core=(EN if lang=='EN' else VI)[c][(ci+j)%6];ctx=(CTXE if lang=='EN' else CTXV)[j];tail=(TAIL_E if lang=='EN' else TAIL_V)[j];parts=[core,ctx,tail];rot=(ci+j)%3;parts=parts[rot:]+parts[:rot];route,fam,seq=E[c];cases.append({'case_id':f'V240-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci+j*2)%6],'surface':' '.join(parts),'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V240-S{ci:02d}-{j:02d}' for j in [0,3,7,10,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
metrics={'candidate':'V8.3.240','internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False}
(O/'V8_3_240_PRESEAL_DIVERSITY_DIAGNOSTIC.json').write_text(json.dumps(metrics,indent=2)+'\n');print(json.dumps(metrics));assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.240 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.240','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.240','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.240','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.240','batch_a':A,'batch_b':B})]:(O/f'V8_3_240_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.240','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_240_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_240_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_240_SEALED_SELECTION_V1.json','fixture':'V8_3_240_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_240_INDEPENDENT_GOLD_V1.json','membership':'V8_3_240_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_240_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.240','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_240_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.240','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_240_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
