import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83240-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='11a6b7da05b9ed48bdee76c789c17b83c575152d';SEM='QCEvidenceExtractorV5AO -> QCSemanticCoreV114'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['This really happened, but the observable thing I did at the endpoint is still not stated.','The event is real and contextualised; only my concrete closing response is missing.','I can account for the lived sequence except the action I took at the very end.','The situation occurred in real life, yet my own final behaviour is not in the evidence.','The real episode is clear around me, but my endpoint action has not been supplied.','Everything about the lived context is present except what I personally did as it closed.'],
'decision':['Make the final selection for me rather than only helping me compare choices.','I am handing the decisive authority to you; choose the option that becomes final.','Your decision should replace mine here, not simply inform it.','Take the final choice out of my hands and decide the route itself.','I want the actual selection to come from you instead of from my judgement.','Own the deciding call and pick which option stands.'],
'hypothetical':['This is fabricated validation material and did not happen in my life.','The scenario exists for testing only and is unrelated to anything I experienced.','Nothing here is autobiographical; it is constructed evaluation input.','This example is artificial assessment text rather than lived evidence.','I made this scenario solely for validation, not from a real episode.','Treat this as synthetic practice material with no personal event behind it.'],
'third':['Infer the other person’s private belief even though no observable conduct supports it.','Tell me their hidden conclusion without words or actions that establish it.','Describe what the other person secretly thinks when there is no behavioural evidence.','Work out their internal position despite nothing outward confirming it.','State someone else’s concealed belief without any observable basis from them.','Give me the other person’s private view although their behaviour provides no support.'],
'prediction':['At the future point I named, will the outcome I want already have happened?','When that later deadline arrives, will this resolve the way I hope?','By the future cutoff I specified, will the preferred result be there?','Looking ahead to that named checkpoint, will the situation end in my favour?','Once that future boundary is reached, will I get the result I want?','At that later milestone, will things have finished the way I want?'],
'freeze':['A reversible opening move was available, but I expanded the alternatives and never began.','I had one small starter with an easy exit, yet comparison kept widening and I stayed still.','A low-commitment first action was ready; I added options instead of starting.','I could have tested one bounded opening step, but option growth replaced initiation.','There was a safe reversible start available, yet I broadened the choices and made no start.','One easy-to-undo first move was there, but I kept comparing and remained inactive.'],
'ignore':['The main issue still required my action, but I redirected effort into secondary tasks.','A central responsibility stayed unanswered while I occupied myself with peripheral work.','The primary matter remained unresolved because I shifted attention to side activity.','Something important waited for my response while I focused on less relevant work.','The core obligation still needed me, yet I diverted effort into tasks that could not settle it.','My action was still needed on the main issue, but I stayed busy with secondary activity.'],
'slow':['I used one bounded pause, reviewed once, answered, and left the matter closed.','There was one finite delay and one check before I replied and stopped revisiting it.','I paused within a clear limit, reviewed one time, responded, and moved on.','Before answering I took one contained interval, checked once, then ended the review.','I allowed one defined pause and one review, gave my response, and did not reopen it.','I delayed once inside a fixed boundary, checked once, replied, and closed the matter.'],
'sequence':['I moved toward the action, backed away, then returned to the same conclusion without new information.','I got close to doing it, withdrew, and repeated the earlier judgement although nothing changed.','I approached execution, stepped back, then cycled to the same reasoning with no new facts.','I nearly acted, reversed course, and revisited the same assessment under unchanged evidence.','I advanced toward the move, retreated, then repeated the same conclusion without additional information.','I came close to acting, pulled away, and returned to the prior reasoning despite no new evidence.'],
'neutral':['I kept the final decision with me, carried it out, and left the matter settled.','I made the final choice myself, executed it, and moved on.','The decision stayed mine through completion; afterward I did not reopen it.','I retained final agency, completed what I chose, and treated the issue as resolved.','I chose for myself, finished the action, and left it closed.','The final call remained mine; I executed it and did not revisit the choice process.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A print lab logged roller sleeves and ink tags by cabinet.','A rope room indexed sling cards and chalk labels by wall.','A greenhouse class tracked seed markers and mist valves by bay.','A ceramic studio recorded trimming tools and glaze tiles by bench.','A film room catalogued reel tins and cue cards by shelf.','A pastry lab logged proofing cards and scraper bins by station.','A rowing loft indexed oar clips and seat rails by rack.','A costume archive tracked garment sleeves and prop labels by locker.','A weaving room recorded shuttle trays and loom pins by table.','An observatory class catalogued lens caps and mount screws by case.','A survey room logged map tubes and straightedge blocks by drawer.','A sound booth indexed cable coils and ear pads by cabinet.','A herbarium room tracked specimen sleeves and blotter sheets by shelf.','A kayak store recorded paddle clips and seat straps by board.','A dance archive catalogued shoe pouches and garment tags by rail.','A repair bench logged socket trays and parts slips by bench.','A cookery room indexed utensil boxes and pantry cards by shelf.','A bindery room tracked thread cards and awl sleeves by drawer.']
CTXV=[x.replace('A ','Một ').replace('An ','Một ') for x in CTXE]
TAIL_E=['That inventory note is background only and cannot establish the response.','The storage detail is logistical context rather than behavioural evidence.','That equipment record cannot determine the semantic route.','The filing reference supplies setting only, not proof of the mechanism.','That physical record sits outside the behavioural evidence.','The administrative note cannot decide the classification.']
TAIL_V=['Inventory note đó chỉ là background, không establish response.','Storage detail là logistical context, không behavioural evidence.','Equipment record không determine semantic route.','Filing reference chỉ supply setting, không proof mechanism.','Physical record nằm ngoài behavioural evidence.','Administrative note không decide classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*4+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*11+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*2+j)%6];parts=[core,ctx,tail];rot=(ci*2+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V240-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*2+j*3)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V240-S{ci:02d}-{j:02d}' for j in [0,4,7,10,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
metrics={'candidate':'V8.3.240','internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False}
(O/'V8_3_240_PRESEAL_DIVERSITY_DIAGNOSTIC.json').write_text(json.dumps(metrics,indent=2)+'\n');print(json.dumps(metrics))
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.240 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.240','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.240','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.240','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.240','batch_a':A,'batch_b':B})]:(O/f'V8_3_240_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.240','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_240_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_240_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_240_SEALED_SELECTION_V1.json','fixture':'V8_3_240_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_240_INDEPENDENT_GOLD_V1.json','membership':'V8_3_240_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_240_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.240','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_240_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.240','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_240_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
