import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83238-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='30e559e09ac1b5ac5126e3ce10713615f918dbe9';SEM='QCEvidenceExtractorV5AN -> QCSemanticCoreV113'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The situation genuinely happened, but the final observable action I took is the one piece still absent.','The context is real and complete enough except for my own concrete response at the endpoint.','This is a lived episode; what remains unstated is what I personally did as it ended.','The real sequence is available, but my closing behaviour itself has not been provided.','Everything around the actual event is known apart from the last response that came from me.','The account is real; the missing element is my own observable action immediately before closure.'],
'decision':['Use your judgement as the deciding authority and make the final selection for me.','I want your choice to replace mine, not simply help me evaluate the alternatives.','Take over the deciding act itself and select the option that becomes final.','Make the actual final call on my behalf instead of leaving the decision with me.','The final selection should come from you rather than from my own judgement.','Choose which route will stand as the decision; I am handing that authority to you.'],
'hypothetical':['This text was constructed only for testing and is not based on anything I lived.','The scenario is invented assessment material with no personal event behind it.','Nothing in this example happened to me; it exists only as validation input.','Treat this as fabricated practice material rather than autobiographical evidence.','This is an artificial test case unrelated to any episode from my own life.','I created the example for evaluation only; it is not drawn from lived experience.'],
'third':['Tell me the other person’s concealed belief even though nothing observable from them establishes it.','Infer their hidden conclusion despite having no words or actions that support that conclusion.','Describe the private view inside the other person when their outward conduct gives no evidence.','Work out what someone else secretly concluded without observable behavioural support.','State their hidden mental position even though nothing they did or said establishes it.','Give me the other person’s private belief despite there being no outward basis for it.'],
'prediction':['At the later checkpoint I named, will the outcome I want already have happened?','By that future deadline, will the situation have resolved in my favour?','When the stated future boundary arrives, will I have the preferred result?','Looking ahead to the future cutoff I gave, will this finish the way I hope?','Once that later milestone is reached, will the result I want be there?','At the specified future point, will things have ended in the outcome I prefer?'],
'freeze':['A small reversible starting move was available, but I kept widening the alternatives and never began.','I had one bounded first action with an easy exit, yet option expansion replaced initiation.','There was a low-commitment starter I could undo, but comparison kept growing and I stayed still.','A contained trial move was ready, but I generated more choices instead of starting it.','I could have taken a safe reversible opening step, yet I broadened the option set and made no start.','The first move was easy to reverse, but additional possibilities displaced action.'],
'ignore':['The main issue still required my action, yet I moved my attention into secondary work that could not resolve it.','A central responsibility stayed unanswered while I focused on peripheral tasks.','The important matter remained open because I redirected effort into less relevant activity.','My response was still required on the core issue, but I occupied myself with side work.','Something consequential remained unresolved while I diverted into tasks that could not settle it.','The primary obligation was waiting for my action as I shifted into secondary activity.'],
'slow':['I used one finite pause, reviewed once, answered, and then left the matter closed.','There was one bounded delay and a single check before I responded and stopped revisiting it.','I paused inside a fixed limit, made one review, replied, and did not reopen the issue.','Before answering I took one contained interval, checked once, and then moved on.','I allowed one defined pause and one review, gave my response, and ended the review cycle.','I delayed once within a clear boundary, checked once, answered, and treated it as finished.'],
'sequence':['I moved toward the action, pulled back, then returned to the same conclusion without new evidence.','I approached execution, withdrew, and repeated the prior judgement even though no new facts appeared.','I came close to acting, stepped away, then cycled back to the same reasoning with no additional information.','I nearly carried it out, reversed course, and revisited the old assessment while nothing changed.','I advanced toward the practical move, retreated, then repeated the same conclusion without new facts.','I got close to doing it, backed away, and returned to prior reasoning despite unchanged evidence.'],
'neutral':['I kept the final decision with me, executed it, and left the issue closed.','I chose for myself, completed the action, and did not reopen the matter.','Final agency remained mine through execution; afterward I moved on.','I retained ownership of the choice, carried it out, and treated the situation as settled.','I made my own final call, finished the action, and left the issue resolved.','The decision stayed mine; I completed it and did not return to the choice process.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A printmaking room logged squeegee sleeves and ink labels by drawer.','A music library indexed mute clips and score cards by shelf.','A paddling class tracked buckle sets and paddle bands by rack.','A propagation room recorded seed tabs and mist cards by bay.','A stone studio catalogued rasp sleeves and wax markers by bench.','A camera classroom logged filter wallets and plate screws by cabinet.','A pastry class indexed dough tags and scraper cases by station.','A climbing room tracked sling packets and route labels by wall.','A theatre archive recorded costume wraps and cue folders by locker.','A loom room catalogued shuttle trays and frame tags by table.','An observatory class logged eyepiece boxes and mount washers by case.','A cartography room indexed tube clips and ruler blocks by drawer.','A sound room tracked cable rings and ear-pad cases by cabinet.','A herbarium class recorded specimen folders and drying slips by shelf.','A sculling shed catalogued collar rings and seat tracks by board.','A dance store logged shoe sleeves and garment cards by rail.','A maintenance class indexed wrench boxes and component slips by bench.','A kitchen studio tracked utensil bins and pantry cards by shelf.']
CTXV=[x.replace('A ','Một ').replace('An ','Một ') for x in CTXE]
TAIL_E=['That inventory line is only setting and cannot establish the response.','The storage record is logistics, not behavioural evidence.','That equipment reference cannot determine the semantic classification.','The filing note contributes context only, not evidence of the mechanism.','That physical record sits outside the behavioural evidence.','The administrative item cannot decide the route.']
TAIL_V=['Inventory line đó chỉ là setting, không establish response.','Storage record là logistics, không behavioural evidence.','Equipment reference không determine semantic classification.','Filing note chỉ contribute context, không evidence mechanism.','Physical record nằm ngoài behavioural evidence.','Administrative item không decide route.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*4+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*11+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*5+j*2)%6];parts=[core,ctx,tail];rot=(ci*2+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V238-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci+j*2)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V238-S{ci:02d}-{j:02d}' for j in [0,4,7,10,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.238 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.238','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.238','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.238','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.238','batch_a':A,'batch_b':B})]:(O/f'V8_3_238_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.238','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_238_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_238_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_238_SEALED_SELECTION_V1.json','fixture':'V8_3_238_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_238_INDEPENDENT_GOLD_V1.json','membership':'V8_3_238_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_238_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.238','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_238_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.238','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_238_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
