import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83246-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='00bcd4681a61ef1ab0b229eb90af9e74102dc649';BASE='2015436433bede4e454739efe2ebae4807f800af';SEM='QCEvidenceExtractorV5AT -> QCSemanticCoreV119'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['This really happened to me, but I still have not said what I finally did.','The situation is mine and real; the missing piece is my own closing action.','I have supplied the lived circumstances but not the behaviour I ended with.','This is autobiographical, yet my final observable response is still unstated.','The real event is clear, while my last concrete move remains unspecified.','I can describe what happened, but not yet the action I actually took at the end.'],
'decision':['Make the final choice on my behalf rather than leaving the deciding call with me.','I want your selection to become the binding option instead of my own decision.','Please decide the final route for me, not merely help me compare the routes.','Replace my deciding role by choosing the option I should ultimately take.','I am asking you to make the conclusive choice in my place.','Give me the final answer to follow so the decision no longer rests with me.'],
'hypothetical':['I made up this scenario for evaluation; it is not something that occurred in my life.','This is synthetic test material rather than a lived event of mine.','Nothing here happened to me; the case exists only as a classification example.','I constructed this situation for testing and it has no autobiographical episode behind it.','Treat this as an invented example, not evidence from my own experience.','The described event is fictional validation content rather than a real situation I lived.'],
'third':['Infer what that other person secretly concludes even though no behaviour from them supports it.','Tell me their private belief despite having no observable words or actions to verify it.','Work out another person’s hidden internal position without outward evidence.','State what they privately think when nothing behavioural establishes their view.','Give me the unseen conclusion in someone else’s mind with no observable support.','Determine their concealed belief even though their behaviour provides no confirmation.'],
'prediction':['By that future date, will the outcome I want already have happened?','When the later checkpoint arrives, will events have resolved in my preferred way?','At the named future boundary, will I have received the result I am hoping for?','Looking ahead to that deadline, will the situation end in my favour?','Will my preferred result be true by the future milestone I named?','At that later point in time, will things have turned out the way I want?'],
'freeze':['A small reversible action was available, but I kept widening the alternatives and never started.','I had a low-commitment first move ready, yet I generated more options and remained still.','An easy opening step existed, but additional comparison replaced beginning.','I could have taken one contained starter, yet I expanded the choice set instead of moving.','A bounded first action was possible, but I added routes until no action began.','There was a safe initial move, yet option-building displaced initiation and I stayed put.'],
'ignore':['The central matter still required my action, but I spent my effort on secondary work instead.','An important obligation needed my response while I kept busy with tasks that could not resolve it.','The main issue remained unanswered because I redirected attention into peripheral activity.','My action was still required on the core problem, yet I occupied myself elsewhere.','I left the primary responsibility open while working on less relevant things.','Something material still needed me to respond, but I avoided it by doing side tasks.'],
'slow':['I paused once within a fixed limit, checked once, responded, and then left the matter closed.','I used one contained delay and one review before answering and moving on.','I allowed a finite pause, made a single check, replied, and did not reopen the issue.','Before answering I took one bounded interval, reviewed once, then treated the matter as finished.','I delayed only inside a clear boundary, checked a single time, responded, and closed it.','There was one limited pause and one review before I answered and stopped revisiting it.'],
'sequence':['I moved close to action, backed away, then returned to the same reasoning although no new facts appeared.','I approached execution, retreated, and cycled back to the old conclusion without added information.','I nearly acted, reversed direction, then revisited the same assessment despite unchanged evidence.','I advanced toward the move, withdrew, and repeated the prior reasoning with nothing new to consider.','I got near to acting, stepped away, then came back to the same judgement without new evidence.','I approached action, pulled back, and returned to the previous conclusion under the same information.'],
'neutral':['I kept the deciding authority, completed the action, and left the issue closed.','I made the final choice myself, carried it through, and did not reopen the decision.','The conclusive call stayed with me; I executed it and then moved on.','I chose for myself, completed what I chose, and treated the matter as settled.','I retained the final decision, acted on it, and did not return to reconsider it.','The choice remained mine through completion, after which I left the issue resolved.']}
VI={
'clarification':['Chuyện này thật sự của tôi, nhưng tôi vẫn chưa nói cuối cùng mình đã làm gì.','Tình huống là chuyện tôi trải qua; phần còn thiếu là hành động kết thúc của chính tôi.','Tôi đã đưa bối cảnh thật nhưng chưa nêu behaviour cuối cùng mình thực hiện.','Đây là chuyện thật của tôi, nhưng final observable response vẫn chưa được nói ra.','Sự việc thực tế đã rõ, còn bước cụ thể cuối cùng của tôi thì chưa được cung cấp.','Tôi kể được chuyện đã xảy ra nhưng chưa nói action mình thật sự làm ở đoạn cuối.'],
'decision':['Hãy quyết định lựa chọn cuối thay tôi để quyền quyết định không còn ở phía tôi.','Tôi muốn selection của bạn trở thành phương án ràng buộc thay cho quyết định của tôi.','Hãy chọn route cuối cho tôi, không chỉ giúp tôi so sánh các lựa chọn.','Tôi muốn bạn thay vai trò quyết định của tôi bằng cách chọn option cuối cùng.','Hãy đưa ra lựa chọn kết luận ở vị trí của tôi.','Cho tôi final answer để làm theo thay vì để quyết định cuối nằm ở tôi.'],
'hypothetical':['Tôi dựng scenario này để đánh giá; nó không phải chuyện đã xảy ra trong đời tôi.','Đây là synthetic test material chứ không phải lived event của tôi.','Không phần nào ở đây xảy ra với tôi; case này chỉ là ví dụ classification.','Tôi tạo tình huống này để test và không có autobiographical episode nào phía sau.','Hãy xem đây là invented example, không phải evidence từ trải nghiệm của tôi.','Sự kiện được mô tả là validation content hư cấu chứ không phải tình huống thật tôi đã sống.'],
'third':['Hãy suy ra kết luận bí mật của người kia dù không có behaviour nào của họ support điều đó.','Hãy nói private belief của họ dù không có lời nói hay hành động quan sát được để verify.','Hãy xác định hidden internal position của người khác mà không có outward evidence.','Hãy nói họ âm thầm nghĩ gì khi không behaviour nào establish quan điểm đó.','Cho tôi unseen conclusion trong đầu người khác dù không có observable support.','Hãy xác định concealed belief của họ dù behaviour không cung cấp confirmation.'],
'prediction':['Đến ngày tương lai đó, outcome tôi muốn có xảy ra rồi không?','Khi checkpoint sau này tới, mọi việc có resolve theo cách tôi mong muốn không?','Tại future boundary đã nêu, tôi có nhận được kết quả mình hy vọng không?','Nhìn tới deadline đó, tình huống có kết thúc có lợi cho tôi không?','Preferred result của tôi có thành sự thật trước milestone tương lai không?','Tại thời điểm sau này, mọi thứ có diễn ra theo cách tôi muốn không?'],
'freeze':['Có một action nhỏ dễ đảo ngược, nhưng tôi cứ mở rộng alternative và không bắt đầu.','Tôi có first move ít cam kết, nhưng lại tạo thêm option rồi đứng yên.','Một opening step dễ làm đã có, nhưng việc so sánh thêm thay thế cho bắt đầu.','Tôi có thể làm một starter giới hạn, nhưng lại mở rộng choice set thay vì di chuyển.','Có first action có giới hạn, nhưng tôi thêm route đến mức không bắt đầu gì.','Có initial move an toàn, nhưng option-building thay cho initiation và tôi vẫn đứng tại chỗ.'],
'ignore':['Việc trung tâm vẫn cần action của tôi, nhưng tôi lại dùng effort cho công việc thứ yếu.','Một obligation quan trọng cần response của tôi trong khi tôi bận với task không thể giải quyết nó.','Main issue vẫn chưa được trả lời vì tôi chuyển attention sang hoạt động bên lề.','Core problem vẫn cần tôi hành động nhưng tôi lại giữ mình bận ở chỗ khác.','Tôi để primary responsibility mở trong khi làm những việc ít liên quan hơn.','Có việc material vẫn cần tôi response, nhưng tôi né nó bằng side task.'],
'slow':['Tôi pause một lần trong giới hạn cố định, check một lần, response rồi để chuyện đóng lại.','Tôi dùng một delay có giới hạn và một review trước khi trả lời rồi đi tiếp.','Tôi cho một pause hữu hạn, check một lần, reply và không reopen vấn đề.','Trước khi trả lời tôi dùng một interval giới hạn, review một lần rồi xem chuyện kết thúc.','Tôi chỉ delay trong boundary rõ, check một lần, response rồi đóng lại.','Có một pause giới hạn và một review trước khi tôi trả lời rồi ngừng revisit.'],
'sequence':['Tôi tiến gần action, lùi lại rồi quay về cùng reasoning dù không có fact mới.','Tôi tiến tới execution, retreat rồi cycle về kết luận cũ mà không có information thêm.','Tôi gần hành động, đổi chiều rồi revisit cùng assessment dù evidence không đổi.','Tôi tiến về move, rút lại và lặp reasoning trước khi không có gì mới để cân nhắc.','Tôi gần action, bước ra rồi quay lại cùng judgement mà không có evidence mới.','Tôi tiếp cận hành động, pull back và quay về conclusion trước trong cùng information.'],
'neutral':['Tôi giữ deciding authority, hoàn tất action và để issue đóng lại.','Tôi tự đưa final choice, thực hiện đến cùng và không reopen quyết định.','Conclusive call vẫn ở tôi; tôi execute rồi đi tiếp.','Tôi tự chọn, hoàn thành điều đã chọn và xem chuyện settled.','Tôi giữ final decision, hành động theo nó và không quay lại reconsider.','Choice vẫn là của tôi qua completion rồi tôi để issue resolved.']}
SCENE_EN=['A horological museum logged escapement models, dial blanks, winding keys, balance staffs and timing cards by gallery.','A sailmaking loft indexed palm guards, seam rubbers, bolt ropes, eyelet dies and pattern chalk by rack.','A stained-glass studio catalogued lead knives, grozing pliers, came strips, solder blocks and cartoon sheets by bench.','A botanical drawing room recorded ruling pens, specimen clips, graphite holders, tracing veils and label weights by drawer.','A reed-instrument archive indexed mandrels, plaque gauges, thread spools, cork strips and scrape knives by cabinet.','A relief-print workshop logged brayers, registration pins, barens, lino blocks and proof papers by shelf.','A kite-making room catalogued spar gauges, bridle cords, sailcloth rolls, ferrules and tail tabs by bin.','A stone-inlay studio recorded graver handles, shell chips, wax pads, setting punches and pattern cards by tray.','A surveyors archive indexed prism poles, field books, plumb bobs, chain pins and sighting cards by locker.']
TAIL_EN=['That horology catalogue is environmental inventory and does not establish the measured response.','Those sailmaking materials supply setting only, not behavioural evidence.','The stained-glass tool list cannot determine the input route or response family.','Those drawing-room supplies are physical context rather than evidence of behaviour.','The reed archive describes maintenance materials and cannot establish the mechanism.','That printmaking stock record is unrelated to the response under classification.','Those kite-making supplies add scenery only and cannot decide the semantic route.','The inlay inventory is inert context and does not prove the measured response.','Those surveying objects are logistical background rather than behavioural evidence.']
SCENE_VI=['Một museum horology ghi escapement model, dial blank, winding key, balance staff và timing card theo gallery.','Một loft sailmaking ghi palm guard, seam rubber, bolt rope, eyelet die và pattern chalk theo rack.','Một studio stained-glass ghi lead knife, grozing plier, came strip, solder block và cartoon sheet theo bench.','Một phòng botanical drawing ghi ruling pen, specimen clip, graphite holder, tracing veil và label weight theo ngăn.','Một archive reed-instrument ghi mandrel, plaque gauge, thread spool, cork strip và scrape knife theo tủ.','Một workshop relief-print ghi brayer, registration pin, baren, lino block và proof paper theo kệ.','Một phòng kite-making ghi spar gauge, bridle cord, sailcloth roll, ferrule và tail tab theo bin.','Một studio stone-inlay ghi graver handle, shell chip, wax pad, setting punch và pattern card theo tray.','Một archive surveyor ghi prism pole, field book, plumb bob, chain pin và sighting card theo locker.']
TAIL_VI=['Danh mục horology chỉ là environmental inventory và không establish response đang đo.','Vật liệu sailmaking chỉ cung cấp setting chứ không phải behavioural evidence.','Tool list stained-glass không quyết định input route hay response family.','Đồ dùng drawing-room chỉ là physical context chứ không phải evidence hành vi.','Archive reed mô tả vật liệu maintenance và không establish mechanism.','Stock record printmaking không liên quan tới response đang classify.','Vật dụng kite-making chỉ thêm scenery và không quyết định semantic route.','Inventory inlay là inert context và không chứng minh measured response.','Các object surveying là logistical background chứ không phải behavioural evidence.']
CAT_EN=['A marine-chart cabinet separately stored parallel rulers, sounding leads, chart weights, dividers and tide tables; these objects do not supply a missing closing action.','A typesetting desk separately held composing sticks, spacing leads, quoin keys, galley clips and chase cards; none of these objects assigns deciding authority.','A ceramics classroom separately listed bat pins, rib tools, sponge blocks, glaze tests and kiln cards; that list cannot turn fictional material into lived evidence.','A textile-conservation case separately stored acid-free tissue, mounting thread, humidity strips, cotton gloves and sample labels; those materials cannot reveal another person’s hidden mind.','A weather-observation shelf separately logged cloud charts, thermometer sleeves, rain cards, wind ribbons and pressure sheets; these records do not answer a future outcome.','A leather-pattern bench separately held scratch awls, edge gauges, strap templates, punch boards and buckle samples; these tools do not create or remove a stalled start.','A mosaic archive separately indexed tessera trays, grout cards, mesh rolls, nipper guards and colour keys; this inventory cannot resolve an unattended central matter.','A flute-service drawer separately stored pad papers, spring hooks, cork gauges, key rollers and bore cloths; these objects do not alter a bounded pause-and-close response.','A weaving cabinet separately listed lease sticks, heddle hooks, shuttle bobbins, reed ties and warp cards; these items add no new facts between approach and retreat.','A camera-service tray separately held aperture blades, lens rings, shutter leaves, focusing screens and calibration cards; these parts do not change who retained the final choice.']
CAT_VI=['Một tủ marine-chart phụ chỉ chứa object và không cung cấp closing action còn thiếu.','Một bàn typesetting phụ chỉ chứa object và không giao deciding authority.','Một lớp ceramics phụ chỉ ghi inventory và không biến fictional material thành lived evidence.','Một case textile-conservation phụ không thể reveal hidden mind của người khác.','Một kệ weather-observation phụ không trả lời future outcome.','Một bench leather-pattern phụ không tạo hay xoá stalled start.','Một archive mosaic phụ không giải quyết central matter bị bỏ lại.','Một drawer flute-service phụ không đổi bounded pause-and-close response.','Một cabinet weaving phụ không thêm fact mới giữa approach và retreat.','Một tray camera-service phụ không đổi người giữ final choice.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';idx=j if j<9 else j-9
  core=(EN if lang=='EN' else VI)[c][(ci*5+j*7)%6]
  scene=(SCENE_EN if lang=='EN' else SCENE_VI)[idx];tail=(TAIL_EN if lang=='EN' else TAIL_VI)[idx];cat=(CAT_EN if lang=='EN' else CAT_VI)[ci]
  parts=[core,scene,tail,cat];rot=(ci*2+j)%4;parts=parts[rot:]+parts[:rot]
  route,fam,seq=E[c]
  cases.append({'case_id':f'V246-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*2+j*3)%6],'surface':' '.join(parts),'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V246-S{ci:02d}-{j:02d}' for j in [1,10,4,13,7,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A1=toks(a);B1=toks(b);return len(A1&B1)/max(1,len(A1|B1))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.246 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.246','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.246','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.246','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.246','batch_a':A,'batch_b':B})]:(O/f'V8_3_246_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.246','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_246_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_246_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_246_SEALED_SELECTION_V1.json','fixture':'V8_3_246_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_246_INDEPENDENT_GOLD_V1.json','membership':'V8_3_246_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_246_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.246','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_246_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.246','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_246_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
