import json,hashlib,pathlib,subprocess,re,zipfile
R=pathlib.Path('.');O=R/'validation/v83222-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='8fd91bfd1e9abdc25b9af12a9494b8e2f14e9f16';SEM='QCEvidenceExtractorV5Z -> QCSemanticCoreV99'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The episode happened, and I know the surrounding facts, but I have not said what I personally did at the final moment.','The real context is available; the missing piece is my own observable action before it closed.','I can reconstruct the situation except for the concrete response that came from me at the end.','The lived event is otherwise specified, while my own last behaviour is unstated.','What remains unknown is not the context but the action I myself took immediately before closure.','The situation is real and sufficiently detailed apart from my personal endpoint response.'],
'decision':['Make the choice itself for me and tell me which option becomes final.','I am transferring the final selection to you rather than keeping the decision with me.','Choose on my behalf; I want your call to replace my own.','Do not merely compare the options—decide which one I should take.','Take responsibility for the final choice and give me the selected route.','I want the answer to be your decision for me, not guidance toward my own decision.'],
'hypothetical':['I fabricated this case for validation; none of it is personal history.','This example is synthetic test material, not an event that happened to me.','The scenario is invented for evaluation and should not count as lived evidence.','This is a made-up practice case rather than something from my actual life.','Nothing described here occurred to me; the text exists only as a test scenario.','Treat this as fictional validation input, not a real situation I experienced.'],
'third':['Infer the other person’s private belief despite having no observable statement or behaviour from them.','Tell me the hidden conclusion in someone else’s mind when nothing outward establishes it.','I want to know what they secretly think without evidence in what they said or did.','State another person’s unspoken view even though their conduct gives no basis for it.','Work out their private internal belief with no observable behaviour supporting the inference.','Tell me what is in the other person’s mind when I have no outward evidence.'],
'prediction':['At the future checkpoint I named, will I have the outcome I want?','When the stated future date arrives, will this resolve in my preferred way?','By that future cutoff, will the result I am hoping for have happened?','At the specified future milestone, will events end with my desired result?','Looking to the future boundary I gave, will the outcome go in my favour?','When that future marker is reached, will I get the result I want?'],
'freeze':['A low-risk reversible first move was ready, but I kept adding alternatives and never initiated it.','I could test a small step and undo it, yet I expanded the option list instead of starting.','There was an easy-to-reverse opening action, but I continued comparing possibilities and did nothing.','A contained starter move was available; I generated more choices rather than taking it.','I had a reversible low-commitment action, yet option expansion kept me from beginning.','The first step had a clear exit, but I kept widening alternatives and left it untouched.'],
'ignore':['The central issue still required my answer, while I redirected myself into side work that could not resolve it.','The main obligation needed action from me, but I spent my effort on peripheral tasks instead.','My response was still required on the consequential matter, yet I occupied myself with secondary activity.','I left the primary responsibility unresolved and shifted attention to work that did not address it.','The core matter was waiting for me, but I diverted into less relevant tasks.','Something important still needed my action; I avoided it by doing side activity that could not settle it.'],
'slow':['I used one bounded pause, checked once, answered, and then stopped reviewing.','I delayed within a fixed limit, made a single review pass, responded, and closed the process.','There was one finite interval before I answered; I checked one time and did not reopen it.','I paused once within a clear boundary, reviewed the point once, then responded and finished.','I allowed one contained delay and one check before answering and closing the matter.','I took a limited pause, reviewed once, gave my response, and ended the review cycle.'],
'sequence':['I moved toward acting, pulled back, then returned to the same judgement with no new facts.','I approached the step, withdrew, and repeated the identical reasoning without new information.','I nearly executed the action, retreated, then came back to the same conclusion under unchanged evidence.','I advanced toward the move, reversed course, and revisited the old assessment although nothing new appeared.','I got close to acting, stepped away, then returned to the same judgement while the facts stayed the same.','I approached execution, backed out, and cycled to the same conclusion without new evidence.'],
'neutral':['I kept the decision as mine, completed the action, and left the matter closed.','I chose for myself, carried out the concrete step, and did not reopen it afterward.','Final agency remained with me; I finished the action and moved on.','I made my own call, executed it, and treated the issue as settled.','The choice stayed mine through completion, after which I did not revisit it.','I retained the final decision, completed what I chose, and left it closed.']}
VI={k:[
{'clarification':'Chuyện này đã xảy ra thật và bối cảnh đã rõ, nhưng tôi chưa nói hành động cuối cùng do chính mình thực hiện.','decision':'Hãy quyết định thay tôi và nói option nào sẽ là lựa chọn cuối.','hypothetical':'Tôi dựng case này để validation; không phần nào là lịch sử cá nhân thật.','third':'Hãy suy ra belief riêng của người kia dù không có lời nói hay hành vi quan sát được từ họ.','prediction':'Tại checkpoint tương lai tôi đã nêu, tôi có nhận được outcome mình muốn không?','freeze':'Một first move ít rủi ro và đảo ngược được đã sẵn, nhưng tôi cứ thêm alternative rồi không bắt đầu.','ignore':'Core issue vẫn cần câu trả lời của tôi, nhưng tôi chuyển sang side work không thể giải quyết nó.','slow':'Tôi dùng một pause có biên, check đúng một lần, trả lời rồi ngừng review.','sequence':'Tôi tiến về phía hành động, pull back rồi quay lại cùng judgement khi không có fact mới.','neutral':'Tôi giữ quyết định là của mình, hoàn thành action rồi để matter đóng.'}[k],
{'clarification':'Context thật đã có; phần còn thiếu là observable action của chính tôi trước closure.','decision':'Tôi giao final selection cho bạn thay vì giữ decision ở mình.','hypothetical':'Ví dụ này là synthetic test material, không phải sự việc từng xảy ra với tôi.','third':'Nói hidden conclusion trong đầu người khác khi không có outward evidence xác lập nó.','prediction':'Khi future date đã nói tới, chuyện này có resolve theo hướng tôi muốn không?','freeze':'Tôi có thể thử một bước nhỏ rồi undo, vậy mà lại mở rộng option list thay vì start.','ignore':'Nghĩa vụ chính cần action của tôi, nhưng tôi dùng effort vào peripheral task.','slow':'Tôi delay trong fixed limit, review một pass, response rồi đóng process.','sequence':'Tôi tiếp cận bước đi, withdraw rồi lặp reasoning cũ khi không có information mới.','neutral':'Tôi tự chọn, thực hiện concrete step rồi không mở lại sau đó.'}[k],
{'clarification':'Tôi dựng lại được situation ngoại trừ response cụ thể từ chính tôi ở đoạn cuối.','decision':'Chọn thay tôi; tôi muốn call của bạn thay cho call của mình.','hypothetical':'Scenario này được bịa để evaluation và không được tính là lived evidence.','third':'Tôi muốn biết người kia nghĩ kín gì mà không có evidence trong lời nói hay hành động.','prediction':'Đến future cutoff đó, result tôi đang mong có xảy ra không?','freeze':'Có opening action dễ đảo ngược, nhưng tôi tiếp tục so possibility rồi không làm.','ignore':'Response của tôi vẫn cần cho consequential matter, vậy mà tôi bận với secondary activity.','slow':'Có một interval hữu hạn trước response; tôi kiểm một lần và không mở lại.','sequence':'Tôi gần execute action, retreat rồi quay về cùng conclusion dưới evidence không đổi.','neutral':'Final agency vẫn ở tôi; tôi làm xong action rồi tiếp tục.'}[k],
{'clarification':'Lived event đã đủ các phần khác, còn last behaviour của tôi chưa được nêu.','decision':'Đừng chỉ compare option—hãy quyết định tôi nên chọn cái nào.','hypothetical':'Đây là practice case bịa chứ không phải chuyện trong đời thật của tôi.','third':'Nói unspoken view của người khác dù conduct của họ không cho basis.','prediction':'Tại future milestone đã xác định, events có kết thúc với desired result của tôi không?','freeze':'Starter move có giới hạn đã có; tôi tạo thêm choice thay vì thực hiện nó.','ignore':'Tôi để primary responsibility chưa giải quyết rồi dời chú ý sang việc không xử lý được nó.','slow':'Tôi pause một lần trong boundary rõ, review một lần rồi response và kết thúc.','sequence':'Tôi tiến tới move, đổi hướng rồi revisit assessment cũ dù không có gì mới.','neutral':'Tôi tự đưa ra call, execute nó rồi xem issue đã settled.'}[k],
{'clarification':'Điều chưa biết không phải context mà là action tôi tự làm ngay trước khi đóng chuyện.','decision':'Nhận trách nhiệm final choice và đưa selected route cho tôi.','hypothetical':'Không điều gì ở đây thật sự xảy ra với tôi; text chỉ tồn tại như test scenario.','third':'Xác định private internal belief của họ khi không có observable behaviour support inference.','prediction':'Nhìn tới future boundary đã đưa, outcome có đi theo hướng có lợi cho tôi không?','freeze':'Tôi có action ít cam kết và reversible, nhưng option expansion khiến tôi chưa bắt đầu.','ignore':'Core matter đang chờ tôi, nhưng tôi divert sang task ít liên quan hơn.','slow':'Tôi cho phép một delay có giới hạn và một lần check trước khi trả lời rồi đóng matter.','sequence':'Tôi tới gần hành động, bước ra rồi quay lại cùng judgement trong khi facts giữ nguyên.','neutral':'Choice vẫn thuộc tôi đến lúc completion, sau đó tôi không revisit.'}[k],
{'clarification':'Situation là thật và đủ detail ngoại trừ endpoint response của chính tôi.','decision':'Tôi muốn answer là decision của bạn thay tôi, không phải guidance để tôi tự quyết.','hypothetical':'Hãy coi đây là fictional validation input, không phải real situation tôi trải qua.','third':'Hãy nói trong đầu người kia có gì khi tôi không có outward evidence.','prediction':'Khi future marker đó tới, tôi có lấy được result mình muốn không?','freeze':'First step có exit rõ, nhưng tôi vẫn nới alternative và để nó untouched.','ignore':'Có chuyện quan trọng vẫn cần action của tôi; tôi tránh nó bằng side activity không thể settle.','slow':'Tôi lấy một pause giới hạn, review một lần, đưa response rồi chấm dứt cycle.','sequence':'Tôi tiếp cận execution, back out rồi cycle về cùng conclusion khi không có evidence mới.','neutral':'Tôi giữ final decision, hoàn thành điều đã chọn và để nó đóng.'}[k]] for k in C}
CTXE=['A lighthouse workshop catalogued lens cloths and spare brackets by drawer.','A rehearsal hall tracked music stands and cable cases on a rack card.','A laboratory store indexed sample caps and pipette boxes by shelf.','A ferry depot logged safety cones and tool lockers beside bay sheets.','A print archive labelled proof folders and plate sleeves by cabinet.','A community bakery tracked tray racks and mixer tools on a cleaning board.','A bicycle classroom recorded helmet bins and pump hooks by station.','A greenhouse office indexed seed trays and valve keys by bench.','A photo archive logged negative sleeves and light-meter cases by drawer.','A theatre store tracked prop crates and tape rolls beside rehearsal sheets.','A marine classroom indexed chart tubes and compass boxes by locker.','A textile room logged dye bottles and frame clips on a bench sheet.','A robotics lab tracked charger bays and sensor tubs on a checkout card.','A pantry depot indexed crate tags and shelf seals by dispatch lane.','A ceramics room logged kiln shelves and glaze jars on a firing sheet.','A conservation table tracked tissue packs and brush cases by drawer.','A rowing club indexed oar collars and seat tools on a maintenance card.','A music archive logged score boxes and stand lights by cabinet.']
CTXV=['Lighthouse workshop catalog lens cloth và spare bracket theo drawer.','Rehearsal hall theo dõi music stand và cable case trên rack card.','Laboratory store lập index sample cap và pipette box theo shelf.','Ferry depot ghi safety cone và tool locker cạnh bay sheet.','Print archive gắn label proof folder và plate sleeve theo cabinet.','Community bakery theo dõi tray rack và mixer tool trên cleaning board.','Bicycle classroom ghi helmet bin và pump hook theo station.','Greenhouse office lập index seed tray và valve key theo bench.','Photo archive ghi negative sleeve và light-meter case theo drawer.','Theatre store theo dõi prop crate và tape roll cạnh rehearsal sheet.','Marine classroom lập index chart tube và compass box theo locker.','Textile room ghi dye bottle và frame clip trên bench sheet.','Robotics lab theo dõi charger bay và sensor tub trên checkout card.','Pantry depot lập index crate tag và shelf seal theo dispatch lane.','Ceramics room ghi kiln shelf và glaze jar trên firing sheet.','Conservation table theo dõi tissue pack và brush case theo drawer.','Rowing club lập index oar collar và seat tool trên maintenance card.','Music archive ghi score box và stand light theo cabinet.']
TAIL_E=['That storage note is contextual only and does not determine the response.','The equipment record belongs to filing, not to the behavioural evidence.','That logistical detail cannot decide the semantic route.','The physical marker adds record context but not response evidence.','That inventory reference cannot create a behavioural signal by itself.','The administrative note is external to the mechanism being measured.']
TAIL_V=['Storage note đó chỉ là context và không quyết response.','Equipment record thuộc filing chứ không phải behavioural evidence.','Logistical detail đó không thể quyết semantic route.','Physical marker thêm record context chứ không thêm response evidence.','Inventory reference không thể tự tạo behavioural signal.','Administrative note nằm ngoài mechanism đang được đo.']
def norm(s):return re.sub(r'\s+',' ',re.sub(r'[^a-z0-9\s]',' ',s.lower())).strip()
def tok(s):return set(norm(s).split())
def sim(a,b):
 A,B=tok(a),tok(b);return len(A&B)/len(A|B) if A|B else 1.0
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def csha(o):return hashlib.sha256(canon(o)).hexdigest()
cases=[]
for ci,cat in enumerate(C):
 for i in range(18):
  lang='EN' if i<9 else 'VI';j=i%9;core=(EN if lang=='EN' else VI)[cat][(j+2*ci)%6];ctx=(CTXE if lang=='EN' else CTXV)[(j*3+ci)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(j+ci)%6];orders=[[core,ctx,tail],[ctx,tail,core],[tail,core,ctx]][(j+ci)%3];s=' '.join(orders);route,fam,seq=E[cat]
  cases.append({'case_id':f'V222-S{ci:02d}-{i+1:02d}','category':cat,'language':lang,'domain':D[(ci+3*i)%6],'surface':s,'construction_expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
internal=(0,None)
for i in range(180):
 for j in range(i+1,180):
  v=sim(cases[i]['surface'],cases[j]['surface']);
  if v>internal[0]:internal=(v,(cases[i]['case_id'],cases[j]['case_id']))
external=[]
for br,v in [('v83219-v1-sealed-validation','219'),('v83220-v1-sealed-validation','220'),('v83221-v1-sealed-validation','221')]:
 subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL)
 p=f'validation/v832{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json';external+=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{p}'],text=True))['cases']
extmax=(0,None);at75=0;exact=0;extnorm={norm(x['surface']) for x in external}
for c in cases:
 exact+=norm(c['surface']) in extnorm
 for x in external:
  v=sim(c['surface'],x['surface']);at75+=v>=.75
  if v>extmax[0]:extmax=(v,(c['case_id'],x['case_id']))
fps=[hashlib.sha256((x['category']+'|'+x['language']+'|'+norm(x['surface'])).encode()).hexdigest() for x in cases];fpdup=len(fps)-len(set(fps))
sel=[]
for ci in range(10):
 ids=[x['case_id'] for x in cases if x['category']==C[ci]];sel += [ids[k] for k in [0,3,6,11,14,17]]
a=[];b=[]
for ci in range(10):
 ids=[x for x in sel if x.startswith(f'V222-S{ci:02d}-')];a+=ids[::2];b+=ids[1::2]
by={x['case_id']:x for x in cases};bank={'authority':'V8.3.222 fresh candidate bank','validated_development_head_sha':DEV,'semantic_authority':SEM,'construction_runtime_used':False,'cases':cases};selection={'authority':'V8.3.222 sealed selection','selected':sel,'batch_a':a,'batch_b':b};fixture={'authority':'V8.3.222 sealed fixture','validated_development_head_sha':DEV,'cases':[by[i] for i in sel]};gold={'authority':'V8.3.222 independent gold','cases':[{'case_id':i,'expected':{'route':E[by[i]['category']][0],'families':E[by[i]['category']][1],'sequence':bool(E[by[i]['category']][2])}} for i in sel]};membership={'authority':'V8.3.222 membership','cases':[{'case_id':i,'batch':'A' if i in set(a) else 'B'} for i in sel]};audit={'candidate':'V8.3.222','internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(extmax[0],6),'external_max_pair':extmax[1],'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'v219_v220_v221_pool_reused':False}
files={'candidate_bank':('V8_3_222_PRESEAL_CANDIDATE_BANK_V1.json',bank),'selection':('V8_3_222_SEALED_SELECTION_V1.json',selection),'fixture':('V8_3_222_SEALED_FIXTURE_V1.json',fixture),'independent_gold':('V8_3_222_INDEPENDENT_GOLD_V1.json',gold),'membership':('V8_3_222_SEALED_MEMBERSHIP_V1.json',membership),'preseal_audit':('V8_3_222_PRESEAL_DIVERSITY_AUDIT_V1.json',audit)}
for _,(n,o) in files.items():(O/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
hashes={k:csha(o) for k,(_,o) in files.items()};passed=internal[0]<.75 and extmax[0]<.75 and at75==0 and exact==0 and fpdup==0
auth={'authority':'V8.3.222 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':hashes,'preseal_pass':passed,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'v221_sealed_rerun':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_222_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.222','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(extmax[0],6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success' if passed else 'failure'};(O/'V8_3_222_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
z=R/'PSC_V8_3_222_V1_PRESEAL_CHECKPOINT.zip'
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED) as q:
 for p in sorted(O.glob('V8_3_222_*.json')):q.write(p,p.name)
(R/'PSC_V8_3_222_V1_PRESEAL_CHECKPOINT_SHA256.txt').write_text(hashlib.sha256(z.read_bytes()).hexdigest()+'  '+z.name+'\n');print(json.dumps(receipt));raise SystemExit(0 if passed else 1)
