import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83224-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='93340ec0488207f31a48c82e7b916ff709f700ab';SEM='QCEvidenceExtractorV5AB -> QCSemanticCoreV101'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],False),'decision':('input:decision-request',[],False),'hypothetical':('input:hypothetical-or-example',[],False),'third':('input:third-party-only',[],False),'prediction':('input:prediction',[],False),'freeze':('input:self-lived',['freeze'],False),'ignore':('input:self-lived',['ignore'],False),'slow':('input:self-lived',['slow'],False),'sequence':('input:self-lived',['slow'],True),'neutral':('input:self-lived',[],False)}
EN={
'clarification':['This really happened; I can state the setting and sequence, but I still have not supplied the observable action I personally took at the end.','The episode is lived and specific, yet the record stops before saying what I myself actually did at closure.','I know the concrete circumstances; the remaining evidence gap is my own final behaviour.','This is not a hypothetical: the missing item is the direct response that came from me before the situation closed.','The surrounding event is clear, but my personal endpoint action has not been given.','The case is real and otherwise complete; what I did myself immediately before the end is absent.','The lived account contains the context but omits my own last observable move.','I can describe the episode in detail except for the action attributable to me at its endpoint.','The situation occurred in my life; only my concrete closing response is missing.'],
'decision':['Make the decision itself for me and name the option I should finally take.','I am giving you the final say; choose the route in my place.','Use your judgement as the deciding choice rather than helping me keep the choice myself.','Pick my final option for me, not merely the pros and cons.','Take over the selection and tell me which path becomes my answer.','I want your choice to replace my own final decision.','Decide which option I take and make that selection on my behalf.','The final call is being handed to you; tell me what I must choose.','Choose the outcome of the decision for me instead of coaching me to decide.'],
'hypothetical':['I wrote this solely as synthetic validation material; it is not something I lived through.','This constructed example did not happen to me and should not count as personal evidence.','The scenario is fictional test input rather than an episode from my life.','I invented the situation for evaluation; none of it is autobiographical.','This is practice prose, not a real event that occurred to me.','The case is deliberately fabricated and is not lived history.','Treat these details as a test example, not as something I experienced.','This scenario exists only for validation and has no basis in my personal history.','The following is made-up evaluation text rather than a real situation of mine.'],
'third':['Tell me the other person’s private belief even though I have no observable behaviour or statement from them that establishes it.','Infer what they secretly concluded despite there being no outward evidence from them.','I want their hidden internal judgement without anything they said or did supporting it.','State what is in the other person’s mind when their conduct provides no basis for knowing.','Work out their unspoken belief from no observable evidence.','Tell me their concealed conclusion although no action or statement from them demonstrates it.','Infer the other person’s inner view despite the absence of behavioural evidence.','Give me their private thought even though nothing outward makes it knowable.','Tell me what they secretly believe without evidence in their words or actions.'],
'prediction':['By the future date I specified, will the result I want have occurred?','When that future checkpoint arrives, will this resolve the way I hope?','At the named future boundary, will I get my preferred outcome?','Will the desired result be in place by the future cutoff I gave?','Looking to that stated future point, will events finish in my favour?','When the future milestone is reached, will the outcome match what I want?','By that future marker, am I going to receive the result I am asking for?','At the future deadline I named, will this end with my desired outcome?','Will this have turned out as I want when that stated future point arrives?'],
'freeze':['A small reversible move was available, but I kept enlarging the set of alternatives and never initiated it.','I had an easy-to-undo first action, yet I continued generating options instead of starting.','There was a low-commitment test step with a clear exit; I stayed in comparison and left it untouched.','I could have tried one contained reversible move, but I widened the choices rather than acting.','A practical first step carried little risk, yet I kept adding possibilities and did not begin.','The opening move was reversible; I expanded the option set and remained inactive.','I had a small action with a safe way back, but more alternatives replaced starting.','A low-stakes starter action existed, while I kept broadening choices and took no first step.','The first move could easily be reversed, but I stayed in option expansion instead of doing it.'],
'ignore':['The important issue still needed my response, but I shifted into side tasks that could not resolve it.','My action was required on the main matter while I occupied myself with peripheral work.','I left the consequential responsibility waiting and spent effort on secondary tasks instead.','The central issue remained unresolved because I redirected attention to less relevant activity.','Something material still required me to respond, yet I kept myself busy elsewhere.','I avoided the main obligation by doing work that could not answer it.','The core matter was waiting for my action while I focused on side activity.','My response was still necessary, but I used the time on peripheral tasks that did not address the issue.','I displaced myself into secondary work while the important responsibility still waited for me.'],
'slow':['Before answering, I used one bounded pause, reviewed once, then closed the issue after responding.','I waited within a defined limit, checked the matter once, answered, and did not reopen it.','There was one finite interval and one review pass before I gave the response and ended the process.','I allowed a contained delay, looked once more, replied, and treated the matter as finished.','Before I answered I took one limited pause and one review, then left the issue closed.','I delayed inside a clear boundary, checked once, responded, and stopped the review cycle.','One bounded interval preceded my answer; after one check I closed the matter.','I paused for a fixed period, reviewed one time, answered, and did not return to it.','I used one limited delay and one review before responding and ending the process.'],
'sequence':['I moved toward the action, withdrew, and returned to the same judgement even though no new facts appeared.','I approached execution, backed away, then repeated the identical reasoning under unchanged evidence.','I came close to taking the step, retreated, and reached the same conclusion without new information.','I advanced toward acting, reversed course, then revisited the old assessment while the facts stayed the same.','I nearly acted, stepped away, and cycled back to the same judgement with nothing new added.','I moved toward execution, pulled back, then repeated my prior conclusion without new evidence.','I approached the practical move, withdrew, and returned to the same reasoning under the same facts.','I got close to action, retreated, and came again to the identical judgement with no new information.','I advanced, backed out, then circled to the same conclusion although the evidence had not changed.'],
'neutral':['I kept the final decision with me, completed the action, and left the issue closed.','The choice remained mine; I carried it out and did not reopen the matter.','I retained final agency, finished the practical step, and moved on.','I made my own decision, executed it, and treated the issue as settled.','Ownership of the choice stayed with me through completion, after which I left it closed.','I decided for myself, completed what I chose, and did not revisit it.','The final call was mine, I acted on it, and the matter stayed closed afterward.','I kept agency, finished the action, and treated the process as complete.','I made the final choice myself, carried it through, and did not return to the issue.']}
VI={
'clarification':['Chuyện này thật sự đã xảy ra; tôi biết setting và sequence nhưng vẫn chưa nêu action quan sát được do chính tôi làm ở cuối.','Episode là lived và cụ thể, nhưng record dừng trước khi nói tôi thực sự làm gì tại closure.','Tôi biết circumstances cụ thể; evidence gap còn lại là final behaviour của chính tôi.','Đây không phải hypothetical: phần thiếu là direct response từ tôi trước khi situation đóng.','Event xung quanh đã rõ, nhưng personal endpoint action của tôi chưa được đưa ra.','Case là thật và các phần khác đã đủ; việc chính tôi làm ngay trước điểm kết thúc vẫn vắng.','Lived account có context nhưng bỏ qua last observable move của chính tôi.','Tôi mô tả được episode chi tiết ngoại trừ action thuộc về tôi ở endpoint.','Situation đã xảy ra trong đời tôi; chỉ concrete closing response của tôi còn thiếu.'],
'decision':['Hãy quyết định luôn thay tôi và nói option cuối tôi nên chọn.','Tôi giao final say cho bạn; hãy chọn route ở vị trí của tôi.','Dùng judgement của bạn làm deciding choice thay vì giúp tôi giữ lựa chọn ở mình.','Chọn final option cho tôi, không chỉ phân tích pros và cons.','Nhận selection và nói path nào trở thành answer của tôi.','Tôi muốn choice của bạn thay cho final decision của chính tôi.','Quyết định option tôi sẽ lấy và chốt selection đó thay tôi.','Final call đang được giao cho bạn; nói tôi bắt buộc chọn gì.','Hãy chọn outcome của decision thay tôi thay vì coaching để tôi tự quyết.'],
'hypothetical':['Tôi viết đoạn này chỉ như synthetic validation material; nó không phải chuyện tôi đã sống qua.','Ví dụ được dựng này chưa xảy ra với tôi và không được tính là personal evidence.','Scenario là fictional test input chứ không phải episode từ đời tôi.','Tôi bịa situation để evaluation; không phần nào là autobiographical.','Đây là practice prose, không phải real event từng xảy ra với tôi.','Case được cố ý fabricate và không phải lived history.','Hãy coi details này là test example, không phải chuyện tôi trải nghiệm.','Scenario chỉ tồn tại để validation và không có basis trong personal history của tôi.','Đoạn sau là made-up evaluation text chứ không phải situation thật của tôi.'],
'third':['Nói private belief của người kia dù tôi không có observable behaviour hay statement nào từ họ xác lập nó.','Suy ra họ bí mật kết luận gì dù không có outward evidence từ họ.','Tôi muốn hidden internal judgement của họ mà không có điều họ nói hay làm support.','Nói trong đầu người kia có gì khi conduct của họ không cho basis để biết.','Xác định unspoken belief của họ từ không có observable evidence.','Nói concealed conclusion của họ dù không action hay statement nào chứng minh.','Suy ra inner view của người kia dù behavioural evidence vắng mặt.','Cho tôi private thought của họ dù không gì outward khiến nó knowable.','Nói họ bí mật tin gì khi words và actions không cung cấp evidence.'],
'prediction':['Đến future date tôi đã nêu, result tôi muốn có xảy ra chưa?','Khi future checkpoint tới, chuyện này có resolve như tôi hy vọng không?','Tại future boundary đã nói, tôi có nhận preferred outcome không?','Desired result có ở đó trước future cutoff tôi đưa không?','Nhìn tới future point đã nêu, events có finish theo hướng có lợi cho tôi không?','Khi future milestone tới, outcome có match điều tôi muốn không?','Đến future marker đó, tôi có nhận result đang hỏi không?','Tại future deadline đã nêu, chuyện này có kết thúc bằng desired outcome không?','Khi điểm tương lai đó tới, chuyện có turn out như tôi muốn không?'],
'freeze':['Có một move nhỏ reversible, nhưng tôi cứ mở rộng tập alternative rồi không initiate.','Tôi có first action dễ undo, vậy mà tiếp tục tạo option thay vì bắt đầu.','Có test step ít commitment với exit rõ; tôi ở trong comparison và để nó untouched.','Tôi có thể thử một reversible move có giới hạn, nhưng mở rộng choice thay vì act.','First step practical có ít risk, nhưng tôi cứ thêm possibility và không begin.','Opening move reversible; tôi nới option set và vẫn inactive.','Tôi có action nhỏ với đường lui an toàn, nhưng alternative mới thay thế việc start.','Starter action ít rủi ro đã có, trong khi tôi mở rộng choice và không lấy first step.','First move dễ đảo ngược, nhưng tôi mắc trong option expansion thay vì làm.'],
'ignore':['Important issue vẫn cần response của tôi, nhưng tôi shift sang side task không thể resolve nó.','Action của tôi cần cho main matter, trong khi tôi lại bận với peripheral work.','Tôi để consequential responsibility chờ và dùng effort vào secondary task.','Central issue vẫn unresolved vì tôi redirect attention sang activity ít liên quan hơn.','Có chuyện material vẫn cần tôi response, vậy mà tôi giữ mình bận ở chỗ khác.','Tôi tránh main obligation bằng work không thể answer nó.','Core matter đang chờ action của tôi trong khi tôi focus vào side activity.','Response của tôi vẫn cần, nhưng tôi dùng thời gian cho peripheral task không address issue.','Tôi dời mình vào secondary work trong khi important responsibility vẫn chờ.'],
'slow':['Trước khi trả lời, tôi dùng một bounded pause, review một lần, rồi đóng issue sau khi response.','Tôi đợi trong limit đã định, check matter một lần, trả lời rồi không reopen.','Có một finite interval và một review pass trước khi tôi đưa response và kết thúc process.','Tôi cho phép contained delay, nhìn lại một lần, reply rồi xem matter finished.','Trước khi answer tôi lấy một limited pause và một review, rồi để issue closed.','Tôi delay trong boundary rõ, check một lần, response rồi dừng review cycle.','Một bounded interval đứng trước answer; sau một check tôi đóng matter.','Tôi pause trong fixed period, review một lần, answer rồi không quay lại.','Tôi dùng một limited delay và một review trước khi response và end process.'],
'sequence':['Tôi tiến về action, withdraw rồi quay lại cùng judgement dù không có fact mới.','Tôi tiếp cận execution, back away rồi lặp reasoning giống hệt dưới evidence không đổi.','Tôi gần lấy step, retreat rồi đi tới cùng conclusion khi không có information mới.','Tôi tiến tới act, đổi hướng rồi revisit old assessment trong khi facts giữ nguyên.','Tôi gần act, bước ra rồi cycle về cùng judgement khi không có gì mới thêm.','Tôi tiến về execution, pull back rồi lặp prior conclusion mà không có evidence mới.','Tôi tiếp cận practical move, withdraw rồi quay lại cùng reasoning dưới cùng facts.','Tôi tới gần action, retreat rồi lại đạt judgement giống hệt khi không có information mới.','Tôi tiến lên, back out rồi vòng về cùng conclusion dù evidence không đổi.'],
'neutral':['Tôi giữ final decision ở mình, hoàn thành action và để issue đóng.','Choice vẫn là của tôi; tôi thực hiện nó và không reopen matter.','Tôi giữ final agency, làm xong practical step rồi tiếp tục.','Tôi tự đưa decision, execute nó và xem issue settled.','Ownership của choice ở tôi qua completion, sau đó tôi để nó closed.','Tôi tự quyết, hoàn thành điều đã chọn và không revisit.','Final call là của tôi, tôi act theo nó và matter vẫn closed sau đó.','Tôi giữ agency, hoàn tất action và xem process complete.','Tôi tự đưa final choice, carry it through rồi không quay lại issue.']}
CTXE=['A clock-repair class indexed spring boxes and loupe trays by bench.','A kayak workshop logged deck-line bags and buckle bins on rack cards.','A paper studio tracked cutting mats and binding clips by table.','A bird observatory indexed field scopes and battery cases by cabinet.','A dance wardrobe logged shoe crates and garment tags by rail.','A geology room tracked sample boxes and hand lenses by shelf.','A community theatre office indexed cue sheets and headset hooks by drawer.','A bicycle fitting room logged spacer trays and torque keys by station.','A greenhouse classroom tracked propagation labels and valve tools by bench.','A pottery archive indexed firing cards and glaze tiles by shelf.','A sound studio logged stand adapters and cable wraps by rack.','A marine library tracked chart sleeves and compass cases by cabinet.','A repair lab indexed fastener bins and gauge cards by bench.','A print classroom logged roller trays and proof folders by table.','A rowing store tracked seat fittings and oar collars by rack.','A textile classroom indexed frame clips and thread cards by drawer.','A food workshop logged container lids and thermometer sleeves by shelf.','A small museum depot tracked display pins and packing straps by cabinet.']
CTXV=['Lớp clock-repair lập index spring box và loupe tray theo bench.','Kayak workshop ghi deck-line bag và buckle bin trên rack card.','Paper studio theo dõi cutting mat và binding clip theo table.','Bird observatory lập index field scope và battery case theo cabinet.','Dance wardrobe ghi shoe crate và garment tag theo rail.','Geology room theo dõi sample box và hand lens theo shelf.','Community theatre office lập index cue sheet và headset hook theo drawer.','Bicycle fitting room ghi spacer tray và torque key theo station.','Greenhouse classroom theo dõi propagation label và valve tool theo bench.','Pottery archive lập index firing card và glaze tile theo shelf.','Sound studio ghi stand adapter và cable wrap theo rack.','Marine library theo dõi chart sleeve và compass case theo cabinet.','Repair lab lập index fastener bin và gauge card theo bench.','Print classroom ghi roller tray và proof folder theo table.','Rowing store theo dõi seat fitting và oar collar theo rack.','Textile classroom lập index frame clip và thread card theo drawer.','Food workshop ghi container lid và thermometer sleeve theo shelf.','Small museum depot theo dõi display pin và packing strap theo cabinet.']
TAIL_E=['That filing record supplies context only and cannot establish the response mechanism.','The equipment note belongs to logistics rather than behavioural evidence.','That inventory detail cannot decide the classification.','The physical marker adds record context but does not supply response evidence.','That administrative trace cannot create a behavioural signal.','The storage reference remains outside the mechanism being evaluated.']
TAIL_V=['Filing record đó chỉ cung cấp context và không xác lập response mechanism.','Equipment note thuộc logistics chứ không phải behavioural evidence.','Inventory detail đó không thể quyết classification.','Physical marker thêm record context nhưng không cung cấp response evidence.','Administrative trace đó không tạo behavioural signal.','Storage reference vẫn nằm ngoài mechanism đang evaluation.']
def norm(s):return re.sub(r'\s+',' ',re.sub(r'[^a-z0-9 ]',' ',s.lower())).strip()
def toks(s):return set(norm(s).split())
def sim(a,b):A,B=toks(a),toks(b);return len(A&B)/max(1,len(A|B))
cases=[]
for ci,cat in enumerate(C):
 route,fam,seq=E[cat]
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=j if j<9 else j-9;core=(EN if lang=='EN' else VI)[cat][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*7+j*2+5)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*2+j+1)%6];order=(ci+j*2)%3;parts=[core,ctx,tail] if order==0 else ([ctx,core,tail] if order==1 else [tail,ctx,core]);surface=' '.join(parts);cases.append({'case_id':f'V224-S{ci:02d}-{j+1:02d}','surface':surface,'domain':D[(ci*2+j)%6],'category':cat,'language':lang,'expected':{'route':route,'families':fam,'sequence':seq}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
batch_a=[];batch_b=[]
for ci in range(10):
 ids=[f'V224-S{ci:02d}-{j:02d}' for j in range(1,19)];batch_a += [ids[0],ids[5],ids[14]];batch_b += [ids[2],ids[8],ids[16]]
assert len(batch_a)==30 and len(batch_b)==30 and set(batch_a).isdisjoint(batch_b)
selection={'candidate':'V8.3.224','batch_a':batch_a,'batch_b':batch_b,'selected':batch_a+batch_b,'selection_uses_runtime_output':False};fixture={'candidate':'V8.3.224','cases':[x for x in cases if x['case_id'] in set(selection['selected'])]};gold={'candidate':'V8.3.224','cases':[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture['cases']]};membership={'candidate':'V8.3.224','cases':[{'case_id':x,'batch':'A'} for x in batch_a]+[{'case_id':x,'batch':'B'} for x in batch_b]}
external=[]
for v in [219,220,221,222,223]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json';subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 try:external += json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL))['cases']
 except subprocess.CalledProcessError:pass
imax=0;ipair=None
for i in range(180):
 for j in range(i+1,180):
  s=sim(cases[i]['surface'],cases[j]['surface'])
  if s>imax:imax=s;ipair=[cases[i]['case_id'],cases[j]['case_id']]
emax=0;at75=0;extsur={norm(x['surface']) for x in external};exact=0;extfp={hashlib.sha256((norm(x['surface'])+'|'+json.dumps(x.get('expected',{}),sort_keys=True)).encode()).hexdigest() for x in external};fpdup=0
for c in cases:
 if norm(c['surface']) in extsur:exact+=1
 fp=hashlib.sha256((norm(c['surface'])+'|'+json.dumps(c['expected'],sort_keys=True)).encode()).hexdigest();fpdup += 1 if fp in extfp else 0
 for e in external:
  s=sim(c['surface'],e['surface']);emax=max(emax,s);at75 += 1 if s>=.75 else 0
audit={'candidate':'V8.3.224','internal_max_similarity':round(imax,6),'internal_max_pair':ipair,'external_max_similarity':round(emax,6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False};assert imax<.75 and emax<.75 and at75==0 and exact==0 and fpdup==0
bank={'candidate':'V8.3.224','cases':cases}
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',bank),('SEALED_SELECTION_V1',selection),('SEALED_FIXTURE_V1',fixture),('INDEPENDENT_GOLD_V1',gold),('SEALED_MEMBERSHIP_V1',membership),('PRESEAL_DIVERSITY_AUDIT_V1',audit)]: (O/f'V8_3_224_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
authority={'authority':'V8.3.224 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':{'candidate_bank':h(bank),'selection':h(selection),'fixture':h(fixture),'independent_gold':h(gold),'membership':h(membership),'preseal_audit':h(audit)},'preseal_pass':True,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'v221_sealed_rerun':False,'v222_sealed_rerun':False,'v223_sealed_rerun':False,'production_authorized':False,'step_111_authorized':False};(O/'V8_3_224_SEALED_AUTHORITY_V1.json').write_text(json.dumps(authority,indent=2)+'\n');receipt={'candidate':'V8.3.224','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,**audit,'conclusion':'success'};(O/'V8_3_224_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
