from pathlib import Path
code=Path('validation/v83250-v1-sealed/v83250-preseal-freeze.py').read_text()
needle="exec(compile(src,'v83250-preseal-adapted.py','exec'))"
CAT4=[
'An archaeometry reference vault separately catalogued thermoluminescence dosimeters, obsidian hydration scales, portable XRF standards, neutron-activation comparators, petrographic mounts, isotope-ratio worksheets, microhardness blocks, provenance matrices, diffraction capillaries, spectral libraries, calibration phantoms, density pycnometers, luminescence aliquots, reference slags, elemental maps, polished briquettes, resin pucks, microprobe stubs, trace-element charts, ceramic standards, metallographic coupons, irradiation vials, flux monitors, oxide pellets, beam apertures, counting geometries, attenuation foils, detector windows, vacuum desiccators and laboratory accession codes; this specialist inventory is unrelated physical scenery.',
'A historical metrology laboratory separately stored Johansson gauge blocks, sine bars, autocollimator targets, optical flats, interferometric fringes, comparator stands, micrometer anvils, vernier height gauges, roundness masters, surface plates, dial-test indicators, slip gauges, angle polygons, reference spheres, cylindricity artefacts, profilometer styli, straightness mirrors, laser trackers, capacitance probes, granite parallels, thermal-compensation tables, air-bearing spindles, torque transducers, force proving rings, calibration certificates, traceability seals, dimensional masters, bore comparators, pitch standards and runout mandrels; none of this equipment assigns the final decision.',
'A molecular ecology freezer archive separately indexed microsatellite primers, SNP panels, extraction columns, lysis buffers, fluorometric standards, electrophoresis ladders, cryovials, barcoded plates, amplicon libraries, qPCR controls, restriction enzymes, magnetic beads, sequencing adapters, haplotype tables, allele bins, mitochondrial loci, reference genomes, contamination blanks, negative controls, consensus reads, phylogenetic trees, bootstrap matrices, genotype calls, fragment analyzers, capillary cartridges, hybridisation probes, nuclease-free aliquots, indexing oligos, library pools and chain-of-custody manifests; these materials cannot turn hypothetical content into lived evidence.',
'A forensic document laboratory separately recorded electrostatic detection films, video spectral comparators, transmitted-light stages, oblique illuminators, ink chromatography strips, fibre microscopes, toner morphology cards, watermark viewers, indentation lifters, ESDA foils, infrared filters, ultraviolet sources, handwriting overlays, line-quality grids, pressure-pattern sheets, paper furnish samples, fluorescence standards, adhesive exemplars, stamp-impression casts, typewriter pitch gauges, printer-defect charts, sequence-of-strokes plates, erasure detectors, solvent-response cards, substrate micrometers, opacity meters, spectral reflectance plots, examination worksheets, evidence sleeves and custody seals; these objects cannot reveal another person’s private conclusion.',
'A polar atmospheric observatory separately logged ceilometer returns, ozonesonde profiles, radiosonde trains, pyranometer traces, nephelometer channels, lidar backscatter, microwave radiometer retrievals, aerosol optical depths, Dobson units, frost-point hygrometers, sonic anemometers, albedo panels, snow-pit stratigraphy, cloud-base records, actinic-flux sensors, black-carbon filters, condensation nuclei counters, spectral irradiance curves, balloon telemetry, pressure transducers, temperature inversions, wind-profiler spectra, boundary-layer heights, ice-nucleation slides, deposition gauges, visibility meters, radiation budgets, calibration lamps, reference gases and synoptic codes; none of these records answers a future-outcome request.',
'A dendroarchaeology workshop separately indexed increment borers, core mounts, sanding grits, ring-width scanners, skeleton plots, crossdating tables, master chronologies, cambial-age estimates, sapwood counts, waney-edge records, pointer-year sheets, dendroprovenance maps, growth-index curves, COFECHA reports, Gleichlaeufigkeit scores, latewood bands, earlywood vessels, false-ring notes, compression-wood flags, resin-duct charts, pith-offset estimates, bark-edge codes, sample radii, serial sections, tracheid measurements, microtome blades, image mosaics, dating certificates, specimen racks and accession ledgers; these tools do not create or remove a stalled opening move.',
'A structural dynamics laboratory separately catalogued modal shakers, triaxial accelerometers, laser vibrometers, impedance heads, force hammers, strain rosettes, frequency-response functions, coherence spectra, damping ratios, mode-shape plots, operational deflection shapes, finite-element meshes, boundary-condition fixtures, charge amplifiers, anti-alias filters, data-acquisition chassis, tachometer pickups, electrodynamic exciters, modal masses, suspension cords, transmissibility curves, resonance sweeps, Nyquist plots, Bode traces, spectral windows, sampling clocks, sensor calibrators, shaker stingers, reference channels and test-article tags; that inventory cannot resolve a central obligation left unattended.',
'A precision chronometry institute separately held rubidium oscillators, cesium references, GPS-disciplined standards, phase comparators, Allan-deviation plots, time-interval counters, frequency synthesizers, distribution amplifiers, pulse-per-second monitors, oven-controlled crystal oscillators, phase-noise analyzers, hydrogen maser logs, leap-second bulletins, UTC traceability sheets, coaxial delay lines, trigger discriminators, reference dividers, thermal chambers, disciplined clocks, holdover curves, aging-rate tables, synchronization fibres, jitter spectra, timestamp validators, rubidium lamps, servo-loop diagrams, drift estimates, calibration epochs, timing receivers and reference epochs; these objects do not alter a bounded pause-review-close response.',
'A palaeomagnetic laboratory separately logged spinner magnetometers, cryogenic magnetometers, alternating-field demagnetizers, thermal demagnetizers, susceptibility bridges, anisotropy tensors, Zijderveld diagrams, equal-area projections, ChRM directions, coercivity spectra, Curie-temperature runs, ARM acquisitions, IRM backfields, paleointensity plots, orientation blocks, sun-compass readings, bedding corrections, tilt tests, reversal tests, fold tests, polarity columns, secular-variation curves, specimen cubes, nonmagnetic holders, mu-metal shields, field coils, fluxgate probes, reference salts, demagnetization steps and sample azimuths; this equipment adds no new evidence between approach and retreat.',
'An astronomical optics laboratory separately stored Hartmann masks, Shack-Hartmann arrays, wavefront sensors, interferometric flats, Ronchi gratings, knife-edge testers, collimated beams, Strehl-ratio reports, encircled-energy curves, modulation-transfer charts, point-spread functions, Zernike coefficients, adaptive-optics mirrors, piezo actuators, guide-star cameras, pupil stops, field flatteners, coma correctors, astigmatism targets, focus stages, optical benches, vibration isolators, beam splitters, neutral-density wheels, monochromator lamps, spectral filters, photodiode standards, CCD linearity curves, dark-current maps and plate-scale solutions; these parts do not change who retained and completed the final choice.'
]
VAR4=[
('archaeobotany suite',['phytolith morphotypes','starch granules','charred caryopses','flotation meshes','sieving fractions','seed atlases','rachis nodes','glume bases','parenchyma casts','silica skeletons','pollen residues','macroremain trays','ubiquity tables','density scores','weed ecologies','crop-processing stages','chaff ratios','grain metrics','lemma impressions','coleoptile scars','cotyledon fragments','pulse hilums','taxonomic keys','reference carpology','sediment subsamples','heavy fractions','light fractions','retent residues','context bags','voucher specimens','carbonization grades','fragment counts','minimum individuals','taphonomic notes','sampling volumes','bucket flotation','washover tanks','mesh towers','drying papers','sample flot']),
('radio interferometry bay',['baseline vectors','uv coverage','visibility amplitudes','closure phases','fringe rates','delay tracking','correlator lags','bandpass solutions','gain calibrators','phase calibrators','primary beams','synthesized beams','dirty maps','clean components','deconvolution masks','self-calibration loops','antenna tables','system temperatures','opacity corrections','RFI flags','spectral windows','channel maps','continuum subtraction','mosaic pointings','w-projection kernels','Briggs weighting','natural weighting','uniform weighting','image cubes','Stokes parameters','polarization leakage','rotation measures','Faraday depths','ionospheric TEC','ephemeris tables','Doppler tracking','rest frequencies','visibility weights','flagging summaries','measurement sets']),
('microfluidics bench',['PDMS channels','SU-8 masters','soft lithography','plasma bonding','flow-focusing junctions','droplet generators','capillary numbers','Dean vortices','hydrodynamic focusing','electroosmotic flow','zeta potentials','Peclet numbers','Reynolds numbers','mixing indices','serpentine channels','pneumatic valves','Quake membranes','micropillar arrays','cell traps','gradient generators','peristaltic pumps','syringe drivers','Luer fittings','PEEK tubing','ferrule unions','bubble traps','pressure controllers','flow sensors','fluorescent tracers','confocal stacks','particle tracks','residence times','shear profiles','channel heights','feature widths','photoresist spins','mask alignments','developer baths','contact angles','surface silanization']),
('numismatic study room',['die axes','flan weights','edge seams','strike centres','legends','mint marks','control symbols','countermarks','bankers marks','test cuts','clipping traces','brockages','double strikes','die clashes','die links','hoard groups','metrological standards','silver fineness','copper alloys','patina layers','corrosion pits','portrait styles','reverse types','epigraphic forms','beaded borders','dotted circles','incuse punches','planchet cracks','casting sprues','file marks','overstrikes','undertypes','die states','obverse dies','reverse dies','weight histograms','diameter ranges','specific gravities','XRF spectra','provenance tickets']),
('karst speleology lab',['speleothems','stalagmite laminae','flowstone bands','dripwater chemistry','calcite fabrics','aragonite needles','U-Th ages','stable isotopes','trace metals','fluid inclusions','cave rafts','moonmilk','soda straws','helictites','rimstone dams','phreatic tubes','vadose canyons','scallop lengths','solution pockets','ceiling channels','guano layers','clastic sediments','cave pearls','pool fingers','microbial mats','radon logs','CO2 profiles','drip intervals','saturation indices','DIC samples','conductivity traces','water temperatures','cave surveys','station vectors','inclination shots','azimuth readings','loop closures','passage profiles','sump levels','entrance coordinates']),
('lichenology cabinet',['foliose thalli','fruticose branches','crustose areoles','soredia','isidia','apothecia','perithecia','pycnidia','ascospores','photobionts','cephalodia','cyphellae','pseudocyphellae','rhizines','cortex reactions','medulla reactions','K tests','C tests','KC tests','P tests','UV fluorescence','thin-layer chromatography','lichen acids','usnic acid','atranorin','salazinic acid','norstictic acid','lobaric acid','spot tests','substrate records','bark pH','rock chemistry','exposure classes','humidity niches','voucher packets','herbarium numbers','microscope sections','spore septa','conidium forms','distribution grids']),
('cryogenic engineering cell',['Gifford-McMahon heads','pulse-tube coolers','Joule-Thomson stages','helium compressors','vacuum jackets','multilayer insulation','radiation shields','thermal straps','copper braids','indium gaskets','ConFlat flanges','turbo pumps','ion gauges','Pirani gauges','cryosorption panels','charcoal getters','quench valves','relief disks','burst pressures','helium leak tests','residual gas spectra','cold heads','regenerator matrices','thermometry diodes','Cernox sensors','RuO2 resistors','heater cartridges','PID loops','thermal gradients','heat loads','boiloff rates','liquid helium dewars','liquid nitrogen shields','transfer lines','bayonet couplings','phase separators','two-phase flow','superinsulation seams','vacuum breaks','warmup curves']),
('seismic instrumentation room',['broadband seismometers','strong-motion accelerographs','velocity transducers','force-balance sensors','digitizers','GPS clocks','mass centering','sensor levelling','vault orientations','instrument responses','poles and zeros','counts-to-velocity','counts-to-acceleration','sample rates','anti-alias filters','trigger thresholds','STA-LTA ratios','event buffers','ring buffers','telemetry packets','SeedLink streams','MiniSEED records','station XML','timing quality','data gaps','clip levels','self-noise spectra','huddle tests','coherence curves','calibration coils','step responses','sine sweeps','orientation checks','azimuth corrections','site amplification','vault temperatures','power budgets','battery banks','solar regulators','lightning arrestors']),
('dendrochronology lab',['ring-width series','crossdating skeletons','pointer years','master chronologies','mean sensitivity','first-order autocorrelation','signal-to-noise ratios','expressed population signals','Rbar statistics','detrending splines','negative exponentials','regional curve standardization','age trends','growth indices','latewood widths','earlywood widths','wood densities','blue intensity','stable carbon isotopes','stable oxygen isotopes','cambial ages','pith offsets','sapwood rings','waney edges','bark preservation','missing rings','false rings','locally absent rings','compression wood','reaction wood','fire scars','frost rings','resin ducts','vessel anomalies','COFECHA flags','ARSTAN outputs','chronology residuals','site chronologies','sample codes','core radii']),
('marine bioacoustics station',['hydrophone arrays','beamforming delays','source levels','received levels','transmission loss','ambient spectra','shipping noise','biophony bands','geophony bands','click trains','whistle contours','pulse intervals','inter-click intervals','spectrogram windows','FFT bins','sampling rates','anti-alias filters','duty cycles','detector thresholds','false-positive rates','localization bearings','time-difference arrivals','sound-speed profiles','CTD casts','depth sensors','mooring lines','acoustic releases','battery packs','data loggers','clock drift','calibration tones','sensitivity curves','preamp gains','dynamic ranges','self-noise floors','propagation models','bathymetric grids','multipath arrivals','surface ducts','bottom loss']),
('geodetic calibration hall',['total stations','digital levels','GNSS receivers','choke-ring antennas','tribrachs','forced-centering pillars','invar staffs','EDM baselines','scale factors','ppm corrections','prism constants','collimation errors','horizontal circle errors','vertical index errors','level compensators','tilt sensors','antenna phase centers','multipath maps','tropospheric delays','ionospheric delays','carrier phases','ambiguity resolutions','baseline vectors','network adjustments','least-squares residuals','variance factors','error ellipses','geoid models','orthometric heights','ellipsoidal heights','benchmark ties','gravity corrections','deflection of vertical','Laplace stations','azimuth observations','distance standards','temperature corrections','pressure corrections','humidity corrections','traceability sheets']),
('paleomagnetism archive',['remanent vectors','characteristic directions','principal components','MAD angles','demagnetization paths','alternating fields','thermal steps','coercivity spectra','blocking temperatures','IRM acquisitions','ARM acquisitions','hysteresis loops','Day plots','FORC diagrams','Curie points','Verwey transitions','susceptibility tensors','AMS ellipsoids','lineations','foliations','tilt corrections','fold tests','reversal tests','bootstrap confidence','Fisher means','alpha95 cones','kappa values','VGP latitudes','polarity zones','magnetostratigraphy','secular variation','paleointensity','Thellier plots','Arai diagrams','pTRM checks','anisotropy corrections','cooling-rate corrections','orientation marks','sample cubes','specimen axes']),
('chromatography core',['HPLC pumps','UHPLC columns','autosampler vials','guard cartridges','gradient mixers','degassers','UV detectors','DAD spectra','fluorescence detectors','mass analyzers','electrospray sources','ion traps','quadrupoles','time-of-flight tubes','retention times','capacity factors','selectivity factors','resolution values','peak asymmetry','theoretical plates','Van Deemter curves','mobile phases','stationary phases','acetonitrile gradients','methanol gradients','buffer strengths','pH modifiers','internal standards','external standards','calibration curves','response factors','limit of detection','limit of quantitation','blank injections','carryover tests','system suitability','peak integrations','extracted ion chromatograms','mass fragments','library matches']),
('textile conservation lab',['warp counts','weft counts','thread diameters','fibre identifications','twist directions','weave structures','plain weaves','twill weaves','satin weaves','damask patterns','brocade floats','embroidery stitches','dye analyses','mordant residues','metal threads','gilt strips','silk fibroin','wool keratin','linen bast fibres','cotton convolutions','stain maps','loss diagrams','tear orientations','seam constructions','selvedges','repair patches','support fabrics','couching threads','conservation netting','humidification screens','suction tables','low-pressure tables','adhesive films','dye bleeding tests','lightfastness scores','microfade curves','display lux','relative humidity','mounting boards','storage rolls']),
('insect morphology unit',['elytral punctures','antennal segments','tarsal formulae','wing venation','genitalic structures','pronotal margins','setal patterns','spiracle positions','mandibular teeth','maxillary palps','labial palps','ocellar counts','compound-eye facets','cerci','ovipositors','aedeagi','spermathecae','coxal cavities','trochanters','femoral spines','tibial spurs','pretarsal claws','empodia','pulvilli','scutellar shapes','abdominal tergites','sternites','pleural sutures','color morphs','sexual dimorphism','larval instars','pupal cases','egg chorions','host records','phenology dates','collection methods','pitfall traps','Malaise traps','light traps','voucher codes']),
('glass chemistry laboratory',['silica networks','borate units','aluminate tetrahedra','network modifiers','alkali ions','alkaline earths','nonbridging oxygens','glass transition temperatures','softening points','annealing points','strain points','thermal expansions','refractive indices','Abbe numbers','dispersion curves','density measurements','viscosity curves','devitrification peaks','crystal phases','nucleation rates','growth rates','DTA traces','DSC traces','XRD patterns','Raman bands','FTIR peaks','UV cutoffs','redox ratios','fictive temperatures','water contents','bubble counts','cord defects','stone inclusions','striae','surface hydration','ion exchange','chemical durability','leach rates','polishing losses','stress birefringence']),
('codicology archive',['quire structures','bifolia','foliation systems','catchwords','signatures','pricking patterns','ruling systems','written spaces','script modules','ductus features','ink recipes','parchment sides','hair sides','flesh sides','watermarks','chain lines','laid lines','sewing stations','endbands','spine linings','covering materials','board attachments','clasp fittings','boss marks','fore-edge titles','ownership notes','ex libris','annotations','palimpsests','erasures','insertions','cancel leaves','replacement leaves','quire guards','stub leaves','binding fragments','provenance marks','shelfmarks','catalogue concordances','collation formulas']),
('ceramic petrography room',['thin sections','quartz grains','feldspar twins','mica flakes','grog fragments','shell inclusions','void shapes','orientation fabrics','matrix colors','birefringence','extinction angles','grain roundness','grain sorting','modal counts','point counting','temper density','clay pellets','iron nodules','carbonate inclusions','volcanic fragments','metamorphic fragments','sedimentary fragments','heavy minerals','reaction rims','vitrification zones','optical activity','micritic calcite','sparry calcite','sericite alteration','chlorite alteration','amphibole grains','pyroxene grains','plagioclase zoning','quartz undulose extinction','textural groups','fabric groups','reference clays','kiln temperatures','provenance groups','sample codes'])
]
for _c in new:
 _m=re.search(r'-S(\\d+)-(\\d+)$',_c['case_id']);_ci,_j=map(int,_m.groups());_n,_it=VAR4[_j];_scene='A separate '+_n+' independently indexed '+', '.join(_it)+'; this specialist material is inert physical context and supplies no behavioural evidence.';_c['surface']=CAT4[_ci]+' '+_scene+' '+_c['surface']
"""
anchor="assert len(new)==180 and len({x['surface'] for x in new})==180"
replacement="src=src.replace("+repr(anchor)+","+repr(insert+'\n'+anchor)+",1); exec(compile(src,'v83250-preseal-adapted.py','exec'))"
if needle not in code: raise SystemExit('outer exec anchor missing')
code=code.replace(needle,replacement,1)
compile(code,'v83250-layer4-wrapper.py','exec')
exec(compile(code,'v83250-layer4-wrapper.py','exec'))
