import json,pathlib
root=pathlib.Path(__file__).parent
domains=['work','money','business','housing','daily-admin','relationship','travel','study','admin','home']
groups=[
('input:clarification-required',[],False,['The events are documented, but the final action attributable specifically to me is still missing.','Timeline details are present; what I personally did after the last change is not.','The narrative becomes concrete, yet ownership of my closing response remains unresolved.','Diễn biến đã đủ chi tiết nhưng bước cuối do chính tôi làm vẫn chưa được xác định.','Câu chuyện có mốc rõ ràng, còn hành vi riêng của tôi sau thay đổi cuối vẫn thiếu.','Record đầy đủ sự kiện nhưng chưa tách được phản ứng cuối nào thực sự là của tôi.']),
('input:decision-request',[],False,['Make the choice on my behalf and give me only the action to carry out.','I want you to select the route for me rather than help me compare the options.','Take the decision out of my hands and state the single next step.','Hãy chọn thay tôi và chỉ đưa đúng một hành động để tôi làm theo.','Tôi muốn bạn quyết định hộ, không phải giúp tôi cân nhắc các phương án.','Đừng để quyền chọn ở tôi; hãy nói chính xác bước tiếp theo phải làm.']),
('input:hypothetical-or-example',[],False,['This is an invented coworker scenario used only to test classification.','The example is fictional and does not describe anything that happened to me.','Use this fabricated client story purely as a semantic exercise.','Đây là tình huống bịa về một người quen chỉ để test phân loại.','Ví dụ này hoàn toàn giả định, không phải trải nghiệm thật của tôi.','Case này được dựng lên để luyện semantic chứ không lấy từ đời thật của tôi.']),
('input:third-party-only',[],False,['What private conclusion is my manager holding about me without saying it?','What are they internally feeling toward me even though nothing has been shown outwardly?','I am asking about the other person\'s hidden assessment of me, not my own behaviour.','Trong lòng họ đang đánh giá tôi thế nào dù chưa hề nói ra?','Người đó đang giữ cảm xúc kín nào về tôi mà chưa thể hiện ra ngoài?','Tôi hỏi về nhận định thầm kín của họ đối với tôi, không phải hành vi của tôi.']),
('input:prediction',[],False,['Will the final outcome become favourable for me before the deadline?','Is this likely to resolve in my favour within the next few weeks?','Will the eventual result turn out the way I want before month end?','Kết quả cuối có chuyển sang hướng có lợi cho tôi trước hạn không?','Chuyện này có kết thúc thuận lợi cho tôi trong vài tuần tới không?','Kết cục sau cùng có đúng hướng tôi mong muốn trước cuối tháng không?']),
('input:self-lived',['freeze'],False,['A reversible low-risk test is ready, but I keep expanding the comparison instead of starting it.','I already have enough evidence for a small undoable step, yet I keep opening more alternatives.','The first experiment is safe to reverse, but I delay by researching more options.','Tôi đã có bước thử nhỏ có thể quay lại nhưng vẫn mở thêm phương án thay vì bắt đầu.','Đủ dữ kiện cho một thử nghiệm ít rủi ro rồi, nhưng tôi cứ so sánh thêm và chưa làm.','Bước đầu có thể undo dễ dàng, vậy mà tôi vẫn nghiên cứu thêm lựa chọn để trì hoãn.']),
('input:self-lived',['ignore'],False,['I saw the issue needed a response, switched to unrelated admin, and left it untouched.','The real task was waiting, but I diverted into something irrelevant and postponed it.','I noticed the update and then occupied myself with a side task instead of responding.','Tôi thấy việc cần xử lý nhưng chuyển sang task phụ không liên quan rồi bỏ đó.','Việc chính đang chờ phản hồi, còn tôi lại làm chuyện không liên quan để trì hoãn.','Tôi đọc update xong rồi lao sang một việc phụ thay vì xử lý vấn đề chính.']),
('input:self-lived',['slow'],False,['No new information appeared, but I kept reopening the same status repeatedly.','The record did not change, yet I revisited it again and again.','I checked the same unchanged state multiple times without any new evidence.','Không có dữ kiện mới nhưng tôi vẫn mở lại cùng trạng thái nhiều lần.','Record không thay đổi, vậy mà tôi cứ quay lại xem đi xem lại.','Tôi kiểm tra cùng một trạng thái lặp lại dù chẳng có thông tin mới.']),
('input:self-lived',[],True,['I moved toward the issue, pulled back, then returned to check again, repeating the loop.','I checked, withdrew, and checked again several times with the same evidence.','I approached it, backed away, then re-entered the same check more than once.','Tôi tiến vào xem, rút ra rồi lại quay vào kiểm tra, lặp lại nhiều vòng.','Tôi kiểm tra, lùi lại, rồi kiểm tra tiếp nhiều lần dù dữ kiện vẫn vậy.','Tôi tiến tới, rút ra rồi quay lại cùng một việc hơn một lần.']),
('input:self-lived',[],False,['I used the available evidence, chose one proportionate action myself, and closed the matter.','I made one reversible decision on my own and did not outsource the choice.','I took a measured step using what I already knew, then stopped reopening the issue.','Tôi dùng dữ kiện sẵn có, tự chọn một bước vừa đủ rồi hoàn tất.','Tôi tự quyết một hành động có thể quay lại và không giao quyền chọn cho ai khác.','Tôi làm một bước hợp lý dựa trên thông tin đã có rồi đóng vấn đề lại.'])]
cases=[];i=1
for gi,(route,fams,seq,surfs) in enumerate(groups):
  for j,surface in enumerate(surfs):
    cases.append({'case_id':f'V187-S{i:03d}','surface':surface,'domain':domains[(gi+j)%len(domains)],'language':'VI' if any(ord(ch)>127 for ch in surface) else 'EN','expected':{'route':route,'families':fams,'sequence':seq}});i+=1
a=[c['case_id'] for n,c in enumerate(cases) if n%2==0];b=[c['case_id'] for n,c in enumerate(cases) if n%2==1]
fixture={'authority':'V8.3.187 V1 SEALED EXECUTION FIXTURE','cases':cases};selection={'authority':'V8.3.187 V1 SEALED SELECTION','batch_a':a,'batch_b':b};membership={'authority':'V8.3.187 V1 SEALED MEMBERSHIP','members':[{'case_id':c['case_id'],'batch':'A' if c['case_id'] in a else 'B'} for c in cases]}
g={}
for c in cases:g.setdefault(json.dumps(c['expected'],sort_keys=True,ensure_ascii=False),[]).append(c['case_id'])
gold={'authority':'V8.3.187 V1 INDEPENDENT GOLD','groups':[{'expected':json.loads(k),'case_ids':v} for k,v in g.items()]}
for n,o in [('V8_3_187_SEALED_FIXTURE_V1.json',fixture),('V8_3_187_SEALED_SELECTION_V1.json',selection),('V8_3_187_SEALED_MEMBERSHIP_V1.json',membership),('V8_3_187_INDEPENDENT_GOLD_V1.json',gold)]:(root/n).write_text(json.dumps(o,ensure_ascii=False,indent=2))