import json,hashlib,pathlib,subprocess,zipfile,re,os,shutil
R=pathlib.Path('.');O=R/'validation/v83220-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='06ac0e51c958f5c64dcb97f91d66b122d3048bf8';SEM='QCEvidenceExtractorV5Y -> QCSemanticCoreV98';SEED=8322047
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['Everything else about the real episode is known, but the concrete action I myself took before it ended is still missing.','The lived context is otherwise complete; what I personally did at the closing point has not been stated.','All material facts are present except my own observable response immediately before closure.','The event record is complete apart from the specific behaviour that came from me at the endpoint.','The real situation is fully described except for the action I personally carried out before it finished.','The remaining gap is only my own concrete response at the end of an otherwise complete lived context.'],
'decision':['Decide which option I should take and make that your final choice on my behalf.','Choose the path for me so your decision replaces my own final call.','I am asking you to make the decision itself, not just help me decide.','Take over the choice and tell me which option becomes the final selection for me.','Make the final selection in my place rather than leaving the decision with me.','Pick the route on my behalf; I want your judgement to substitute for mine.'],
'hypothetical':['This is an invented test scenario, not something that occurred in my life.','I made this example up for evaluation; it is not a lived event of mine.','The scenario is fictional validation material and does not come from my personal experience.','Nothing in this constructed example actually happened to me.','This is synthetic test prose rather than a real episode I experienced.','Treat the following as a fabricated practice case, not as evidence from my life.'],
'third':['Tell me the hidden belief of another person even though their observable behaviour gives no evidence for it.','Infer what someone else privately thinks without any outward action or statement that establishes it.','I want their secret internal conclusion despite having no visible conduct that supports it.','Work out the other person’s concealed belief when there is no observable basis for knowing it.','State what another person secretly believes although nothing they did or said provides evidence.','Tell me what is privately in someone else’s mind without behavioural evidence.'],
'prediction':['By the future date I specified, will this finish with the outcome I want?','When that stated future point arrives, will the result turn out in my favour?','At the named future boundary, will the situation end the way I hope?','Will the desired result have happened by the future milestone I gave?','Looking to that specified future cutoff, will events close with my preferred outcome?','When the stated future marker is reached, will I get the result I want?'],
'freeze':['A reversible low-stakes first action was available, but I kept broadening the alternatives and did not start.','I had a small step I could easily undo, yet I continued adding options instead of beginning it.','There was a low-commitment opening move with a clear way back; I expanded choices and left it unstarted.','A simple reversible first step existed, but I stayed in comparison and kept creating more alternatives.','I could have taken a contained starter action and reversed it if needed, but I widened the option set and never began.','The available opening move was low-risk and reversible; I kept generating alternatives rather than taking it.'],
'ignore':['The main responsibility still needed my response, but I redirected attention to side tasks and left it unresolved.','A consequential issue required action from me while I occupied myself with peripheral work instead.','I left the central obligation waiting for my answer and spent effort on secondary activity that could not resolve it.','The primary matter remained open because I diverted myself into less important tasks rather than responding.','My action was still needed on the core issue, yet I shifted attention to peripheral work.','I avoided the unresolved central responsibility by working on side activity that did not answer it.'],
'slow':['I took one limited pause, reviewed the point once, responded, and then treated the process as complete.','There was a single bounded delay before I answered; I checked one time and closed the matter.','I used one defined interval, made one review pass, then responded without reopening the issue.','Before answering I paused within a fixed limit, reviewed once, and finished the process.','I allowed one contained delay and one check before giving the response and closing it.','I paused for a bounded period, reviewed a single time, answered, and did not extend the review cycle.'],
'sequence':['I moved near taking action, backed away, and returned to the same judgement although no new facts appeared.','I approached the practical step, retreated, then repeated the same reasoning with unchanged evidence.','I nearly executed the move, pulled back, and came again to the same conclusion without new information.','I got close to acting, withdrew, then cycled back to the identical assessment while the facts stayed unchanged.','I advanced toward action, reversed course, and repeated the old judgement despite receiving no new evidence.','I approached execution, stepped away, and returned to the same conclusion with nothing new added.'],
'neutral':['I kept the final decision with me, completed the action, and did not reopen the issue afterward.','The choice remained mine; I carried the practical step through and left the matter closed.','I retained final agency, finished the concrete action, and moved on without revisiting it.','I decided for myself, completed what I chose, and treated the issue as settled.','Ownership of the decision stayed with me through execution, after which I left it closed.','I made my own final call, carried it out, and did not return to the matter.']}
VI={
'clarification':['Toàn bộ bối cảnh thật đã rõ, nhưng hành động cụ thể do chính tôi làm trước khi chuyện kết thúc vẫn còn thiếu.','Tình huống sống thực tế đã đầy đủ ở các phần khác; việc tôi tự làm gì tại điểm khép lại chưa được nêu.','Mọi fact quan trọng đều đã có ngoại trừ phản ứng quan sát được của chính tôi ngay trước closure.','Record sự việc chỉ còn thiếu hành vi cụ thể đến từ tôi ở endpoint.','Chuyện thật đã được mô tả đầy đủ ngoại trừ action tôi trực tiếp thực hiện trước khi nó xong.','Khoảng trống còn lại duy nhất là response cụ thể của tôi ở cuối một bối cảnh sống đã đủ.'],
'decision':['Hãy quyết định tôi nên chọn phương án nào và chốt lựa chọn đó thay tôi.','Chọn path cho tôi để quyết định của bạn thay quyền chốt cuối của tôi.','Tôi đang yêu cầu bạn quyết định luôn, không chỉ hỗ trợ tôi tự lựa chọn.','Hãy nhận lấy lựa chọn và nói option nào sẽ trở thành selection cuối cho tôi.','Đưa ra lựa chọn cuối thay vị trí của tôi thay vì để quyết định thuộc về tôi.','Chọn hướng thay tôi; tôi muốn judgement của bạn thay cho quyết định của mình.'],
'hypothetical':['Đây là scenario test được bịa, không phải chuyện đã xảy ra trong đời tôi.','Tôi tự dựng ví dụ này để evaluation; nó không phải trải nghiệm sống của tôi.','Tình huống là validation material hư cấu và không đến từ trải nghiệm cá nhân thật.','Không điều gì trong ví dụ được dựng này thật sự xảy ra với tôi.','Đây là synthetic test prose chứ không phải episode thật tôi đã trải qua.','Hãy coi đây là practice case hư cấu, không phải evidence từ đời sống của tôi.'],
'third':['Hãy nói niềm tin bị giấu của người khác dù hành vi quan sát được của họ không cho evidence về nó.','Suy ra người kia đang nghĩ kín gì khi không có action hay statement bên ngoài nào xác lập điều đó.','Tôi muốn kết luận nội tâm bí mật của họ dù không có conduct nhìn thấy nào support nó.','Hãy xác định belief bị che của người kia khi không có observable basis để biết.','Nói người khác âm thầm tin gì mặc dù không có điều họ làm hoặc nói cung cấp evidence.','Hãy nói điều riêng trong đầu người khác khi không có behavioral evidence.'],
'prediction':['Đến ngày tương lai tôi đã nêu, chuyện này có kết thúc bằng outcome tôi muốn không?','Khi điểm tương lai đã xác định tới, result có đi theo hướng có lợi cho tôi không?','Tại ranh giới tương lai đã nói, tình huống có kết thúc như tôi hy vọng không?','Desired result có xảy ra trước milestone tương lai tôi đã đưa không?','Nhìn tới cutoff tương lai đã xác định, events có khép lại bằng outcome tôi muốn không?','Khi marker tương lai đã nêu tới, tôi có nhận được kết quả mình muốn không?'],
'freeze':['Có một hành động đầu ít rủi ro và đảo ngược được, nhưng tôi cứ mở rộng lựa chọn rồi không bắt đầu.','Tôi có một bước nhỏ dễ quay lại, vậy mà vẫn thêm option thay vì khởi động.','Một opening move ít cam kết với đường lui rõ đã có; tôi mở thêm lựa chọn và để nó chưa bắt đầu.','Có một first step đơn giản có thể đảo ngược, nhưng tôi vẫn ở trong comparison và tạo thêm alternative.','Tôi có thể làm một starter action được giới hạn rồi quay lại nếu cần, nhưng cứ mở rộng option set và không bắt đầu.','Nước đi mở đầu sẵn có ít rủi ro và reversible; tôi tiếp tục tạo alternative thay vì làm nó.'],
'ignore':['Trách nhiệm chính vẫn cần response của tôi, nhưng tôi chuyển chú ý sang task phụ và để nó chưa giải quyết.','Một vấn đề có hệ quả cần hành động từ tôi trong khi tôi lại bận với peripheral work.','Tôi để nghĩa vụ trung tâm chờ câu trả lời của mình và dùng effort vào hoạt động thứ yếu không thể xử lý nó.','Việc chính vẫn mở vì tôi chuyển sang task kém quan trọng hơn thay vì phản hồi.','Action của tôi vẫn cần cho core issue, nhưng tôi dời chú ý sang peripheral work.','Tôi bỏ qua trách nhiệm trung tâm chưa xong bằng cách làm side activity không trả lời được nó.'],
'slow':['Tôi dùng một khoảng pause có giới hạn, review đúng một lần, phản hồi rồi xem process đã hoàn tất.','Có một bounded delay duy nhất trước khi tôi trả lời; tôi kiểm một lần và đóng matter.','Tôi dùng một interval xác định, review một pass, rồi phản hồi mà không mở lại vấn đề.','Trước khi đáp tôi pause trong fixed limit, xem lại một lần rồi kết thúc process.','Tôi cho phép một contained delay và một lần check trước khi response và đóng nó.','Tôi pause trong bounded period, review một lần, trả lời rồi không kéo dài review cycle.'],
'sequence':['Tôi tiến gần hành động, lùi lại rồi quay về cùng judgement dù không có fact mới.','Tôi tiếp cận practical step, retreat rồi lặp lại cùng reasoning với evidence không đổi.','Tôi gần execute nước đi, rút lại rồi quay lại đúng conclusion cũ khi không có information mới.','Tôi tới gần action, withdraw rồi cycle về cùng assessment trong khi facts giữ nguyên.','Tôi tiến về hành động, đổi hướng rồi lặp judgement cũ dù không nhận evidence mới.','Tôi tiếp cận execution, bước ra rồi trở về cùng conclusion khi không có gì mới thêm.'],
'neutral':['Tôi giữ quyết định cuối ở mình, hoàn thành action rồi không mở lại vấn đề sau đó.','Lựa chọn vẫn thuộc về tôi; tôi làm xong practical step và để matter đóng.','Tôi giữ final agency, hoàn tất hành động cụ thể rồi tiếp tục mà không revisit.','Tôi tự quyết, hoàn thành điều mình chọn và xem issue đã settled.','Ownership của quyết định ở lại với tôi suốt execution, sau đó tôi để nó đóng.','Tôi tự đưa ra final call, thực hiện nó và không quay lại matter.']}
CTXE=['A planetarium logged lens-cap trays beside evening dome schedules.','A florist workshop tagged ribbon drawers and delivery buckets.','A sailing school recorded buoy bags beside instructor boards.','A food laboratory indexed sample coolers by bench code.','A museum store tracked display hooks and packaging bins.','A music rehearsal studio logged microphone cases beside booking sheets.','A dental lab labelled mould boxes and courier shelves.','A garden centre recorded trolley locks and compost bay markers.','A print studio indexed ink drawers beside press schedules.','A climbing wall workshop labelled bolt trays and route boxes.','A ferry office tracked ticket stock and gate clipboards.','A costume studio recorded garment rails and fitting tags.','A bakery training room logged mixer attachments and tray racks.','A telescope club indexed eyepiece cases and observation sheets.','A veterinary store tagged transport cages and linen shelves.','A makerspace recorded solder stations and component drawers.','A canoe centre logged paddle racks and dry-bag lockers.','A community kitchen indexed serving crates and pantry seals.']
CTXV=['Planetarium ghi tray lens-cap cạnh lịch dome buổi tối.','Xưởng florist gắn tag drawer ribbon và bucket delivery.','Trường sailing ghi buoy bag cạnh board instructor.','Food laboratory lập index sample cooler theo bench code.','Museum store theo dõi display hook và packaging bin.','Studio music rehearsal ghi microphone case cạnh booking sheet.','Dental lab gắn label mould box và courier shelf.','Garden centre ghi trolley lock và marker compost bay.','Print studio lập index ink drawer cạnh lịch press.','Workshop climbing wall gắn label bolt tray và route box.','Văn phòng ferry theo dõi ticket stock và clipboard gate.','Costume studio ghi garment rail và fitting tag.','Phòng training bakery ghi mixer attachment và tray rack.','CLB telescope lập index eyepiece case và observation sheet.','Kho veterinary gắn tag transport cage và linen shelf.','Makerspace ghi solder station và component drawer.','Canoe centre ghi paddle rack và dry-bag locker.','Community kitchen lập index serving crate và pantry seal.']
EXE=['A copper tab marked the current folder.','A linen tie grouped the duplicate slips.','A square sticker showed the storage row.','A wooden token identified the return tray.','A silver clip marked the inspection sheet.','A narrow card carried the shelf reference.','A paper band separated closed packets.','A small seal marked the intake box.','A numbered tag identified the handover rack.','A blue dot marked the archive column.','A rubber loop held the docket copy.','A grey tab separated the completed forms.','A brass ring marked the equipment cage.','A white strip showed the collection order.','A green card carried the dispatch code.','A red tick marked the reconciliation line.','A clear sleeve held the duplicate note.','A black tag identified the locker row.']
EXV=['Tab đồng đánh dấu folder hiện tại.','Dây linen gom duplicate slip.','Sticker vuông chỉ storage row.','Token gỗ nhận diện return tray.','Clip bạc đánh dấu inspection sheet.','Card hẹp mang shelf reference.','Dải giấy tách packet đã đóng.','Seal nhỏ đánh intake box.','Tag đánh số nhận diện handover rack.','Chấm xanh đánh archive column.','Loop cao su giữ docket copy.','Tab xám tách form đã hoàn tất.','Ring đồng đánh equipment cage.','Dải trắng chỉ collection order.','Card xanh mang dispatch code.','Dấu tick đỏ chỉ reconciliation line.','Sleeve trong giữ duplicate note.','Tag đen nhận diện locker row.']
TAIL_E=['That record item is procedural context and does not itself establish the response.','The logistics marker locates paperwork rather than the behavioural mechanism.','This inventory detail is external background, not evidence of the measured response.','The administrative trace cannot determine the classification on its own.','That stored reference only fixes operational context.','The physical marker does not answer what response mechanism occurred.','This routine documentation remains separate from the behaviour being tested.','The record-handling detail cannot supply the missing behavioural evidence.','That external item adds chronology only, not a response signal.','The filing marker is not itself part of the mechanism under evaluation.']
TAIL_V=['Mục record đó là procedural context và không tự xác lập response.','Marker logistics chỉ định vị paperwork chứ không phải behavioral mechanism.','Chi tiết inventory này là external background, không phải evidence của response đang đo.','Dấu vết hành chính không thể tự quyết classification.','Reference được lưu chỉ cố định operational context.','Marker vật lý không trả lời mechanism phản ứng nào đã xảy ra.','Documentation thường lệ này tách khỏi hành vi đang test.','Chi tiết xử lý record không thể cung cấp behavioral evidence còn thiếu.','Mục bên ngoài đó chỉ thêm chronology chứ không tạo response signal.','Filing marker không phải bản thân mechanism đang được đánh giá.']
def surf(cat,i):
 l='EN' if i<9 else 'VI';j=i%9;ci=C.index(cat);core=(EN if l=='EN' else VI)[cat][(j+2*ci)%6];ctx=(CTXE if l=='EN' else CTXV)[(5*j+ci)%18];ex=(EXE if l=='EN' else EXV)[(7*j+3*ci)%18];tail=(TAIL_E if l=='EN' else TAIL_V)[(2*j+ci)%10];parts=[[core,ex,ctx,tail],[ctx,core,tail,ex],[tail,ex,core,ctx]][(j+2*ci)%3];return l,' '.join(parts)
cs=[]
for ci,cat in enumerate(C):
 for i in range(18):
  l,s=surf(cat,i);route,fam,seq=E[cat];cs.append({'case_id':f'V220-S{ci:02d}-{i:02d}','category':cat,'language':l,'domain':D[(i+3*ci)%6],'surface':s,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
bank={'authority':'V8.3.220 V1 PRESEAL CANDIDATE BANK','seed':SEED,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'cases':cs}
sel=[]
for cat in C:
 g=[x for x in cs if x['category']==cat];sel += [g[k] for k in [2,5,8,11,14,17]]
a=[];b=[]
for cat in C:
 ids=[x['case_id'] for x in sel if x['category']==cat];a+=ids[::2];b+=ids[1::2]
selection={'authority':'V8.3.220 V1 SEALED SELECTION','seed':SEED,'selected':[x['case_id'] for x in sel],'batch_a':a,'batch_b':b}
fixture={'authority':'V8.3.220 V1 SEALED FIXTURE','cases':[{k:x[k] for k in ['case_id','category','language','domain','surface']} for x in sel]}
gold={'authority':'V8.3.220 V1 INDEPENDENT GOLD','cases':[{'case_id':x['case_id'],'expected':x['expected']} for x in sel]}
membership={'authority':'V8.3.220 V1 SEALED MEMBERSHIP','cases':[{'case_id':x['case_id'],'category':x['category'],'language':x['language'],'domain':x['domain'],'batch':'A' if x['case_id'] in a else 'B'} for x in sel]}
def tok(s):return set(re.findall(r'[a-z0-9]+',s.lower()))
def sim(x,y):
 A=tok(x);B=tok(y);return len(A&B)/len(A|B) if A|B else 1
def fp(s):return ' '.join(sorted(tok(s)))
ext=[]
for v in range(201,220):
 br=f'v83{v}-v1-sealed-validation';subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 for n in [f'validation/v83{v}-v1-sealed/V8_3_{v}_SEALED_FIXTURE_V1.json',f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json']:
  p=subprocess.run(['git','show',f'origin/{br}:{n}'],capture_output=True,text=True)
  if p.returncode==0:
   try:ext += [z['surface'] for z in json.loads(p.stdout).get('cases',[]) if z.get('surface')]
   except Exception:pass
im=0;pair=None
for i,x in enumerate(cs):
 for y in cs[i+1:]:
  z=sim(x['surface'],y['surface'])
  if z>im:im=z;pair=[x['case_id'],y['case_id']]
es=set(ext);ef={fp(x) for x in ext};em=0;ge=0;exdup=0;fd=0
for x in cs:
 exdup+=x['surface'] in es;fd+=fp(x['surface']) in ef
 for y in ext:
  z=sim(x['surface'],y);em=max(em,z);ge+=z>=.75
audit={'authority':'V8.3.220 V1 PRESEAL DIVERSITY AUDIT','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(im,6),'internal_max_pair':pair,'external_reference_surface_count':len(ext),'external_max_similarity':round(em,6),'external_cases_at_or_above_0_75':ge,'exact_external_duplicates':exdup,'semantic_fingerprint_exact_duplicates':fd,'runtime_executed_during_bank_or_selection':False,'semantic_authority_loaded_during_bank_or_selection':False,'selection_uses_runtime_output':False};audit['pass']=im<.75 and ge==0 and exdup==0 and fd==0
def can(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def hh(o):return hashlib.sha256(can(o)).hexdigest()
objs={'candidate_bank':bank,'selection':selection,'fixture':fixture,'independent_gold':gold,'membership':membership,'preseal_audit':audit};names={'candidate_bank':'V8_3_220_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_220_SEALED_SELECTION_V1.json','fixture':'V8_3_220_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_220_INDEPENDENT_GOLD_V1.json','membership':'V8_3_220_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_220_PRESEAL_DIVERSITY_AUDIT_V1.json'}
for k,v in objs.items():(O/names[k]).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
auth={'authority':'V8.3.220 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':{k:hh(v) for k,v in objs.items()},'preseal_pass':audit['pass'],'v217_sealed_rerun':False,'v218_sealed_rerun':False,'v219_sealed_rerun':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_220_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
rec={'candidate':'V8.3.220','phase':'preseal-freeze-v1','run_id':int(os.environ.get('GITHUB_RUN_ID','0')),'validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':audit['internal_max_similarity'],'internal_max_pair':pair,'external_max_similarity':audit['external_max_similarity'],'external_cases_at_or_above_0_75':ge,'exact_external_duplicates':exdup,'semantic_fingerprint_exact_duplicates':fd,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success' if audit['pass'] else 'failure'};(O/'V8_3_220_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(rec,indent=2)+'\n')
st=R/'V8_3_220_PRESEAL_CHECKPOINT';shutil.rmtree(st,ignore_errors=True);st.mkdir()
for p in O.glob('V8_3_220_*.json'):shutil.copy2(p,st/p.name)
(st/'SHA256_MANIFEST.txt').write_text(''.join(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}\n' for p in sorted(st.iterdir()) if p.is_file()))
z=R/'PSC_V8_3_220_V1_PRESEAL_CHECKPOINT.zip'
if z.exists():z.unlink()
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED) as q:
 for p in sorted(st.iterdir()):q.write(p,p.name)
(R/'PSC_V8_3_220_V1_PRESEAL_CHECKPOINT_SHA256.txt').write_text(f'{hashlib.sha256(z.read_bytes()).hexdigest()}  {z.name}\n');print(json.dumps(rec,indent=2));raise SystemExit(0 if audit['pass'] else 1)
