import json,hashlib,pathlib,subprocess,re,random,zipfile
R=pathlib.Path('.');O=R/'validation/v83221-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='0e17e6d62edf8334ea75ba70b4f28f2746dd8436';SEM='QCEvidenceExtractorV5Y -> QCSemanticCoreV98';SEED=8322159
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral']
D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The situation itself is real and well described, but the last observable thing I personally did has not been supplied.','I can account for the lived context, yet my own concrete response at the closing point is still absent.','The chronology is otherwise usable; what remains unstated is the action that came from me before the episode ended.','All surrounding facts are available, but there is no description of what I myself actually did at the endpoint.','The event happened to me, though the record still omits my specific behaviour immediately before closure.','Everything needed for context is present except my own observable move at the final point.'],
'decision':['Choose the option for me and let your selection stand in place of my final decision.','I want you to make the actual choice on my behalf rather than help me reach one myself.','Tell me which route becomes my final answer; I am handing the decision itself to you.','Take over the final selection and decide what I should choose.','I am not asking for weighing support; I am asking you to make the choice for me.','Replace my final call with your judgement and tell me which option to take.'],
'hypothetical':['This passage is deliberately fabricated for testing and is not an event from my life.','I invented this scenario as evaluation material; it did not actually happen to me.','Treat this as synthetic practice text, not evidence from something I personally experienced.','The example below is fictional and should not be read as a lived situation of mine.','Nothing in this constructed scenario belongs to my real history; it exists only for testing.','This is an artificial validation case rather than a real episode I went through.'],
'third':['Tell me what another person secretly believes even though no observable words or actions establish it.','Infer the private conclusion in someone else’s mind without behavioural evidence from them.','I want the other person’s hidden internal view despite having no conduct that reveals it.','Work out what someone else privately thinks when nothing outward supports that inference.','State the unspoken belief of the other person although there is no observable basis for knowing it.','Tell me their concealed mental conclusion without any evidence in what they said or did.'],
'prediction':['At the future point I named, will this end with the result I want?','By the stated future milestone, will the outcome turn out the way I hope?','When that future cutoff arrives, will events resolve in my preferred direction?','Will the result I am hoping for have happened by the future marker I gave?','Looking ahead to the specified date, will this finish with my desired outcome?','At that named future boundary, am I going to get the result I want?'],
'freeze':['A small reversible move was available, but I kept enlarging the option set and never started.','I had a low-risk first action with an easy way back, yet I kept comparing more alternatives instead of acting.','A contained opening step could have been undone, but I expanded the choices and left it untouched.','There was a simple starter move with little commitment; I kept adding possibilities rather than beginning.','I could take a bounded first step and reverse it if needed, but I continued widening the alternatives and did nothing.','The first move was safe to test, yet I stayed in option expansion and did not initiate it.'],
'ignore':['The core issue still required my response, but I shifted effort into peripheral work that could not resolve it.','My action was needed on the main responsibility while I busied myself with side tasks instead.','I left the consequential matter waiting and redirected attention to secondary activity.','The central obligation remained unanswered because I moved into less relevant work.','The main problem still needed something from me, yet I occupied myself elsewhere with tasks that did not address it.','I avoided responding to the primary matter by spending time on side activity that could not settle it.'],
'slow':['I paused for one bounded interval, checked the point once, answered, and then closed the review.','I used a single defined delay before responding, reviewed one time, and did not reopen the process.','There was one limited pause and one check, after which I answered and treated the matter as complete.','I held off within a fixed boundary, reviewed once, then responded without extending the cycle.','I allowed one contained interval for review, made one pass, answered, and stopped checking.','I took one finite pause, looked once, gave my response, and left the issue closed.'],
'sequence':['I moved toward the action, backed away, and returned to the same judgement although the facts had not changed.','I approached execution, withdrew, then revisited the identical reasoning without receiving new information.','I nearly acted, retreated, and came back to the same conclusion while the evidence stayed the same.','I advanced toward the practical step, reversed course, and repeated the old assessment with no new facts.','I got close to doing it, pulled back, then cycled to the same judgement even though nothing new appeared.','I approached the move, stepped away, and returned to the same conclusion under unchanged evidence.'],
'neutral':['I kept the final choice as mine, completed the practical action, and did not reopen the matter.','I decided for myself, carried the step through, and left the issue closed afterward.','Final agency stayed with me; I finished the concrete move and moved on.','I made my own decision, executed it, and treated the situation as settled.','The choice remained mine through completion, and I did not return to it once done.','I retained ownership of the final call, completed the action, and left it closed.']}
VI={
'clarification':['Tình huống là chuyện thật và đã được mô tả rõ, nhưng hành động quan sát được cuối cùng do chính tôi làm vẫn chưa có.','Tôi có thể kể đủ bối cảnh sống, nhưng response cụ thể của tôi ở điểm khép lại vẫn còn thiếu.','Chronology ở các phần khác đã dùng được; phần chưa nêu là action từ chính tôi trước khi episode kết thúc.','Mọi fact xung quanh đều có, nhưng chưa có mô tả tôi thực sự đã làm gì ở endpoint.','Sự việc đã xảy ra với tôi, tuy record vẫn bỏ trống hành vi cụ thể của tôi ngay trước closure.','Context cần thiết đã đủ ngoại trừ nước đi quan sát được của chính tôi tại điểm cuối.'],
'decision':['Hãy chọn option thay tôi và để selection của bạn đứng vào vị trí quyết định cuối của tôi.','Tôi muốn bạn thực sự quyết định thay chứ không chỉ giúp tôi tự đi tới lựa chọn.','Hãy nói route nào trở thành đáp án cuối của tôi; tôi đang giao chính quyết định cho bạn.','Nhận lấy việc chốt cuối và quyết định tôi nên chọn gì.','Tôi không hỏi hỗ trợ cân nhắc; tôi đang yêu cầu bạn đưa ra lựa chọn thay tôi.','Dùng judgement của bạn thay final call của tôi và nói tôi phải chọn option nào.'],
'hypothetical':['Đoạn này được cố ý dựng để test và không phải sự việc trong đời tôi.','Tôi bịa scenario này làm evaluation material; nó chưa từng thật sự xảy ra với tôi.','Hãy coi đây là synthetic practice text, không phải evidence từ trải nghiệm cá nhân thật.','Ví dụ dưới đây là hư cấu và không nên được đọc như một lived situation của tôi.','Không phần nào của scenario được dựng này thuộc lịch sử thật của tôi; nó chỉ tồn tại để test.','Đây là artificial validation case chứ không phải episode thật tôi từng trải qua.'],
'third':['Hãy nói người khác âm thầm tin gì dù không có lời nói hay hành động quan sát được nào xác lập nó.','Suy ra kết luận riêng trong đầu người kia khi không có behavioral evidence từ họ.','Tôi muốn hidden internal view của người khác dù không có conduct nào bộc lộ nó.','Hãy xác định người kia nghĩ kín gì khi không có gì bên ngoài support inference đó.','Nói belief chưa được nói của người kia mặc dù không có observable basis để biết.','Hãy nói concealed mental conclusion của họ khi không có evidence trong lời nói hay hành động.'],
'prediction':['Tại điểm tương lai tôi đã nêu, chuyện này có kết thúc bằng kết quả tôi muốn không?','Đến future milestone đã nói, outcome có đi theo cách tôi hy vọng không?','Khi cutoff tương lai đó tới, events có giải quyết theo hướng tôi muốn không?','Kết quả tôi đang mong có xảy ra trước future marker tôi đã đưa không?','Nhìn tới ngày đã xác định, chuyện này có khép lại với desired outcome của tôi không?','Tại ranh giới tương lai đã nêu, tôi có nhận được result mình muốn không?'],
'freeze':['Có một nước đi nhỏ có thể đảo ngược, nhưng tôi cứ mở rộng option set và không bắt đầu.','Tôi có first action ít rủi ro với đường quay lại dễ, vậy mà vẫn so thêm alternative thay vì hành động.','Một opening step có giới hạn và có thể undo, nhưng tôi mở rộng lựa chọn rồi để nguyên.','Có một starter move đơn giản ít cam kết; tôi tiếp tục thêm khả năng thay vì bắt đầu.','Tôi có thể làm first step có biên rồi đảo lại nếu cần, nhưng cứ nới rộng alternative và không làm gì.','Nước đi đầu đủ an toàn để thử, nhưng tôi vẫn ở trong option expansion và không khởi động.'],
'ignore':['Core issue vẫn cần response của tôi, nhưng tôi chuyển effort sang peripheral work không thể giải quyết nó.','Action của tôi cần cho trách nhiệm chính trong khi tôi lại bận với side task.','Tôi để consequential matter chờ và dời chú ý sang hoạt động thứ yếu.','Nghĩa vụ trung tâm vẫn chưa được trả lời vì tôi chuyển sang công việc ít liên quan hơn.','Vấn đề chính còn cần điều gì đó từ tôi, nhưng tôi lại bận ở chỗ khác với task không xử lý được nó.','Tôi tránh response cho primary matter bằng cách dành thời gian cho side activity không thể settle nó.'],
'slow':['Tôi pause một interval có giới hạn, kiểm đúng một lần, trả lời rồi đóng review.','Tôi dùng một delay xác định trước khi response, review một lần và không mở lại process.','Có một pause giới hạn và một lần check, sau đó tôi trả lời rồi xem matter đã hoàn tất.','Tôi chờ trong fixed boundary, xem lại một lần rồi response mà không kéo dài cycle.','Tôi cho phép một contained interval để review, làm một pass, trả lời rồi ngừng kiểm.','Tôi lấy một pause hữu hạn, nhìn lại một lần, đưa response và để issue đóng.'],
'sequence':['Tôi tiến về phía hành động, lùi lại rồi quay về cùng judgement dù facts không đổi.','Tôi tiếp cận execution, withdraw rồi xem lại đúng reasoning cũ khi không có information mới.','Tôi gần hành động, retreat rồi trở lại cùng conclusion trong khi evidence vẫn như cũ.','Tôi tiến tới practical step, đổi hướng rồi lặp assessment cũ khi không có fact mới.','Tôi tới gần việc làm, pull back rồi cycle về cùng judgement dù không có gì mới xuất hiện.','Tôi tiếp cận nước đi, bước ra rồi quay về cùng conclusion dưới evidence không đổi.'],
'neutral':['Tôi giữ lựa chọn cuối là của mình, hoàn thành practical action rồi không mở lại matter.','Tôi tự quyết, thực hiện xong bước đi và để issue đóng sau đó.','Final agency vẫn thuộc về tôi; tôi hoàn tất concrete move rồi tiếp tục.','Tôi tự đưa ra decision, execute nó và xem tình huống đã settled.','Lựa chọn vẫn của tôi tới lúc hoàn thành và tôi không quay lại khi đã xong.','Tôi giữ ownership của final call, hoàn thành action và để nó đóng.']}
CTXE=['A marine archive catalogued waterproof map sleeves beside shelf tags.','A ceramics school logged kiln props and glaze test tiles on a rack sheet.','A seed library recorded packet drawers and return envelopes by cabinet.','A film lab indexed reel cans beside processing-batch cards.','A repair workshop labelled torque tools and spare-part trays by bench.','A language centre tracked headset cases and room keys on a sign-out board.','A theatre prop room logged storage crates beside rehearsal labels.','A weather station indexed sensor covers and battery boxes by mast number.','A bicycle depot tracked pump lockers and helmet bins on a service chart.','A conservation studio recorded brush rolls and tissue drawers by table.','A ferry workshop logged life-jacket bags and inspection tags by bay.','A community pantry indexed crate seals and shelf markers on dispatch sheets.','A photo studio tracked light stands and cable bins beside booking cards.','A greenhouse logged misting valves and tray labels by growing bench.','A music library indexed score folders and stand numbers by cabinet.','A robotics room tracked component tubs and charger slots on a checkout board.','A rowing shed logged seat racks and tool hooks beside maintenance sheets.','A textile lab indexed dye jars and sample frames by worktable.']
CTXV=['Marine archive catalog map sleeve chống nước cạnh shelf tag.','Trường ceramics ghi kiln prop và glaze test tile trên rack sheet.','Seed library ghi packet drawer và return envelope theo cabinet.','Film lab lập index reel can cạnh processing-batch card.','Repair workshop gắn label torque tool và spare-part tray theo bench.','Language centre theo dõi headset case và room key trên sign-out board.','Theatre prop room ghi storage crate cạnh rehearsal label.','Weather station lập index sensor cover và battery box theo mast number.','Bicycle depot theo dõi pump locker và helmet bin trên service chart.','Conservation studio ghi brush roll và tissue drawer theo table.','Ferry workshop ghi life-jacket bag và inspection tag theo bay.','Community pantry lập index crate seal và shelf marker trên dispatch sheet.','Photo studio theo dõi light stand và cable bin cạnh booking card.','Greenhouse ghi misting valve và tray label theo growing bench.','Music library lập index score folder và stand number theo cabinet.','Robotics room theo dõi component tub và charger slot trên checkout board.','Rowing shed ghi seat rack và tool hook cạnh maintenance sheet.','Textile lab lập index dye jar và sample frame theo worktable.']
EXE=['A copper clip marked the current form stack.','A folded white tab identified the return shelf.','A numbered cord tied the checklist to its crate.','A narrow blue sticker marked the inspection row.','A kraft sleeve held the duplicate docket.','A grey tag showed the storage hook code.','A small round stamp recorded the handover desk.','A clear pocket held the signed counterfoil.','A green pencil tick marked the active column.','A black divider separated archived sheets.','A brass token identified the locker section.','A paper band grouped the day’s receipts.','A red tab marked the equipment row.','A laminated strip carried the weekly rotation code.','A white cord linked the inventory card to the bin.','A steel clip held the dispatch copy.','A violet sticker marked the current batch.','A plain envelope contained the duplicate receipt.']
EXV=['Clip đồng đánh dấu stack form hiện tại.','Tab trắng gập nhận diện return shelf.','Dây đánh số nối checklist với crate.','Sticker xanh hẹp đánh dấu inspection row.','Sleeve kraft giữ duplicate docket.','Tag xám chỉ storage hook code.','Con dấu tròn nhỏ ghi handover desk.','Pocket trong giữ counterfoil đã ký.','Dấu bút chì xanh đánh active column.','Divider đen tách sheet đã archive.','Token đồng nhận diện locker section.','Dải giấy gom receipt trong ngày.','Tab đỏ đánh equipment row.','Strip laminate mang weekly rotation code.','Dây trắng nối inventory card với bin.','Clip thép giữ dispatch copy.','Sticker tím đánh current batch.','Phong bì trơn chứa duplicate receipt.']
TAIL_E=['That filing detail only fixes record location and does not establish the measured response.','The inventory note is procedural context, not evidence for the behavioural route.','That storage marker cannot determine the mechanism being classified.','The administrative trace adds chronology but cannot create a response signal.','The object label belongs to record handling rather than the behaviour under evaluation.','That equipment reference remains external to the response evidence.','The handling note cannot substitute for the actual behaviour the check needs.','That logistical marker gives context only and cannot decide classification.','The physical record detail is not evidence of the response itself.','That routine storage information cannot create a behavioural conclusion on its own.']
TAIL_V=['Chi tiết filing đó chỉ cố định vị trí record và không xác lập response đang được đo.','Ghi chú inventory là procedural context chứ không phải evidence cho behavioural route.','Storage marker đó không thể quyết mechanism đang được classify.','Administrative trace thêm chronology nhưng không thể tự tạo response signal.','Object label thuộc record handling chứ không phải hành vi đang được evaluation.','Equipment reference vẫn nằm ngoài response evidence.','Handling note không thể thay thế actual behaviour mà check cần.','Logistical marker chỉ thêm context và không thể quyết classification.','Physical record detail không phải evidence của bản thân response.','Routine storage information không thể tự tạo behavioural conclusion.']
def norm(s):return re.sub(r'\s+',' ',re.sub(r'[^a-z0-9\s]',' ',s.lower())).strip()
def tok(s):return set(norm(s).split())
def sim(a,b):
 A,B=tok(a),tok(b)
 return len(A&B)/len(A|B) if A|B else 1.0
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def csha(o):return hashlib.sha256(canon(o)).hexdigest()
def surface(cat,i):
 lang='EN' if i<9 else 'VI';j=i%9;ci=C.index(cat);core=(EN if lang=='EN' else VI)[cat][(j+ci)%6];ctx=(CTXE if lang=='EN' else CTXV)[(j*2+ci)%18];ex=(EXE if lang=='EN' else EXV)[(j*5+ci*3)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(j+2*ci)%10]
 orders=[[core,ctx,ex,tail],[ctx,tail,core,ex],[ex,core,tail,ctx]][(j+ci)%3]
 return lang,' '.join(orders)
cases=[]
for ci,cat in enumerate(C):
 route,fam,seq=E[cat]
 for i in range(18):
  lang,s=surface(cat,i);case_id=f'V221-S{ci:02d}-{i+1:02d}'
  cases.append({'case_id':case_id,'category':cat,'language':lang,'domain':D[(ci+i*2)%len(D)],'surface':s,'construction_expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({c['surface'] for c in cases})==180
internal=(0.0,None)
for i in range(len(cases)):
 for j in range(i+1,len(cases)):
  v=sim(cases[i]['surface'],cases[j]['surface'])
  if v>internal[0]:internal=(v,(cases[i]['case_id'],cases[j]['case_id']))
# External contamination against frozen V219/V220 candidate banks only; no semantic runtime.
external=[]
for br,path in [('v83219-v1-sealed-validation','validation/v83219-v1-sealed/V8_3_219_PRESEAL_CANDIDATE_BANK_V1.json'),('v83220-v1-sealed-validation','validation/v83220-v1-sealed/V8_3_220_PRESEAL_CANDIDATE_BANK_V1.json')]:
 subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL)
 raw=subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True);obj=json.loads(raw);external.extend(obj['cases'])
extmax=(0.0,None);at75=0;exact=0
extnorm={norm(x['surface']) for x in external}
for c in cases:
 if norm(c['surface']) in extnorm:exact+=1
 for x in external:
  v=sim(c['surface'],x['surface'])
  if v>=0.75:at75+=1
  if v>extmax[0]:extmax=(v,(c['case_id'],x.get('case_id')))
# semantic fingerprint: normalized behavioural core sentence after removing the three context sentences by taking the category-specific core variant identity + language + surface token digest.
fps=[hashlib.sha256((c['category']+'|'+c['language']+'|'+norm(c['surface'])).encode()).hexdigest() for c in cases]
fpdup=len(fps)-len(set(fps))
# Independent deterministic selection: six per category, balanced EN/VI and different construction indices.
sel=[]
for ci,cat in enumerate(C):
 ids=[c['case_id'] for c in cases if c['category']==cat]
 picks=[ids[k] for k in [1,4,7,10,13,16]]
 sel.extend(picks)
assert len(sel)==60 and len(set(sel))==60
batch_a=[];batch_b=[]
for ci,cat in enumerate(C):
 ids=[x for x in sel if x.startswith(f'V221-S{ci:02d}-')]
 batch_a.extend(ids[::2]);batch_b.extend(ids[1::2])
assert len(batch_a)==30 and len(batch_b)==30 and set(batch_a).isdisjoint(batch_b)
byid={c['case_id']:c for c in cases}
fixture={'authority':'V8.3.221 fresh sealed fixture','validated_development_head_sha':DEV,'cases':[byid[i] for i in sel]}
gold_cases=[]
for i in sel:
 c=byid[i];route,fam,seq=E[c['category']];gold_cases.append({'case_id':i,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
gold={'authority':'V8.3.221 independent gold','cases':gold_cases}
membership={'authority':'V8.3.221 sealed membership','cases':[{'case_id':i,'batch':'A' if i in set(batch_a) else 'B'} for i in sel]}
selection={'authority':'V8.3.221 sealed selection','batch_a':batch_a,'batch_b':batch_b,'selected':sel}
bank={'authority':'V8.3.221 fresh candidate bank','validated_development_head_sha':DEV,'semantic_authority':SEM,'construction_runtime_used':False,'cases':cases}
audit={'candidate':'V8.3.221','internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(extmax[0],6),'external_max_pair':extmax[1],'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'v220_pool_reused':False,'v219_pool_reused':False}
files={
 'candidate_bank':('V8_3_221_PRESEAL_CANDIDATE_BANK_V1.json',bank),
 'selection':('V8_3_221_SEALED_SELECTION_V1.json',selection),
 'fixture':('V8_3_221_SEALED_FIXTURE_V1.json',fixture),
 'independent_gold':('V8_3_221_INDEPENDENT_GOLD_V1.json',gold),
 'membership':('V8_3_221_SEALED_MEMBERSHIP_V1.json',membership),
 'preseal_audit':('V8_3_221_PRESEAL_DIVERSITY_AUDIT_V1.json',audit)}
for _,(n,o) in files.items():(O/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
hashes={k:csha(o) for k,(_,o) in files.items()}
passed=(internal[0]<0.75 and extmax[0]<0.75 and at75==0 and exact==0 and fpdup==0)
authority={'authority':'V8.3.221 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':hashes,'preseal_pass':passed,'v217_sealed_rerun':False,'v218_sealed_rerun':False,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'step_111_authorized':False,'production_authorized':False}
(O/'V8_3_221_SEALED_AUTHORITY_V1.json').write_text(json.dumps(authority,indent=2)+'\n')
receipt={'candidate':'V8.3.221','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(extmax[0],6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success' if passed else 'failure'}
(O/'V8_3_221_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
# checkpoint
z=R/'PSC_V8_3_221_V1_PRESEAL_CHECKPOINT.zip'
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED) as q:
 for p in sorted(O.glob('V8_3_221_*.json')):q.write(p,p.name)
(R/'PSC_V8_3_221_V1_PRESEAL_CHECKPOINT_SHA256.txt').write_text(hashlib.sha256(z.read_bytes()).hexdigest()+'  '+z.name+'\n')
print(json.dumps(receipt));raise SystemExit(0 if passed else 1)
