import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83235-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='4c58dbbd7315719093e58eb01ac18acec8cdb6fd';SEM='QCEvidenceExtractorV5AK -> QCSemanticCoreV110'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The episode happened to me and its background is clear, but the last thing I personally did is not stated.','This is a real situation with enough context; my own closing action is the missing part.','The lived account is otherwise complete, yet the concrete response from me at the end is absent.','I can explain what happened around the event, but not the observable step I took as it finished.','The situation is real and described; what remains unknown is my personal endpoint behaviour.','Everything needed about the real episode is present except my own final response.'],
'decision':['Take ownership of the decision and pick the option that becomes final.','Choose the actual route for me rather than only helping me assess the alternatives.','I am transferring the deciding call to you; make the choice that stands.','Make the final selection itself so the decision comes from you instead of me.','I want you to decide which option becomes my final choice, not merely advise me.','The deciding act is yours here; select the route that will count as my decision.'],
'hypothetical':['This is synthetic test material and does not come from any event in my life.','I invented the scenario for evaluation; it is not something I experienced.','The example is artificial validation text rather than personal evidence.','Nothing described here happened to me; this is a constructed assessment case.','This scenario is fictional practice input with no autobiographical event behind it.','I made this up solely for testing, not from lived experience.'],
'third':['Tell me the hidden belief of the other person although nothing observable from them supports it.','Infer their private conclusion without any words or actions establishing that view.','Describe what someone else secretly believes when there is no behavioural basis from them.','Work out the concealed thought in the other person’s mind despite no outward evidence.','State their internal belief even though their conduct gives no observable support.','Give me someone else’s private conclusion when nothing they said or did substantiates it.'],
'prediction':['By the future date I specified, will the outcome I want be there?','When that later checkpoint arrives, will this resolve in my favour?','At the future milestone I named, will I have the result I am hoping for?','Will the desired outcome exist by the future boundary I gave?','Looking ahead to that stated deadline, will things end the way I want?','Once that future point arrives, will the preferred result have happened?'],
'freeze':['I had a small reversible opening step, but kept expanding the alternatives until I never started.','A bounded starter action with an easy exit was available; I added options and stayed inactive.','I could have tested one low-commitment move, yet comparison widened instead of action beginning.','There was a contained first step I could undo, but more possibilities replaced initiation.','A reversible trial move was ready; I broadened the choice set and made no start.','I had an easy-to-reverse first action, but kept generating options and remained still.'],
'ignore':['The main issue still needed my response, but I redirected attention into side work that could not resolve it.','An important responsibility remained unanswered while I occupied myself with peripheral tasks.','The central matter stayed unresolved because I shifted effort to secondary activity.','Something consequential required action from me, yet I kept busy with less relevant work.','The core obligation was waiting for my response while I diverted into side tasks.','My response was still needed on the important matter, but I focused on work that did not address it.'],
'slow':['I took one clearly bounded pause, checked once, responded, and then closed the matter.','There was one finite delay and one review before I answered and stopped revisiting it.','I paused inside a fixed limit, reviewed a single time, replied, and did not reopen the issue.','Before responding I used one contained interval and one check, then left the matter settled.','I allowed one defined pause, made one review, gave my response, and moved on.','I delayed once within a clear boundary, checked once, answered, and ended the review.'],
'sequence':['I moved toward the action, pulled back, then returned to the same conclusion without new facts.','I approached execution, retreated, and repeated the prior judgement although no new evidence appeared.','I came close to acting, stepped away, then cycled back to the same reasoning with no new information.','I nearly carried it out, reversed course, and revisited the old assessment while nothing changed.','I advanced toward the practical move, withdrew, then repeated the same conclusion without additional evidence.','I got close to doing it, backed out, and returned to prior reasoning despite no new facts.'],
'neutral':['I kept the decision with me, carried it out, and left the matter closed.','I chose for myself, completed the action, and did not reopen the issue.','Final agency stayed mine through execution; afterward I moved on.','I retained ownership of the choice, executed it, and treated the matter as settled.','I made my own final call, finished the action, and left the issue resolved.','The decision remained mine; I completed it and did not return to the choice process.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A violin workshop logged bow wraps and bridge tags by cabinet.','A climbing archive indexed carabiner cards and rope labels by wall.','A botanical classroom tracked pot markers and mist valves by bay.','A glass studio recorded cutter sleeves and kiln notes by bench.','A film archive catalogued reel cans and cue labels by shelf.','A baking classroom logged mixer cards and tray clips by station.','A sailing loft indexed sail ties and buckle kits by rack.','A costume room tracked garment bags and prop cards by locker.','A textile lab recorded spindle boxes and loom tags by table.','A stargazing club catalogued eyepiece caps and tripod screws by case.','A drafting room logged tube straps and ruler weights by drawer.','A podcast booth indexed cable loops and ear pads by cabinet.','A herbarium room tracked specimen sheets and drying boards by shelf.','A rowing shed recorded seat rails and collar clips by board.','A dance archive catalogued shoe pouches and costume tags by rail.','A repair classroom logged socket cases and part slips by bench.','A culinary studio indexed utensil trays and pantry labels by shelf.','A bookbinding room tracked awl sleeves and thread cards by drawer.']
CTXV=[x.replace('A ','Một ').replace('An ','Một ') for x in CTXE]
TAIL_E=['That inventory detail is only setting and cannot establish the response.','The storage note is logistical background, not behavioural evidence.','That equipment reference does not determine the semantic mechanism.','The filing detail supplies context only, not proof of the response.','That physical record is outside the behavioural evidence.','The administrative note cannot decide the classification.']
TAIL_V=['Inventory detail đó chỉ là setting, không establish response.','Storage note chỉ là logistical background, không behavioural evidence.','Equipment reference không determine semantic mechanism.','Filing detail chỉ supply context, không proof response.','Physical record nằm ngoài behavioural evidence.','Administrative note không decide classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*5+j*2)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*13+j*5)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*3+j)%6];parts=[core,ctx,tail];rot=(ci+j*2)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V235-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*3+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V235-S{ci:02d}-{j:02d}' for j in [1,5,8,10,13,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
(O/'V8_3_235_PRESEAL_CANDIDATE_BANK_V1.json').write_text(json.dumps({'authority':'V8.3.235 PRESEAL CANDIDATE BANK V1','cases':cases},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_235_SEALED_SELECTION_V1.json').write_text(json.dumps({'candidate':'V8.3.235','selected':selected,'batch_a':A,'batch_b':B},indent=2)+'\n')
(O/'V8_3_235_SEALED_FIXTURE_V1.json').write_text(json.dumps({'candidate':'V8.3.235','cases':fixture},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_235_INDEPENDENT_GOLD_V1.json').write_text(json.dumps({'candidate':'V8.3.235','cases':gold},indent=2)+'\n')
(O/'V8_3_235_SEALED_MEMBERSHIP_V1.json').write_text(json.dumps({'candidate':'V8.3.235','batch_a':A,'batch_b':B},indent=2)+'\n')
audit={'candidate':'V8.3.235','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
(O/'V8_3_235_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={'candidate_bank':ho(json.loads((O/'V8_3_235_PRESEAL_CANDIDATE_BANK_V1.json').read_text())),'selection':ho(json.loads((O/'V8_3_235_SEALED_SELECTION_V1.json').read_text())),'fixture':ho(json.loads((O/'V8_3_235_SEALED_FIXTURE_V1.json').read_text())),'independent_gold':ho(json.loads((O/'V8_3_235_INDEPENDENT_GOLD_V1.json').read_text())),'membership':ho(json.loads((O/'V8_3_235_SEALED_MEMBERSHIP_V1.json').read_text())),'preseal_audit':ho(audit)}
auth={'candidate':'V8.3.235','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False}
(O/'V8_3_235_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.235','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'}
(O/'V8_3_235_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
