import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83234-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='6486a01fe4db04ad9594af67a8401d5340d54720';SEM='QCEvidenceExtractorV5AJ -> QCSemanticCoreV109'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The event itself is real and the context is clear, but what I personally did at the final moment is still missing.','This happened to me and the circumstances are known; my own observable closing response has not been stated.','The lived episode is otherwise complete, except for the concrete action that came from me at the end.','Everything around the situation is available, but my personal endpoint behaviour is absent.','I can describe the real sequence, yet I have not supplied my own last action before it closed.','The account is about a real experience; only my actual response at the finish remains unspecified.'],
'decision':['Take the deciding act itself from me and choose which option becomes final.','I want the selection to come from you, not advice on how I should choose.','Make the actual choice on my behalf so your decision replaces mine.','Pick the final route itself instead of simply helping me compare alternatives.','I am giving you ownership of the deciding call; choose the option that stands.','Use your judgement to make the final choice in place of my own decision.'],
'hypothetical':['This is fabricated assessment text, not a report of anything that happened to me.','The scenario was invented for testing and has no autobiographical event behind it.','Nothing here comes from my life; it is synthetic validation material.','This example is deliberately constructed and does not describe a lived experience.','Treat the text as a fictional practice case rather than personal evidence.','I created this artificial example only for evaluation, not from something I experienced.'],
'third':['Tell me the private belief inside the other person when nothing observable from them supports it.','Infer someone else’s hidden conclusion despite no words or actions that establish it.','State what the other person secretly thinks without behavioural evidence from them.','Work out their concealed internal view even though their outward conduct gives no basis.','Describe the private conclusion in someone else’s mind when there is no observable support.','Give me the other person’s hidden belief although nothing they said or did substantiates it.'],
'prediction':['By the future date I named, will the result I want have occurred?','When that future checkpoint arrives, will the situation end in my favour?','At the future milestone I specified, will I get the outcome I am hoping for?','Will the preferred outcome exist by the future cutoff I gave?','Looking ahead to that future boundary, will things resolve the way I want?','Once the future point is reached, will the desired result be there?'],
'freeze':['A reversible opening move was available, yet I kept adding alternatives and never began.','I had a bounded first step with an easy way back, but option growth kept me inactive.','There was a contained starter action I could undo; I widened the choices instead of starting.','The initial move was low-commitment and reversible, but I kept expanding possibilities and made no start.','I could have tested one safe first action, yet broader comparison left me still.','A small reversible starter was ready, but I generated more options and did not initiate it.'],
'ignore':['The central matter still needed my response, but I redirected effort into secondary work that could not settle it.','An important obligation remained unanswered while I focused on side activity.','The main issue stayed unresolved because I diverted attention into less relevant tasks.','Something consequential required action from me, yet I occupied myself with peripheral work.','The core responsibility was waiting for my response while I shifted into secondary activity.','My action was still needed on the important matter, but I used side work instead of addressing it.'],
'slow':['I used one bounded pause, reviewed once, responded, and then left the matter closed.','There was a single finite delay and one check before I answered and stopped reviewing.','I paused within a clear limit, made one review pass, replied, and did not reopen the issue.','Before answering I took one contained interval, checked once, then ended the review process.','I allowed one defined pause and one review, gave my response, and moved on.','I delayed once inside a fixed boundary, checked once, answered, and left it closed.'],
'sequence':['I moved toward acting, pulled back, then returned to the same conclusion with no new information.','I approached execution, withdrew, and repeated the earlier judgement despite no new evidence.','I got close to the practical move, retreated, then cycled back to identical reasoning without new facts.','I nearly acted, reversed course, and revisited the same assessment while nothing had changed.','I advanced toward the action, stepped away, then repeated the same conclusion with no additional evidence.','I came close to doing it, backed out, and returned to prior reasoning although no new information appeared.'],
'neutral':['I kept the final decision with me, carried it out, and left the matter settled.','I chose for myself, completed the action, and moved on without reopening it.','Final agency remained mine through execution; afterward I treated the issue as closed.','I retained ownership of the choice, executed it, and did not return to the decision.','I made my own final call, finished what I chose, and left the issue resolved.','The decision stayed mine; I completed it and did not revisit the matter.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ').replace('the ','the ') for x in v] for k,v in EN.items()}
CTXE=['A print room logged roller sleeves and ink cards by cabinet.','A climbing school indexed harness tags and chalk bags by wall.','A music archive tracked score folders and tuning clips by shelf.','A greenhouse room recorded tray labels and mist nozzles by bay.','A pottery lab catalogued carving tools and glaze tiles by bench.','A photo classroom logged filter wallets and tripod plates by drawer.','A pastry room indexed proofing cards and scraper bins by station.','A sailing shed tracked buckle kits and rope labels by rack.','A costume archive recorded garment sleeves and cue cards by locker.','A weaving room catalogued shuttle boxes and loom pegs by table.','An astronomy club logged lens caps and mount bolts by case.','A chart room indexed map tubes and paper weights by drawer.','An audio booth tracked cable loops and headset pads by cabinet.','A specimen room recorded plant sleeves and drying sheets by shelf.','A rowing store catalogued seat bolts and oar clips by board.','A dance studio logged shoe bags and costume labels by rail.','A repair room indexed wrench trays and parts packets by bench.','A cookery class tracked utensil boxes and pantry cards by shelf.']
CTXV=[x.replace('A ','Một ').replace('An ','Một ') for x in CTXE]
TAIL_E=['That inventory note is background only and cannot establish the response.','The storage reference is logistical context, not behavioural evidence.','That equipment detail cannot determine the semantic route.','The filing record adds setting only, not proof of the mechanism.','That physical item sits outside the response evidence.','The administrative detail cannot decide the classification.']
TAIL_V=['Inventory note đó chỉ là background, không establish response.','Storage reference chỉ là logistical context, không behavioural evidence.','Equipment detail không determine semantic route.','Filing record chỉ add setting, không proof mechanism.','Physical item nằm ngoài response evidence.','Administrative detail không decide classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*4+j*3)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*11+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*2+j)%6];parts=[core,ctx,tail];rot=(ci*2+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V234-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*5+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V234-S{ci:02d}-{j:02d}' for j in [0,4,7,11,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
(O/'V8_3_234_PRESEAL_CANDIDATE_BANK_V1.json').write_text(json.dumps({'authority':'V8.3.234 PRESEAL CANDIDATE BANK V1','cases':cases},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_234_SEALED_SELECTION_V1.json').write_text(json.dumps({'candidate':'V8.3.234','selected':selected,'batch_a':A,'batch_b':B},indent=2)+'\n')
(O/'V8_3_234_SEALED_FIXTURE_V1.json').write_text(json.dumps({'candidate':'V8.3.234','cases':fixture},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_234_INDEPENDENT_GOLD_V1.json').write_text(json.dumps({'candidate':'V8.3.234','cases':gold},indent=2)+'\n')
(O/'V8_3_234_SEALED_MEMBERSHIP_V1.json').write_text(json.dumps({'candidate':'V8.3.234','batch_a':A,'batch_b':B},indent=2)+'\n')
audit={'candidate':'V8.3.234','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
(O/'V8_3_234_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={'candidate_bank':ho(json.loads((O/'V8_3_234_PRESEAL_CANDIDATE_BANK_V1.json').read_text())),'selection':ho(json.loads((O/'V8_3_234_SEALED_SELECTION_V1.json').read_text())),'fixture':ho(json.loads((O/'V8_3_234_SEALED_FIXTURE_V1.json').read_text())),'independent_gold':ho(json.loads((O/'V8_3_234_INDEPENDENT_GOLD_V1.json').read_text())),'membership':ho(json.loads((O/'V8_3_234_SEALED_MEMBERSHIP_V1.json').read_text())),'preseal_audit':ho(audit)}
auth={'candidate':'V8.3.234','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False}
(O/'V8_3_234_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.234','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'}
(O/'V8_3_234_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
