import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83230-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='695b3ec998c73be2a0c0f45bcdcd29821ed112d6';SEM='QCEvidenceExtractorV5AG -> QCSemanticCoreV106'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The event is real and I know the lead-up, but I have not said what action I myself took at the final moment.','I can describe the lived situation around its ending, yet my own concrete closing response is still missing.','This actually happened; the context is known, but the last observable thing I did has not been stated.','The sequence of the real episode is clear except for the behaviour that came from me at closure.','I have supplied the surrounding facts from a lived event, not the action I personally took just before it ended.','Everything needed about the real situation is present apart from my own endpoint behaviour.'],
'decision':['Choose the route for me so your call becomes the choice I act on.','I want you to make the final decision itself, rather than help me make it.','Select the option on my behalf so your judgement replaces mine.','Take the choice out of my hands and decide which course becomes final.','Use your call as the decision I follow instead of leaving the final selection with me.','Pick the outcome of the choice for me; I am handing over decision ownership.'],
'hypothetical':['This is invented assessment text and does not describe anything that happened in my life.','I made this scenario only as a test example; there is no real event behind it.','Treat this as fictional validation material rather than a personal experience.','The case is constructed practice input, not something I actually lived through.','Nothing in this scenario is autobiographical; it was written solely for testing.','This example is artificial and unrelated to any event I experienced.'],
'third':['Tell me what the other person privately believes even though they gave no observable evidence for it.','Infer someone else’s hidden conclusion when none of their words or actions establishes it.','Work out the private view in their mind despite no outward behaviour supporting the claim.','State what the other person secretly thinks when there is no observable basis from them.','Give me their internal conclusion although nothing they said or did demonstrates it.','Describe the concealed belief of someone else without any behavioural evidence from that person.'],
'prediction':['By the future date I named, will I have the outcome I want?','When that future checkpoint arrives, will events have resolved in my favour?','At the future milestone I specified, will the desired result be true?','Will things end the way I hope by the future cutoff I gave?','Looking ahead to my stated future boundary, will the preferred outcome happen?','Once the named future point is reached, will I get the result I want?'],
'freeze':['A reversible first step was available, but I kept adding options and never started it.','I could have tried a small move with an easy way back; instead I widened the choice set and stayed inactive.','There was a low-commitment opening action, yet comparison kept expanding and no start happened.','One contained step could have been tested and undone, but more possibilities replaced initiation.','The starter move was low risk and reversible; I generated alternatives until I did nothing.','I had a bounded first action with a clear exit, but option growth kept me from beginning.'],
'ignore':['The main issue still needed my response, but I redirected effort into side work that could not solve it.','A central responsibility was waiting for action from me while I occupied myself with peripheral tasks.','The important matter stayed unanswered because I shifted attention to secondary work instead.','My response was still required on the core issue, yet I diverted into less relevant activity.','The primary obligation remained unresolved while I kept busy with tasks that did not address it.','Something consequential still needed action from me, but I used side activity to avoid answering it.'],
'slow':['I took one bounded pause, checked once, responded, and then stopped reviewing the issue.','There was one finite delay and one review before I answered and closed the matter.','I paused within a clear limit, reviewed a single time, replied, and did not reopen it.','Before responding I allowed one contained interval and one check, then treated the process as finished.','I used one defined delay, made one review pass, gave my response, and left it closed.','I paused once inside a fixed boundary, checked once, answered, and ended the review cycle.'],
'sequence':['I moved toward the action, pulled back, then returned to the same judgement without new evidence.','I got close to execution, stepped away, and repeated the earlier reasoning although nothing changed.','I approached doing it, retreated, then came back to the same conclusion with no new facts.','I nearly acted, reversed course, and cycled back to my prior assessment while the evidence stayed unchanged.','I advanced toward the move, backed out, then revisited the same reasoning with no additional information.','I came close to carrying it out, withdrew, and repeated the same judgement despite no new evidence.'],
'neutral':['I made the final decision myself, completed the action, and left the matter closed.','The choice stayed mine; I carried it out and moved on once it was done.','I kept final agency, executed what I chose, and did not reopen the issue afterward.','I made my own call through completion and treated the situation as settled.','Decision ownership remained with me; I finished the action and did not return to it.','I chose for myself, completed what I decided, and left the issue resolved.']}
VI={
'clarification':['Event này là thật và tôi biết lead-up, nhưng chưa nói action chính tôi làm ở final moment.','Tôi mô tả được lived situation quanh ending, nhưng concrete closing response của tôi vẫn thiếu.','Chuyện này thực sự xảy ra; context đã biết nhưng observable thing cuối tôi làm chưa được nêu.','Sequence của real episode rõ trừ behaviour đến từ tôi ở closure.','Tôi đã đưa surrounding facts từ lived event nhưng chưa đưa action chính tôi làm ngay trước ending.','Mọi thứ cần về real situation đều có trừ endpoint behaviour của chính tôi.'],
'decision':['Chọn route thay tôi để call của bạn trở thành choice tôi sẽ làm theo.','Tôi muốn bạn make final decision luôn chứ không chỉ giúp tôi tự quyết.','Select option on my behalf để judgement của bạn replace mine.','Lấy choice khỏi tay tôi và decide course nào thành final.','Dùng call của bạn làm decision tôi follow thay vì để final selection ở tôi.','Pick outcome của choice cho tôi; tôi đang hand over decision ownership.'],
'hypothetical':['Đây là invented assessment text và không describe chuyện nào xảy ra trong đời tôi.','Tôi tạo scenario chỉ như test example; không có real event phía sau.','Hãy coi đây là fictional validation material chứ không phải personal experience.','Case là constructed practice input, không phải thứ tôi actually lived through.','Không gì trong scenario là autobiographical; nó chỉ được viết để testing.','Example này artificial và không liên quan event tôi experienced.'],
'third':['Nói người kia privately believes gì dù họ không đưa observable evidence.','Suy ra hidden conclusion của người khác khi không words hay actions nào establish nó.','Xác định private view trong đầu họ dù không outward behaviour support claim.','Nói người kia secretly thinks gì khi không có observable basis từ họ.','Cho tôi internal conclusion của họ dù không điều họ nói hay làm demonstrate nó.','Mô tả concealed belief của người khác khi không có behavioural evidence từ người đó.'],
'prediction':['Đến future date tôi nêu, tôi có outcome mình muốn không?','Khi future checkpoint đó tới, events có resolve in my favour không?','Tại future milestone đã specify, desired result có true không?','Things có end như tôi hope trước future cutoff tôi đưa không?','Nhìn tới stated future boundary, preferred outcome có happen không?','Khi named future point tới, tôi có get result mình muốn không?'],
'freeze':['Có reversible first step nhưng tôi cứ thêm option rồi không start.','Tôi có thể thử small move với easy way back; thay vào đó tôi widen choice set và inactive.','Có low-commitment opening action nhưng comparison expand và không start.','Một contained step có thể test rồi undo, nhưng possibility thêm vào thay initiation.','Starter move low risk và reversible; tôi generate alternative tới mức không làm gì.','Tôi có bounded first action với clear exit nhưng option growth ngăn tôi begin.'],
'ignore':['Main issue vẫn cần response của tôi nhưng tôi redirect effort sang side work không solve được nó.','Central responsibility đang chờ action từ tôi trong khi tôi occupy với peripheral task.','Important matter vẫn unanswered vì tôi shift attention sang secondary work.','Response của tôi vẫn required ở core issue nhưng tôi divert vào less relevant activity.','Primary obligation vẫn unresolved trong lúc tôi busy với task không address nó.','Một consequential matter vẫn cần action từ tôi nhưng tôi dùng side activity để avoid answering.'],
'slow':['Tôi lấy một bounded pause, check một lần, response rồi stop reviewing issue.','Có one finite delay và one review trước khi tôi answer rồi close matter.','Tôi pause trong clear limit, review một lần, reply rồi không reopen.','Trước response tôi cho một contained interval và one check rồi xem process finished.','Tôi dùng one defined delay, make one review pass, đưa response rồi để closed.','Tôi pause một lần trong fixed boundary, check một lần, answer rồi end review cycle.'],
'sequence':['Tôi move toward action, pull back rồi quay lại same judgement khi không new evidence.','Tôi gần execution, step away rồi repeat earlier reasoning dù nothing changed.','Tôi approach doing it, retreat rồi come back same conclusion khi no new facts.','Tôi nearly acted, reverse course rồi cycle về prior assessment khi evidence unchanged.','Tôi advance toward move, back out rồi revisit same reasoning khi không additional information.','Tôi gần carry it out, withdraw rồi repeat same judgement dù no new evidence.'],
'neutral':['Tôi tự make final decision, complete action rồi để matter closed.','Choice vẫn ở tôi; tôi carry it out rồi move on khi done.','Tôi giữ final agency, execute điều đã chọn và không reopen issue.','Tôi tự make call tới completion rồi xem situation settled.','Decision ownership ở tôi; tôi finish action rồi không return.','Tôi tự choose, complete điều đã decide rồi để issue resolved.']}
CTXE=['A printmaking room logged brayer sleeves and ink cards by cabinet.','A language studio indexed microphone pouches and desk tokens by drawer.','A climbing workshop tracked rope tags and chalk clips by wall.','A marine lab recorded chart tubes and compass cases by locker.','A flower school catalogued ribbon rolls and stem labels by shelf.','A woodworking room logged sanding blocks and clamp tags by bench.','A dance archive indexed costume sleeves and shoe labels by rail.','A community bakery tracked tray markers and scraper bins by station.','A conservation lab recorded brush wraps and tissue folders by table.','A music room catalogued stand clips and cable bags by cabinet.','A gardening shed logged hose keys and seed tags by rack.','A photography class indexed filter wallets and tripod plates by drawer.','A rowing store tracked seat bolts and collar rings by board.','A theatre workshop recorded prop cards and cue folders by locker.','A repair classroom catalogued socket trays and parts envelopes by bench.','A map archive logged tube straps and paper weights by cabinet.','A ceramics school indexed glaze chips and sponge trays by shelf.','A telescope room tracked mount screws and eyepiece caps by case.']
CTXV=['Printmaking room ghi brayer sleeve và ink card theo cabinet.','Language studio lập index microphone pouch và desk token theo drawer.','Climbing workshop theo dõi rope tag và chalk clip theo wall.','Marine lab ghi chart tube và compass case theo locker.','Flower school catalog ribbon roll và stem label theo shelf.','Woodworking room ghi sanding block và clamp tag theo bench.','Dance archive lập index costume sleeve và shoe label theo rail.','Community bakery theo dõi tray marker và scraper bin theo station.','Conservation lab ghi brush wrap và tissue folder theo table.','Music room catalog stand clip và cable bag theo cabinet.','Gardening shed ghi hose key và seed tag theo rack.','Photography class lập index filter wallet và tripod plate theo drawer.','Rowing store theo dõi seat bolt và collar ring theo board.','Theatre workshop ghi prop card và cue folder theo locker.','Repair classroom catalog socket tray và parts envelope theo bench.','Map archive ghi tube strap và paper weight theo cabinet.','Ceramics school lập index glaze chip và sponge tray theo shelf.','Telescope room theo dõi mount screw và eyepiece cap theo case.']
TAIL_E=['That inventory note is background only, not evidence for the response.','The storage detail belongs to logistics and cannot establish the mechanism.','That equipment record does not determine the semantic route.','The filing reference adds setting, not behavioural evidence.','That physical detail is outside the response evidence.','The administrative note cannot decide the mechanism being classified.']
TAIL_V=['Inventory note đó chỉ là background, không phải response evidence.','Storage detail thuộc logistics và không establish mechanism.','Equipment record không determine semantic route.','Filing reference chỉ add setting chứ không behavioural evidence.','Physical detail đó nằm ngoài response evidence.','Administrative note không thể decide mechanism đang classify.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*3+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*11+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci+j*2)%6];parts=[core,ctx,tail];rot=(ci+2*j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V230-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*5+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V230-S{ci:02d}-{j:02d}' for j in [1,4,8,10,14,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 x,y=toks(a),toks(b);return len(x&y)/max(1,len(x|y))
internal=(0,None)
for i in range(len(cases)):
 for j in range(i+1,len(cases)):
  q=sim(cases[i]['surface'],cases[j]['surface'])
  if q>internal[0]:internal=(q,(cases[i]['case_id'],cases[j]['case_id']))
external_surfaces=[]
for v in [219,220,221,222,223,224,225,226,227,228,229]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  raw=subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True);obj=json.loads(raw);external_surfaces += [x['surface'] for x in obj.get('cases',[])]
 except Exception:pass
external=(0,None);over=[];exact=0
extset=set(external_surfaces)
for c in cases:
 if c['surface'] in extset:exact+=1
 for s in external_surfaces:
  q=sim(c['surface'],s)
  if q>external[0]:external=(q,c['case_id'])
  if q>=.75:over.append((c['case_id'],q))
fp=lambda s:' '.join(sorted(toks(re.sub(r'\b(?:room|studio|lab|school|archive|workshop|store|shed|class|classroom)\b','',s.lower()))))
oldfp={fp(s) for s in external_surfaces};finger=sum(1 for c in cases if fp(c['surface']) in oldfp)
assert internal[0]<.75 and external[0]<.75 and not over and exact==0 and finger==0
bank={'authority':'V8.3.230 PRESEAL candidate bank','cases':cases};selection={'authority':'V8.3.230 SEALED selection','selected':selected,'batch_a':A,'batch_b':B};fix={'authority':'V8.3.230 SEALED fixture','cases':fixture};g={'authority':'V8.3.230 independent gold','cases':gold};membership={'authority':'V8.3.230 sealed membership','batch_a':A,'batch_b':B}
def dump(n,o):(O/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
for n,o in [('V8_3_230_PRESEAL_CANDIDATE_BANK_V1.json',bank),('V8_3_230_SEALED_SELECTION_V1.json',selection),('V8_3_230_SEALED_FIXTURE_V1.json',fix),('V8_3_230_INDEPENDENT_GOLD_V1.json',g),('V8_3_230_SEALED_MEMBERSHIP_V1.json',membership)]:dump(n,o)
def h(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={'candidate_bank':h(bank),'selection':h(selection),'fixture':h(fix),'independent_gold':h(g),'membership':h(membership)}
audit={'candidate':'V8.3.230','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':len(over),'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':finger,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};dump('V8_3_230_PRESEAL_DIVERSITY_AUDIT_V1.json',audit);hashes['preseal_audit']=h(audit)
auth={'candidate':'V8.3.230','phase':'PRESEAL_AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hashes':hashes,'preseal_pass':True,'semantic_runtime_executed':False,'batch_a_executed':False,'batch_b_executed':False};dump('V8_3_230_SEALED_AUTHORITY_V1.json',auth)
receipt={'candidate':'V8.3.230','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':0,'exact_external_duplicates':0,'semantic_fingerprint_exact_duplicates':0,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};dump('V8_3_230_PRESEAL_RUN_RECEIPT.json',receipt);print(json.dumps(receipt))
