import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83241-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='c9da21d4507ff8727d58af13cd931dcc2a442faa';SEM='QCEvidenceExtractorV5AP -> QCSemanticCoreV115'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The incident was real; only my own observable last response is absent.','This lived situation is described except for the concrete action I took at the endpoint.','I can give the real context, but not the behavioural step that came from me at the close.','The episode happened to me, yet my final response has not been stated.','The surrounding facts are available from a real event; my endpoint behaviour is the missing evidence.','This is autobiographical, but what I personally did at the finish is unspecified.'],
'decision':['Make the actual final decision on my behalf instead of only advising me.','I am transferring final choice ownership to you; select the route that stands.','Let your decision replace mine here, rather than merely shape it.','Take the deciding act away from me and make the final selection yourself.','I want you to own the choice and determine which option becomes final.','The final call should be yours; choose the option that will count.'],
'hypothetical':['This is manufactured test input and has no lived event behind it.','The scenario was created for evaluation and is not something I experienced.','Nothing described here is autobiographical; it is synthetic validation text.','This artificial example exists for assessment rather than as personal evidence.','I invented this solely for testing, not from a real episode.','Treat this as fictional practice material, not a situation from my life.'],
'third':['Infer the other person’s hidden belief without observable conduct supporting it.','Tell me their private conclusion although no words or actions establish it.','Describe someone else’s concealed thought when there is no behavioural basis.','Work out the other person’s internal position despite no outward evidence.','State what they secretly believe even though nothing observable supports it.','Give me their private view without any behaviour from them that substantiates it.'],
'prediction':['At the later date I named, will the preferred outcome already be true?','When that future checkpoint arrives, will the situation resolve in my favour?','By the future boundary I specified, will I have the result I want?','Looking ahead to the named cutoff, will this finish the way I hope?','Once that later milestone is reached, will the outcome I want have happened?','At that future point, will things have ended in the way I want?'],
'freeze':['A small reversible first move was available, but I broadened the choices and did not begin.','I had a bounded starter with an easy exit, yet comparison expanded and I stayed inactive.','A low-commitment opening step was ready; I generated alternatives instead of starting.','I could have tested one reversible action, but option growth displaced initiation.','There was a safe first move available, yet I widened possibilities and made no start.','One easy-to-undo opening action was there, but I kept comparing and remained still.'],
'ignore':['The core matter still needed my action, but I redirected effort into secondary work.','A primary responsibility remained unanswered while I focused on peripheral tasks.','The central issue stayed unresolved because I shifted attention to side activity.','Something important required my response while I kept busy with less relevant work.','The main obligation still needed me, yet I diverted effort into tasks that could not settle it.','My action was required on the central issue, but I occupied myself with secondary activity.'],
'slow':['I took one bounded pause, reviewed once, answered, and left the issue closed.','There was one finite delay and one check before I replied and stopped revisiting it.','I paused within a fixed limit, reviewed once, responded, and moved on.','Before answering I used one contained interval, checked once, then ended the review.','I allowed one defined pause and one review, gave my response, and did not reopen it.','I delayed once inside a clear boundary, checked once, replied, and closed the matter.'],
'sequence':['I moved toward acting, backed away, then returned to the same conclusion without new information.','I got close to execution, withdrew, and repeated the earlier judgement although nothing changed.','I approached the practical move, stepped back, then cycled to the same reasoning with no new facts.','I nearly acted, reversed course, and revisited the same assessment under unchanged evidence.','I advanced toward the action, retreated, then repeated the same conclusion without additional information.','I came close to doing it, pulled away, and returned to prior reasoning despite no new evidence.'],
'neutral':['I kept final decision ownership, carried out the choice, and left the matter settled.','I made the final choice myself, executed it, and moved on.','The decision stayed mine through completion; afterward I did not reopen it.','I retained final agency, completed what I chose, and treated the issue as resolved.','I chose for myself, finished the action, and left it closed.','The final call remained mine; I executed it and did not revisit the choice process.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A piano workshop logged felt strips, tuning wedges, and pedal screws by drawer.','A microscopy room indexed slide trays, objective caps, and focus keys by cabinet.','A sailing classroom tracked cleat samples, knot cards, and compass mounts by rack.','A print archive recorded plate sleeves, registration pins, and proof folders by shelf.','A glass studio catalogued scoring wheels, foil rolls, and kiln spacers by bench.','A robotics club logged sensor brackets, cable clips, and motor tags by board.','A tailoring room indexed button cards, chalk blocks, and zipper packets by locker.','A bread lab tracked banneton liners, lame covers, and dough cards by station.','A birding club recorded lens hoods, field slates, and tripod feet by case.','A jewelry class catalogued mandrels, polishing pads, and clasp trays by desk.','A map archive logged tube collars, scale rulers, and legend cards by drawer.','A radio booth indexed patch leads, windshields, and headphone cushions by cabinet.','A seed library tracked envelope dividers, sample spoons, and drying cards by shelf.','A canoe shed recorded thwart bolts, paddle grips, and strap loops by board.','A dance wardrobe catalogued shoe bags, sash cards, and garment clips by rail.','A tool school logged hex keys, washer tins, and torque slips by bench.','A spice classroom indexed jar labels, scoop trays, and recipe cards by shelf.','A paper studio tracked bone folders, thread cones, and awl guards by drawer.']
TAIL_E=['That workshop inventory concerns physical maintenance only and does not establish my response.','Those microscopy records are operational context, not behavioural evidence.','The sailing equipment list cannot determine the semantic route.','That print filing adds setting only and provides no proof of the mechanism.','The glass-tool record is outside the evidence about the behaviour.','Those robotics parts are background details and cannot establish the pattern signal.','The tailoring stock log is separate from evidence of my action.','Those bread-lab materials are context rather than behavioural proof.','The birding equipment note cannot decide the classification.','That jewelry inventory concerns objects, not the response being measured.','The map-archive ledger cannot substitute for evidence of what I did.','Those radio-booth items add scenery only and do not establish the mechanism.','The seed-library storage list is unrelated to the behavioural question.','That canoe equipment log is logistical context and cannot classify my response.','The wardrobe inventory sits outside evidence for the response mechanism.','Those tool-school records describe hardware only, not behaviour.','The spice-class list does not determine the semantic interpretation.','That paper-studio record is background only and cannot prove my response.']
CTXV=['Một xưởng piano ghi dải nỉ, nêm chỉnh dây và vít pedal theo ngăn.','Một phòng kính hiển vi ghi khay slide, nắp objective và khóa focus theo tủ.','Một lớp thuyền buồm ghi mẫu cleat, thẻ nút dây và giá la bàn theo rack.','Một kho in ghi bao plate, chốt registration và folder proof theo kệ.','Một studio kính ghi bánh cắt, cuộn foil và spacer lò theo bàn.','Một câu lạc bộ robot ghi bracket sensor, kẹp cáp và tag motor theo bảng.','Một phòng may ghi thẻ nút, block phấn và gói zipper theo tủ.','Một lab bánh mì ghi lớp banneton, bao lame và thẻ dough theo trạm.','Một câu lạc bộ birding ghi hood lens, field slate và chân tripod theo hộp.','Một lớp trang sức ghi mandrel, pad đánh bóng và khay clasp theo bàn.','Một kho bản đồ ghi cổ ống, thước scale và thẻ legend theo ngăn.','Một booth radio ghi patch lead, windshield và đệm headphone theo tủ.','Một thư viện hạt giống ghi vách phong bì, thìa mẫu và thẻ sấy theo kệ.','Một kho canoe ghi bolt thwart, grip paddle và loop dây theo bảng.','Một kho đồ múa ghi túi giày, thẻ sash và kẹp garment theo ray.','Một lớp dụng cụ ghi hex key, hộp washer và phiếu torque theo bàn.','Một lớp gia vị ghi nhãn lọ, khay scoop và thẻ recipe theo kệ.','Một studio giấy ghi bone folder, cone chỉ và guard awl theo ngăn.']
TAIL_V=['Danh mục xưởng chỉ nói về bảo trì vật thể, không chứng minh phản ứng của tôi.','Bản ghi kính hiển vi là bối cảnh vận hành, không phải bằng chứng hành vi.','Danh sách thiết bị thuyền không quyết định tuyến ngữ nghĩa.','Hồ sơ in chỉ thêm bối cảnh và không chứng minh cơ chế.','Bản ghi dụng cụ kính nằm ngoài bằng chứng về hành vi.','Linh kiện robot chỉ là hậu cảnh và không xác lập tín hiệu pattern.','Log kho may tách biệt khỏi bằng chứng về hành động của tôi.','Vật liệu lab bánh chỉ là bối cảnh chứ không phải bằng chứng hành vi.','Ghi chú thiết bị birding không quyết định phân loại.','Danh mục trang sức nói về đồ vật, không phải phản ứng đang đo.','Sổ kho bản đồ không thể thay thế bằng chứng về điều tôi đã làm.','Vật phẩm booth radio chỉ thêm khung cảnh và không xác lập cơ chế.','Danh sách thư viện hạt giống không liên quan tới câu hỏi hành vi.','Log thiết bị canoe là bối cảnh logistics và không phân loại phản ứng.','Danh mục wardrobe nằm ngoài bằng chứng cho cơ chế phản ứng.','Bản ghi lớp dụng cụ chỉ nói về hardware, không phải hành vi.','Danh sách lớp gia vị không quyết định diễn giải ngữ nghĩa.','Bản ghi studio giấy chỉ là hậu cảnh và không chứng minh phản ứng.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';core=(EN if lang=='EN' else VI)[c][(ci*2+j)%6];ctx=(CTXE if lang=='EN' else CTXV)[j];tail=(TAIL_E if lang=='EN' else TAIL_V)[j];parts=[core,ctx,tail];rot=(ci+j*2)%3;parts=parts[rot:]+parts[:rot];route,fam,seq=E[c];cases.append({'case_id':f'V241-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*3+j)%6],'surface':' '.join(parts),'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V241-S{ci:02d}-{j:02d}' for j in [1,4,8,10,13,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.241 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.241','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.241','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.241','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.241','batch_a':A,'batch_b':B})]:(O/f'V8_3_241_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.241','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_241_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_241_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_241_SEALED_SELECTION_V1.json','fixture':'V8_3_241_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_241_INDEPENDENT_GOLD_V1.json','membership':'V8_3_241_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_241_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.241','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_241_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.241','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_241_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
