import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83239-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='00ad4e2e12d58a22f26f171523c67231c662d325';SEM='QCEvidenceExtractorV5AO -> QCSemanticCoreV114'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['This happened to me, but the exact action I took at the close is still missing.','The real context is available except for my own observable behaviour at the final point.','It is a lived situation; what I personally did at the endpoint has not been stated.','The event is real and otherwise clear, but my concrete closing response is absent.','The surrounding sequence is known, yet the last action from me has not been supplied.','This is an actual episode with one gap: what I myself did immediately before it ended.'],
'decision':['Make the final choice for me; I am giving you the deciding authority.','I want the actual decision to come from you rather than from my own judgement.','Take the choice out of my hands and select the option that will stand.','Use your judgement as the final call, not merely as advice for my decision.','I am handing you ownership of the deciding act; choose the route itself.','Replace my deciding call with yours and make the final selection.'],
'hypothetical':['This is fabricated testing material and not something I lived.','Nothing in this scenario comes from my own experience; it is only evaluation input.','The example was invented for validation and has no autobiographical event behind it.','Treat this as an artificial assessment case rather than personal evidence.','This is constructed practice text unrelated to anything that happened to me.','I created this solely as test material, not from a lived episode.'],
'third':['Infer the other person’s private belief even though nothing observable supports it.','Tell me their concealed conclusion without any words or actions establishing it.','Describe the hidden view in someone else’s mind when their conduct gives no evidence.','Work out what the other person secretly believes despite no outward behavioural basis.','State their internal conclusion even though nothing they did or said supports it.','Give me the other person’s private mental position without observable evidence.'],
'prediction':['By the future deadline I named, will the outcome I want have happened?','When that later checkpoint arrives, will this have resolved in my favour?','At the specified future point, will I have the preferred result?','Looking ahead to the stated cutoff, will the situation end the way I hope?','Once that future boundary arrives, will the desired outcome be there?','At that later milestone, will things have finished in the result I want?'],
'freeze':['A reversible first move was ready, but I kept adding alternatives and did not start.','I had a low-commitment opening action, yet comparison widened and initiation never happened.','There was one contained starter with an exit, but I expanded the option set instead of beginning.','A bounded trial move was available; I generated more choices and remained inactive.','I could have taken a safe reversible first step, but more possibilities displaced starting.','The initial move was easy to undo, yet option growth kept me still.'],
'ignore':['The main matter still required my response, but I shifted effort into secondary work.','A central responsibility remained unanswered while I focused on peripheral tasks.','The important issue stayed unresolved because I redirected attention to less relevant activity.','My action was still needed on the core matter, yet I occupied myself with side work.','Something consequential remained open while I diverted into tasks that could not settle it.','The primary obligation waited for my response as I moved into secondary activity.'],
'slow':['I took one bounded pause, checked once, answered, and then closed the matter.','There was one finite delay and one review before I replied and stopped revisiting it.','I paused within a fixed limit, reviewed once, responded, and did not reopen the issue.','Before answering I used one contained interval, made one check, and moved on.','I allowed one defined pause and one review, gave my response, and ended the review cycle.','I delayed once inside a clear boundary, checked once, replied, and treated it as finished.'],
'sequence':['I moved toward the action, pulled back, then returned to the same conclusion without new evidence.','I approached execution, withdrew, and repeated the prior judgement though no new facts appeared.','I came close to acting, stepped away, then cycled back to the same reasoning with no additional information.','I nearly did it, reversed course, and revisited the old assessment while nothing changed.','I advanced toward the move, retreated, then repeated the same conclusion without new facts.','I got close to execution, backed away, and returned to prior reasoning despite unchanged evidence.'],
'neutral':['I kept the decision with me, carried it out, and left the matter closed.','I chose for myself, completed the action, and did not reopen the issue.','Final agency remained mine through execution; afterward I moved on.','I retained ownership of the choice, executed it, and treated the matter as settled.','I made my own final call, finished the action, and left the issue resolved.','The decision stayed mine; I completed it and did not return to the choice process.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A print lab logged screen frames and ink tabs by cabinet.','A choir room indexed tuning slips and folder clips by shelf.','A canoe class tracked buckle straps and paddle bands by rack.','A plant nursery recorded seed labels and mist cards by bay.','A carving studio catalogued rasp cases and wax blocks by bench.','A photo room logged filter sleeves and tripod plates by drawer.','A pastry workshop indexed dough cards and scraper bins by station.','A climbing store tracked sling packets and route cards by wall.','A theatre room recorded costume wraps and cue folders by locker.','A weaving lab catalogued shuttle trays and loom pegs by table.','An astronomy club logged lens covers and mount screws by case.','A mapping room indexed tube clips and ruler blocks by drawer.','A recording room tracked cable loops and ear-pad boxes by cabinet.','A specimen room recorded plant folders and drying cards by shelf.','A rowing shed catalogued collar clips and seat rails by board.','A dance room logged shoe sleeves and garment tags by rail.','A repair class indexed wrench boxes and parts slips by bench.','A cooking studio tracked utensil trays and pantry cards by shelf.']
CTXV=[x.replace('A ','Một ').replace('An ','Một ') for x in CTXE]
TAIL_E=['That inventory line is setting only and cannot establish the response.','The storage record is logistics rather than behavioural evidence.','That equipment reference cannot determine the semantic route.','The filing note adds context only, not evidence of the mechanism.','That physical record lies outside the behavioural evidence.','The administrative item cannot decide the classification.']
TAIL_V=['Inventory line đó chỉ là setting, không establish response.','Storage record là logistics, không behavioural evidence.','Equipment reference không determine semantic route.','Filing note chỉ add context, không evidence mechanism.','Physical record nằm ngoài behavioural evidence.','Administrative item không decide classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*3+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*7+j*11)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci+j*3)%6];parts=[core,ctx,tail];rot=(ci+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V239-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*3+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V239-S{ci:02d}-{j:02d}' for j in [1,4,8,10,15,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.239 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.239','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.239','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.239','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.239','batch_a':A,'batch_b':B})]:(O/f'V8_3_239_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.239','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_239_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_239_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_239_SEALED_SELECTION_V1.json','fixture':'V8_3_239_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_239_INDEPENDENT_GOLD_V1.json','membership':'V8_3_239_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_239_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.239','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_239_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.239','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_239_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
