import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83237-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='b4eb9e00fffcfea5dcd73406f1e1216810002cd2';SEM='QCEvidenceExtractorV5AM -> QCSemanticCoreV112'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The real event is otherwise accounted for, but the last concrete thing I did is not in the record.','This actually happened; the missing evidence is my own observable response at the endpoint.','The lived sequence is available except for the action I personally took as it closed.','Everything about the real situation is described apart from my final behaviour.','The event is not hypothetical, but my own closing response has not been supplied.','The real context is complete except for what I did immediately before the end.'],
'decision':['You should make the actual final choice, not merely advise me about it.','I am transferring the deciding authority to you; pick the option that becomes final.','Make the selection itself in place of me making it.','Take the final call out of my hands and choose the route.','I want your decision to substitute for mine, not just guide it.','Own the deciding act and choose which option stands.'],
'hypothetical':['This was invented for validation and is not drawn from my own experience.','The scenario is synthetic test material, not something that happened in my life.','This is a fabricated assessment example with no autobiographical event behind it.','Nothing described here was lived by me; it exists only as test input.','The example is artificial evaluation material rather than personal evidence.','This constructed practice case is unrelated to any real episode I experienced.'],
'third':['Tell me the belief inside the other person’s mind even though no observable behaviour establishes it.','Infer someone else’s private conclusion without words or actions that support it.','Work out their hidden mental position despite no outward evidence.','State what the other person secretly believes when their conduct gives no basis.','Describe their concealed conclusion although nothing observable from them supports it.','Give me the other person’s private view without behavioural evidence.'],
'prediction':['At the future cutoff I named, will the result I want have occurred?','When that later deadline arrives, will the situation resolve in my favour?','By the future date I specified, will the preferred outcome exist?','Looking ahead to the named checkpoint, will this end the way I hope?','Once that future boundary is reached, will I get the result I want?','At that later point, will things finish in the way I want?'],
'freeze':['A reversible first move was available, but I kept expanding alternatives and never started.','I had a contained starter step with an exit, yet I generated more options and stayed inactive.','There was a low-commitment opening action, but comparison widened instead of action beginning.','I could have tested one bounded first step; instead I broadened possibilities and remained still.','The opening move was easy to undo, but option growth displaced initiation.','A safe reversible starter was ready, yet I kept adding choices and made no start.'],
'ignore':['The important issue still needed my action, but I redirected effort into secondary tasks.','A central responsibility remained unanswered while I worked on peripheral activity.','The main obligation was still open because I shifted attention to side work.','Something consequential waited for my response while I occupied myself with less relevant tasks.','The core matter stayed unresolved as I diverted effort into work that could not settle it.','My action was still required on the primary issue, yet I focused on secondary activity.'],
'slow':['I used one time-bounded pause, checked once, answered, and did not reopen the matter.','There was one finite delay and one review before I replied and stopped revisiting it.','I paused inside a clear limit, reviewed once, responded, and left the issue closed.','Before answering I took one contained interval, made one check, then moved on.','I allowed one defined delay and one review, gave my response, and ended the review cycle.','I paused once within a fixed boundary, checked once, replied, and closed it.'],
'sequence':['I approached the action, backed away, then returned to the same conclusion without new information.','I got close to doing it, withdrew, and repeated the prior judgement even though nothing changed.','I moved toward execution, stepped back, then cycled to the same reasoning with no new facts.','I nearly acted, reversed course, and revisited the same assessment under unchanged evidence.','I advanced toward the move, retreated, then repeated the same conclusion without additional information.','I came close to acting, pulled away, and returned to the prior reasoning despite no new evidence.'],
'neutral':['I kept decision ownership, executed the choice, and left the matter settled.','I made the final choice myself, carried it out, and moved on.','The decision stayed mine through completion; afterward I did not reopen it.','I retained final agency, completed what I chose, and treated the issue as resolved.','I chose for myself, finished the action, and left it closed.','The final call remained mine; I executed it and did not revisit the decision.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A leather studio logged punch sets and thread spools by drawer.','A choir archive indexed folder clips and tuning cards by shelf.','A kayak school tracked strap loops and paddle tags by rack.','A nursery room recorded seed trays and moisture cards by bay.','A sculpture lab catalogued carving tools and wax blocks by bench.','A camera store logged filter cases and tripod shoes by cabinet.','A bakery room indexed dough labels and scraper boxes by station.','A climbing club tracked sling bundles and route tags by wall.','A stage store recorded costume sleeves and cue sheets by locker.','A textile room catalogued shuttle cases and loom pins by table.','A telescope club logged eyepiece covers and mount bolts by case.','A survey archive indexed map rolls and straightedge weights by drawer.','A recording booth tracked cable coils and headphone pads by cabinet.','A botany lab recorded specimen sleeves and blotter cards by shelf.','A rowing store catalogued collar clips and seat runners by board.','A dance archive logged garment pouches and shoe cards by rail.','A mechanics class indexed socket racks and parts envelopes by bench.','A culinary room tracked utensil trays and pantry labels by shelf.']
CTXV=[x.replace('A ','Một ').replace('An ','Một ') for x in CTXE]
TAIL_E=['That inventory entry is background only and does not establish the response.','The storage detail is logistical context rather than behavioural evidence.','That equipment note cannot determine the semantic classification.','The filing reference adds setting only, not evidence of the mechanism.','That physical record is outside the behavioural evidence.','The administrative detail cannot decide the route.']
TAIL_V=['Inventory entry đó chỉ là background, không establish response.','Storage detail là logistics context, không behavioural evidence.','Equipment note không determine semantic classification.','Filing reference chỉ add setting, không evidence mechanism.','Physical record nằm ngoài behavioural evidence.','Administrative detail không decide route.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*5+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*9+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*2+j*3)%6];parts=[core,ctx,tail];rot=(ci+j*2)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V237-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*2+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V237-S{ci:02d}-{j:02d}' for j in [1,5,8,11,15,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.237 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.237','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.237','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.237','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.237','batch_a':A,'batch_b':B})]:(O/f'V8_3_237_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.237','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_237_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_237_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_237_SEALED_SELECTION_V1.json','fixture':'V8_3_237_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_237_INDEPENDENT_GOLD_V1.json','membership':'V8_3_237_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_237_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.237','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_237_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.237','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_237_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
