import json,hashlib,pathlib,subprocess,zipfile,tempfile,shutil
R=pathlib.Path('.');O=R/'validation/v83237-v1-sealed';DEV='b4eb9e00fffcfea5dcd73406f1e1216810002cd2';SEM='QCEvidenceExtractorV5AM -> QCSemanticCoreV112'
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def ho(o):return hashlib.sha256(canon(o)).hexdigest()
def hb(b):return hashlib.sha256(b).hexdigest()
def show(path):return subprocess.check_output(['git','show',f'{DEV}:{path}'])
a=json.loads((O/'V8_3_237_SEALED_AUTHORITY_V1.json').read_text());rec=json.loads((O/'V8_3_237_PRESEAL_RUN_RECEIPT.json').read_text())
assert a['validated_development_head_sha']==DEV and a['semantic_authority']==SEM and a['preseal_pass'] is True and rec['conclusion']=='success'
files={'candidate_bank':'V8_3_237_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_237_SEALED_SELECTION_V1.json','fixture':'V8_3_237_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_237_INDEPENDENT_GOLD_V1.json','membership':'V8_3_237_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_237_PRESEAL_DIVERSITY_AUDIT_V1.json'}
hash_match={k:ho(json.loads((O/n).read_text()))==a['hashes'][k] for k,n in files.items()};assert all(hash_match.values())
dev_auth=json.loads(show('validation/V8_3_237_DEVELOPMENT_AUTHORITY_V1.json'));reg=json.loads(show('validation/V8_3_237_V112_REGRESSION_RECEIPT.json'))
assert dev_auth['regression_pass'] is True and reg['conclusion']=='success' and reg['immutable_regression_passed']==1470 and reg['v216_frozen_a_passed']==30
for k in ['v219_frozen_a_passed','v221_frozen_a_passed','v222_frozen_a_passed','v223_frozen_a_passed','v224_frozen_a_passed','v225_frozen_a_passed','v226_frozen_a_passed','v227_frozen_a_passed','v229_frozen_a_passed','v230_frozen_a_passed','v231_frozen_a_passed','v233_frozen_a_passed','v234_frozen_a_passed','v235_frozen_a_passed','v236_frozen_a_passed']:assert reg[k]==30,k
assert reg['v236_previous_failures_repaired']==8 and reg['v236_previous_passes_preserved']==22 and reg['expected_gold_changed'] is False and reg['sealed_validation_executed'] is False
semfiles=['validation/qc-evidence-extractor-v5x-v217-relational-recall.js','validation/psc-v83217-v216-v97-relational-recall.js','validation/qc-evidence-extractor-v5y-v220-bounded-recall.js','validation/psc-v83220-v219-v98-bounded-recall.js','validation/qc-evidence-extractor-v5z-v222-compositional-generalization.js','validation/psc-v83222-v221-v99-compositional-generalization.js','validation/qc-evidence-extractor-v5aa-v223-precedence-generalization.js','validation/psc-v83223-v222-v100-precedence-generalization.js','validation/qc-evidence-extractor-v5ab-v224-compositional-recall.js','validation/psc-v83224-v223-v101-compositional-recall.js','validation/qc-evidence-extractor-v5ac-v225-residual-composition.js','validation/psc-v83225-v224-v102-residual-composition.js','validation/qc-evidence-extractor-v5ad-v226-full-input-witness.js','validation/psc-v83226-v225-v103-full-input-witness.js','validation/qc-evidence-extractor-v5ae-v227-residual-witness.js','validation/psc-v83227-v226-v104-residual-witness.js','validation/qc-evidence-extractor-v5af-v228-witness-completion.js','validation/psc-v83228-v227-v105-witness-completion.js','validation/qc-evidence-extractor-v5ag-v230-concept-generalization.js','validation/psc-v83230-v229-v106-concept-generalization.js','validation/qc-evidence-extractor-v5ah-v231-isolated-concepts.js','validation/psc-v83231-v230-v107-isolated-concepts.js','validation/qc-evidence-extractor-v5ai-v232-residual-isolated-generalization.js','validation/psc-v83232-v231-v108-residual-isolated-generalization.js','validation/qc-evidence-extractor-v5aj-v234-residual-generalization.js','validation/psc-v83234-v233-v109-residual-generalization.js','validation/qc-evidence-extractor-v5ak-v235-final-residuals.js','validation/psc-v83235-v234-v110-final-residuals.js','validation/qc-evidence-extractor-v5al-v236-contextual-mechanisms.js','validation/psc-v83236-v235-v111-contextual-mechanisms.js','validation/qc-evidence-extractor-v5am-v237-final-compositional.js','validation/psc-v83237-v236-v112-final-compositional.js']
sem_identity={p:hb(pathlib.Path(p).read_bytes())==hb(show(p)) for p in semfiles};assert all(sem_identity.values())
archive=R/'PSC_V8_3_139_FINAL_LOCAL_READINESS_EXTERNAL_BUILD_PENDING_CHECKPOINT (1).zip';assert archive.exists();tmp=pathlib.Path(tempfile.mkdtemp(prefix='v83237-transport-'))
try:
 with zipfile.ZipFile(archive) as z:z.extractall(tmp)
 public=tmp/'PSC_V8_3_138_DEV/public/psc-v3.js';assert public.exists() and public.stat().st_size>0
 transport={'candidate':'V8.3.237','phase':'transport-verification','validated_development_head_sha':DEV,'semantic_authority':SEM,'public_runtime_materialized':True,'public_psc_v3_exists':True,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'pass':True}
finally:shutil.rmtree(tmp,ignore_errors=True)
(O/'V8_3_237_TRANSPORT_VERIFICATION_V1.json').write_text(json.dumps(transport,indent=2)+'\n')
marker_absent=not (O/'V8_3_237_SEALED_FIRST_RUN_MARKER.json').exists();attempt_absent=not (O/'V8_3_237_BATCH_A_ATTEMPT_MARKER.json').exists();result_absent=not (O/'V8_3_237_BATCH_A_RESULT_V1.json').exists()
pf={'candidate':'V8.3.237','phase':'static-sealed-preflight','validated_development_head_sha':DEV,'loader_chain':SEM,'loader_chain_static_verified':True,'semantic_files_byte_identical_to_v237_dev':all(sem_identity.values()),'parent_layers_byte_identical':all(sem_identity[p] for p in semfiles[:-2]),'frozen_canonical_hashes_match':hash_match,'transport_pass':True,'zero_failure_development_predicate':True,'runner_runtime_root_contract':{'version_root':'validation/v83237-v1-sealed-runtime','fixture':'V8_3_237_SEALED_FIXTURE_V1.json','selection':'V8_3_237_SEALED_SELECTION_V1.json','gold':'V8_3_237_INDEPENDENT_GOLD_V1.json','single_source_of_truth_for_runtime_root':True,'adapter_from_parent_runner_forbidden':True},'first_run_marker_absent':marker_absent,'batch_a_attempt_marker_absent':attempt_absent,'prior_batch_a_execution_absent':result_absent,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'v221_sealed_rerun':False,'v222_sealed_rerun':False,'v223_sealed_rerun':False,'v224_sealed_rerun':False,'v225_sealed_rerun':False,'v226_sealed_rerun':False,'v227_sealed_rerun':False,'v228_sealed_rerun':False,'v229_sealed_rerun':False,'v230_sealed_rerun':False,'v231_sealed_rerun':False,'v232_sealed_rerun':False,'v233_sealed_rerun':False,'v234_sealed_rerun':False,'v235_sealed_rerun':False,'v236_sealed_rerun':False,'pass':all(hash_match.values()) and marker_absent and attempt_absent and result_absent}
assert pf['pass'];(O/'V8_3_237_STATIC_SEALED_PREFLIGHT_V1.json').write_text(json.dumps(pf,indent=2)+'\n');print(json.dumps(pf))
