import json,hashlib,pathlib,subprocess,re,difflib
R=pathlib.Path('.');O=R/'validation/v83227-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='a610a249639cb2a0e5fae5a8f69fed05cc3fe509';SEM='QCEvidenceExtractorV5AE -> QCSemanticCoreV104'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The event itself is real and the chronology is known; what I still have not stated is my own observable action at the end.','Everything material about the situation is present except the concrete response that came from me before it finished.','This is lived experience, not an example, but my personal closing behaviour remains unspecified.','The surrounding facts are sufficiently clear; the missing piece is what I myself actually did at the endpoint.','The episode happened to me and is otherwise described, yet my final observable response is absent.','All relevant circumstances are known except the action I personally took immediately before closure.'],
'decision':['Decide the final option for me so your choice replaces the call I would otherwise make.','I am giving you the final choice; select the route itself rather than advising me how to choose.','Take ownership of the final selection and tell me which option becomes mine.','Use your judgement to make the actual decision in my place.','Do not leave the decision with me; choose the final course on my behalf.','I want your choice to stand as the final answer instead of my own.'],
'hypothetical':['This was written only as fabricated validation material and does not describe anything I experienced.','The scenario is synthetic test input; there is no lived event behind it.','Nothing in this example happened to me; it exists solely for evaluation.','Treat this as an invented practice case rather than personal evidence.','The text is deliberately fictional and should not be read as my history.','I made up this scenario for testing; it is not a report from my life.'],
'third':['Tell me the other person’s hidden belief even though nothing they said or did gives observable support.','Infer someone else’s private conclusion without any outward statement or behaviour establishing it.','Work out what the other person secretly thinks when there is no behavioural evidence from them.','State their concealed internal view despite having no observable basis for the inference.','I want the private thought of someone else even though their conduct provides no evidence.','Tell me what is in their mind when no action or statement from them supports that claim.'],
'prediction':['At the future date I named, will the outcome I want have happened?','By that stated future checkpoint, will this resolve in my favour?','When the specified future milestone arrives, will I get the result I am hoping for?','Will the preferred outcome be true by the future cutoff I gave?','Looking ahead to the future boundary I named, will events end the way I want?','At that future marker, will the desired result have occurred?'],
'freeze':['A small first move was reversible and easy to undo, but I kept adding alternatives and did not begin.','There was a low-commitment test step available; comparison expanded and I stayed inactive.','I could have tried one bounded action with a clear exit, yet I widened the option set instead of starting.','The opening step was reversible, but I generated more choices until no action was initiated.','A contained move could have been tested safely; I kept comparing possibilities and remained still.','There was an easy-to-reverse starter action, yet option expansion prevented me from taking it.'],
'ignore':['The central issue still required my response, but I shifted attention into side work that could not resolve it.','Something important was waiting for action from me while I occupied myself with peripheral tasks.','The main responsibility remained unanswered; I diverted effort into secondary activity instead.','My action was still needed on the core matter, yet I busied myself with less relevant work.','The primary obligation needed a response from me, but I redirected into side tasks that did not address it.','A consequential issue remained unresolved because I moved into peripheral activity instead of answering it.'],
'slow':['I used one clearly bounded pause, reviewed once, answered, and then closed the issue.','There was one finite delay and a single check before I responded and stopped reviewing.','I paused within a fixed limit, made one review pass, replied, and did not reopen the matter.','Before answering I allowed one contained interval, checked once, and then treated the process as complete.','I took one limited pause, reviewed a single time, gave my response, and ended the review cycle.','I delayed inside one defined boundary, checked once, answered, and left it closed.'],
'sequence':['I moved close to acting, pulled back, and returned to the same judgement without any new evidence.','I approached execution, withdrew, then repeated my prior conclusion while the facts stayed unchanged.','I advanced toward the action, stepped away, and cycled back to identical reasoning with no new information.','I nearly carried out the move, reversed course, and revisited the old assessment although nothing new appeared.','I got close to execution, retreated, and came back to the same conclusion under unchanged evidence.','I approached doing it, backed out, then repeated the same judgement while no new facts emerged.'],
'neutral':['I kept the final decision with me, completed the action, and left the matter settled afterward.','I chose for myself, carried out the step, and did not revisit it once complete.','Final agency remained mine through execution; I finished the action and moved on.','I made my own final call, completed what I chose, and treated the issue as closed.','The choice stayed mine until completion, after which I did not reopen the matter.','I retained the decision, executed it, and left the issue settled.']}
VI={
'clarification':['Chuyện này xảy ra thật và chronology đã rõ; phần tôi chưa nói là observable action của chính tôi ở đoạn cuối.','Mọi material detail đều có trừ concrete response do tôi tạo ra trước khi chuyện kết thúc.','Đây là lived experience chứ không phải example, nhưng personal closing behaviour của tôi vẫn chưa được nêu.','Surrounding facts đã đủ rõ; phần còn thiếu là chính tôi thực sự làm gì ở endpoint.','Episode xảy ra với tôi và đã được mô tả đủ phần khác, nhưng final observable response của tôi còn absent.','Mọi circumstance liên quan đều biết trừ action tôi tự làm ngay trước closure.'],
'decision':['Hãy quyết final option thay tôi để choice của bạn thay cho call mà tôi sẽ tự đưa ra.','Tôi giao final choice cho bạn; hãy chọn route luôn chứ không chỉ advise cách chọn.','Nhận final selection và nói option nào sẽ trở thành lựa chọn của tôi.','Dùng judgement của bạn để make actual decision ở vị trí của tôi.','Đừng để decision ở tôi; hãy chọn final course thay mặt tôi.','Tôi muốn choice của bạn đứng thành final answer thay cho decision của tôi.'],
'hypothetical':['Đoạn này chỉ là fabricated validation material và không mô tả chuyện tôi từng trải qua.','Scenario là synthetic test input; không có lived event phía sau.','Không điều gì trong example này xảy ra với tôi; nó chỉ tồn tại để evaluation.','Hãy xem đây là invented practice case chứ không phải personal evidence.','Text này cố ý fictional và không nên đọc như history của tôi.','Tôi bịa scenario này để test; nó không phải report từ đời tôi.'],
'third':['Nói hidden belief của người kia dù không lời nói hay hành động nào từ họ cho observable support.','Suy ra private conclusion của người khác khi không outward statement hay behaviour nào xác lập.','Xác định người kia secretly nghĩ gì khi không có behavioural evidence từ họ.','Nói concealed internal view của họ dù không có observable basis cho inference.','Tôi muốn private thought của người khác dù conduct của họ không cung cấp evidence.','Nói điều trong đầu họ khi không action hay statement nào support claim đó.'],
'prediction':['Đến future date tôi đã nêu, outcome tôi muốn có xảy ra không?','Tới future checkpoint đó, chuyện này có resolve theo hướng có lợi cho tôi không?','Khi future milestone đã xác định đến, tôi có nhận result mình hy vọng không?','Preferred outcome có thành sự thật trước future cutoff tôi đưa không?','Nhìn tới future boundary đã nêu, events có kết thúc theo cách tôi muốn không?','Tại future marker đó, desired result có xảy ra không?'],
'freeze':['Có first move nhỏ reversible và dễ undo, nhưng tôi cứ thêm alternative rồi không bắt đầu.','Có low-commitment test step sẵn; comparison mở rộng và tôi vẫn inactive.','Tôi có thể thử một bounded action với exit rõ, nhưng lại nới option set thay vì start.','Opening step reversible, nhưng tôi tạo thêm choice đến mức không initiate action nào.','Một contained move có thể test an toàn; tôi cứ compare possibility rồi đứng yên.','Có starter action dễ reverse, nhưng option expansion ngăn tôi làm nó.'],
'ignore':['Central issue vẫn cần response của tôi, nhưng tôi shift attention sang side work không thể resolve.','Một chuyện important chờ action từ tôi trong khi tôi bận với peripheral task.','Main responsibility vẫn unanswered; tôi divert effort sang secondary activity.','Action của tôi vẫn cần ở core matter, nhưng tôi lại bận với work ít relevant hơn.','Primary obligation cần response từ tôi, nhưng tôi redirect sang side task không address nó.','Một consequential issue vẫn unresolved vì tôi chuyển sang peripheral activity thay vì answer.'],
'slow':['Tôi dùng một bounded pause rõ, review một lần, trả lời rồi đóng issue.','Có một finite delay và single check trước khi tôi response rồi ngừng review.','Tôi pause trong fixed limit, review một pass, reply rồi không reopen matter.','Trước khi answer tôi cho một contained interval, check một lần rồi xem process complete.','Tôi lấy một limited pause, review một lần, đưa response rồi kết thúc review cycle.','Tôi delay trong một defined boundary, check một lần, answer rồi để closed.'],
'sequence':['Tôi tiến gần tới acting, pull back rồi quay lại cùng judgement khi không có evidence mới.','Tôi approach execution, withdraw rồi lặp prior conclusion khi facts không đổi.','Tôi tiến tới action, bước ra rồi cycle về reasoning giống hệt khi không có information mới.','Tôi gần carry out move, reverse course rồi revisit old assessment dù không có gì mới.','Tôi gần execution, retreat rồi quay lại same conclusion dưới unchanged evidence.','Tôi approach việc làm nó, back out rồi lặp same judgement khi không có new facts.'],
'neutral':['Tôi giữ final decision ở mình, complete action rồi để matter settled sau đó.','Tôi tự choose, carry out step và không revisit khi đã complete.','Final agency vẫn ở tôi suốt execution; tôi finish action rồi move on.','Tôi tự đưa final call, complete điều đã chọn và xem issue closed.','Choice vẫn ở tôi đến completion, sau đó tôi không reopen matter.','Tôi giữ decision, execute nó và để issue settled.']}
CTXE=['A bookbinding room catalogued press boards beside thread drawers.','A climbing centre logged chalk buckets and route cards by wall.','A florist workshop indexed stem cutters and ribbon reels by bench.','A sound archive tracked cable labels and case tags by shelf.','A bicycle studio recorded spoke tools and pump heads by station.','A print room catalogued ink rollers and proof sleeves by rack.','A museum store logged foam blocks and object labels by bay.','A theatre booth indexed cue sheets and headset hooks by desk.','A pottery room tracked trimming tools and glaze tiles by cabinet.','A rowing shed recorded seat bolts and oar collars by board.','A sewing room catalogued pattern weights and bobbin boxes by table.','A science lab logged sample trays and lens cloths by drawer.','A garden shed indexed hose keys and plant markers by bench.','A map studio tracked tube labels and paper weights by cabinet.','A kitchen store logged pantry clips and crate tags by shelf.','A ferry desk indexed ticket sleeves and gate cards by drawer.','A camera room tracked clamp bags and tripod plates by case.','A rehearsal room logged stand clips and score folders by locker.']
CTXV=['Bookbinding room ghi press board cạnh thread drawer.','Climbing centre ghi chalk bucket và route card theo wall.','Florist workshop lập index stem cutter và ribbon reel theo bench.','Sound archive theo dõi cable label và case tag theo shelf.','Bicycle studio ghi spoke tool và pump head theo station.','Print room lập catalog ink roller và proof sleeve theo rack.','Museum store ghi foam block và object label theo bay.','Theatre booth lập index cue sheet và headset hook theo desk.','Pottery room theo dõi trimming tool và glaze tile theo cabinet.','Rowing shed ghi seat bolt và oar collar theo board.','Sewing room lập catalog pattern weight và bobbin box theo table.','Science lab ghi sample tray và lens cloth theo drawer.','Garden shed lập index hose key và plant marker theo bench.','Map studio theo dõi tube label và paper weight theo cabinet.','Kitchen store ghi pantry clip và crate tag theo shelf.','Ferry desk lập index ticket sleeve và gate card theo drawer.','Camera room theo dõi clamp bag và tripod plate theo case.','Rehearsal room ghi stand clip và score folder theo locker.']
TAIL_E=['That inventory note is setting only and does not establish the response mechanism.','The storage record is logistical context, not behavioural evidence.','That equipment reference cannot determine the semantic route.','The filing detail adds background only and does not prove the response.','That physical marker is external to the behavioural mechanism.','The administrative note cannot create the signal being classified.']
TAIL_V=['Inventory note đó chỉ là setting và không xác lập response mechanism.','Storage record là logistics context chứ không phải behavioural evidence.','Equipment reference đó không thể quyết semantic route.','Filing detail chỉ thêm background và không chứng minh response.','Physical marker đó nằm ngoài behavioural mechanism.','Administrative note không thể tạo signal đang được classify.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(j+ci)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*11+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci+2*j)%6];parts=[core,ctx,tail];rot=(2*ci+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V227-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*3+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V227-S{ci:02d}-{j:02d}' for j in [0,2,5,10,13,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]

def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 ta,tb=toks(a),toks(b);return (len(ta&tb)/len(ta|tb)) if ta|tb else 1.0
internal=(0,None)
for i in range(len(cases)):
 for j in range(i):
  q=sim(cases[i]['surface'],cases[j]['surface'])
  if q>internal[0]:internal=(q,(cases[j]['case_id'],cases[i]['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226]:
 br=f'v83{v}-v1-sealed-validation';p=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  z=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{p}'],text=True));prior += z.get('cases',[])
 except Exception: pass
ext=(0,None);at75=0;exact=0;prior_sur={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_sur:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:at75+=1
  if q>ext[0]:ext=(q,(x['case_id'],y.get('case_id')))
fps=[(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface'])))) for x in cases]
fpdup=len(fps)-len(set(fps))
assert internal[0]<.75 and ext[0]<.75 and at75==0 and exact==0 and fpdup==0

def dump(name,obj): (O/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def ho(o):return hashlib.sha256(canon(o)).hexdigest()
bank={'authority':'V8.3.227 PRESEAL CANDIDATE BANK','cases':cases};selection={'authority':'V8.3.227 SEALED SELECTION','selected':selected,'batch_a':A,'batch_b':B};fix={'authority':'V8.3.227 SEALED FIXTURE','cases':fixture};g={'authority':'V8.3.227 INDEPENDENT GOLD','cases':gold};membership={'authority':'V8.3.227 SEALED MEMBERSHIP','selected':selected,'batch_a':A,'batch_b':B}
audit={'candidate':'V8.3.227','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(ext[0],6),'external_max_pair':ext[1],'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
for n,o in [('V8_3_227_PRESEAL_CANDIDATE_BANK_V1.json',bank),('V8_3_227_SEALED_SELECTION_V1.json',selection),('V8_3_227_SEALED_FIXTURE_V1.json',fix),('V8_3_227_INDEPENDENT_GOLD_V1.json',g),('V8_3_227_SEALED_MEMBERSHIP_V1.json',membership),('V8_3_227_PRESEAL_DIVERSITY_AUDIT_V1.json',audit)]:dump(n,o)
hashes={'candidate_bank':ho(bank),'selection':ho(selection),'fixture':ho(fix),'independent_gold':ho(g),'membership':ho(membership),'preseal_audit':ho(audit)}
auth={'candidate':'V8.3.227','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'semantic_runtime_executed':False,'batch_a_executed':False,'batch_b_executed':False};dump('V8_3_227_SEALED_AUTHORITY_V1.json',auth)
receipt={'candidate':'V8.3.227','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(ext[0],6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};dump('V8_3_227_PRESEAL_RUN_RECEIPT.json',receipt);print(json.dumps(receipt))
