from pathlib import Path
import re,sys
p=Path(sys.argv[1] if len(sys.argv)>1 else 'candidate/client/candidate.html')
s=p.read_text(encoding='utf-8')
old="const DONATION={vietnam_url:'',paypal_url:''};"
new="const DONATION={vietnam_enabled:true,paypal_url:'https://www.paypal.com/pool/9s2GZ5zO1g?sr=accr',paypal_expires:'2027-02-24',bank:'ACB',account_name:'DUONG THANH LIEM',account_number:'129099639',qr_asset:'assets/v83256-vietqr-acb.svg'};"
assert s.count(old)==1,'donation config anchor mismatch'
s=s.replace(old,new,1)
new_func='''function donationMarkup(){return `<div class="note donation-note"><b>REPORT NÀY ĐÃ ĐỦ HỮU ÍCH CHO BẠN LÚC NÀY?</b><p>Pattern Signal Check được cung cấp miễn phí. Nếu kết quả này có giá trị với bạn và bạn muốn góp phần giúp công cụ tiếp tục được duy trì, cải thiện và phát triển theo hướng bền vững lâu dài để hỗ trợ nhiều người hơn, bạn có thể đóng góp tùy ý.</p><button id="supportToggle" type="button" class="support-toggle">ỦNG HỘ PATTERN SIGNAL CHECK</button><div id="supportPanel" class="support-panel" hidden><div class="support-route"><button id="supportVietnamToggle" type="button" class="support-route-btn">VIỆT NAM — QUÉT QR / CHUYỂN KHOẢN</button><div id="supportVietnamDetails" class="support-vietnam" hidden><img src="${t256(DONATION.qr_asset)}" alt="Mã VietQR chuyển khoản ACB" width="220" height="220"><p><b>Ngân hàng:</b> ${t256(DONATION.bank)}<br><b>Chủ tài khoản:</b> ${t256(DONATION.account_name)}<br><b>Số tài khoản:</b> ${t256(DONATION.account_number)}</p><p class="privacy-note">Không cần ghi tình huống hoặc kết quả Pattern Signal Check vào nội dung chuyển khoản.</p></div></div><div class="support-route"><a id="supportPaypal" class="support-route-link" href="${t256(DONATION.paypal_url)}" target="_blank" rel="noopener noreferrer">QUỐC TẾ — PAYPAL</a><p class="privacy-note">PayPal support route hiện tại hết hạn ngày 24/02/2027. Đây chỉ là thời hạn của đường dẫn thanh toán, không phải thời hạn của Pattern Signal Check.</p></div><p class="privacy-note">Ủng hộ là hoàn toàn tùy ý, không mở khóa nội dung, không tạo quyền ưu tiên và không thay thế tư vấn trả phí.</p></div></div>`}
const _wireResultActions256=wireResultActions;wireResultActions=function(){_wireResultActions256();const t=$('supportToggle'),p=$('supportPanel'),v=$('supportVietnamToggle'),d=$('supportVietnamDetails');if(t&&p)t.onclick=()=>{p.hidden=!p.hidden;t.setAttribute('aria-expanded',String(!p.hidden))};if(v&&d)v.onclick=()=>{d.hidden=!d.hidden;v.setAttribute('aria-expanded',String(!d.hidden))}};'''
s,n=re.subn(r"function donationMarkup\(\)\{.*?\}\nresultActions=function",new_func+'\nresultActions=function',s,count=1,flags=re.S)
assert n==1,'donationMarkup function replacement mismatch'
style='''.support-toggle,.support-route-btn{margin-top:12px;padding:9px 13px;border:1px solid #765a38;border-radius:7px;background:transparent;color:#eee1d0;font-weight:700}.support-panel{margin-top:14px;padding-top:4px}.support-route{margin-top:12px}.support-route-link{display:inline-block;padding:9px 13px;border:1px solid #765a38;border-radius:7px;color:#eee1d0;text-decoration:none;font-weight:700}.support-vietnam{margin-top:12px}.support-vietnam img{display:block;max-width:220px;width:100%;height:auto;background:#fff;padding:8px;border-radius:8px}.support-vietnam p{margin-top:10px}.donation-note{border-color:#4c3d2b}'''
anchor='</head>'
assert s.count(anchor)==1,'head insertion anchor mismatch'
s=s.replace(anchor,'<style id="psc-v83256-donation-style">'+style+'</style>\n</head>',1)
p.write_text(s,encoding='utf-8')
