import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83243-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='885608fce9e70a8818d1ebda23c786a81005a2fe';SEM='QCEvidenceExtractorV5AR -> QCSemanticCoreV117'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The real event is clear except for the concrete response I made at the end.','This actually occurred; what I personally did at closure is still missing.','The lived context is available, but my own endpoint behaviour is absent.','Everything comes from a real situation except the final action from me.','The episode is genuine; the unresolved gap is my observable closing move.','I can supply the real circumstances but not my last behavioural step.'],
'decision':['Make the final choice itself for me rather than merely advising.','Move the deciding authority to you and select what becomes final.','I want your choice to replace mine, not just shape my thinking.','Take the final decision out of my hands and choose the option.','The binding selection should come from you instead of my judgement.','Own the deciding call and determine which route stands.'],
'hypothetical':['This is fabricated evaluation material and not something I lived.','The scenario was written only for testing and has no personal episode behind it.','Nothing here is autobiographical; it is synthetic assessment input.','This example is artificial validation text rather than lived evidence.','I constructed this solely to test classification, not from my life.','Treat this as fictional practice content with no real event behind it.'],
'third':['Infer their private belief although no observable behaviour supports it.','Tell me the hidden conclusion in their mind without words or actions establishing it.','Describe what another person secretly thinks when no conduct confirms it.','Work out their internal position despite no behavioural evidence from them.','State someone else’s concealed view without any observable basis.','Give me the other person’s private conclusion although their actions provide no support.'],
'prediction':['At the later checkpoint, will the outcome I want already be true?','When the future deadline arrives, will this resolve in my favour?','By the future boundary, will the preferred result have happened?','Looking ahead to the named milestone, will this finish as I hope?','Once that later cutoff is reached, will I have the result I want?','At that future point, will things have ended the way I want?'],
'freeze':['A reversible starter was available, but I enlarged the option set and never began.','I had one easy-to-undo first action; instead I kept comparing and stayed still.','A small bounded start was ready, yet I generated more alternatives rather than acting.','I could have tried one reversible move, but option growth displaced initiation.','There was a low-commitment opening available, yet I widened possibilities and made no move.','A safe first action existed, but I kept adding choices and did not start.'],
'ignore':['The main issue still required my action, but I redirected effort into secondary work.','A central obligation remained unanswered while I focused on peripheral tasks.','The core matter stayed open because I shifted attention to side activity.','Something important needed my response while I kept busy with less relevant work.','The primary responsibility still needed me, yet I worked on tasks that could not settle it.','My action was needed on the main matter, but I occupied myself elsewhere.'],
'slow':['I used one bounded pause, checked once, replied, and then closed the issue.','There was one finite delay and one review before I answered and moved on.','I paused inside a clear limit, reviewed once, responded, and did not reopen it.','Before answering I took one contained interval, made one check, then ended the review.','I allowed one defined pause and one review, gave my response, and stopped revisiting it.','I delayed once within a fixed boundary, checked once, replied, and closed the matter.'],
'sequence':['I moved toward action, backed away, then returned to the same conclusion without new facts.','I came close to doing it, withdrew, and repeated the old judgement although nothing changed.','I approached execution, retreated, then cycled to the same reasoning with no new evidence.','I nearly acted, reversed course, and revisited the same assessment under unchanged information.','I advanced toward the move, pulled away, then repeated the same conclusion without added facts.','I got close to acting, stepped back, and returned to prior reasoning despite no new information.'],
'neutral':['I kept the final choice, completed it, and left the matter settled.','I made the decision myself, carried it out, and moved on.','The choice remained mine through completion; afterward I did not reopen it.','I retained final agency, executed what I chose, and treated the issue as resolved.','I chose for myself, finished the action, and left it closed.','The final call stayed with me; I executed it and did not revisit the decision.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A stained-glass archive logged lead strips, solder spools and pattern cards by rack.','A navigation school recorded sextant cases, compass roses and chart weights by cabinet.','A leathercraft room catalogued awl guards, edge slickers and thread cards by bench.','A choir library tracked score tabs, pitch pipes and folder clips by shelf.','A bicycle workshop indexed spoke keys, cable caps and torque cards by drawer.','A pottery classroom logged trimming loops, clay gauges and glaze swatches by table.','A telescope club recorded eyepiece caps, mount knobs and finder cards by case.','A sewing archive catalogued bobbin tins, pattern rulers and zipper tags by locker.','A coffee lab tracked filter papers, dose scoops and roast cards by station.','A sailing shed indexed shackle bins, line gauges and cleat samples by rack.','A clock repair bench logged spring envelopes, loupe cases and crown tubes by drawer.','A lithography room recorded roller sleeves, plate blankets and registration pins by table.','A fisheries classroom catalogued net gauges, buoy labels and chart sleeves by cabinet.','A sound archive tracked patch cords, mic clips and cue sheets by shelf.','A loom workshop indexed heddle hooks, yarn samples and shuttle guides by bin.','A nursery classroom logged grafting knives, seed spoons and moisture tags by bay.','A percussion room recorded drum keys, felt strips and tension cards by drawer.','A baking studio catalogued piping nozzles, mould rings and proof labels by station.']
TAIL_E=['Those glasswork records describe stored materials only, not the response being tested.','The navigation inventory supplies setting but cannot establish behaviour.','That leathercraft list is logistical context rather than response evidence.','The choir-library record is separate from the measured behaviour.','Those bicycle parts are physical background, not semantic evidence.','The pottery inventory cannot determine the response classification.','That telescope register describes objects, not what I did.','The sewing-stock list adds scenery only and cannot prove the mechanism.','Those coffee-lab notes are operational detail, not behavioural evidence.','The sailing inventory cannot substitute for evidence of my response.','That clock-repair stock list is outside the behaviour being measured.','The lithography record is context only and cannot decide the route.','Those fisheries items do not establish the underlying response.','The sound-archive inventory concerns equipment, not behavioural proof.','That loom ledger is background detail rather than mechanism evidence.','The nursery list cannot classify my response.','Those percussion records describe hardware only, not behaviour.','The baking inventory adds context but no proof of the response.']
CTXV=['Một kho kính màu ghi strip chì, spool solder và thẻ pattern theo rack.','Một trường navigation ghi case sextant, compass rose và weight chart theo tủ.','Một phòng leathercraft ghi guard awl, edge slicker và thẻ thread theo bàn.','Một thư viện choir ghi tab score, pitch pipe và clip folder theo kệ.','Một xưởng bicycle ghi spoke key, cap cable và thẻ torque theo ngăn.','Một lớp pottery ghi loop trimming, gauge clay và swatch glaze theo bàn.','Một CLB telescope ghi cap eyepiece, knob mount và thẻ finder theo case.','Một kho sewing ghi tin bobbin, ruler pattern và tag zipper theo locker.','Một lab coffee ghi filter paper, scoop dose và thẻ roast theo trạm.','Một kho sailing ghi bin shackle, gauge line và sample cleat theo rack.','Một bàn sửa clock ghi envelope spring, case loupe và tube crown theo ngăn.','Một phòng lithography ghi sleeve roller, blanket plate và pin registration theo bàn.','Một lớp fisheries ghi gauge net, label buoy và sleeve chart theo tủ.','Một kho sound ghi patch cord, clip mic và sheet cue theo kệ.','Một xưởng loom ghi hook heddle, sample yarn và guide shuttle theo bin.','Một lớp nursery ghi knife grafting, spoon seed và tag moisture theo bay.','Một phòng percussion ghi key drum, strip felt và thẻ tension theo ngăn.','Một studio baking ghi nozzle piping, ring mould và label proof theo trạm.']
TAIL_V=['Bản ghi kính màu chỉ nói về vật liệu lưu trữ, không phải phản ứng đang test.','Danh mục navigation chỉ thêm bối cảnh và không chứng minh hành vi.','Danh sách leathercraft là logistics context chứ không phải response evidence.','Log thư viện choir tách biệt khỏi hành vi đang đo.','Phụ tùng bicycle là background vật thể, không phải semantic evidence.','Danh mục pottery không quyết định phân loại phản ứng.','Register telescope nói về đồ vật, không phải điều tôi đã làm.','Danh sách kho sewing chỉ thêm scenery và không chứng minh mechanism.','Ghi chú coffee lab là operational detail, không phải behavioural evidence.','Danh mục sailing không thể thay thế bằng chứng về phản ứng của tôi.','Stock list sửa clock nằm ngoài hành vi đang đo.','Bản ghi lithography chỉ là context và không quyết định route.','Vật phẩm fisheries không establish underlying response.','Danh mục sound archive nói về thiết bị, không phải behavioural proof.','Ledger loom là background detail chứ không phải mechanism evidence.','Danh sách nursery không thể classify phản ứng của tôi.','Bản ghi percussion chỉ nói về hardware, không phải behaviour.','Danh mục baking thêm context nhưng không có proof của response.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';core=(EN if lang=='EN' else VI)[c][(ci*4+j*5)%6];ctx=(CTXE if lang=='EN' else CTXV)[j];tail=(TAIL_E if lang=='EN' else TAIL_V)[j];parts=[core,ctx,tail];rot=(ci+j)%3;parts=parts[rot:]+parts[:rot];route,fam,seq=E[c];cases.append({'case_id':f'V243-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*2+j)%6],'surface':' '.join(parts),'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V243-S{ci:02d}-{j:02d}' for j in [2,5,8,10,14,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.243 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.243','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.243','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.243','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.243','batch_a':A,'batch_b':B})]:(O/f'V8_3_243_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.243','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_243_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_243_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_243_SEALED_SELECTION_V1.json','fixture':'V8_3_243_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_243_INDEPENDENT_GOLD_V1.json','membership':'V8_3_243_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_243_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.243','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_243_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.243','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_243_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
