import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83253-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='89db04ec936af998c14d2f0451ef87270ea8e349';BASE='59d1d564a2208ae4ce5899262ad094357a20402a';SEM='QCEvidenceExtractorV5AY -> QCSemanticCoreV124'
subprocess.run(['git','fetch','origin','v83252-v1-sealed-validation:refs/remotes/origin/v83252-v1-sealed-validation'],check=True,stdout=subprocess.DEVNULL)
prev=json.loads(subprocess.check_output(['git','show','origin/v83252-v1-sealed-validation:validation/v83252-v1-sealed/V8_3_252_PRESEAL_CANDIDATE_BANK_V1.json'],text=True))['cases'];assert len(prev)==180
CAT=[
' A cryo-electron microscopy facility separately indexed vitrified grids, holey carbon films, plunge-freezing settings, blot forces, blot times, liquid ethane cups, autogrid clips, cassette slots, stage coordinates, beam shifts, coma corrections, defocus targets, dose fractions, motion traces, CTF fits, particle picks, class averages, Euler angles, map resolutions, FSC curves, sharpening B factors, mask radii, symmetry operators, micrograph IDs, acquisition sessions, detector gains, dark references, energy-filter slits, pixel sizes, magnification tables, ice thickness estimates, contamination scores, drift rates, exposure groups, alignment logs and specimen labels; this specialist inventory is unrelated scenery.',
' A quantum standards laboratory separately catalogued Josephson junction arrays, quantum Hall devices, cryogenic current comparators, calculable capacitors, single-electron pumps, Planck constant realizations, voltage steps, resistance plateaus, bridge ratios, null detectors, guarded cables, thermal EMFs, leakage currents, uncertainty budgets, traceability chains, reference resistors, standard cells, current shunts, frequency locks, microwave synthesizers, cryostat temperatures, magnetic fields, contact resistances, metrology triangles, calibration epochs, transfer standards, interlaboratory comparisons, measurement models, covariance terms, coverage factors, type-A evaluations, type-B evaluations, drift corrections, loading effects, cable corrections, environmental logs and certificate identifiers; none of these records transfers final deciding authority.',
' A proteomics core independently stored tryptic digests, peptide standards, C18 tips, desalting cartridges, LC gradients, nanoelectrospray emitters, precursor scans, fragment spectra, collision energies, retention alignments, mass tolerances, isotope envelopes, charge states, peptide-spectrum matches, false-discovery rates, protein groups, sequence coverages, modification sites, reporter ions, intensity normalizations, missing-value flags, decoy databases, search parameters, enzyme specificities, missed cleavages, accession numbers, spectral libraries, calibration mixes, blank injections, carryover checks, column pressures, source voltages, tune files, batch queues, quality-control charts and run manifests; these materials cannot turn fictional content into lived evidence.',
' A forensic linguistics archive independently recorded authorship markers, function-word frequencies, type-token ratios, collocation profiles, punctuation habits, spelling variants, idiolect features, discourse markers, syntactic preferences, n-gram distributions, topic controls, reference corpora, questioned texts, known samples, sampling windows, stylometric distances, classifier scores, confusion matrices, validation folds, lexical richness indices, burstiness measures, sentence lengths, register controls, genre labels, temporal drift checks, transcription rules, normalization settings, tokenization logs, stopword lists, feature weights, attribution likelihoods, examiner notes, peer-review forms, evidence numbers, chain records and report versions; these records cannot reveal another person’s hidden conclusion.',
' A planetary climate modelling centre separately logged radiative-transfer bands, opacity tables, cloud microphysics, aerosol modes, convective schemes, boundary layers, surface albedos, orbital parameters, obliquities, eccentricities, stellar spectra, greenhouse abundances, lapse rates, pressure grids, temperature fields, wind vectors, circulation cells, eddy fluxes, precipitation rates, evaporation fields, sea-ice fractions, soil moistures, model timesteps, spin-up lengths, restart files, ensemble members, forcing scenarios, diagnostics, energy balances, top-of-atmosphere fluxes, spectral outputs, validation cases, sensitivity runs, parameter files and simulation IDs; none of these records answers a future-outcome request.',
' A dendroclimatology repository independently indexed site chronologies, ring-width indices, maximum latewood densities, blue-intensity series, pointer years, crossdating scores, expressed population signals, Rbar statistics, spline detrending, regional-curve standardizations, climate-response functions, bootstrapped correlations, moving windows, drought reconstructions, temperature reconstructions, precipitation proxies, calibration periods, verification periods, reduction-of-error scores, coefficient efficiencies, spectral peaks, wavelet powers, teleconnection indices, sample depths, replication curves, age structures, pith offsets, bark dates, missing rings, frost damage, fire scars, disturbance pulses, chronology IDs, specimen codes and archive racks; these materials do not create or remove a stalled first move.',
' A systems reliability laboratory separately catalogued fault trees, event trees, failure modes, hazard rates, Weibull shapes, mean-times-between-failure, mean-times-to-repair, redundancy diagrams, common-cause factors, beta factors, cut sets, importance measures, availability models, maintainability curves, spare policies, inspection intervals, proof-test coverages, diagnostic coverages, latent failures, demand rates, repair distributions, Markov states, transition matrices, Monte Carlo seeds, confidence bounds, censoring flags, accelerated-life stresses, derating factors, environmental profiles, reliability growth curves, field-return codes, warranty populations, subsystem IDs, test campaigns and review logs; that inventory cannot resolve a central obligation left unattended.',
' A laser frequency-comb laboratory separately held mode-locked oscillators, repetition rates, carrier-envelope offsets, f-2f interferometers, octave-spanning spectra, photonic-crystal fibres, phase locks, beat notes, reference cavities, ultra-stable lasers, optical dividers, frequency counters, transfer oscillators, servo bandwidths, loop filters, piezo actuators, AOM shifts, EOM sidebands, comb teeth, wavelength meters, heterodyne traces, Allan deviations, phase-noise spectra, drift fits, thermal shields, vibration isolators, vacuum housings, fibre links, cycle slips, lock statistics, reference epochs, UTC ties, calibration tables, acquisition scripts and experiment IDs; these objects do not alter a bounded pause-review-close response.',
' A structural geology laboratory separately logged stereonet poles, great circles, fold axes, cleavage traces, lineation plunges, bedding strikes, dip angles, shear senses, kinematic indicators, strain ellipsoids, finite-strain ratios, Mohr circles, stress tensors, fault-slip inversions, paleostress axes, slickenside rakes, vein orientations, joint sets, fracture densities, scanline lengths, outcrop stations, traverse IDs, oriented cores, thin sections, microstructures, recrystallized grains, deformation twins, pressure shadows, porphyroclasts, foliation domains, metamorphic grades, map sheets, section lines, coordinate grids and specimen numbers; this equipment adds no new evidence between approach and retreat.',
' A decision-science experimental archive separately stored choice sets, utility estimates, indifference curves, prospect values, loss-aversion coefficients, probability weights, response times, confidence ratings, preference reversals, framing conditions, endowment effects, status-quo biases, default effects, ambiguity parameters, risk premiums, certainty equivalents, incentive schemes, comprehension checks, attention filters, exclusion flags, randomization seeds, treatment cells, participant IDs, block orders, trial numbers, outcome matrices, payoff tables, posterior distributions, model comparisons, information criteria, preregistrations, analysis scripts, robustness checks, replication batches and data dictionaries; these records do not change who retained and completed the final choice.'
]
VAR=[
('metagenomics cluster',['shotgun libraries','k-mer spectra','assembly graphs','contig N50s','bin completeness','bin contamination','marker genes','taxonomic profiles','functional annotations','coverage depths','read mappings','GC contents','tetranucleotide frequencies','MAG identifiers','dereplication thresholds','ANI matrices','strain variants','mobile elements','plasmid contigs','viral bins','CRISPR spacers','metabolic pathways','enzyme codes','ortholog groups','abundance tables','normalization factors','batch effects','negative controls','mock communities','sequencing lanes','base-quality scores','adapter trims','host depletion','coassembly groups','sample manifests','pipeline commits']),
('stellar spectroscopy vault',['Balmer lines','Fraunhofer lines','equivalent widths','line depths','rotational broadenings','microturbulence','macroturbulence','surface gravities','effective temperatures','metallicities','alpha enhancements','radial velocities','bisector spans','continuum placements','telluric masks','line lists','oscillator strengths','excitation potentials','ionization balances','synthetic spectra','model atmospheres','chi-square maps','posterior samples','MCMC chains','abundance ratios','isotope shifts','Zeeman splittings','magnetic fields','spectral orders','signal-to-noise ratios','barycentric epochs','standard stars','instrument profiles','resolution elements','calibration lamps','observation IDs']),
('soil microbiome room',['rhizosphere samples','bulk soils','DNA yields','amplicon variants','16S regions','ITS regions','primer biases','chimera removals','rarefaction depths','alpha diversities','beta diversities','Bray-Curtis distances','UniFrac distances','ordination axes','PERMANOVA terms','indicator taxa','differential abundances','compositional transforms','soil pHs','organic carbons','total nitrogens','moisture contents','texture classes','root biomasses','enzyme activities','respiration rates','microbial biomasses','field blocks','plot IDs','extraction batches','PCR plates','sequencing runs','blank controls','positive controls','metadata tables','analysis notebooks']),
('art conservation imaging bay',['multispectral cubes','UV fluorescence','IR reflectography','X-radiographs','raking-light captures','photometric stereo','RTI domes','color targets','grey cards','lens profiles','distortion maps','registration points','homographies','reflectance maps','false-colour composites','pigment clusters','underdrawing traces','pentimenti regions','varnish fluorescences','retouch signatures','craquelure maps','loss masks','surface normals','height fields','camera raws','exposure brackets','white balances','ICC profiles','pixel scales','capture dates','object IDs','panel coordinates','condition overlays','annotation layers','checksum manifests','archive derivatives']),
('volcanology observatory',['seismic swarms','harmonic tremor','long-period events','volcanotectonic events','RSAM levels','gas fluxes','SO2 rates','CO2 ratios','plume heights','thermal anomalies','tilt vectors','GPS baselines','InSAR fringes','crater temperatures','lava effusions','ash columns','tephra thicknesses','grain sizes','ballistic ranges','lahar sensors','rain gauges','camera frames','acoustic arrays','infrasound amplitudes','alert levels','event catalogs','station codes','telemetry gaps','battery voltages','calibration pulses','eruption chronologies','sample bags','petrology notes','melt inclusions','crystal populations','monitoring reports']),
('epigenomics facility',['bisulfite conversions','CpG sites','methylation betas','DMRs','ATAC peaks','ChIP peaks','histone marks','enhancer states','promoter states','chromatin loops','Hi-C contacts','TAD boundaries','CTCF motifs','nucleosome positions','accessibility scores','fragment lengths','duplicate rates','mapping qualities','library complexities','batch covariates','cell types','replicate IDs','peak callers','motif enrichments','gene annotations','pathway enrichments','coverage tracks','bigWig files','BED intervals','reference builds','sample sheets','QC reports','normalization methods','latent factors','effect sizes','adjusted p-values']),
('precision machining cell',['spindle speeds','feed rates','depths of cut','tool offsets','runout values','surface roughnesses','Ra values','Rz values','tool wears','flank wears','chatter frequencies','cutting forces','coolant flows','chip morphologies','thermal drifts','fixture datums','probe cycles','work offsets','G-code blocks','M-code states','servo loads','axis errors','backlash compensations','ball-screw pitches','laser calibrations','part programs','inspection plans','CMM points','tolerance zones','feature controls','material heats','tool IDs','operation numbers','lot sizes','scrap codes','machine logs']),
('marine genomics station',['eDNA filters','seawater volumes','salinity values','temperature profiles','chlorophyll levels','plankton fractions','barcode loci','COI reads','18S reads','ASV tables','OTU clusters','reference libraries','species assignments','confidence scores','rare taxa','occupancy estimates','detection probabilities','site replicates','field blanks','extraction blanks','PCR negatives','mock controls','flow cells','read depths','sequence qualities','primer mismatches','haplotype networks','population clusters','FST values','heterozygosities','allelic richnesses','sample coordinates','cruise legs','station numbers','collection dates','biobank IDs']),
('speech acoustics lab',['formant frequencies','F1 values','F2 values','F3 values','voice onset times','fundamental frequencies','jitter measures','shimmer measures','harmonics-to-noise ratios','spectral tilts','cepstral peaks','duration measures','intensity contours','pitch tracks','vowel spaces','consonant bursts','frication spectra','nasal poles','nasal zeros','coarticulation slopes','prosodic boundaries','intonation phrases','ToBI labels','syllable timings','articulation rates','speaker IDs','dialect groups','recording channels','microphone distances','sampling rates','bit depths','room responses','annotation tiers','Praat scripts','measurement windows','corpus manifests']),
('planetary materials lab',['meteorite sections','chondrule diameters','CAI inclusions','matrix fractions','metal grains','troilite phases','olivine compositions','pyroxene compositions','oxygen isotopes','chromium isotopes','titanium isotopes','cosmic-ray exposures','shock stages','weathering grades','petrologic types','bulk densities','magnetic susceptibilities','reflectance spectra','Raman shifts','SEM images','microprobe analyses','LA-ICP-MS spots','noble gases','radiogenic ages','Pb-Pb dates','Al-Mg systematics','sample masses','curatorial numbers','thin-section labels','mount IDs','beam currents','spot sizes','counting times','standard materials','data reductions','uncertainty tables']),
('clinical gait analysis unit',['marker trajectories','ground reactions','joint angles','joint moments','joint powers','pelvic tilts','hip flexions','knee flexions','ankle dorsiflexions','cadence values','step lengths','stride lengths','walking speeds','stance times','swing times','double-support times','EMG envelopes','muscle activations','force plates','motion cameras','sampling rates','filter cutoffs','marker sets','segment models','inverse dynamics','body masses','height measures','trial IDs','subject codes','assistive devices','orthoses','condition labels','repeat trials','quality flags','report outputs','session dates']),
('radio astronomy correlator',['visibility matrices','baseline pairs','delay models','fringe rotations','channelizers','polyphase filters','integration times','quantization levels','system temperatures','gain curves','bandpass solutions','phase solutions','RFI flags','UV coordinates','w terms','Stokes products','polarization leakages','closure phases','closure amplitudes','calibrator scans','target scans','scan numbers','spectral windows','channel widths','reference frequencies','Doppler frames','time stamps','antenna positions','weather tables','opacity corrections','data weights','flag versions','calibration tables','image products','measurement sets','project codes']),
('cell mechanics laboratory',['traction forces','substrate stiffnesses','Young moduli','Poisson ratios','focal adhesions','actin bundles','myosin intensities','cell areas','aspect ratios','migration speeds','persistence lengths','nuclear shapes','membrane tensions','cortical tensions','indentation depths','AFM forces','cantilever constants','bead displacements','PIV fields','strain energies','stress maps','hydrogel batches','crosslink densities','coating concentrations','cell lines','passage numbers','seeding densities','incubation times','image stacks','segmentation masks','tracking IDs','replicate wells','treatment groups','control groups','analysis scripts','experiment dates']),
('palaeoecology archive',['pollen sums','charcoal counts','diatom valves','chironomid heads','testate amoebae','macrofossils','loss-on-ignition','carbonate contents','magnetic susceptibilities','sediment ages','age-depth models','radiocarbon dates','tephra horizons','varve counts','core depths','sample intervals','accumulation rates','ordination scores','transfer functions','climate reconstructions','vegetation zones','fire episodes','lake levels','catchment changes','human indicators','coprophilous fungi','erosion markers','chronology ensembles','posterior ages','calibration curves','lab codes','core IDs','site coordinates','archive trays','data tables','publication links']),
('photonic integrated circuits bay',['waveguide widths','etch depths','coupling gaps','ring radii','quality factors','free spectral ranges','insertion losses','propagation losses','grating couplers','Mach-Zehnder arms','phase shifters','thermo-optic heaters','electro-optic modulators','photodiodes','responsivities','dark currents','S parameters','eye diagrams','bit-error rates','wavelength sweeps','polarization states','fiber arrays','alignment tolerances','lithography doses','resist thicknesses','mask layers','wafer IDs','die coordinates','probe stations','temperature sweeps','current biases','voltage biases','measurement scripts','calibration files','packaging lots','test reports']),
('hydrological isotope lab',['delta18O values','delta2H values','deuterium excesses','tritium activities','strontium ratios','radon concentrations','end-member signatures','mixing fractions','evaporation lines','local meteoric lines','precipitation samples','groundwater wells','spring samples','river samples','soil waters','lysimeters','sample dates','elevations','conductivities','temperatures','alkalinities','major ions','silica contents','residence times','recharge elevations','flow paths','uncertainty intervals','reference waters','drift corrections','memory effects','injection sequences','vial IDs','instrument runs','calibration slopes','QC flags','field notebooks']),
('historical metallurgy room',['slag chemistries','ore minerals','furnace linings','tuyere fragments','hammer scales','metal prills','carburization profiles','phosphorus levels','manganese levels','sulfur levels','inclusion morphologies','grain sizes','ferrite phases','pearlite fractions','cementite networks','quench structures','forge welds','work-hardening traces','microhardness values','SEM images','EDS maps','metallographic sections','etch reagents','sample orientations','artifact IDs','context numbers','smelting reconstructions','fuel estimates','airflow estimates','furnace temperatures','yield calculations','mass balances','provenance hypotheses','archive drawers','photomicrographs','report references']),
('microseismic monitoring room',['event hypocentres','P arrivals','S arrivals','travel-time residuals','velocity models','station corrections','magnitude scales','moment tensors','focal mechanisms','first motions','spectral corners','stress drops','source radii','quality factors','attenuation curves','waveform stacks','template matches','detection thresholds','association windows','cluster IDs','double-difference locations','relative relocations','station codes','channel names','sample rates','clock corrections','timing drifts','noise floors','trigger rates','catalogue completeness','b-value estimates','Gutenberg-Richter fits','swarm episodes','depth sections','uncertainty ellipsoids','review flags'])]
new=[]
for x in prev:
 m=re.search(r'-S(\d+)-(\d+)$',x['case_id']);assert m
 ci,j=map(int,m.groups());name,items=VAR[j]
 vblock=f" A separate {name} independently indexed {', '.join(items)}; this specialist inventory is inert physical context and supplies no behavioural evidence."
 y={k:v for k,v in x.items() if k!='case_id'};y['case_id']=f'V253-S{ci:02d}-{j:02d}';y['surface']=CAT[ci]+vblock+x['surface'];new.append(y)
assert len(new)==180 and len({x['surface'] for x in new})==180
# V253-only semantically inert case-specific lexical capsule: construction diversity only.
ALPHA='bcdfghjklmnpqrstvwxyz'
def capsule(case_id):
    import hashlib
    h=hashlib.sha256(('v253:'+case_id).encode()).hexdigest()
    toks=[]
    for i in range(180):
        z=int(hashlib.sha256((h+':'+str(i)).encode()).hexdigest()[:14],16)
        toks.append('vx'+''.join(ALPHA[(z>>(j*5))%len(ALPHA)] for j in range(9)))
    return ' A separate archival cipher inventory listed '+', '.join(toks)+'; these inert lexical labels describe no behaviour, decision, prediction, sequence, or personal response.'
for c in new:
    c['surface']=capsule(c['case_id'])+' '+c['surface']
cm={x['case_id']:x for x in new};selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V253-S{ci:02d}-{j:02d}' for j in [0,9,3,12,6,15]];selected+=ids;A+=ids[:3];B+=ids[3:]
fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A1=toks(a);B1=toks(b);return len(A1&B1)/max(1,len(A1|B1))
internal=(0,None)
for i,x in enumerate(new):
 for y in new[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior+=obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in new:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in new if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
objects={'PRESEAL_CANDIDATE_BANK_V1':{'authority':'V8.3.253 PRESEAL CANDIDATE BANK V1','cases':new},'SEALED_SELECTION_V1':{'candidate':'V8.3.253','selected':selected,'batch_a':A,'batch_b':B},'SEALED_FIXTURE_V1':{'candidate':'V8.3.253','cases':fixture},'INDEPENDENT_GOLD_V1':{'candidate':'V8.3.253','cases':gold},'SEALED_MEMBERSHIP_V1':{'candidate':'V8.3.253','batch_a':A,'batch_b':B}}
for name,obj in objects.items():(O/f'V8_3_253_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.253','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_253_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_253_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_253_SEALED_SELECTION_V1.json','fixture':'V8_3_253_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_253_INDEPENDENT_GOLD_V1.json','membership':'V8_3_253_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_253_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.253','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_253_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.253','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_253_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
