import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83226-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='ca32baec5d57886c71b62ad21f938253572d1229';SEM='QCEvidenceExtractorV5AD -> QCSemanticCoreV103'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The real episode is otherwise accounted for; the only missing evidence is the action I personally took at the endpoint.','This happened to me, and the surrounding sequence is known, but my own last observable response has not been supplied.','The lived situation is concrete; what remains unstated is what I myself actually did before it closed.','All material context is available except the behaviour that came from me at the final point.','The event is real and sufficiently described, yet my personal closing action is absent.','Nothing important is missing from the setting except my own concrete response immediately before completion.'],
'decision':['Choose the final option in my place so your decision substitutes for mine.','Make the selection itself for me; I am handing you the final call.','I want your judgement to determine which route I take rather than keeping the choice myself.','Take over the decision and name the option that becomes final for me.','Do not merely advise me; make the final selection on my behalf.','Use your decision as the final answer instead of leaving me to choose.'],
'hypothetical':['This scenario was invented only for a validation exercise and never happened to me.','I created this as synthetic test material, not as a report of lived experience.','Treat the case as fictional evaluation input; there is no personal event behind it.','The example is deliberately fabricated and is not part of my history.','Nothing described is something I lived through; it is a constructed test case.','This is made-up practice material rather than evidence from my life.'],
'third':['Infer the private belief of the other person although no observable statement or action from them supports it.','Tell me what someone else secretly concluded when their outward behaviour gives no evidence.','State their hidden internal view despite having no conduct or words that establish it.','Work out the other person’s concealed thought without any observable basis from them.','I want their private conclusion even though nothing they did or said demonstrates it.','Tell me what is secretly in their mind when no behavioural evidence is available.'],
'prediction':['At the future checkpoint I specified, will I get the outcome I want?','By the stated future date, will the result resolve in my favour?','When that future milestone arrives, will events end the way I hope?','Will the preferred result have occurred by the future cutoff I named?','Looking ahead to that boundary, will this conclude with my desired outcome?','When the named future marker is reached, will I have the result I want?'],
'freeze':['A reversible low-commitment opening was ready, but I expanded alternatives and never began.','I could have tested a small step and undone it, yet I kept widening the option set instead of starting.','A contained first move with a clear exit existed; I added possibilities and remained inactive.','There was an easy-to-reverse starter action, but comparison kept expanding and I did not initiate it.','The initial move was low risk and reversible; I generated more choices and left it untouched.','I had a bounded reversible first action available, yet option expansion prevented any start.'],
'ignore':['The main responsibility still needed my response, but I redirected attention into peripheral work that could not resolve it.','A consequential issue required action from me while I busied myself with side tasks instead.','The core obligation was waiting for me, yet I shifted effort into secondary activity.','My response was still needed on the central matter, but I diverted into less relevant work.','I left the important issue unresolved and occupied myself elsewhere with tasks that did not answer it.','The primary responsibility required my action; I avoided it through side activity that could not settle it.'],
'slow':['I took one bounded pause, reviewed once, answered, and then closed the issue.','There was one finite delay and one check before I responded and stopped reviewing.','I paused within a clear limit, made a single review pass, replied, and did not reopen it.','Before answering I used one contained interval and one review, then treated the process as complete.','I allowed one limited pause, checked once, gave my response, and ended the review cycle.','I delayed inside a defined boundary, reviewed one time, answered, and left it closed.'],
'sequence':['I moved toward execution, pulled back, then repeated the same judgement without new evidence.','I approached the action, withdrew, and returned to my prior conclusion with no new facts.','I got close to acting, stepped away, then cycled back to identical reasoning without new information.','I advanced toward the move, reversed course, and revisited the old assessment although nothing new appeared.','I nearly executed the step, retreated, and came back to the same conclusion under unchanged evidence.','I approached doing it, backed out, then repeated the same judgement while the facts stayed the same.'],
'neutral':['I kept the final choice with me, completed the action, and left the matter closed.','I decided for myself, carried out what I chose, and did not revisit it afterward.','Final agency remained mine through execution; I finished the step and moved on.','I made my own final call, completed it, and treated the issue as settled.','Ownership of the choice stayed with me until completion, after which I did not reopen it.','I retained the decision, executed it, and left the issue closed.']}
VI={k:[
{'clarification':'Episode thật đã đủ các phần khác; evidence còn thiếu duy nhất là action tôi tự làm ở endpoint.','decision':'Chọn final option thay tôi để decision của bạn thay cho decision của tôi.','hypothetical':'Scenario này được bịa chỉ để validation và chưa từng xảy ra với tôi.','third':'Suy ra private belief của người kia dù không observable statement hay action nào support nó.','prediction':'Tại future checkpoint đã nêu, tôi có nhận outcome mình muốn không?','freeze':'Có opening ít commitment và reversible, nhưng tôi mở rộng alternative rồi không bắt đầu.','ignore':'Main responsibility vẫn cần response của tôi nhưng tôi redirect attention sang peripheral work không thể resolve nó.','slow':'Tôi lấy một bounded pause, review một lần, trả lời rồi đóng issue.','sequence':'Tôi tiến về execution, pull back rồi lặp cùng judgement khi không có evidence mới.','neutral':'Tôi giữ final choice ở mình, hoàn thành action rồi để matter closed.'}[k],
{'clarification':'Chuyện xảy ra thật với tôi, sequence xung quanh đã biết nhưng last observable response của tôi chưa có.','decision':'Hãy make selection luôn cho tôi; tôi giao final call cho bạn.','hypothetical':'Tôi tạo đoạn này như synthetic test material, không phải lived experience.','third':'Nói người khác secretly concluded gì khi outward behaviour không cho evidence.','prediction':'Đến future date đã nói, result có resolve theo hướng có lợi cho tôi không?','freeze':'Tôi có thể test bước nhỏ rồi undo, vậy mà cứ nới option set thay vì start.','ignore':'Một issue consequential cần action từ tôi trong khi tôi lại bận với side task.','slow':'Có một finite delay và một check trước khi tôi response rồi ngừng review.','sequence':'Tôi tiếp cận action, withdraw rồi quay lại prior conclusion khi không có fact mới.','neutral':'Tôi tự quyết, thực hiện điều đã chọn và không revisit sau đó.'}[k],
{'clarification':'Lived situation cụ thể; phần chưa nêu là chính tôi thực sự làm gì trước closure.','decision':'Tôi muốn judgement của bạn quyết route tôi đi thay vì giữ choice ở mình.','hypothetical':'Hãy coi case là fictional evaluation input, không có personal event phía sau.','third':'Nói hidden internal view của họ dù không conduct hay words nào xác lập.','prediction':'Khi future milestone tới, events có kết thúc như tôi hy vọng không?','freeze':'Có first move giới hạn với exit rõ; tôi thêm possibility và vẫn inactive.','ignore':'Core obligation đang chờ tôi nhưng tôi shift effort sang secondary activity.','slow':'Tôi pause trong clear limit, review một pass, reply rồi không mở lại.','sequence':'Tôi gần acting, bước ra rồi cycle về reasoning giống hệt khi không có information mới.','neutral':'Final agency vẫn ở tôi qua execution; tôi finish step rồi move on.'}[k],
{'clarification':'Mọi material context đều có trừ behaviour đến từ tôi ở final point.','decision':'Nhận lấy decision và nói option nào trở thành final cho tôi.','hypothetical':'Ví dụ cố ý fabricated và không thuộc history của tôi.','third':'Xác định concealed thought của người kia khi không có observable basis.','prediction':'Preferred result có xảy ra trước future cutoff tôi nêu không?','freeze':'Có starter action dễ reverse nhưng comparison cứ mở rộng và tôi không initiate.','ignore':'Response của tôi vẫn cần cho central matter nhưng tôi divert sang work ít relevant hơn.','slow':'Trước khi trả lời tôi dùng một contained interval và một review rồi xem process complete.','sequence':'Tôi tiến tới move, đổi hướng rồi revisit old assessment dù không có gì mới.','neutral':'Tôi tự đưa final call, complete nó và xem issue settled.'}[k],
{'clarification':'Event là thật và đủ detail, nhưng personal closing action của tôi vẫn absent.','decision':'Đừng chỉ advise; hãy make final selection thay tôi.','hypothetical':'Không điều nào là chuyện tôi lived through; đây là constructed test case.','third':'Tôi muốn private conclusion của họ dù không điều họ làm hay nói chứng minh.','prediction':'Nhìn tới future boundary đó, chuyện này có kết thúc bằng desired outcome không?','freeze':'Initial move ít risk và reversible; tôi tạo thêm choice rồi để nó untouched.','ignore':'Tôi để important issue unresolved rồi bận ở chỗ khác với task không answer nó.','slow':'Tôi cho phép một limited pause, check một lần, response rồi kết thúc review cycle.','sequence':'Tôi gần execute step, retreat rồi quay về same conclusion dưới evidence không đổi.','neutral':'Ownership của choice ở tôi đến completion, sau đó tôi không reopen.'}[k],
{'clarification':'Setting không thiếu gì quan trọng trừ concrete response của tôi ngay trước completion.','decision':'Dùng decision của bạn làm final answer thay vì để tôi tự choose.','hypothetical':'Đây là made-up practice material chứ không phải evidence từ đời tôi.','third':'Nói điều secretly trong đầu họ khi không có behavioural evidence.','prediction':'Khi future marker đã nêu tới, tôi có result mình muốn không?','freeze':'Có bounded reversible first action nhưng option expansion ngăn tôi start.','ignore':'Primary responsibility cần action của tôi; tôi avoid qua side activity không thể settle.','slow':'Tôi delay trong defined boundary, review một lần, trả lời rồi để closed.','sequence':'Tôi tiếp cận việc làm nó, back out rồi lặp same judgement khi facts giữ nguyên.','neutral':'Tôi giữ decision, execute nó và để issue closed.'}[k]] for k in C}
CTXE=['A lantern workshop logged wick trays beside inventory cards.','A choir archive indexed folder clips and stand tags by cabinet.','A paddle centre tracked dry-bag seals beside equipment boards.','A microscope room recorded slide boxes and lens sleeves by drawer.','A costume library indexed garment hooks and fitting tokens by rail.','A print lab tracked proof sleeves and roller cases by bench.','A greenhouse store logged nozzle keys and tray markers by bay.','A ceramics depot indexed shelf posts and glaze labels by rack.','A community pantry tracked crate seals and dispatch cards by shelf.','A camera workshop logged clamp bags and cable reels by drawer.','A restoration desk indexed tissue packets and brush tubes by table.','A rehearsal archive tracked score envelopes and mic clips by locker.','A nursery shed logged pot tags and hose keys by bench.','A map room indexed paper weights and tube labels by cabinet.','A repair studio tracked parts bins and tool tags by station.','A harbour office logged gate paddles and ticket sleeves by desk.','An astronomy club indexed eyepiece caps and tripod tags by case.','A fabric studio tracked sample frames and dye labels by table.']
CTXV=['Lantern workshop ghi wick tray cạnh inventory card.','Choir archive lập index folder clip và stand tag theo cabinet.','Paddle centre theo dõi dry-bag seal cạnh equipment board.','Microscope room ghi slide box và lens sleeve theo drawer.','Costume library lập index garment hook và fitting token theo rail.','Print lab theo dõi proof sleeve và roller case theo bench.','Greenhouse store ghi nozzle key và tray marker theo bay.','Ceramics depot lập index shelf post và glaze label theo rack.','Community pantry theo dõi crate seal và dispatch card theo shelf.','Camera workshop ghi clamp bag và cable reel theo drawer.','Restoration desk lập index tissue packet và brush tube theo table.','Rehearsal archive theo dõi score envelope và mic clip theo locker.','Nursery shed ghi pot tag và hose key theo bench.','Map room lập index paper weight và tube label theo cabinet.','Repair studio theo dõi parts bin và tool tag theo station.','Harbour office ghi gate paddle và ticket sleeve theo desk.','Astronomy club lập index eyepiece cap và tripod tag theo case.','Fabric studio theo dõi sample frame và dye label theo table.']
TAIL_E=['That storage detail is contextual only and cannot establish the response.','The inventory marker belongs to logistics rather than behavioural evidence.','That equipment note cannot determine the semantic mechanism.','The filing record adds setting only, not evidence of the response.','That physical reference is external to the behaviour being classified.','The administrative marker cannot create a response signal.']
TAIL_V=['Storage detail đó chỉ là context và không thể xác lập response.','Inventory marker thuộc logistics chứ không phải behavioural evidence.','Equipment note đó không thể quyết semantic mechanism.','Filing record chỉ thêm setting chứ không thêm evidence của response.','Physical reference nằm ngoài behaviour đang được classify.','Administrative marker không thể tạo response signal.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI'; k=j%6; core=(EN if lang=='EN' else VI)[c][k]; ctx=(CTXE if lang=='EN' else CTXV)[(ci*7+j*5)%18]; tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*2+j)%6]; parts=[core,ctx,tail]; rot=(ci+j)%3; parts=parts[rot:]+parts[:rot]; surface=' '.join(parts); route,fam,seq=E[c]; cases.append({'case_id':f'V226-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(2*ci+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
sel=[];A=[];B=[]
for ci in range(10):
 ids=[f'V226-S{ci:02d}-{j:02d}' for j in [0,3,7,9,13,17]]; sel+=ids; A+=ids[:3]; B+=ids[3:]
assert len(sel)==60 and len(A)==len(B)==30 and set(A).isdisjoint(B)
selection={'authority':'V8.3.226 PRESEAL SELECTION','selection_method':'category-balanced deterministic construction-only; no runtime output','selected':sel,'batch_a':A,'batch_b':B}; chosen=set(sel); fixture={'authority':'V8.3.226 SEALED FIXTURE','cases':[x for x in cases if x['case_id'] in chosen]}; gold={'authority':'V8.3.226 INDEPENDENT GOLD','construction':'category contract independent of semantic runtime','cases':[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture['cases']]}; membership={'authority':'V8.3.226 SEALED MEMBERSHIP','cases':[{'case_id':i,'batch':'A' if i in set(A) else 'B'} for i in sel]}
def toks(s):return set(re.findall(r'[a-z0-9]+',s.lower()))
def jac(a,b):
 a,b=toks(a),toks(b);return len(a&b)/len(a|b) if a|b else 1
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  z=jac(x['surface'],y['surface']);
  if z>internal[0]:internal=(z,(x['case_id'],y['case_id']))
external_surfaces=[]
for v in [219,220,221,222,223,224,225]:
 br=f'v83{v}-v1-sealed-validation'; path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'; subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL); data=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True)); external_surfaces += [(v,x['case_id'],x['surface']) for x in data['cases']]
external=(0,None);ge75=0;exact=0;oldset={s for _,_,s in external_surfaces}
for x in cases:
 if x['surface'] in oldset:exact+=1
 for v,cid,s in external_surfaces:
  z=jac(x['surface'],s); ge75+=int(z>=.75)
  if z>external[0]:external=(z,(x['case_id'],v,cid))
fps=[(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],x['surface'].lower()) for x in cases];fpdup=len(fps)-len(set(fps))
audit={'candidate':'V8.3.226','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':ge75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':internal[0]<.75 and external[0]<.75 and ge75==0 and exact==0 and fpdup==0};assert audit['pass'],audit
bank={'authority':'V8.3.226 PRESEAL CANDIDATE BANK','cases':cases};objs={'candidate_bank':bank,'selection':selection,'fixture':fixture,'independent_gold':gold,'membership':membership,'preseal_audit':audit};files={'candidate_bank':'V8_3_226_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_226_SEALED_SELECTION_V1.json','fixture':'V8_3_226_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_226_INDEPENDENT_GOLD_V1.json','membership':'V8_3_226_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_226_PRESEAL_DIVERSITY_AUDIT_V1.json'}
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
for k,o in objs.items():(O/files[k]).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
auth={'authority':'V8.3.226 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':{k:h(o) for k,o in objs.items()},'preseal_pass':True,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'v221_sealed_rerun':False,'v222_sealed_rerun':False,'v223_sealed_rerun':False,'v224_sealed_rerun':False,'v225_sealed_rerun':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_226_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n');receipt={'candidate':'V8.3.226','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,**{k:audit[k] for k in ['candidate_count','selected_count','batch_a_count','batch_b_count','internal_max_similarity','internal_max_pair','external_max_similarity','external_cases_at_or_above_0_75','exact_external_duplicates','semantic_fingerprint_exact_duplicates','semantic_runtime_executed','semantic_authority_loaded','selection_uses_runtime_output','batch_a_executed','batch_b_executed']},'conclusion':'success'};(O/'V8_3_226_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
