import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83242-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='79645f8973c9e8288119f79318b39646e2feb00f';SEM='QCEvidenceExtractorV5AQ -> QCSemanticCoreV116'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['A real episode is described, but my final observable move is still missing.','This happened in my life; the endpoint action from me has not been supplied.','The surrounding event is concrete, yet what I did at closure is absent.','I can describe the lived context but not my last behavioural response.','The situation is real; only my own final action remains unknown.','Everything is grounded in a real event except my closing behaviour.'],
'decision':['Take over the actual choosing and decide the final option for me.','I want the deciding authority moved to you, not advice from you.','Choose the final route in place of me making that choice.','Make the binding selection yourself rather than helping me weigh it.','The decision itself should come from you instead of from my judgement.','Remove final choice ownership from me and select what stands.'],
'hypothetical':['This is synthetic evaluation text and not an event I lived.','Nothing here comes from my experience; it was fabricated for testing.','The scenario is constructed assessment material without a personal episode behind it.','This example is fictional validation input rather than autobiographical evidence.','I invented this case only to test classification, not to describe my life.','Treat this as artificial practice text with no lived event attached.'],
'third':['Infer the other person’s private thought with no outward behaviour supporting it.','Tell me their hidden conclusion even though no words or actions establish it.','State what someone else secretly believes without observable evidence from them.','Describe their internal view despite nothing behavioural confirming it.','Work out another person’s concealed belief without an observable basis.','Give me their private mental position although their conduct provides no support.'],
'prediction':['At the future checkpoint, will the outcome I want already have happened?','When the later deadline arrives, will this end in my favour?','By the future boundary, will the preferred result be true?','Looking ahead to the named milestone, will things finish as I hope?','Once that later cutoff is reached, will I have the result I want?','At that future point, will the situation have resolved the way I want?'],
'freeze':['A reversible starter was available, but I widened the option set and never began.','I had one easy-to-undo first move; instead I kept comparing and stayed still.','A small bounded start was ready, yet I generated more alternatives rather than acting.','I could have tried one reversible opening move, but option growth replaced initiation.','There was a low-commitment start available, yet I expanded possibilities and made no move.','A safe first action existed, but I kept adding choices and did not start.'],
'ignore':['The main issue still needed my action, but I shifted effort into secondary work.','A central obligation remained unanswered while I worked on peripheral tasks.','The core matter stayed open because I diverted attention to side activity.','Something important required my response while I kept busy with less relevant work.','The primary responsibility still needed me, yet I focused on tasks that could not settle it.','My action was needed on the main matter, but I occupied myself elsewhere.'],
'slow':['I took one bounded pause, checked once, answered, and then closed the issue.','There was one finite delay and one review before I replied and moved on.','I paused within a clear limit, reviewed once, responded, and did not reopen it.','Before answering I used one contained interval, made one check, then ended the review.','I allowed one defined pause and one review, gave my response, and stopped revisiting it.','I delayed once inside a fixed boundary, checked once, replied, and closed the matter.'],
'sequence':['I moved toward action, withdrew, then returned to the same conclusion without new facts.','I came close to doing it, stepped back, and repeated the old judgement although nothing changed.','I approached execution, retreated, then cycled to the same reasoning with no new evidence.','I nearly acted, reversed course, and revisited the same assessment under unchanged information.','I advanced toward the move, pulled away, then repeated the same conclusion without added facts.','I got close to acting, backed off, and returned to prior reasoning despite no new information.'],
'neutral':['I kept the final choice, carried it out, and left the matter settled.','I made the decision myself, executed it, and moved on.','The choice remained mine through completion; afterward I did not reopen it.','I retained final agency, completed the action, and treated the issue as resolved.','I chose for myself, finished what I chose, and left it closed.','The final call stayed with me; I executed it and did not revisit the decision.']}
VI={k:[x.replace('I ','Tôi ').replace('my ','của tôi ') for x in v] for k,v in EN.items()}
CTXE=['A ceramics archive logged glaze paddles, kiln cones and sponge blocks by bay.','A lighthouse workshop recorded lens rings, brass screws and wick gauges by cabinet.','A fencing club catalogued mask straps, foil tips and scoring cards by rack.','A bookbinding room tracked linen tapes, paste brushes and press boards by shelf.','A perfumery lab indexed pipette sleeves, scent strips and vial caps by drawer.','A theatre prop room logged pulley hooks, paint tins and cue markers by locker.','A geology class recorded sample trays, hand lenses and field labels by bench.','A violin workshop catalogued bridge blanks, peg shapers and rosin cloths by drawer.','A fermentation lab tracked airlock seals, pH cards and jar clips by station.','A surveying shed indexed tripod clamps, flag rolls and plumb bob cases by rack.','A watchmaking bench logged spring tins, loupe cases and crown tubes by drawer.','A printmaking studio recorded brayer sleeves, plate blankets and registration tabs by table.','A marine classroom catalogued buoy tags, rope gauges and chart clips by cabinet.','A photography darkroom tracked reel cores, timer cards and chemical labels by shelf.','A weaving archive indexed heddle hooks, yarn cards and shuttle pins by bin.','A horticulture room logged grafting tape, seed spoons and humidity cards by bay.','A drum workshop recorded tension rods, felt strips and key sleeves by drawer.','A pastry classroom catalogued mould rings, piping tips and proof cards by station.']
TAIL_E=['Those ceramics records concern stored materials only, not the response under test.','The lighthouse inventory adds setting but cannot establish behaviour.','The fencing equipment list is logistical context rather than response evidence.','That bindery stock record is separate from the measured behaviour.','Those perfumery items are physical background, not semantic evidence.','The prop-room inventory cannot determine the response classification.','That geology register describes objects, not what I did.','The violin-tool list adds scenery only and cannot prove the mechanism.','Those fermentation notes are operational detail, not behavioural evidence.','The surveying inventory cannot substitute for evidence of my response.','That watchmaking stock list is outside the behaviour being measured.','The printmaking record is context only and cannot decide the route.','Those marine items do not establish the underlying response.','The darkroom inventory concerns equipment, not behavioural proof.','That weaving ledger is background detail rather than mechanism evidence.','The horticulture list cannot classify my response.','Those drum-workshop records describe hardware only, not behaviour.','The pastry inventory adds context but no proof of the response.']
CTXV=['Một kho gốm ghi paddle men, cone lò và block sponge theo bay.','Một xưởng hải đăng ghi ring lens, vít đồng và gauge tim đèn theo tủ.','Một CLB fencing ghi strap mask, tip foil và thẻ điểm theo rack.','Một phòng đóng sách ghi tape linen, brush hồ và press board theo kệ.','Một lab nước hoa ghi sleeve pipette, strip mùi và nắp vial theo ngăn.','Một phòng đạo cụ sân khấu ghi hook pulley, tin sơn và marker cue theo locker.','Một lớp địa chất ghi khay sample, hand lens và field label theo bàn.','Một xưởng violin ghi bridge blank, peg shaper và cloth rosin theo ngăn.','Một lab lên men ghi seal airlock, thẻ pH và clip jar theo trạm.','Một kho survey ghi clamp tripod, roll cờ và case plumb bob theo rack.','Một bàn sửa đồng hồ ghi tin spring, case loupe và tube crown theo ngăn.','Một studio printmaking ghi sleeve brayer, blanket plate và tab registration theo bàn.','Một lớp marine ghi tag buoy, gauge rope và clip chart theo tủ.','Một darkroom ảnh ghi core reel, thẻ timer và label hóa chất theo kệ.','Một kho weaving ghi hook heddle, thẻ yarn và pin shuttle theo bin.','Một phòng horticulture ghi tape grafting, thìa seed và thẻ humidity theo bay.','Một xưởng drum ghi tension rod, strip felt và sleeve key theo ngăn.','Một lớp pastry ghi ring mould, tip piping và thẻ proof theo trạm.']
TAIL_V=['Bản ghi kho gốm chỉ nói về vật liệu lưu trữ, không phải phản ứng đang test.','Danh mục hải đăng chỉ thêm bối cảnh và không chứng minh hành vi.','Danh sách đồ fencing là logistics context chứ không phải response evidence.','Log kho đóng sách tách biệt khỏi hành vi đang đo.','Vật phẩm lab nước hoa là background vật thể, không phải semantic evidence.','Danh mục phòng đạo cụ không quyết định phân loại phản ứng.','Register địa chất nói về đồ vật, không phải điều tôi đã làm.','Danh sách tool violin chỉ thêm scenery và không chứng minh mechanism.','Ghi chú lên men là operational detail, không phải behavioural evidence.','Danh mục survey không thể thay thế bằng chứng về phản ứng của tôi.','Stock list đồng hồ nằm ngoài hành vi đang đo.','Bản ghi printmaking chỉ là context và không quyết định route.','Vật phẩm marine không establish underlying response.','Danh mục darkroom nói về thiết bị, không phải behavioural proof.','Ledger weaving là background detail chứ không phải mechanism evidence.','Danh sách horticulture không thể classify phản ứng của tôi.','Bản ghi xưởng drum chỉ nói về hardware, không phải behaviour.','Danh mục pastry thêm context nhưng không có proof của response.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';core=(EN if lang=='EN' else VI)[c][(ci*3+j*5)%6];ctx=(CTXE if lang=='EN' else CTXV)[j];tail=(TAIL_E if lang=='EN' else TAIL_V)[j];parts=[core,ctx,tail];rot=(ci*2+j)%3;parts=parts[rot:]+parts[:rot];route,fam,seq=E[c];cases.append({'case_id':f'V242-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci+j*2)%6],'surface':' '.join(parts),'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V242-S{ci:02d}-{j:02d}' for j in [0,3,7,11,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.242 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.242','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.242','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.242','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.242','batch_a':A,'batch_b':B})]:(O/f'V8_3_242_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.242','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_242_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_242_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_242_SEALED_SELECTION_V1.json','fixture':'V8_3_242_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_242_INDEPENDENT_GOLD_V1.json','membership':'V8_3_242_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_242_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.242','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_242_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.242','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_242_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
