import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83232-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='7731574dd6db5d4c257dc088f5e791b1e980d5be';SEM='QCEvidenceExtractorV5AI -> QCSemanticCoreV108'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The actual situation is otherwise clear, but I have left out the concrete response I made at the endpoint.','This was lived, and I can account for the surrounding events; my own final observable action is the part not supplied.','Everything relevant around the episode is known except what I personally did as it closed.','The event and sequence are real; I still have not stated my own closing behaviour.','The situation is sufficiently described apart from the last action that came from me.','I have given the real context but not my own endpoint behaviour.'],
'decision':['Take the decision itself from me and choose which option becomes final.','Make the final call on my behalf rather than leaving me to choose it.','I am handing over the choice itself; select the route that will stand as my decision.','Use your judgement to make the deciding choice instead of only advising me.','Choose the final option in my place so your call replaces mine.','I want you to own the selection itself and make the final decision.'],
'hypothetical':['This is invented test material; none of it is an event I experienced.','The scenario is artificial validation input and has no lived episode behind it.','I fabricated this example for assessment; it is not autobiographical.','Nothing described happened to me; this is only a constructed test case.','Treat this as fictional practice material rather than evidence from my life.','The example exists for testing and is unrelated to any real experience of mine.'],
'third':['Infer the other person’s hidden belief even though their words and actions provide no observable support.','Tell me what someone else privately thinks when there is no behavioural evidence from them.','Work out the concealed conclusion in their mind without any outward conduct that establishes it.','State another person’s internal view despite no statement or action supporting that inference.','Describe their secret belief when nothing observable from them demonstrates it.','Give me the private conclusion of the other person even though there is no evidence in their behaviour.'],
'prediction':['By the future deadline I specified, will I have the result I want?','When that future milestone arrives, will the outcome go in my favour?','At the future checkpoint I named, will the desired result have happened?','Will the preferred outcome exist by the future date I gave?','Looking ahead to that future boundary, will this end the way I hope?','Once the future point is reached, will I get the result I want?'],
'freeze':['I had a contained first move with an easy exit, but I kept adding possibilities and never began.','A small reversible starter was available; comparison kept expanding and I remained inactive.','I could have tested one bounded opening action and undone it, yet option growth replaced starting.','There was a low-commitment first step, but I widened the choices until no move was made.','A reversible trial action was ready; I generated more alternatives instead of initiating it.','I had one safe-to-reverse starter action, but kept expanding options and stayed still.'],
'ignore':['The main matter still needed my action, but I redirected myself into secondary work that could not settle it.','A central responsibility waited for my response while I occupied myself with side tasks.','The important issue remained unanswered because I shifted effort into peripheral activity.','My response was still required, yet I kept busy with work that did not address the core matter.','The primary obligation stayed unresolved while I diverted attention elsewhere.','Something consequential needed action from me, but I used less relevant tasks instead.'],
'slow':['I took one bounded pause, checked once, answered, and did not reopen the matter.','There was a single limited delay and one review before I responded and closed the issue.','I paused within a defined boundary, reviewed once, replied, and then stopped reviewing.','Before responding I used one contained interval, checked one time, and left the matter closed.','I allowed one finite pause and one review pass, answered, and moved on.','I delayed within one clear limit, checked once, gave my response, and ended the review cycle.'],
'sequence':['I approached the action, withdrew, then cycled back to the same conclusion with no new evidence.','I moved close to execution, stepped away, and repeated the same reasoning although nothing changed.','I advanced toward the move, retreated, then returned to my prior judgement without new facts.','I nearly acted, pulled back, and revisited the same assessment while the evidence stayed unchanged.','I came close to doing it, reversed course, then repeated the same conclusion with no additional information.','I moved toward execution, backed out, and returned to identical reasoning despite no new evidence.'],
'neutral':['I retained the final choice, executed it, and left the issue resolved.','I made the decision myself, completed the action, and moved on afterward.','The final call stayed with me through execution; once done, I did not reopen it.','I kept decision ownership, carried out what I chose, and treated the matter as settled.','I chose for myself, finished the action, and left the issue closed.','Final agency remained mine; I completed what I decided and did not revisit it.']}
VI={
'clarification':['Situation thật đã rõ các phần khác nhưng tôi bỏ thiếu concrete response mình làm ở endpoint.','Chuyện này lived và surrounding event đã rõ; final observable action của tôi chưa được đưa.','Mọi thứ quanh episode đã biết trừ chính tôi làm gì lúc closure.','Event và sequence là thật; tôi vẫn chưa nêu closing behaviour của mình.','Situation đủ detail trừ last action đến từ tôi.','Tôi đã đưa real context nhưng chưa có endpoint behaviour của mình.'],
'decision':['Take decision khỏi tôi và chọn option nào thành final.','Make final call on my behalf thay vì để tôi choose.','Tôi hand over choice; hãy select route đứng thành decision của tôi.','Dùng judgement của bạn make deciding choice thay vì chỉ advise.','Chọn final option ở vị trí của tôi để call của bạn replace call của tôi.','Tôi muốn bạn own selection và make final decision.'],
'hypothetical':['Đây là invented test material; không điều gì là event tôi trải qua.','Scenario là artificial validation input và không có lived episode phía sau.','Tôi fabricate example để assessment; nó không autobiographical.','Không điều nào xảy ra với tôi; đây chỉ constructed test case.','Hãy coi đây là fictional practice material chứ không evidence từ đời tôi.','Example chỉ để testing và không liên quan real experience của tôi.'],
'third':['Suy ra hidden belief của người kia dù words/actions không observable support.','Nói người khác privately nghĩ gì khi không behavioural evidence từ họ.','Xác định concealed conclusion trong mind họ khi không outward conduct establish.','Nói internal view của người khác dù không statement/action support inference.','Mô tả secret belief khi không observable từ họ demonstrate.','Cho private conclusion của người kia dù behaviour không có evidence.'],
'prediction':['Đến future deadline tôi nêu, tôi có result mình muốn không?','Khi future milestone tới, outcome có in my favour không?','Tại future checkpoint đó, desired result có xảy ra không?','Preferred outcome có tồn tại trước future date không?','Nhìn tới future boundary, chuyện này có end như tôi hope không?','Khi future point tới, tôi có get result mình muốn không?'],
'freeze':['Tôi có contained first move với easy exit nhưng cứ add possibility rồi không begin.','Có small reversible starter nhưng comparison expand và tôi inactive.','Tôi có thể test bounded opening action rồi undo nhưng option growth thay starting.','Có low-commitment first step nhưng tôi widen choice tới mức không move.','Reversible trial action đã sẵn nhưng tôi generate alternative thay vì initiate.','Có starter action dễ reverse nhưng tôi expand option và stay still.'],
'ignore':['Main matter vẫn cần action của tôi nhưng tôi redirect sang secondary work không settle được.','Central responsibility chờ response của tôi trong khi tôi bận side task.','Important issue unanswered vì tôi shift effort sang peripheral activity.','Response vẫn required nhưng tôi bận work không address core matter.','Primary obligation unresolved trong khi tôi divert attention elsewhere.','Consequential matter cần action nhưng tôi dùng less relevant task thay.'],
'slow':['Tôi take one bounded pause, check once, answer rồi không reopen.','Có single limited delay và one review trước response rồi close issue.','Tôi pause trong defined boundary, review once, reply rồi stop reviewing.','Trước response tôi dùng contained interval, check one time rồi để closed.','Tôi cho finite pause và one review pass, answer rồi move on.','Tôi delay trong clear limit, check once, response rồi end review cycle.'],
'sequence':['Tôi approach action, withdraw rồi cycle về same conclusion không new evidence.','Tôi move gần execution, step away rồi repeat same reasoning dù nothing changed.','Tôi advance toward move, retreat rồi return prior judgement không new facts.','Tôi nearly acted, pull back rồi revisit same assessment khi evidence unchanged.','Tôi gần doing it, reverse course rồi repeat same conclusion không additional information.','Tôi move toward execution, back out rồi return identical reasoning dù no new evidence.'],
'neutral':['Tôi retain final choice, execute rồi để issue resolved.','Tôi tự make decision, complete action rồi move on.','Final call ở tôi qua execution; xong rồi tôi không reopen.','Tôi giữ decision ownership, carry out choice rồi xem matter settled.','Tôi tự choose, finish action rồi để issue closed.','Final agency ở tôi; tôi complete decision rồi không revisit.']}
CTXE=['A paper workshop logged cutting guides and glue pots by bench.','A rehearsal library indexed music folders and stand clips by cabinet.','A sailing classroom tracked shackle kits and line tags by locker.','A greenhouse store recorded tray markers and mist keys by bay.','A clay studio catalogued trimming loops and glaze cards by shelf.','A film archive logged reel sleeves and clamp bags by case.','A pastry room indexed scraper boxes and proof cards by station.','A hiking club tracked rope coils and route tags by rack.','A costume store recorded garment labels and cue cards by rail.','A weaving class catalogued shuttle cases and frame clips by table.','A stargazing club logged lens caps and tripod bolts by case.','A chart room indexed tube labels and weight strips by drawer.','A recording booth tracked cable loops and headset covers by cabinet.','A botany room recorded specimen sleeves and drying sheets by shelf.','A rowing shed catalogued seat runners and blade collars by board.','A movement studio logged shoe bags and costume tags by locker.','A maker lab indexed tool trays and component labels by bench.','A catering class tracked utensil crates and pantry labels by shelf.']
CTXV=['Paper workshop ghi cutting guide và glue pot theo bench.','Rehearsal library index music folder và stand clip theo cabinet.','Sailing classroom theo dõi shackle kit và line tag theo locker.','Greenhouse store ghi tray marker và mist key theo bay.','Clay studio catalog trimming loop và glaze card theo shelf.','Film archive ghi reel sleeve và clamp bag theo case.','Pastry room index scraper box và proof card theo station.','Hiking club theo dõi rope coil và route tag theo rack.','Costume store ghi garment label và cue card theo rail.','Weaving class catalog shuttle case và frame clip theo table.','Stargazing club ghi lens cap và tripod bolt theo case.','Chart room index tube label và weight strip theo drawer.','Recording booth theo dõi cable loop và headset cover theo cabinet.','Botany room ghi specimen sleeve và drying sheet theo shelf.','Rowing shed catalog seat runner và blade collar theo board.','Movement studio ghi shoe bag và costume tag theo locker.','Maker lab index tool tray và component label theo bench.','Catering class theo dõi utensil crate và pantry label theo shelf.']
TAIL_E=['That inventory record is context only and cannot establish the behavioural response.','The storage note belongs to logistics rather than semantic evidence.','That equipment detail cannot determine the response route.','The filing entry adds setting only, not evidence of the mechanism.','That physical record sits outside the behavioural evidence.','The administrative detail cannot decide the semantic classification.']
TAIL_V=['Inventory record đó chỉ là context và không establish behavioural response.','Storage note thuộc logistics chứ không semantic evidence.','Equipment detail không determine response route.','Filing entry chỉ add setting chứ không evidence mechanism.','Physical record nằm ngoài behavioural evidence.','Administrative detail không decide semantic classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci+j*4)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*13+j*5)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*4+j*2)%6];parts=[core,ctx,tail];rot=(ci*2+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V232-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*2+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V232-S{ci:02d}-{j:02d}' for j in [0,2,7,11,15,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
(O/'V8_3_232_PRESEAL_CANDIDATE_BANK_V1.json').write_text(json.dumps({'authority':'V8.3.232 fresh PRESEAL candidate bank','cases':cases},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_232_SEALED_SELECTION_V1.json').write_text(json.dumps({'authority':'V8.3.232 sealed selection','selected':selected,'batch_a':A,'batch_b':B},indent=2)+'\n')
(O/'V8_3_232_SEALED_FIXTURE_V1.json').write_text(json.dumps({'authority':'V8.3.232 SEALED FIXTURE','cases':fixture},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_232_INDEPENDENT_GOLD_V1.json').write_text(json.dumps({'authority':'V8.3.232 independent gold','cases':gold},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_232_SEALED_MEMBERSHIP_V1.json').write_text(json.dumps({'authority':'V8.3.232 sealed membership','batch_a':A,'batch_b':B},indent=2)+'\n')
audit={'candidate':'V8.3.232','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
(O/'V8_3_232_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
files={'candidate_bank':'V8_3_232_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_232_SEALED_SELECTION_V1.json','fixture':'V8_3_232_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_232_INDEPENDENT_GOLD_V1.json','membership':'V8_3_232_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_232_PRESEAL_DIVERSITY_AUDIT_V1.json'}
hashes={k:h(json.loads((O/n).read_text())) for k,n in files.items()}
auth={'candidate':'V8.3.232','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False}
(O/'V8_3_232_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.232','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'}
(O/'V8_3_232_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
