import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83228-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='2d5725e4b12f532ca9b710083e55e21efdb6c686';SEM='QCEvidenceExtractorV5AF -> QCSemanticCoreV105'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The situation really happened and the sequence is otherwise clear; the missing evidence is the observable thing I myself did at the end.','This is my lived event and the surrounding facts are known, but I have not said what action came from me before closure.','The episode is concrete rather than hypothetical; only my own endpoint behaviour remains unstated.','Everything needed about the context is present except the response I personally made at the final moment.','The real-life chronology is sufficiently described, yet my closing action has not been supplied.','The setting is complete enough to understand the event, but the last behaviour performed by me is still missing.'],
'decision':['Choose the actual final option for me and let your decision replace mine.','I want you to make the final call itself, not merely help me compare the options.','Take the choice out of my hands and decide which option becomes final.','Use your judgement as the decision-maker in my place.','Select the final course on my behalf rather than leaving me with the choice.','Make the final selection for me so I do not make that decision myself.'],
'hypothetical':['This is invented test material only and did not happen in my life.','The case is synthetic validation input, not a lived situation.','I fabricated this example for evaluation; none of it is personal history.','Treat this solely as a fictional practice scenario rather than something I experienced.','Nothing described here happened to me; the text was made only for testing.','This example is deliberately constructed and has no real event behind it.'],
'third':['Tell me the other person’s private belief even though no observable conduct or statement from them supports it.','Infer what someone else secretly concluded without any outward evidence from them.','Work out the hidden thought of the other person when nothing they did or said establishes it.','State their concealed internal conclusion despite having no behavioural basis for that inference.','I want you to tell me someone else’s private view although their actions provide no evidence.','Tell me what is secretly in their mind when no statement or conduct from them supports the claim.'],
'prediction':['By the future date I named, will I have the result I want?','At that stated future checkpoint, will the outcome resolve in my favour?','When the future milestone arrives, will events have ended the way I hope?','Will my preferred result be true by the future cutoff I specified?','Looking ahead to that future boundary, will I get the desired outcome?','At the named future marker, will this have turned out the way I want?'],
'freeze':['A reversible first step was available, but I kept expanding the alternatives and never started.','I had a low-commitment move I could undo; comparison kept growing and I stayed inactive.','There was a bounded test action with an easy exit, yet I widened the choices instead of beginning.','The first move was safe to reverse, but I generated more options until I did nothing.','A small action could have been tried and undone; I kept comparing possibilities and remained still.','An easy-to-reverse starter move existed, but option expansion stopped me from initiating it.'],
'ignore':['The main issue still required my response, but I redirected attention to side work that could not settle it.','An important matter was waiting for action from me while I busied myself with peripheral tasks.','The central obligation remained unresolved; I diverted effort into secondary activity instead.','My response was still necessary on the core matter, yet I shifted into less relevant work.','The primary issue needed action from me, but I occupied myself with side tasks that did not address it.','A consequential responsibility stayed unanswered because I moved into peripheral activity rather than responding.'],
'slow':['I took one bounded pause, checked once, answered, and then closed the matter.','There was one finite delay and one review before I responded and stopped reconsidering it.','I paused within a clear limit, reviewed one time, replied, and did not reopen the issue.','Before answering I used one contained interval, made a single check, and then treated it as complete.','I allowed one limited pause, reviewed once, gave my response, and ended the review cycle.','I delayed inside a defined boundary, checked once, answered, and left it closed.'],
'sequence':['I moved toward acting, pulled back, then returned to the same judgement without new evidence.','I approached execution, withdrew, and repeated my prior conclusion while the facts stayed the same.','I got close to action, stepped away, and cycled back to identical reasoning with no new information.','I nearly carried out the move, reversed course, and revisited the old assessment although nothing new appeared.','I advanced toward execution, retreated, and came back to the same conclusion under unchanged evidence.','I approached doing it, backed out, then repeated the same judgement while no new facts emerged.'],
'neutral':['I kept the final decision with me, completed the action, and left the matter settled.','I chose for myself, carried out the step, and did not revisit it once finished.','Final agency stayed with me through execution; I completed the action and moved on.','I made my own final call, completed what I chose, and treated the issue as closed.','The choice remained mine until completion, after which I did not reopen the matter.','I retained the decision, executed it, and left the issue settled.']}
VI={
'clarification':['Situation này xảy ra thật và sequence phần khác đã rõ; evidence còn thiếu là observable action chính tôi làm ở cuối.','Đây là lived event của tôi và surrounding facts đã biết, nhưng tôi chưa nói action nào đến từ tôi trước closure.','Episode là concrete chứ không hypothetical; chỉ own endpoint behaviour của tôi chưa được nêu.','Context cần thiết đã đủ trừ response tôi tự làm ở final moment.','Real-life chronology đã mô tả đủ, nhưng closing action của tôi chưa được cung cấp.','Setting đủ để hiểu event, nhưng last behaviour do tôi thực hiện vẫn còn thiếu.'],
'decision':['Chọn actual final option thay tôi và để decision của bạn thay cho decision của tôi.','Tôi muốn bạn make final call luôn, không chỉ giúp compare option.','Lấy choice khỏi tay tôi và quyết option nào trở thành final.','Dùng judgement của bạn làm decision-maker ở vị trí của tôi.','Chọn final course thay mặt tôi thay vì để choice ở tôi.','Make final selection cho tôi để tôi không tự đưa decision đó.'],
'hypothetical':['Đây chỉ là invented test material và không xảy ra trong đời tôi.','Case này là synthetic validation input, không phải lived situation.','Tôi fabricate example này để evaluation; không phần nào là personal history.','Chỉ coi đây là fictional practice scenario chứ không phải chuyện tôi trải qua.','Không điều nào ở đây xảy ra với tôi; text chỉ được tạo để testing.','Example này deliberately constructed và không có real event phía sau.'],
'third':['Nói private belief của người kia dù không observable conduct hay statement nào từ họ support.','Suy ra người khác secretly concluded gì khi không có outward evidence từ họ.','Xác định hidden thought của người kia khi không điều họ làm hay nói xác lập nó.','Nói concealed internal conclusion của họ dù không có behavioural basis cho inference.','Tôi muốn private view của người khác dù actions của họ không cho evidence.','Nói điều secretly trong đầu họ khi không statement hay conduct nào support claim.'],
'prediction':['Đến future date tôi nêu, tôi có result mình muốn không?','Tại future checkpoint đó, outcome có resolve theo hướng có lợi cho tôi không?','Khi future milestone tới, events có kết thúc như tôi hy vọng không?','Preferred result có đúng trước future cutoff tôi đã specify không?','Nhìn tới future boundary đó, tôi có desired outcome không?','Tại future marker đã nêu, chuyện này có turn out như tôi muốn không?'],
'freeze':['Có reversible first step, nhưng tôi cứ expand alternative rồi không start.','Tôi có low-commitment move có thể undo; comparison cứ tăng và tôi vẫn inactive.','Có bounded test action với easy exit, vậy mà tôi widen choice thay vì begin.','First move safe to reverse, nhưng tôi generate thêm option tới mức không làm gì.','Một small action có thể try rồi undo; tôi cứ compare possibility và đứng yên.','Có starter move dễ reverse, nhưng option expansion ngăn tôi initiate.'],
'ignore':['Main issue vẫn cần response của tôi, nhưng tôi redirect attention sang side work không thể settle.','Một matter important đang chờ action từ tôi khi tôi lại bận peripheral task.','Central obligation vẫn unresolved; tôi divert effort sang secondary activity.','Response của tôi vẫn necessary ở core matter, nhưng tôi shift sang work ít relevant.','Primary issue cần action từ tôi, nhưng tôi occupy với side task không address nó.','Một consequential responsibility vẫn unanswered vì tôi move sang peripheral activity thay vì responding.'],
'slow':['Tôi lấy một bounded pause, check một lần, answer rồi đóng matter.','Có một finite delay và một review trước khi tôi response rồi stop reconsidering.','Tôi pause trong clear limit, review một lần, reply rồi không reopen issue.','Trước khi answer tôi dùng một contained interval, single check rồi xem complete.','Tôi cho một limited pause, review một lần, response rồi end review cycle.','Tôi delay trong defined boundary, check một lần, answer rồi để closed.'],
'sequence':['Tôi move toward acting, pull back rồi quay lại same judgement khi không có new evidence.','Tôi approach execution, withdraw rồi lặp prior conclusion khi facts không đổi.','Tôi gần action, step away rồi cycle về identical reasoning khi không có new information.','Tôi gần carry out move, reverse course rồi revisit old assessment dù không có gì mới.','Tôi advance toward execution, retreat rồi quay lại same conclusion dưới unchanged evidence.','Tôi approach việc làm nó, back out rồi lặp same judgement khi không có new facts.'],
'neutral':['Tôi giữ final decision ở mình, complete action rồi để matter settled.','Tôi tự choose, carry out step và không revisit khi finished.','Final agency ở tôi suốt execution; tôi complete action rồi move on.','Tôi tự make final call, complete điều đã chọn và xem issue closed.','Choice vẫn ở tôi đến completion, sau đó tôi không reopen matter.','Tôi giữ decision, execute nó và để issue settled.']}
CTXE=['A violin workshop catalogued bridge blanks and string packets by drawer.','A bakery school logged proofing baskets and scraper tags by bench.','A kayak store indexed paddle collars and dry-bag clips by rack.','A textile archive tracked swatch folders and loom tools by shelf.','A photo studio recorded light clamps and cable ties by case.','A herbarium room catalogued specimen sleeves and label cards by cabinet.','A dance wardrobe logged shoe bags and costume hooks by rail.','A repair library indexed bit sets and parts trays by station.','A pottery classroom tracked trimming loops and glaze cards by table.','A ferry workshop recorded rope tags and gate keys by locker.','A language room catalogued headset bags and workbook trays by cabinet.','A greenhouse shed logged nozzle keys and pot labels by bay.','A print archive indexed roller covers and proof folders by rack.','A telescope room tracked lens caps and mount plates by case.','A cooking lab logged pantry bins and utensil tags by shelf.','A map library catalogued tube sleeves and weight bars by drawer.','A rowing club indexed seat tools and oar collars by board.','A theatre store tracked prop labels and headset hooks by cabinet.']
CTXV=['Violin workshop catalog bridge blank và string packet theo drawer.','Bakery school ghi proofing basket và scraper tag theo bench.','Kayak store lập index paddle collar và dry-bag clip theo rack.','Textile archive theo dõi swatch folder và loom tool theo shelf.','Photo studio ghi light clamp và cable tie theo case.','Herbarium room catalog specimen sleeve và label card theo cabinet.','Dance wardrobe ghi shoe bag và costume hook theo rail.','Repair library lập index bit set và parts tray theo station.','Pottery classroom theo dõi trimming loop và glaze card theo table.','Ferry workshop ghi rope tag và gate key theo locker.','Language room catalog headset bag và workbook tray theo cabinet.','Greenhouse shed ghi nozzle key và pot label theo bay.','Print archive lập index roller cover và proof folder theo rack.','Telescope room theo dõi lens cap và mount plate theo case.','Cooking lab ghi pantry bin và utensil tag theo shelf.','Map library catalog tube sleeve và weight bar theo drawer.','Rowing club lập index seat tool và oar collar theo board.','Theatre store theo dõi prop label và headset hook theo cabinet.']
TAIL_E=['That inventory record is background only and cannot establish the response.','The storage note belongs to logistics, not behavioural evidence.','That equipment detail cannot determine the semantic route.','The filing entry adds setting only and does not prove the response.','That physical reference is outside the mechanism being classified.','The administrative note cannot create the behavioural signal.']
TAIL_V=['Inventory record đó chỉ là background và không thể xác lập response.','Storage note thuộc logistics chứ không phải behavioural evidence.','Equipment detail đó không thể quyết semantic route.','Filing entry chỉ thêm setting và không chứng minh response.','Physical reference nằm ngoài mechanism đang được classify.','Administrative note không thể tạo behavioural signal.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(j*5+ci)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*13+j*5)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(3*ci+j)%6];parts=[core,ctx,tail];rot=(ci+2*j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V228-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci+j*2)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V228-S{ci:02d}-{j:02d}' for j in [1,4,8,9,14,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 ta,tb=toks(a),toks(b);return len(ta&tb)/len(ta|tb) if ta|tb else 1.0
internal=(0,None)
for i in range(len(cases)):
 for j in range(i):
  q=sim(cases[i]['surface'],cases[j]['surface'])
  if q>internal[0]:internal=(q,(cases[j]['case_id'],cases[i]['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227]:
 br=f'v83{v}-v1-sealed-validation';p=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  z=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{p}'],text=True));prior+=z.get('cases',[])
 except Exception: pass
ext=(0,None);at75=0;exact=0;prior_sur={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_sur:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:at75+=1
  if q>ext[0]:ext=(q,(x['case_id'],y.get('case_id')))
fps=[(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface'])))) for x in cases];fpdup=len(fps)-len(set(fps))
assert internal[0]<.75 and ext[0]<.75 and at75==0 and exact==0 and fpdup==0
def dump(n,o):(O/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def ho(o):return hashlib.sha256(canon(o)).hexdigest()
bank={'authority':'V8.3.228 PRESEAL CANDIDATE BANK','cases':cases};selection={'authority':'V8.3.228 SEALED SELECTION','selected':selected,'batch_a':A,'batch_b':B};fix={'authority':'V8.3.228 SEALED FIXTURE','cases':fixture};g={'authority':'V8.3.228 INDEPENDENT GOLD','cases':gold};membership={'authority':'V8.3.228 SEALED MEMBERSHIP','selected':selected,'batch_a':A,'batch_b':B};audit={'candidate':'V8.3.228','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(ext[0],6),'external_max_pair':ext[1],'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
for n,o in [('V8_3_228_PRESEAL_CANDIDATE_BANK_V1.json',bank),('V8_3_228_SEALED_SELECTION_V1.json',selection),('V8_3_228_SEALED_FIXTURE_V1.json',fix),('V8_3_228_INDEPENDENT_GOLD_V1.json',g),('V8_3_228_SEALED_MEMBERSHIP_V1.json',membership),('V8_3_228_PRESEAL_DIVERSITY_AUDIT_V1.json',audit)]:dump(n,o)
hashes={'candidate_bank':ho(bank),'selection':ho(selection),'fixture':ho(fix),'independent_gold':ho(g),'membership':ho(membership),'preseal_audit':ho(audit)};auth={'candidate':'V8.3.228','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'semantic_runtime_executed':False,'batch_a_executed':False,'batch_b_executed':False};dump('V8_3_228_SEALED_AUTHORITY_V1.json',auth)
receipt={'candidate':'V8.3.228','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(ext[0],6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};dump('V8_3_228_PRESEAL_RUN_RECEIPT.json',receipt);print(json.dumps(receipt))
