import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83233-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='8f85efc8b8383420c65a50724d2512693302dbcb';SEM='QCEvidenceExtractorV5AI -> QCSemanticCoreV108'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['This really occurred, and the surrounding sequence is available, but my own last observable response is not included.','The episode is lived and otherwise described; what remains missing is the action that came from me at the close.','I can give the real context, yet the concrete behaviour I personally showed at the endpoint is absent.','The situation itself is clear except for what I actually did as it finished.','The account covers the event but leaves out my own closing action.','Everything relevant is there except my personal response immediately before the end.'],
'decision':['I am transferring the choice itself to you; decide which option becomes final.','Take the final decision from my hands and make the selection on my behalf.','I want your call to replace mine, so choose the route itself.','Make the deciding choice rather than merely helping me compare.','Use your judgement as the final selection in place of my own.','I am handing over decision ownership; pick the option that will stand.'],
'hypothetical':['This is synthetic evaluation material and not an episode from my life.','I made this scenario up for testing; nothing described happened to me.','The case is deliberately fictional and not autobiographical.','This example exists only for validation and has no lived experience behind it.','Treat this as an artificial practice scenario, not personal evidence.','The text is invented test input and unrelated to anything I experienced.'],
'third':['Tell me the private conclusion in the other person’s mind even though no observable words or conduct support it.','Infer what someone else secretly believes without behavioural evidence from them.','Work out the hidden view of the other person despite no outward action establishing it.','State their internal belief when nothing they said or did gives evidence.','Describe what the other person privately concluded with no observable basis.','Give me someone else’s concealed belief even though their behaviour provides no support.'],
'prediction':['At the future date I specified, will the desired outcome have happened?','By the future checkpoint I named, will things resolve in my favour?','When that future milestone arrives, will I have the result I want?','Will the preferred result exist by the future cutoff I gave?','Looking ahead to that future boundary, will the situation end the way I hope?','Once that future point arrives, will the outcome be what I want?'],
'freeze':['A reversible starter move was available, but I kept enlarging the choice set and never initiated it.','I had a small low-commitment step with an easy exit; comparison widened and I stayed inactive.','There was one contained opening action I could undo, yet more alternatives replaced starting.','A bounded first move was ready, but I kept adding possibilities and made no start.','I could have tested a safe reversible step, yet option growth kept me still.','The first action was easy to reverse, but I broadened alternatives instead of beginning.'],
'ignore':['The core issue still required my response, but I put effort into side tasks that could not answer it.','An important responsibility waited for my action while I focused on peripheral work.','The main matter remained unresolved because I shifted attention to secondary activity.','My response was still needed, yet I occupied myself with work unrelated to settling it.','The central obligation stayed unanswered while I diverted into less relevant tasks.','Something consequential required action from me, but I redirected into side work instead.'],
'slow':['I paused once within a fixed limit, reviewed once, responded, and left the issue closed.','There was one contained delay and one check before I answered and stopped reviewing.','I used a bounded interval, made a single review pass, replied, and did not reopen it.','Before responding I took one finite pause, checked once, then closed the matter.','I allowed one defined delay and one review, gave my response, and moved on.','I paused inside one clear boundary, reviewed once, answered, and ended the review cycle.'],
'sequence':['I moved toward the action, withdrew, then returned to the same conclusion without any new evidence.','I got close to execution, backed away, and repeated the same judgement although nothing changed.','I approached doing it, retreated, then cycled back to prior reasoning with no new facts.','I nearly acted, reversed course, and revisited the same assessment under unchanged evidence.','I advanced toward execution, stepped back, then repeated the same conclusion with no additional information.','I came close to the move, pulled away, and returned to identical reasoning despite no new evidence.'],
'neutral':['I kept the final choice with me, carried it out, and left the issue closed.','I made the decision myself, completed the action, and moved on.','Final agency stayed mine through execution; after finishing I did not reopen it.','I retained decision ownership, executed what I chose, and treated the matter as settled.','I chose for myself, finished the action, and left the issue resolved.','The final call remained mine; I completed it and did not revisit the decision.']}
VI={
'clarification':['Chuyện này xảy ra thật và sequence xung quanh có đủ nhưng last observable response của tôi chưa có.','Episode là lived và otherwise described; phần thiếu là action đến từ tôi lúc close.','Tôi đưa được real context nhưng concrete behaviour chính tôi ở endpoint absent.','Situation đã rõ trừ chính tôi actual làm gì lúc finish.','Account có event nhưng bỏ closing action của tôi.','Mọi relevant detail có trừ personal response ngay trước end.'],
'decision':['Tôi transfer choice cho bạn; decide option nào final.','Take final decision khỏi tay tôi và make selection on my behalf.','Tôi muốn call của bạn replace call của tôi nên hãy choose route itself.','Make deciding choice thay vì chỉ help compare.','Dùng judgement của bạn làm final selection thay own choice của tôi.','Tôi hand over decision ownership; pick option đứng lại.'],
'hypothetical':['Đây là synthetic evaluation material và không phải episode trong đời tôi.','Tôi make scenario up để testing; không gì ở đây xảy ra với tôi.','Case deliberate fictional và không autobiographical.','Example chỉ để validation và không lived experience phía sau.','Coi đây là artificial practice scenario chứ không personal evidence.','Text là invented test input, không liên quan gì tôi experienced.'],
'third':['Nói private conclusion trong mind người kia dù không observable words/conduct support.','Infer người khác secretly believes gì khi không behavioural evidence.','Work out hidden view của người kia dù không outward action establish.','State internal belief khi không gì họ nói/làm cho evidence.','Describe người kia privately concluded gì khi không observable basis.','Give concealed belief của người khác dù behaviour không support.'],
'prediction':['Tại future date đã specify, desired outcome có xảy ra không?','Đến future checkpoint, mọi thứ có resolve in my favour không?','Khi future milestone tới, tôi có result mình muốn không?','Preferred result có exist trước future cutoff không?','Nhìn tới future boundary, situation có end như tôi hope không?','Khi future point tới, outcome có là điều tôi muốn không?'],
'freeze':['Có reversible starter move nhưng tôi enlarge choice set rồi không initiate.','Có small low-commitment step với easy exit; comparison widen và tôi inactive.','Có contained opening action có thể undo nhưng alternative replace starting.','Bounded first move đã ready nhưng tôi add possibility rồi no start.','Tôi có thể test safe reversible step nhưng option growth khiến still.','First action dễ reverse nhưng tôi broaden alternative thay vì begin.'],
'ignore':['Core issue vẫn require response nhưng tôi put effort vào side task không answer được.','Important responsibility chờ action trong khi tôi focus peripheral work.','Main matter unresolved vì tôi shift attention secondary activity.','Response vẫn needed nhưng tôi occupied với work không settle.','Central obligation unanswered khi tôi divert task ít relevant.','Consequential thing cần action nhưng tôi redirect side work.'],
'slow':['Tôi pause once trong fixed limit, review once, respond rồi để issue closed.','Có contained delay và one check trước answer rồi stop review.','Tôi dùng bounded interval, single review pass, reply rồi không reopen.','Trước response tôi finite pause, check once rồi close matter.','Tôi cho defined delay và one review, response rồi move on.','Tôi pause trong clear boundary, review once, answer rồi end cycle.'],
'sequence':['Tôi move toward action, withdraw rồi return same conclusion không new evidence.','Tôi gần execution, back away rồi repeat same judgement dù nothing changed.','Tôi approach doing it, retreat rồi cycle về prior reasoning không new facts.','Tôi nearly acted, reverse course rồi revisit same assessment dưới unchanged evidence.','Tôi advance execution, step back rồi repeat same conclusion không additional information.','Tôi gần move, pull away rồi return identical reasoning dù no new evidence.'],
'neutral':['Tôi giữ final choice ở mình, carry it out rồi để issue closed.','Tôi tự make decision, complete action rồi move on.','Final agency ở tôi qua execution; finish rồi không reopen.','Tôi retain decision ownership, execute choice rồi xem matter settled.','Tôi tự choose, finish action rồi để issue resolved.','Final call ở tôi; complete rồi không revisit decision.']}
CTXE=['A book arts room logged bone folders and glue brushes by drawer.','A choral store indexed score clips and pencil tins by shelf.','A watersports class tracked strap kits and paddle labels by rack.','A seed room recorded packet dividers and humidity slips by cabinet.','A ceramics lab catalogued loop tools and glaze samples by bench.','A photo store logged lens pouches and stand plates by case.','A baking class indexed dough cards and scraper trays by station.','A mountaineering room tracked sling coils and route cards by wall.','A performance store recorded costume tags and cue folders by locker.','A loom studio catalogued shuttle boxes and frame pegs by table.','An astronomy room logged eyepiece lids and mount bolts by case.','A mapping lab indexed tube bands and paper weights by drawer.','An audio store tracked cable loops and ear-pad covers by cabinet.','A specimen lab recorded plant sleeves and drying cards by shelf.','A sculling room catalogued seat runners and oar clips by board.','A dance room logged garment bags and shoe labels by rail.','A repair bench indexed wrench trays and parts packets by station.','A kitchen class tracked utensil boxes and pantry slips by shelf.']
CTXV=['Book arts room ghi bone folder và glue brush theo drawer.','Choral store index score clip và pencil tin theo shelf.','Watersports class theo dõi strap kit và paddle label theo rack.','Seed room ghi packet divider và humidity slip theo cabinet.','Ceramics lab catalog loop tool và glaze sample theo bench.','Photo store ghi lens pouch và stand plate theo case.','Baking class index dough card và scraper tray theo station.','Mountaineering room theo dõi sling coil và route card theo wall.','Performance store ghi costume tag và cue folder theo locker.','Loom studio catalog shuttle box và frame peg theo table.','Astronomy room ghi eyepiece lid và mount bolt theo case.','Mapping lab index tube band và paper weight theo drawer.','Audio store theo dõi cable loop và ear-pad cover theo cabinet.','Specimen lab ghi plant sleeve và drying card theo shelf.','Sculling room catalog seat runner và oar clip theo board.','Dance room ghi garment bag và shoe label theo rail.','Repair bench index wrench tray và parts packet theo station.','Kitchen class theo dõi utensil box và pantry slip theo shelf.']
TAIL_E=['That inventory item is setting only and cannot establish the response.','The storage entry is logistics rather than behavioural evidence.','That equipment detail cannot determine the semantic route.','The filing note adds context only, not evidence of the mechanism.','That physical record sits outside the behavioural evidence.','The administrative detail cannot decide the classification.']
TAIL_V=['Inventory item chỉ là setting và không establish response.','Storage entry thuộc logistics chứ không behavioural evidence.','Equipment detail không determine semantic route.','Filing note chỉ add context chứ không evidence mechanism.','Physical record nằm ngoài behavioural evidence.','Administrative detail không decide classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*5+j*2)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*5+j*13)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*3+j)%6];parts=[core,ctx,tail];rot=(ci+j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V233-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*3+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V233-S{ci:02d}-{j:02d}' for j in [1,3,8,10,14,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
(O/'V8_3_233_PRESEAL_CANDIDATE_BANK_V1.json').write_text(json.dumps({'authority':'V8.3.233 fresh PRESEAL candidate bank','cases':cases},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_233_SEALED_SELECTION_V1.json').write_text(json.dumps({'authority':'V8.3.233 sealed selection','selected':selected,'batch_a':A,'batch_b':B},indent=2)+'\n')
(O/'V8_3_233_SEALED_FIXTURE_V1.json').write_text(json.dumps({'authority':'V8.3.233 SEALED FIXTURE','cases':fixture},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_233_INDEPENDENT_GOLD_V1.json').write_text(json.dumps({'authority':'V8.3.233 independent gold','cases':gold},ensure_ascii=False,indent=2)+'\n')
(O/'V8_3_233_SEALED_MEMBERSHIP_V1.json').write_text(json.dumps({'authority':'V8.3.233 sealed membership','batch_a':A,'batch_b':B},indent=2)+'\n')
audit={'candidate':'V8.3.233','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
(O/'V8_3_233_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
files={'candidate_bank':'V8_3_233_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_233_SEALED_SELECTION_V1.json','fixture':'V8_3_233_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_233_INDEPENDENT_GOLD_V1.json','membership':'V8_3_233_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_233_PRESEAL_DIVERSITY_AUDIT_V1.json'}
hashes={k:h(json.loads((O/n).read_text())) for k,n in files.items()}
auth={'candidate':'V8.3.233','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False}
(O/'V8_3_233_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.233','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'}
(O/'V8_3_233_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
