import json,pathlib
root=pathlib.Path('validation/v83181-v1-sealed');root.mkdir(parents=True,exist_ok=True)
cases=[]
def add(i,surface,domain,language,route,families=None,sequence=False):
    cases.append({'case_id':f'V181-S{i:03d}','surface':surface,'domain':domain,'language':language,'expected':{'route':route,'families':families or [],'sequence':sequence}})
clar=[('The account lists several exchanges, but it never identifies which observable response was mine in the most recent exchange.','work','EN'),('Tôi kể diễn biến khá đầy đủ nhưng chưa tách được hành động cụ thể nào là do chính tôi thực hiện.','romantic','VI'),('Actor của response vẫn lẫn giữa tôi và người kia; cần xác định attribution trước khi đọc pattern.','family','MIXED_VI_EN'),('Cau chuyen co nhieu lan lap lai nhung chua chon mot su kien cu the de thay toi phan ung ra sao.','daily','VI_NO_DIACRITICS'),('The chronology is clear, yet the person who actually made the response is still unresolved.','money','EN'),('Tôi có background và cảm xúc, nhưng phần behaviour quan sát được của riêng tôi vẫn thiếu.','wellbeing','VI'),("The record says 'we' in one place and 'I' elsewhere, so my own action cannot yet be isolated.",'home','EN'),('Chua co mot incident rieng cho thay response cua toi sau update moi nhat.','direction','VI_NO_DIACRITICS'),('There are documents and dates, but no concrete step attributable to me after the latest message.','business','EN'),('Phần mô tả đổi chủ thể liên tục; chưa đủ để biết ai thực sự làm bước tiếp theo.','study','VI')]
for j,x in enumerate(clar,1):add(j,*x,'input:clarification-required')
dec=[('Choose the next action for me; I do not want to make the choice myself.','money','EN'),('Hãy quyết hộ tôi lựa chọn nào phải làm tiếp, không cần đưa trade-off.','work','VI'),('I want action selection from you rather than options I need to judge myself.','study','EN'),('Chon thay toi mot buoc cu the va dung de quyet dinh lai cho toi.','daily','VI_NO_DIACRITICS'),('Replace my judgement with a direct instruction about what I should do next.','business','EN'),('Tôi không muốn cân nhắc nữa; hãy chọn phương án thay tôi.','romantic','VI'),('Give me the command to follow, not a comparison of alternatives.','direction','EN'),('Hay chot giup toi hanh dong co outcome tot nhat, toi khong muon tu chon.','family','VI_NO_DIACRITICS')]
for k,x in enumerate(dec,11):add(k,*x,'input:decision-request')
hyp=[('Use an invented neighbour as the example; this did not happen to me.','home','EN'),('Giả sử một người hoàn toàn hư cấu gặp tình huống này; đây không phải trải nghiệm của tôi.','daily','VI'),('This is a classroom scenario about a fictional employee, not an autobiographical event.','work','EN'),('Tinh huong nay chi de role-play, toi khong phai actor trong do.','study','VI_NO_DIACRITICS'),('Imagine a made-up couple for classification; neither person represents me.','romantic','EN'),('Đây là ví dụ giả định để luyện phân loại, không phải chuyện đã xảy ra với tôi.','direction','VI'),('Classify the imaginary case below rather than anything from my own life.','business','EN'),('Mot nhan vat bia ra dang dung trong case nay; khong co incident that cua toi.','money','VI_NO_DIACRITICS')]
for k,x in enumerate(hyp,19):add(k,*x,'input:hypothetical-or-example')
third=[('What are they secretly thinking about me even though none of it is observable?','romantic','EN'),('Anh ấy đang có cảm xúc kín nào với tôi mà chưa hề bộc lộ?','romantic','VI'),('Tell me her hidden motive toward me right now; I am asking only about her internal state.','work','EN'),('Ho dang nghi gi ve toi o ben trong ma toi khong the quan sat?','family','VI_NO_DIACRITICS'),('What private emotional state is my colleague holding toward me behind the visible behaviour?','business','EN'),('Tôi muốn biết suy nghĩ bí mật của người kia về tôi, không phải phân tích response của tôi.','daily','VI'),('Do they privately regret what happened with me even though there is no outward sign?','home','EN'),('Nguoi do co dang am tham thay doi cach nhin ve toi khong?','direction','VI_NO_DIACRITICS'),('What intention are they secretly holding toward me behind what I can see?','money','EN'),('Cô ấy thật sự cảm thấy gì về tôi ở bên trong mà chưa nói ra?','family','VI')]
for k,x in enumerate(third,27):add(k,*x,'input:third-party-only')
pred=[('Will the final result land in my favour before the deadline?','money','EN'),('Ket qua sap toi co nghieng ve phia toi nhu toi hy vong khong?','business','VI_NO_DIACRITICS'),('Is this situation going to end the way I want over the next few weeks?','direction','EN'),('Có phải kết cục cuối cùng sẽ thuận lợi cho tôi không?','romantic','VI'),('Will the outcome resolve in my favour by the end of the month?','work','EN'),('Chuyen nay cuoi cung co ra dung ket qua toi mong doi khong?','family','VI_NO_DIACRITICS'),('Can you predict whether the eventual result will match what I am hoping for?','study','EN'),('Kết quả tương lai có rơi về phía có lợi cho tôi không?','daily','VI')]
for k,x in enumerate(pred,37):add(k,*x,'input:prediction')
freeze=[('I had enough information for a reversible first move, but kept comparing more options instead of starting.','work','EN'),('Tôi có một bước thử nhỏ có thể quay lại, nhưng vẫn tìm thêm lựa chọn nên chưa bắt đầu.','romantic','VI'),('Co du du kien de thu mot buoc nho an toan, nhung toi cu mo them tai lieu so sanh va chua lam.','family','VI_NO_DIACRITICS'),('A small experiment was safe to undo, yet I preserved more alternatives rather than trying it.','business','EN'),('Tôi biết có thể thử trước rồi đổi lại, nhưng vẫn cân nhắc thêm phương án và đứng yên.','direction','VI'),('The reversible test was ready; I delayed action by researching still more choices.','money','EN')]
for k,x in enumerate(freeze,45):add(k,*x,'input:self-lived',['freeze'])
ign=[('After the update I switched to unrelated admin and left the actual issue for later.','work','EN'),('Tôi chuyển sang làm việc lặt vặt để tránh bắt đầu nhiệm vụ chính.','daily','VI'),('Sau update toi moved sang low-value admin thay vi xu ly van de chinh.','business','MIXED_VI_EN')]
for k,x in enumerate(ign,51):add(k,*x,'input:self-lived',['ignore'])
slow=[('I reopened the same note several times even though no new information had appeared.','business','EN'),('Tôi kiểm tra lại cùng một tài liệu nhiều lần dù dữ liệu không thay đổi.','money','VI'),('Toi mo lai cung mot record ba lan trong ngay du khong co update moi.','home','VI_NO_DIACRITICS')]
for k,x in enumerate(slow,54):add(k,*x,'input:self-lived',['slow'])
neutral=[('I took one concrete step and then stopped; I did not keep opening more alternatives.','direction','EN'),('Tôi đã thử một bước nhỏ rồi kết thúc, không tiếp tục mở thêm lựa chọn.','romantic','VI'),('I completed the next action myself rather than asking someone else to decide it.','family','EN'),('Toi da lam buoc tiep theo cu the va khong ne sang viec khac.','daily','VI_NO_DIACRITICS')]
for k,x in enumerate(neutral,57):add(k,*x,'input:self-lived',[])
batch_a=[c['case_id'] for c in cases if int(c['case_id'].split('S')[1])%2==1];batch_b=[c['case_id'] for c in cases if int(c['case_id'].split('S')[1])%2==0]
fixture={'authority':'V8.3.181 V1 SEALED EXECUTION FIXTURE','cases':cases,'batch_a':batch_a,'batch_b':batch_b}
selection={'authority':'V8.3.181 V1 OWNER SELECTION','batch_a':batch_a,'batch_b':batch_b}
membership={'authority':'V8.3.181 V1 SEALED MEMBERSHIP','all_case_ids':sorted(batch_a+batch_b),'batch_a':batch_a,'batch_b':batch_b}
keys=[]
for c in cases:
    e=c['expected'];key=(e['route'],tuple(e['families']),e['sequence'])
    if key not in keys:keys.append(key)
groups=[]
for i,key in enumerate(keys,1):
    r,f,s=key;groups.append({'group':f'G{i:02d}','case_ids':[c['case_id'] for c in cases if (c['expected']['route'],tuple(c['expected']['families']),c['expected']['sequence'])==key],'expected':{'route':r,'families':list(f),'sequence':s}})
gold={'authority':'V8.3.181 V1 INDEPENDENT GOLD','construction':'manual semantic contract; no V50R3 runtime consulted','groups':groups}
for n,o in [('V8_3_181_SEALED_EXECUTION_FIXTURE_V1.json',fixture),('V8_3_181_SEALED_SELECTION_V1.json',selection),('V8_3_181_SEALED_MEMBERSHIP_V1.json',membership),('V8_3_181_INDEPENDENT_GOLD_V1.json',gold)]: (root/n).write_text(json.dumps(o,ensure_ascii=False,indent=2))
