import json,hashlib,pathlib,subprocess,re,zipfile
R=pathlib.Path('.');O=R/'validation/v83225-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='96955e1cf7538912104700e8dd6307ac4e67cb73';SEM='QCEvidenceExtractorV5AC -> QCSemanticCoreV102'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['This happened in my life; the surrounding sequence is clear, but the concrete thing I personally did just before it ended is missing.','The episode is real and otherwise complete; I have not supplied my own observable closing response.','I know what happened around the event, yet the final behaviour that came from me has not been stated.','The lived context is sufficiently specified except for my personal action at the closing point.','This is a real situation, and the remaining gap is what I myself actually did before closure.','All relevant context is present except my own concrete endpoint behaviour.'],
'decision':['Make the final selection on my behalf so your choice replaces the decision I would otherwise make.','Choose the option for me; I am asking your decision to stand in for my own final call.','Take over the final choice and tell me which route becomes mine.','I want you to decide the option itself rather than support me to decide it.','Give me the final answer by choosing in my place.','Use your judgement as the final selection instead of leaving the choice with me.'],
'hypothetical':['I constructed this solely as evaluation text; it is not an event from my life.','This case is intentionally fictional test material and should not be treated as lived evidence.','Nothing here happened to me; the scenario exists only for validation.','The example is synthetic and invented rather than personal history.','Treat this as a fabricated practice scenario, not something I experienced.','This is deliberately made-up input for testing, with no lived event behind it.'],
'third':['Infer the other person’s private conclusion even though no observable action or statement from them establishes it.','Tell me their concealed belief when nothing they did or said provides evidence for it.','Work out what someone else secretly thinks despite having no outward behaviour that supports the inference.','State the other person’s hidden internal view without any observable basis from them.','I want their private belief even though there is no statement or conduct that demonstrates it.','Tell me what is secretly in their mind when no behavioural evidence is available.'],
'prediction':['At the future point I named, will I have the result I want?','By that specified future cutoff, will the outcome turn out in my favour?','When the stated future milestone arrives, will this end the way I hope?','Will my desired result have happened by the future date I gave?','Looking to that future boundary, will events resolve with my preferred outcome?','When the future marker is reached, will I get the result I want?'],
'freeze':['A small reversible opening move was available, but I kept enlarging the alternatives and never initiated it.','I had a low-commitment step with an easy exit, yet I expanded the option set instead of beginning.','There was a reversible starter action, but I remained inactive while adding more possibilities.','A contained first move could have been tested and undone; I kept widening choices and did not start.','The opening action was low-risk and reversible, yet option expansion kept me from initiating it.','I could have taken a bounded reversible first step, but I kept generating alternatives and stayed inactive.'],
'ignore':['The central responsibility still needed my action, but I redirected effort into side work that could not resolve it.','The main issue was waiting for my response while I occupied myself with peripheral tasks.','Something consequential still required action from me, yet I diverted attention to secondary activity instead.','I left the primary obligation unresolved and busied myself elsewhere with work that did not address it.','The core matter needed my response, but I shifted into less relevant tasks rather than answering it.','My action was still required on the important issue; I avoided it through side activity that could not settle it.'],
'slow':['I paused within one clear boundary, reviewed once, answered, and then closed the matter.','There was one bounded delay and one check before I responded and stopped reviewing.','I used a finite pause, made a single review pass, gave my response, and did not reopen the issue.','Before answering I allowed one limited interval and one review, then treated the process as complete.','I took one contained pause, checked once, responded, and ended the review cycle.','I delayed within a defined limit, reviewed one time, answered, and left it closed.'],
'sequence':['I moved toward execution, pulled back, then returned to the same judgement without new evidence.','I approached the action, withdrew, and repeated my prior conclusion with no new facts.','I got close to acting, stepped away, then cycled back to the identical reasoning without new information.','I advanced toward the practical move, reversed course, and returned to the old assessment although nothing new appeared.','I nearly executed the step, retreated, and came back to the same conclusion under unchanged evidence.','I approached doing it, backed out, then repeated the same judgement while the facts stayed the same.'],
'neutral':['I kept the final decision with me, completed the action, and left the issue closed afterward.','I decided for myself, carried out what I chose, and did not revisit it once complete.','Final agency remained mine through execution; I finished the step and moved on.','I made my own final call, completed the action, and treated the matter as settled.','Ownership of the choice stayed with me until completion, after which I left it closed.','I retained the decision, executed it, and did not reopen the issue.']}
VI={
'clarification':['Chuyện này xảy ra thật với tôi; sequence xung quanh đã rõ nhưng hành động cụ thể do chính tôi làm ngay trước lúc kết thúc vẫn còn thiếu.','Episode là thật và các phần khác đã đủ; tôi chưa cung cấp observable closing response của chính mình.','Tôi biết bối cảnh diễn ra thế nào, nhưng behaviour cuối đến từ tôi chưa được nêu.','Lived context đã đủ ngoại trừ personal action của tôi tại closing point.','Đây là situation thật, khoảng trống còn lại là chính tôi đã thực sự làm gì trước closure.','Mọi context liên quan đều có trừ concrete endpoint behaviour của chính tôi.'],
'decision':['Hãy đưa final selection thay tôi để choice của bạn thay cho decision cuối mà tôi sẽ tự đưa ra.','Chọn option thay tôi; tôi muốn decision của bạn đứng vào chỗ final call của tôi.','Nhận lấy final choice và nói route nào sẽ trở thành lựa chọn của tôi.','Tôi muốn bạn quyết định option luôn chứ không chỉ hỗ trợ tôi tự quyết.','Đưa final answer bằng cách chọn ở vị trí của tôi.','Dùng judgement của bạn làm final selection thay vì để choice ở tôi.'],
'hypothetical':['Tôi dựng đoạn này chỉ để evaluation; nó không phải event trong đời tôi.','Case này là fictional test material có chủ ý và không được xem là lived evidence.','Không điều gì ở đây xảy ra với tôi; scenario chỉ tồn tại để validation.','Ví dụ này synthetic và invented chứ không phải personal history.','Hãy coi đây là fabricated practice scenario, không phải chuyện tôi trải qua.','Đây là input cố ý bịa để test, không có lived event phía sau.'],
'third':['Suy ra private conclusion của người kia dù không observable action hay statement nào từ họ xác lập nó.','Nói concealed belief của họ khi không điều họ làm hay nói cung cấp evidence.','Xác định người khác secretly nghĩ gì dù không có outward behaviour support inference.','Nói hidden internal view của người kia khi không có observable basis từ họ.','Tôi muốn private belief của họ dù không statement hay conduct nào chứng minh nó.','Nói điều bí mật trong đầu họ khi không có behavioural evidence.'],
'prediction':['Tại future point tôi đã nêu, tôi có nhận result mình muốn không?','Đến future cutoff đã xác định, outcome có đi theo hướng có lợi cho tôi không?','Khi future milestone đã nói tới, chuyện này có kết thúc như tôi hy vọng không?','Desired result có xảy ra trước future date tôi đã đưa không?','Nhìn tới future boundary đó, events có resolve bằng preferred outcome của tôi không?','Khi future marker tới, tôi có lấy được result mình muốn không?'],
'freeze':['Có một opening move nhỏ reversible, nhưng tôi cứ mở rộng alternative rồi không initiate.','Tôi có step ít commitment với exit dễ, vậy mà lại nới option set thay vì bắt đầu.','Có starter action reversible, nhưng tôi vẫn inactive trong lúc thêm possibility.','Một first move giới hạn có thể test rồi undo; tôi cứ mở rộng choice và không start.','Opening action ít risk và reversible, nhưng option expansion khiến tôi không initiate.','Tôi có thể làm bounded reversible first step, nhưng vẫn tạo thêm alternative và giữ inactive.'],
'ignore':['Central responsibility vẫn cần action của tôi, nhưng tôi chuyển effort sang side work không thể resolve nó.','Main issue đang chờ response của tôi trong khi tôi bận với peripheral task.','Một chuyện consequential vẫn cần action từ tôi, vậy mà tôi divert attention sang secondary activity.','Tôi để primary obligation unresolved và bận ở chỗ khác với work không xử lý nó.','Core matter cần response của tôi, nhưng tôi chuyển sang task ít relevant hơn thay vì trả lời.','Action của tôi vẫn cần cho important issue; tôi avoid nó bằng side activity không thể settle.'],
'slow':['Tôi pause trong một boundary rõ, review một lần, trả lời rồi đóng matter.','Có một bounded delay và một lần check trước khi tôi response rồi ngừng review.','Tôi dùng finite pause, review một pass, đưa response và không mở lại issue.','Trước khi trả lời tôi cho phép một limited interval và một review rồi xem process hoàn tất.','Tôi lấy một contained pause, check một lần, response rồi kết thúc review cycle.','Tôi delay trong defined limit, review một lần, trả lời và để nó closed.'],
'sequence':['Tôi tiến về execution, pull back rồi quay lại cùng judgement khi không có evidence mới.','Tôi tiếp cận action, withdraw rồi lặp prior conclusion khi không có fact mới.','Tôi gần acting, bước ra rồi cycle về reasoning giống hệt khi không có information mới.','Tôi tiến tới practical move, đổi hướng rồi quay lại old assessment dù không có gì mới.','Tôi gần execute step, retreat rồi quay về cùng conclusion dưới evidence không đổi.','Tôi tiếp cận việc làm nó, back out rồi lặp cùng judgement khi facts giữ nguyên.'],
'neutral':['Tôi giữ final decision ở mình, hoàn thành action rồi để issue closed sau đó.','Tôi tự quyết, thực hiện điều đã chọn và không revisit khi hoàn tất.','Final agency vẫn ở tôi suốt execution; tôi finish step rồi tiếp tục.','Tôi tự đưa final call, hoàn thành action và xem matter settled.','Ownership của choice ở tôi đến completion, sau đó tôi để nó closed.','Tôi giữ decision, execute nó và không mở lại issue.']}
CTXE=['A glass studio logged kiln gloves and mould trays by shelf.','A language lab indexed headset pouches and room cards by cabinet.','A rowing workshop tracked seat tools and oar collars on maintenance boards.','A seed archive recorded packet boxes and humidity tags by drawer.','A puppet theatre indexed control strings and costume bins by rack.','A bicycle co-op logged pump heads and repair aprons by station.','A marine classroom tracked chart sleeves and compass cases by locker.','A ceramics archive indexed glaze cards and kiln props by cabinet.','A community kitchen logged serving crates and pantry clips on dispatch sheets.','A photo lab tracked filter wallets and stand clamps by drawer.','A conservation room indexed tissue rolls and brush wraps by table.','A rehearsal store logged score folders and cable ties by rack.','A garden lab tracked pot markers and irrigation keys by bench.','A map archive indexed weight bars and sleeve folders by drawer.','A repair café logged tool cards and component trays by station.','A ferry office tracked ticket rolls and gate paddles by cabinet.','A telescope club indexed lens caps and tripod plates by case.','A textile studio logged dye bottles and frame clips by table.']
CTXV=['Glass studio ghi kiln glove và mould tray theo shelf.','Language lab lập index headset pouch và room card theo cabinet.','Rowing workshop theo dõi seat tool và oar collar trên maintenance board.','Seed archive ghi packet box và humidity tag theo drawer.','Puppet theatre lập index control string và costume bin theo rack.','Bicycle co-op ghi pump head và repair apron theo station.','Marine classroom theo dõi chart sleeve và compass case theo locker.','Ceramics archive lập index glaze card và kiln prop theo cabinet.','Community kitchen ghi serving crate và pantry clip trên dispatch sheet.','Photo lab theo dõi filter wallet và stand clamp theo drawer.','Conservation room lập index tissue roll và brush wrap theo table.','Rehearsal store ghi score folder và cable tie theo rack.','Garden lab theo dõi pot marker và irrigation key theo bench.','Map archive lập index weight bar và sleeve folder theo drawer.','Repair café ghi tool card và component tray theo station.','Ferry office theo dõi ticket roll và gate paddle theo cabinet.','Telescope club lập index lens cap và tripod plate theo case.','Textile studio ghi dye bottle và frame clip theo table.']
TAIL_E=['That inventory detail is context only and cannot determine the behavioural route.','The storage record belongs to logistics rather than response evidence.','That physical marker cannot create the mechanism being classified.','The filing note adds setting only, not behavioural evidence.','That equipment reference is external to the response mechanism.','The administrative record cannot decide the semantic classification.']
TAIL_V=['Inventory detail đó chỉ là context và không thể quyết behavioural route.','Storage record thuộc logistics chứ không phải response evidence.','Physical marker đó không thể tạo mechanism đang được classify.','Filing note chỉ thêm setting chứ không thêm behavioural evidence.','Equipment reference nằm ngoài response mechanism.','Administrative record không thể quyết semantic classification.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=j%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*5+j*7)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci+j*5)%6];parts=[core,ctx,tail];rot=(ci+2*j)%3;parts=parts[rot:]+parts[:rot]
  surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V225-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
# Select six per category without semantic runtime: indices 0,2,5,9,12,16; A first three, B last three.
sel=[];A=[];B=[]
for ci,c in enumerate(C):
 ids=[f'V225-S{ci:02d}-{j:02d}' for j in [0,2,5,9,12,16]];sel+=ids;A+=ids[:3];B+=ids[3:]
assert len(sel)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
selection={'authority':'V8.3.225 PRESEAL SELECTION','selection_method':'category-balanced deterministic construction-only; no runtime output','selected':sel,'batch_a':A,'batch_b':B}
fixture={'authority':'V8.3.225 SEALED FIXTURE','cases':[x for x in cases if x['case_id'] in set(sel)]}
gold={'authority':'V8.3.225 INDEPENDENT GOLD','construction':'category contract, independent of semantic runtime','cases':[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture['cases']]}
membership={'authority':'V8.3.225 SEALED MEMBERSHIP','cases':[{'case_id':i,'batch':'A' if i in set(A) else 'B'} for i in sel]}
def tok(s):return set(re.findall(r"[a-z0-9]+",s.lower()))
def jac(a,b):
 a,b=tok(a),tok(b);return len(a&b)/len(a|b) if a|b else 1
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  z=jac(x['surface'],y['surface']);
  if z>internal[0]:internal=(z,(x['case_id'],y['case_id']))
# External audit against frozen candidate banks V219-V224.
external_surfaces=[]
for v in [219,220,221,222,223,224]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL)
 data=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True));external_surfaces += [(v,x['case_id'],x['surface']) for x in data['cases']]
external=(0,None);ge75=0;exact=0
oldset={s for _,_,s in external_surfaces}
for x in cases:
 if x['surface'] in oldset:exact+=1
 for v,cid,s in external_surfaces:
  z=jac(x['surface'],s)
  if z>=0.75:ge75+=1
  if z>external[0]:external=(z,(x['case_id'],v,cid))
fps=[(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],re.sub(r'\s+',' ',x['surface'].lower()).strip()) for x in cases]
fpdup=len(fps)-len(set(fps))
audit={'candidate':'V8.3.225','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':ge75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':internal[0]<0.75 and external[0]<0.75 and ge75==0 and exact==0 and fpdup==0}
assert audit['pass'],audit
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o):return hashlib.sha256(canon(o)).hexdigest()
bank={'authority':'V8.3.225 PRESEAL CANDIDATE BANK','cases':cases}
objs={'candidate_bank':bank,'selection':selection,'fixture':fixture,'independent_gold':gold,'membership':membership,'preseal_audit':audit}
files={'candidate_bank':'V8_3_225_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_225_SEALED_SELECTION_V1.json','fixture':'V8_3_225_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_225_INDEPENDENT_GOLD_V1.json','membership':'V8_3_225_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_225_PRESEAL_DIVERSITY_AUDIT_V1.json'}
for k,o in objs.items():(O/files[k]).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
auth={'authority':'V8.3.225 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_authority':SEM,'hash_contract':'canonical-json-sort-keys-compact','hashes':{k:h(o) for k,o in objs.items()},'preseal_pass':True,'v219_sealed_rerun':False,'v220_sealed_rerun':False,'v221_sealed_rerun':False,'v222_sealed_rerun':False,'v223_sealed_rerun':False,'v224_sealed_rerun':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_225_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.225','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,**{k:audit[k] for k in ['candidate_count','selected_count','batch_a_count','batch_b_count','internal_max_similarity','internal_max_pair','external_max_similarity','external_cases_at_or_above_0_75','exact_external_duplicates','semantic_fingerprint_exact_duplicates','semantic_runtime_executed','semantic_authority_loaded','selection_uses_runtime_output','batch_a_executed','batch_b_executed']},'conclusion':'success'};(O/'V8_3_225_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps(receipt))
