from pathlib import Path
import json,zipfile,ast,subprocess
archive=Path('PSC_V8_3_139_FINAL_LOCAL_READINESS_EXTERNAL_BUILD_PENDING_CHECKPOINT (1).zip');assert archive.exists()
with zipfile.ZipFile(archive) as z:z.extractall('.')
base=Path('validation/run-v83196-full-regression-sweep-v2.cjs').read_text();needle="'psc-v83196-v195-v1-hypothetical-preservation-repair.js'];";assert needle in base
tree=ast.parse(Path('validation/v83220-v98-regression-orchestrator.py').read_text());ext=None
for node in ast.walk(tree):
 if isinstance(node,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='ext' for t in node.targets):ext=ast.literal_eval(node.value);break
assert ext
ext += ['qc-evidence-extractor-v5z-v222-compositional-generalization.js','psc-v83222-v221-v99-compositional-generalization.js','qc-evidence-extractor-v5aa-v223-precedence-generalization.js','psc-v83223-v222-v100-precedence-generalization.js','qc-evidence-extractor-v5ab-v224-compositional-recall.js','psc-v83224-v223-v101-compositional-recall.js','qc-evidence-extractor-v5ac-v225-residual-composition.js','psc-v83225-v224-v102-residual-composition.js','qc-evidence-extractor-v5ad-v226-full-input-witness.js','psc-v83226-v225-v103-full-input-witness.js','qc-evidence-extractor-v5ae-v227-residual-witness.js','psc-v83227-v226-v104-residual-witness.js','qc-evidence-extractor-v5af-v228-witness-completion.js','psc-v83228-v227-v105-witness-completion.js','qc-evidence-extractor-v5ag-v230-concept-generalization.js','psc-v83230-v229-v106-concept-generalization.js','qc-evidence-extractor-v5ah-v231-isolated-concepts.js','psc-v83231-v230-v107-isolated-concepts.js','qc-evidence-extractor-v5ai-v232-residual-isolated-generalization.js','psc-v83232-v231-v108-residual-isolated-generalization.js','qc-evidence-extractor-v5aj-v234-residual-generalization.js','psc-v83234-v233-v109-residual-generalization.js','qc-evidence-extractor-v5ak-v235-final-residuals.js','psc-v83235-v234-v110-final-residuals.js']
base=base.replace(needle,"'psc-v83196-v195-v1-hypothetical-preservation-repair.js',"+','.join(repr(x) for x in ext)+'];',1);marker="const files=fs.readdirSync('validation')";prefix=base.split(marker)[0]
runner=Path('validation/run-v83235-v231-residual.cjs');tail=r'''
if(!s.QCSemanticCoreV110)throw Error('V110 missing');const C=JSON.parse(fs.readFileSync('validation/V8_3_235_V231_A_FROZEN_CARRIER.json')).cases;let passed=0;const results=[];for(const c of C){const r=s.QCSemanticCoreV110.analyze(c.surface,c.domain);const actual={route:r.input_route.id,families:[...(r.families||[])].sort(),sequence:!!r.sequence};const expected={route:c.expected.route,families:[...(c.expected.families||[])].sort(),sequence:!!c.expected.sequence};const ok=JSON.stringify(actual)===JSON.stringify(expected);if(ok)passed++;results.push({case_id:c.case_id,category:c.category,language:c.language,source_first_run_pass:c.source_first_run_pass,pass:ok,expected,actual,surface:c.surface});}fs.writeFileSync('validation/V8_3_235_V231_A_V110_DIAGNOSTIC_RESULTS.json',JSON.stringify({total:30,passed,failed:30-passed,results},null,2));console.log(passed+'/30');
''';runner.write_text(prefix+tail);cp=subprocess.run(['node',str(runner)],text=True);assert cp.returncode==0
r=json.loads(Path('validation/V8_3_235_V231_A_V110_DIAGNOSTIC_RESULTS.json').read_text());fails=[x for x in r['results'] if not x['pass']];assert len(fails)==1
Path('validation/V8_3_235_V110_V231_REGRESSION_FAILURE.json').write_text(json.dumps({'candidate':'V8.3.235','semantic_authority':'QCEvidenceExtractorV5AK -> QCSemanticCoreV110','v231_total':30,'v231_passed':29,'v231_failed':1,'failure':fails[0],'sealed_validation_executed':False,'v231_sealed_rerun':False,'v234_sealed_rerun':False},ensure_ascii=False,indent=2)+'\n');print(json.dumps(fails[0],ensure_ascii=False))
