import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83244-v1-sealed';O.mkdir(parents=True,exist_ok=True)
BASE='885608fce9e70a8818d1ebda23c786a81005a2fe';DEV='184cb1253121307b72f66462ec7196625623635c';SEM='QCEvidenceExtractorV5AR -> QCSemanticCoreV117'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The event really happened, but my concrete final response is still missing.','I can give the real context, yet I have not stated what I actually did at the end.','This is a lived episode, but my observable closing behaviour is absent.','The situation is real; the missing evidence is my own final action.','I know the actual circumstances, but I have not supplied my last behavioural move.','Everything is autobiographical except the response I made at closure.'],
'decision':['Choose the final option for me instead of helping me evaluate it.','I want you to make the binding decision in my place.','Take over the final choice so your selection replaces mine.','Do not just advise; decide which route I should finally take.','Make the actual deciding call rather than leaving the choice with me.','I want the final selection to come from you, not from my judgement.'],
'hypothetical':['This is invented test material, not an episode from my life.','The scenario is synthetic evaluation text with no lived event behind it.','I fabricated this example only for classification testing.','Nothing described here is autobiographical; it is practice input.','Treat this as fictional validation content rather than personal evidence.','This case was constructed for testing and did not happen to me.'],
'third':['Tell me what the other person privately believes without observable evidence.','Infer their hidden thought although nothing they did confirms it.','Work out someone else’s internal conclusion with no behavioural support.','State their secret view even though no words or actions establish it.','Describe another person’s private position without outward evidence.','Give me their concealed belief despite having no behaviour to verify it.'],
'prediction':['By the future milestone, will the result I want have happened?','At that later deadline, will this end in the outcome I prefer?','When the future checkpoint arrives, will things resolve in my favour?','Looking ahead to that date, will the hoped-for result already be true?','By the later cutoff, will the situation have finished the way I want?','At the named future point, will my preferred outcome have occurred?'],
'freeze':['A reversible first step was available, but I kept expanding options and did not begin.','I could have made one low-risk start, yet I compared more alternatives instead.','A bounded opening move existed, but I generated extra possibilities and stayed still.','There was an easy-to-reverse first action, yet I widened the choice set rather than acting.','A small safe start was ready, but I kept adding routes and made no move.','I had a contained starter available, yet option growth replaced initiation.'],
'ignore':['The main matter still needed my action, but I diverted effort into secondary tasks.','A central responsibility remained open while I stayed busy with side work.','The important issue required my response, yet I occupied myself with peripheral activity.','My action was still needed on the core problem, but I shifted attention elsewhere.','The primary task remained unanswered while I worked on things that could not resolve it.','Something important needed me to act, but I kept doing less relevant work instead.'],
'slow':['I took one bounded pause, checked once, responded, and then closed the issue.','I delayed within a clear limit, reviewed once, answered, and moved on.','There was one contained interval and one check before I replied and stopped revisiting it.','I paused once inside a defined boundary, made one review, responded, and closed it.','I allowed a finite delay, checked one time, answered, and did not reopen the matter.','Before responding I used one limited pause and one review, then treated it as settled.'],
'sequence':['I moved toward acting, pulled back, then returned to the same conclusion without new facts.','I nearly acted, withdrew, and repeated the old judgement even though nothing changed.','I approached the move, retreated, then cycled back to the same reasoning with no new evidence.','I got close to execution, backed away, and revisited the same assessment under unchanged information.','I advanced toward action, reversed course, then repeated the same conclusion without added facts.','I came near to acting, stepped back, and returned to prior reasoning despite no new information.'],
'neutral':['I kept the final choice, carried it out, and left the matter settled.','I made the decision myself, completed it, and did not reopen it.','The final call remained mine through execution, after which I moved on.','I chose for myself, finished the action, and treated the issue as closed.','I retained deciding authority, acted on it, and left the matter resolved.','The choice stayed with me; I executed it and did not revisit the decision.']}
# VI surfaces keep the same measured mechanism but use distinct lexical framing.
VI={
'clarification':['Chuyện này thật sự đã xảy ra, nhưng tôi vẫn chưa nói hành động cụ thể cuối cùng của mình.','Tôi có thể kể bối cảnh thật, nhưng phần tôi đã làm gì ở cuối vẫn còn thiếu.','Đây là chuyện tôi đã trải qua, nhưng hành vi kết thúc có thể quan sát của tôi chưa được nêu.','Tình huống là thật; phần evidence còn thiếu là hành động cuối của chính tôi.','Tôi biết rõ hoàn cảnh thực tế nhưng chưa cung cấp bước hành vi cuối cùng của mình.','Mọi phần đều là chuyện thật của tôi ngoại trừ response tôi đã làm ở đoạn kết.'],
'decision':['Hãy chọn phương án cuối cùng thay tôi, không chỉ giúp tôi cân nhắc.','Tôi muốn bạn đưa ra quyết định ràng buộc thay cho tôi.','Hãy cầm quyền chọn cuối để lựa chọn của bạn thay thế lựa chọn của tôi.','Đừng chỉ tư vấn; hãy quyết định route cuối cùng tôi phải lấy.','Hãy đưa ra quyết định thực sự thay vì để phần chọn cuối cho tôi.','Tôi muốn lựa chọn cuối đến từ bạn chứ không phải judgement của tôi.'],
'hypothetical':['Đây là material test được bịa ra, không phải chuyện tôi đã sống qua.','Scenario này là text đánh giá synthetic và không có sự kiện thật của tôi phía sau.','Tôi tạo ví dụ này chỉ để test classification.','Không phần nào ở đây là autobiographical; đây là practice input.','Hãy xem đây là validation content hư cấu chứ không phải evidence cá nhân.','Case này được dựng để test và chưa từng xảy ra với tôi.'],
'third':['Hãy nói người kia âm thầm tin gì dù không có evidence quan sát được.','Hãy suy ra hidden thought của họ dù không hành vi nào xác nhận.','Hãy xác định kết luận bên trong của người khác khi không có behavioural support.','Hãy nói secret view của họ dù lời nói hay hành động không establish điều đó.','Hãy mô tả private position của người khác mà không có outward evidence.','Hãy cho tôi concealed belief của họ dù không có behaviour để verify.'],
'prediction':['Đến milestone tương lai, kết quả tôi muốn có xảy ra chưa?','Tại deadline sau này, chuyện này có kết thúc theo outcome tôi thích không?','Khi future checkpoint tới, mọi thứ có resolve có lợi cho tôi không?','Nhìn tới ngày đó, hoped-for result có thành sự thật chưa?','Đến cutoff sau này, tình huống có kết thúc theo cách tôi muốn không?','Tại future point đã nêu, preferred outcome của tôi có xảy ra không?'],
'freeze':['Có một bước đầu reversible nhưng tôi cứ mở rộng option và không bắt đầu.','Tôi có thể làm một bước low-risk, nhưng lại so thêm alternative thay vì làm.','Có opening move giới hạn, nhưng tôi tạo thêm possibility rồi đứng yên.','Có first action dễ đảo ngược, nhưng tôi mở rộng choice set thay vì hành động.','Một bước khởi đầu nhỏ và an toàn đã sẵn, nhưng tôi cứ thêm route và không làm gì.','Tôi có starter có giới hạn, nhưng option growth thay cho initiation.'],
'ignore':['Việc chính vẫn cần tôi hành động, nhưng tôi chuyển effort sang task thứ yếu.','Một trách nhiệm trung tâm vẫn mở trong khi tôi bận với side work.','Chuyện quan trọng cần response của tôi, nhưng tôi lại giữ mình bận bằng hoạt động bên lề.','Core problem vẫn cần hành động của tôi, nhưng tôi chuyển attention sang chỗ khác.','Primary task vẫn chưa được trả lời trong khi tôi làm những việc không thể giải quyết nó.','Có việc quan trọng cần tôi làm, nhưng tôi cứ làm việc ít liên quan hơn.'],
'slow':['Tôi dừng một khoảng có giới hạn, kiểm tra một lần, trả lời rồi đóng chuyện lại.','Tôi delay trong boundary rõ, review một lần, trả lời rồi đi tiếp.','Có một interval hữu hạn và một lần check trước khi tôi reply và không quay lại nữa.','Tôi pause một lần trong giới hạn đã định, review một lần, trả lời rồi đóng lại.','Tôi cho một delay hữu hạn, check một lần, trả lời và không reopen.','Trước khi phản hồi tôi dùng một pause giới hạn và một review, rồi xem chuyện đã settled.'],
'sequence':['Tôi tiến gần tới hành động, lùi lại rồi quay về cùng kết luận dù không có fact mới.','Tôi gần làm, rút lại rồi lặp judgement cũ dù không gì thay đổi.','Tôi tiến tới move, retreat rồi cycle về cùng reasoning khi không có evidence mới.','Tôi gần execute, lùi lại và revisit cùng assessment trong information không đổi.','Tôi tiến về action, đổi chiều rồi lặp cùng conclusion mà không có fact thêm.','Tôi gần hành động, bước lùi và quay lại reasoning trước dù không có information mới.'],
'neutral':['Tôi giữ quyền chọn cuối, thực hiện xong và để chuyện kết thúc.','Tôi tự quyết định, hoàn tất và không reopen.','Final call vẫn là của tôi qua execution rồi tôi đi tiếp.','Tôi tự chọn, làm xong và xem chuyện đã closed.','Tôi giữ deciding authority, hành động theo nó và để chuyện resolved.','Choice vẫn ở phía tôi; tôi execute và không revisit quyết định.']}
CTXE=['A marquetry studio indexed veneer fans, fret saws, glue cauls, burnishers and tracing sheets by drawer.','A beekeeping school logged hive tools, queen cages, frame grips, smoker plugs and wax tags by crate.','A cartography room catalogued ruling pens, contour templates, scale bars, map weights and vellum rolls by cabinet.','A fencing armoury recorded mask cords, foil guards, body wires, scoring clips and lame tags by locker.','A glassblowing bench tracked punties, jacks, paddles, annealing labels and colour rods by rack.','A watchmaking class indexed movement holders, oil cups, pegwood sticks, mainspring tins and dial guards by tray.','A print archive logged type gauges, composing sticks, quoin keys, chase cards and galley slips by shelf.','A canoe workshop catalogued thwart bolts, gunwale clamps, stem bands, seat webbing and rib gauges by bay.','A microscopy lab recorded slide boxes, immersion droppers, stage clips, lens tissue and graticule cards by station.','A book conservation room indexed bone folders, wheat paste jars, blotter packs, mull rolls and spine tapes by cupboard.','A brass workshop logged valve felts, mouthpiece brushes, cork sheets, slide grease and spring hooks by drawer.','A ceramics kiln room catalogued pyrometer sleeves, shelf posts, witness cones, wash tubs and stilt bins by bay.','A botanical press archive recorded specimen straps, blotting boards, linen tabs, mounting corners and label weights by cabinet.','A radio workshop indexed tuning coils, ferrite rods, solder wick, dial cords and terminal strips by bench.','A shoemaking room logged lasting pincers, heel lifts, welt knives, shank boards and eyelet trays by rack.','A theatre wardrobe catalogued hook cards, bias tapes, snap boxes, hem gauges and repair patches by rail.','A geology store recorded core boxes, acid bottles, field slates, sample bags and compass clinometers by locker.','A violin bow room indexed tip plates, winding wire, frog screws, hair gauges and rosin tins by drawer.']
TAIL_E=['That marquetry inventory concerns stored craft materials only and cannot establish the measured response.','Those apiary records describe equipment placement, not behavioural evidence.','The cartography stock list supplies scenery only and cannot determine the route.','That fencing register concerns gear, not the response under classification.','Those glassblowing items are physical context and do not prove behaviour.','The watchmaking inventory cannot establish what I did in the measured situation.','That print-room ledger is logistical background rather than mechanism evidence.','Those canoe components do not determine the response family.','The microscopy list describes lab supplies only, not behaviour.','That conservation stock record is separate from the response being tested.','Those brass-maintenance items add context but no behavioural proof.','The kiln-room inventory cannot classify my response.','That botanical archive concerns specimen handling, not the measured mechanism.','Those radio parts are background objects and cannot decide the route.','The shoemaking ledger is operational context rather than response evidence.','Those wardrobe supplies do not establish the underlying behaviour.','The geology inventory adds setting only and cannot prove the mechanism.','That bow-making stock list concerns tools and materials, not my response.']
CTXV=['Một studio marquetry ghi veneer fan, fret saw, glue caul, burnisher và tracing sheet theo ngăn.','Một lớp nuôi ong ghi hive tool, queen cage, frame grip, smoker plug và wax tag theo thùng.','Một phòng cartography ghi ruling pen, contour template, scale bar, map weight và vellum roll theo tủ.','Một kho fencing ghi mask cord, foil guard, body wire, scoring clip và lame tag theo locker.','Một bàn glassblowing ghi punty, jack, paddle, annealing label và colour rod theo rack.','Một lớp watchmaking ghi movement holder, oil cup, pegwood stick, mainspring tin và dial guard theo khay.','Một kho print ghi type gauge, composing stick, quoin key, chase card và galley slip theo kệ.','Một xưởng canoe ghi thwart bolt, gunwale clamp, stem band, seat webbing và rib gauge theo bay.','Một lab microscopy ghi slide box, immersion dropper, stage clip, lens tissue và graticule card theo trạm.','Một phòng bảo tồn sách ghi bone folder, wheat paste jar, blotter pack, mull roll và spine tape theo tủ.','Một xưởng brass ghi valve felt, mouthpiece brush, cork sheet, slide grease và spring hook theo ngăn.','Một phòng kiln ceramics ghi pyrometer sleeve, shelf post, witness cone, wash tub và stilt bin theo bay.','Một kho botanical press ghi specimen strap, blotting board, linen tab, mounting corner và label weight theo tủ.','Một xưởng radio ghi tuning coil, ferrite rod, solder wick, dial cord và terminal strip theo bàn.','Một phòng shoemaking ghi lasting pincer, heel lift, welt knife, shank board và eyelet tray theo rack.','Một kho wardrobe theatre ghi hook card, bias tape, snap box, hem gauge và repair patch theo rail.','Một kho geology ghi core box, acid bottle, field slate, sample bag và compass clinometer theo locker.','Một phòng violin bow ghi tip plate, winding wire, frog screw, hair gauge và rosin tin theo ngăn.']
TAIL_V=['Danh mục marquetry chỉ nói về vật liệu craft lưu trữ và không establish response đang đo.','Bản ghi apiary mô tả vị trí thiết bị, không phải behavioural evidence.','Stock list cartography chỉ thêm scenery và không quyết định route.','Register fencing nói về gear, không phải response đang classify.','Các vật phẩm glassblowing là physical context và không prove behaviour.','Inventory watchmaking không establish điều tôi đã làm trong tình huống đo.','Ledger print-room là logistical background chứ không phải mechanism evidence.','Các component canoe không quyết định response family.','Danh sách microscopy chỉ mô tả lab supply, không phải behaviour.','Stock record conservation tách biệt khỏi response đang test.','Các item brass-maintenance thêm context nhưng không có behavioural proof.','Inventory kiln-room không thể classify response của tôi.','Archive botanical nói về specimen handling, không phải measured mechanism.','Các part radio là background object và không quyết định route.','Ledger shoemaking là operational context chứ không phải response evidence.','Các supply wardrobe không establish underlying behaviour.','Inventory geology chỉ thêm setting và không prove mechanism.','Stock list bow-making nói về tool/material, không phải response của tôi.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';core=(EN if lang=='EN' else VI)[c][(ci*3+j*5)%6];ctx=(CTXE if lang=='EN' else CTXV)[j];tail=(TAIL_E if lang=='EN' else TAIL_V)[j];parts=[core,ctx,tail];rot=(ci*2+j)%3;parts=parts[rot:]+parts[:rot];route,fam,seq=E[c];cases.append({'case_id':f'V244-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci+j*2)%6],'surface':' '.join(parts),'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V244-S{ci:02d}-{j:02d}' for j in [1,4,7,10,13,16]];selected+=ids;A+=ids[:3];B+=ids[3:]
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A=toks(a);B=toks(b);return len(A&B)/max(1,len(A|B))
internal=(0,None)
for i,x in enumerate(cases):
 for y in cases[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in range(219,244):
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior += obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in cases if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
for name,obj in [('PRESEAL_CANDIDATE_BANK_V1',{'authority':'V8.3.244 PRESEAL CANDIDATE BANK V1','cases':cases}),('SEALED_SELECTION_V1',{'candidate':'V8.3.244','selected':selected,'batch_a':A,'batch_b':B}),('SEALED_FIXTURE_V1',{'candidate':'V8.3.244','cases':fixture}),('INDEPENDENT_GOLD_V1',{'candidate':'V8.3.244','cases':gold}),('SEALED_MEMBERSHIP_V1',{'candidate':'V8.3.244','batch_a':A,'batch_b':B})]:(O/f'V8_3_244_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.244','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_244_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_244_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_244_SEALED_SELECTION_V1.json','fixture':'V8_3_244_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_244_INDEPENDENT_GOLD_V1.json','membership':'V8_3_244_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_244_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.244','phase':'SEALED_AUTHORITY_PRE_BATCH_A','recovery_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'semantic_change':False,'runner_materialized':True,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_244_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.244','phase':'preseal-freeze-v1','recovery_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_244_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
