import json,hashlib,pathlib,subprocess,zipfile,re,os,shutil
R=pathlib.Path('.');O=R/'validation/v83219-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='27a338cb88b054a05f61daa6c902ed8537574eba';SEM='456a88d01b671f0cb92a0be31f4d34d68f60d135';SEED=8321941
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['The surrounding facts are complete, but the observable action that came from me just before closure is still unspecified.','I can describe the full setting, yet the concrete thing I myself did at the endpoint is missing from the record.','The event is otherwise clear; what remains absent is my own visible response before it finished.','All external details are known, but my final self-owned action has not been stated.','The sequence can be reconstructed except for the behaviour I personally carried out at the end.','Nothing material is missing except the specific action I took before the matter closed.'],
'decision':['Choose the option for me and let your judgement replace my own final decision.','I want you to take over the deciding role and tell me which route to follow.','Make the selection on my behalf rather than helping me reach a choice myself.','Give me the final answer about which option I should take, not merely a framework for deciding.','I am handing you the choice itself; decide which path becomes my final selection.','Do the deciding for me so that your choice substitutes for my own call.'],
'hypothetical':['This paragraph is deliberately invented test material and does not describe a lived event of mine.','The scenario is synthetic validation prose; I did not personally experience it.','Treat this as a fabricated example only, unrelated to anything that actually happened to me.','This is constructed evaluation text rather than personal history.','Nothing here comes from my real life; the situation exists only for testing.','The case is intentionally fictional and should not be read as evidence from lived experience.'],
'third':['Tell me what another person secretly believes even though no outward behaviour gives evidence for that belief.','Infer the private conclusion in someone else’s mind without any observable words or actions establishing it.','I want the hidden internal view of another person despite having no behavioural basis for it.','Work out what the other person privately thinks when nothing visible supports that inference.','State the unspoken belief of someone else even though their conduct gives no evidence of it.','Tell me their concealed mental conclusion without an observable basis.'],
'prediction':['At the future cutoff I named, will this end with the result I want?','When the specified future milestone arrives, will the outcome go in my preferred direction?','By the stated future point, is this going to resolve the way I hope?','At that future deadline, will events produce my desired result?','Looking ahead to the named future boundary, will the matter close in my favour?','When that future marker is reached, will I get the outcome I am asking about?'],
'freeze':['A reversible first move was available, but I kept expanding alternatives and never started it.','I had a low-stakes step I could undo, yet I continued comparing more options instead of beginning.','There was an easy-to-reverse opening action, but I added possibilities and left it untouched.','A small starter move with a clear exit existed, while I kept widening the choice set and did not act.','I could have begun with a bounded reversible step, but I stayed in option expansion and never launched it.','The first action was low-risk and reversible; I nevertheless kept generating alternatives rather than taking it.'],
'ignore':['The central responsibility still needed my action, but I diverted effort into secondary work and left it open.','The consequential issue was waiting for my response while I occupied myself with peripheral tasks.','I shifted attention to side activity even though the main obligation still required action from me.','The core matter remained unresolved because I worked on less important tasks instead of responding to it.','My answer was still required on the primary issue, yet I spent time elsewhere on work that could not settle it.','I redirected effort away from the main responsibility and into secondary activity while the main issue stayed open.'],
'slow':['I used one bounded pause, reviewed the point once, then answered and treated the matter as finished.','There was one limited interval before my response; I made a single review pass and then closed the process.','I delayed for one defined period, checked once, responded, and did not reopen the issue.','Before acting I took one finite pause, reviewed a single time, then completed the response.','I allowed one contained delay and one check before treating the matter as complete.','I paused within a set limit, reviewed once, then finished without extending the review cycle.'],
'sequence':['I moved close to action, backed away, then returned to the same judgement even though no new facts appeared.','I approached execution, retreated, and repeated the same reasoning with unchanged evidence.','I nearly acted, pulled back, then cycled to the identical conclusion without receiving new information.','I advanced toward the practical step, withdrew, and came back to the same assessment while the facts stayed the same.','I got near execution, reversed course, then repeated the old judgement despite no new evidence.','I approached the move, stepped away, and returned to the same conclusion with nothing new added.'],
'neutral':['I kept final agency, completed the practical action, and left the issue closed afterward.','The choice remained mine; I carried out the step and did not reopen the matter.','I made my own final decision, executed it, and moved on once the issue was settled.','Agency stayed with me through completion, and I did not return to the issue afterward.','I chose for myself, finished the concrete action, and treated the matter as closed.','I retained ownership of the decision, completed the move, and did not revisit it.']}
VI={
'clarification':['Bối cảnh xung quanh đã đủ, nhưng hành động quan sát được do chính tôi làm ngay trước lúc khép lại vẫn chưa được nêu.','Tôi có thể kể đầy đủ tình huống, nhưng bước cụ thể tôi tự làm ở điểm kết thúc còn thiếu khỏi record.','Sự việc về cơ bản đã rõ; phần còn thiếu là response nhìn thấy được của chính tôi trước khi nó kết thúc.','Mọi chi tiết bên ngoài đã có, nhưng hành động cuối do tôi tự chịu trách nhiệm vẫn chưa được nói ra.','Có thể dựng lại sequence ngoại trừ hành vi tôi trực tiếp thực hiện ở đoạn cuối.','Không thiếu gì đáng kể ngoài việc tôi cụ thể đã làm gì trước khi chuyện đóng lại.'],
'decision':['Hãy chọn phương án thay tôi và để phán đoán của bạn thay cho quyết định cuối của tôi.','Tôi muốn bạn nhận luôn vai trò quyết định và nói tôi phải đi theo hướng nào.','Hãy chọn thay tôi chứ không chỉ giúp tôi tự đi tới lựa chọn.','Cho tôi câu trả lời cuối về phương án phải chọn, không chỉ một framework để tự quyết.','Tôi giao luôn lựa chọn cho bạn; hãy quyết định path nào trở thành lựa chọn cuối của tôi.','Hãy quyết định thay để lựa chọn của bạn thế chỗ cho quyền chốt của tôi.'],
'hypothetical':['Đoạn này được cố ý bịa làm dữ liệu test và không mô tả trải nghiệm thật của tôi.','Scenario này là prose validation tổng hợp; tôi chưa từng trực tiếp trải qua nó.','Hãy xem đây chỉ là ví dụ hư cấu, không liên quan tới chuyện thật sự xảy ra với tôi.','Đây là text đánh giá được dựng lên chứ không phải lịch sử cá nhân.','Không phần nào ở đây đến từ đời sống thật của tôi; tình huống chỉ tồn tại để test.','Case này hoàn toàn fictional và không nên được dùng như evidence từ trải nghiệm sống.'],
'third':['Hãy nói người khác âm thầm tin gì dù không có hành vi bên ngoài nào làm evidence cho niềm tin đó.','Hãy suy ra kết luận riêng trong đầu người kia khi không có lời nói hay hành động quan sát được nào xác lập nó.','Tôi muốn biết góc nhìn nội tâm bị giấu của người khác mặc dù không có căn cứ hành vi.','Hãy đoán người kia đang nghĩ kín điều gì khi không có biểu hiện nhìn thấy nào support suy luận đó.','Nói niềm tin chưa được nói ra của người khác dù conduct của họ không cung cấp evidence.','Hãy nói kết luận tinh thần bị che của họ khi không có observable basis.'],
'prediction':['Đến cutoff tương lai tôi đã nêu, chuyện này có kết thúc bằng kết quả tôi muốn không?','Khi milestone tương lai đã xác định tới, outcome có đi theo hướng tôi mong không?','Tới điểm tương lai đã nói, việc này có giải quyết theo cách tôi hy vọng không?','Đến deadline tương lai đó, mọi thứ có tạo ra kết quả tôi muốn không?','Nhìn tới ranh giới tương lai đã nêu, chuyện này có khép lại có lợi cho tôi không?','Khi marker tương lai đó tới, tôi có nhận được outcome mình đang hỏi không?'],
'freeze':['Có một bước đầu dễ đảo ngược, nhưng tôi cứ mở thêm phương án và không bắt đầu.','Tôi có một bước ít rủi ro có thể quay lại, vậy mà vẫn tiếp tục so thêm lựa chọn thay vì làm.','Một opening action dễ hoàn tác đã sẵn, nhưng tôi thêm option và để nguyên chưa đụng tới.','Có một nước đi nhỏ với đường lui rõ, trong khi tôi cứ mở rộng tập lựa chọn và không hành động.','Tôi có thể bắt đầu bằng một bước giới hạn và đảo ngược được, nhưng vẫn ở trong option expansion và chưa khởi động.','Hành động đầu ít rủi ro và reversible; tôi vẫn tạo thêm lựa chọn thay vì thực hiện nó.'],
'ignore':['Trách nhiệm trung tâm vẫn cần hành động của tôi, nhưng tôi chuyển công sức sang việc thứ yếu và để nó còn mở.','Vấn đề có hệ quả vẫn chờ response của tôi trong khi tôi bận với task bên lề.','Tôi dời chú ý sang hoạt động phụ dù nghĩa vụ chính vẫn cần tôi hành động.','Việc cốt lõi chưa được giải quyết vì tôi làm task ít quan trọng hơn thay vì phản hồi nó.','Câu trả lời của tôi vẫn cần cho vấn đề chính, nhưng tôi dành thời gian vào việc khác không thể xử lý nó.','Tôi chuyển effort khỏi trách nhiệm chính sang hoạt động thứ yếu trong khi vấn đề chính vẫn chưa đóng.'],
'slow':['Tôi dùng một khoảng dừng có giới hạn, review đúng một lần, rồi phản hồi và xem chuyện đã xong.','Có một interval hữu hạn trước response; tôi xem lại một pass rồi đóng quá trình.','Tôi trì hoãn trong đúng một khoảng đã xác định, kiểm một lần, phản hồi rồi không mở lại.','Trước khi làm tôi dừng trong một khoảng finite, review một lượt rồi hoàn tất response.','Tôi cho phép một độ trễ được chứa trong biên và một lần kiểm trước khi xem việc đã hoàn tất.','Tôi pause trong giới hạn đã đặt, xem lại một lần rồi kết thúc mà không kéo dài review cycle.'],
'sequence':['Tôi tiến sát tới hành động, lùi lại rồi quay về cùng phán đoán dù không có fact mới.','Tôi tiếp cận execution, retreat rồi lặp lại cùng reasoning trong khi evidence không đổi.','Tôi gần hành động, rút ra rồi quay vòng về đúng kết luận cũ mà không có thông tin mới.','Tôi tiến về bước thực tế, rút lại và trở về cùng assessment trong khi fact vẫn y nguyên.','Tôi tới gần execution, đổi hướng rồi lặp lại phán đoán cũ dù không có evidence mới.','Tôi tiếp cận nước đi, bước ra rồi quay lại cùng conclusion khi không có gì mới được thêm.'],
'neutral':['Tôi giữ quyền quyết định cuối, hoàn tất hành động thực tế rồi để vấn đề đóng sau đó.','Lựa chọn vẫn là của tôi; tôi thực hiện xong bước đi và không mở lại chuyện.','Tôi tự đưa ra quyết định cuối, execute nó rồi tiếp tục khi vấn đề đã settled.','Agency vẫn thuộc về tôi tới lúc hoàn tất và tôi không quay lại vấn đề sau đó.','Tôi tự chọn, làm xong hành động cụ thể rồi xem chuyện đã đóng.','Tôi giữ ownership của quyết định, hoàn thành nước đi và không revisit nó.']}
CTXE=['A climbing gym logged harness inspection tags beside route-setting sheets.','A cinema booth recorded projector filter changes on a maintenance card.','A ceramics studio listed kiln shelf positions and glaze batch numbers.','A rowing club stored oar rack labels beside launch rosters.','A pharmacy stockroom logged tote seals and shelf-count windows.','A language school kept headset cabinet keys on a lesson-room register.','A farmers market coordinator tagged stall crates with collection slots.','A repair cafe recorded tool tray numbers beside volunteer shifts.','A dance rehearsal room tracked speaker cases and floor tape rolls.','A wildlife centre indexed transport boxes by enclosure code.','A coffee roastery marked sample jars with roast-cycle references.','A community radio desk logged cable bags and studio handover times.','A bookbinding workshop tracked press boards and thread drawers.','A swimming pool plant room listed gauge checks and chemical locker seals.','A photo lab recorded negative sleeves and enlarger station numbers.','A theatre box office archived ticket rolls by counter drawer.','A bicycle courier hub labelled battery lockers and dispatch racks.','A catering kitchen logged insulated boxes and collection trays.']
CTXV=['Phòng climbing gym ghi tag inspection harness cạnh sheet route-setting.','Booth rạp phim ghi lần thay projector filter trên maintenance card.','Studio ceramics liệt kê vị trí kiln shelf và số glaze batch.','CLB rowing lưu label oar rack cạnh roster launch.','Kho pharmacy ghi seal tote và cửa sổ shelf-count.','Trường ngôn ngữ giữ chìa khóa headset cabinet trên register phòng học.','Điều phối farmers market gắn crate stall với slot collection.','Repair cafe ghi số tool tray cạnh ca volunteer.','Phòng dance rehearsal theo dõi speaker case và cuộn floor tape.','Wildlife centre lập index transport box theo enclosure code.','Coffee roastery đánh dấu sample jar bằng reference roast-cycle.','Bàn community radio ghi cable bag và giờ handover studio.','Xưởng bookbinding theo dõi press board và ngăn thread.','Plant room hồ bơi liệt kê gauge check và seal chemical locker.','Photo lab ghi sleeve negative và số enlarger station.','Box office nhà hát archive ticket roll theo counter drawer.','Hub courier xe đạp gắn label battery locker và dispatch rack.','Bếp catering ghi insulated box và collection tray.']
EXE=['A violet clip marked the current batch.','A cork tag showed the return hook.','A striped band grouped the duplicate forms.','A steel washer identified the rack row.','A pale card carried the handover code.','A numbered loop marked the storage cage.','A folded stub held the receipt copy.','A narrow flag marked the active ledger page.','A white tie linked the checklist to its crate.','A green dot sticker marked the inspection lane.','A brass token identified the locker bank.','A grey sleeve contained the counterfoil.','A blue tab separated archived entries.','A kraft strip showed the dispatch sequence.','A clear pocket held the signed docket.','A red pencil tick marked the return column.','A small stamp indicated the intake station.','A black clip separated closed forms.']
EXV=['Clip tím đánh dấu batch hiện tại.','Tag cork chỉ return hook.','Dải sọc gom các form bản sao.','Washer thép nhận diện hàng rack.','Card nhạt mang handover code.','Loop đánh số chỉ storage cage.','Stub gập giữ receipt copy.','Flag hẹp đánh dấu trang ledger đang dùng.','Dây trắng nối checklist với crate tương ứng.','Sticker chấm xanh đánh dấu inspection lane.','Token đồng nhận diện bank locker.','Sleeve xám chứa counterfoil.','Tab xanh tách entry đã archive.','Dải kraft hiển thị dispatch sequence.','Pocket trong giữ docket đã ký.','Dấu bút chì đỏ đánh return column.','Con dấu nhỏ chỉ intake station.','Clip đen tách form đã đóng.']
TAIL_E=['That object only identifies record handling and cannot establish my response.','This logistics detail supplies location context, not behavioural evidence.','The inventory marker is external to the mechanism being classified.','That procedural trace does not answer the response question.','The storage reference fixes chronology but not the behavioural route.','This administrative item cannot create a response signal by itself.','The physical marker belongs to documentation rather than the measured behaviour.','That routine record detail does not determine the mechanism.','The operational reference adds context only and cannot establish the classification.','This filing trace is separate from the behaviour under evaluation.']
TAIL_V=['Vật đó chỉ nhận diện cách xử lý record và không thể xác lập response của tôi.','Chi tiết logistics này cung cấp context vị trí chứ không phải behavioral evidence.','Marker inventory nằm ngoài mechanism đang được phân loại.','Dấu vết thủ tục đó không trả lời câu hỏi response.','Reference storage cố định chronology chứ không quyết behavioural route.','Mục hành chính này không thể tự tạo response signal.','Marker vật lý thuộc documentation chứ không phải hành vi đang được đo.','Chi tiết record thường lệ đó không quyết định mechanism.','Reference vận hành chỉ thêm context và không thể xác lập classification.','Dấu vết filing này tách khỏi hành vi đang được đánh giá.']
def surf(cat,i):
 l='EN' if i<9 else 'VI';j=i%9;ci=C.index(cat);core=(EN if l=='EN' else VI)[cat][(j+ci)%6];ctx=(CTXE if l=='EN' else CTXV)[(3*j+ci)%18];ex=(EXE if l=='EN' else EXV)[(5*j+2*ci)%18];tail=(TAIL_E if l=='EN' else TAIL_V)[(j+2*ci)%10];orders=[[core,ctx,ex,tail],[ctx,tail,core,ex],[ex,core,tail,ctx]][(j+ci)%3];return l,' '.join(orders)
cs=[]
for ci,cat in enumerate(C):
 for i in range(18):
  l,s=surf(cat,i);route,fam,seq=E[cat];cs.append({'case_id':f'V219-S{ci:02d}-{i:02d}','category':cat,'language':l,'domain':D[(i+2*ci)%6],'surface':s,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
bank={'authority':'V8.3.219 V1 PRESEAL CANDIDATE BANK','seed':SEED,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'cases':cs}
sel=[]
for cat in C:
 g=[x for x in cs if x['category']==cat];sel += [g[k] for k in [1,4,7,10,13,16]]
a=[];b=[]
for cat in C:
 ids=[x['case_id'] for x in sel if x['category']==cat];a+=ids[::2];b+=ids[1::2]
selection={'authority':'V8.3.219 V1 SEALED SELECTION','seed':SEED,'selected':[x['case_id'] for x in sel],'batch_a':a,'batch_b':b}
fixture={'authority':'V8.3.219 V1 SEALED FIXTURE','cases':[{k:x[k] for k in ['case_id','category','language','domain','surface']} for x in sel]}
gold={'authority':'V8.3.219 V1 INDEPENDENT GOLD','cases':[{'case_id':x['case_id'],'expected':x['expected']} for x in sel]}
membership={'authority':'V8.3.219 V1 SEALED MEMBERSHIP','cases':[{'case_id':x['case_id'],'category':x['category'],'language':x['language'],'domain':x['domain'],'batch':'A' if x['case_id'] in a else 'B'} for x in sel]}
def tok(s):return set(re.findall(r'[a-z0-9]+',s.lower()))
def sim(x,y):
 A=tok(x);B=tok(y);return len(A&B)/len(A|B) if A|B else 1
def fp(s):return ' '.join(sorted(tok(s)))
ext=[]
for v in range(201,219):
 br=f'v83{v}-v1-sealed-validation';subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 for n in [f'validation/v83{v}-v1-sealed/V8_3_{v}_SEALED_FIXTURE_V1.json',f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json']:
  p=subprocess.run(['git','show',f'origin/{br}:{n}'],capture_output=True,text=True)
  if p.returncode==0:
   try: ext += [z['surface'] for z in json.loads(p.stdout).get('cases',[]) if z.get('surface')]
   except Exception: pass
im=0;pair=None
for i,x in enumerate(cs):
 for y in cs[i+1:]:
  z=sim(x['surface'],y['surface'])
  if z>im:im=z;pair=[x['case_id'],y['case_id']]
es=set(ext);ef={fp(x) for x in ext};em=0;ge=0;exdup=0;fd=0
for x in cs:
 exdup += x['surface'] in es;fd += fp(x['surface']) in ef
 for y in ext:
  z=sim(x['surface'],y);em=max(em,z);ge+=z>=.75
audit={'authority':'V8.3.219 V1 PRESEAL DIVERSITY AUDIT','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(im,6),'internal_max_pair':pair,'external_reference_surface_count':len(ext),'external_max_similarity':round(em,6),'external_cases_at_or_above_0_75':ge,'exact_external_duplicates':exdup,'semantic_fingerprint_exact_duplicates':fd,'runtime_executed_during_bank_or_selection':False,'semantic_authority_loaded_during_bank_or_selection':False,'selection_uses_runtime_output':False};audit['pass']=im<.75 and ge==0 and exdup==0 and fd==0
def can(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def hh(o):return hashlib.sha256(can(o)).hexdigest()
objs={'candidate_bank':bank,'selection':selection,'fixture':fixture,'independent_gold':gold,'membership':membership,'preseal_audit':audit};names={'candidate_bank':'V8_3_219_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_219_SEALED_SELECTION_V1.json','fixture':'V8_3_219_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_219_INDEPENDENT_GOLD_V1.json','membership':'V8_3_219_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_219_PRESEAL_DIVERSITY_AUDIT_V1.json'}
for k,v in objs.items():(O/names[k]).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
auth={'authority':'V8.3.219 V1 SEALED AUTHORITY','validated_development_head_sha':DEV,'semantic_base_sha':SEM,'semantic_authority':'QCEvidenceExtractorV5X -> QCSemanticCoreV97','hash_contract':'canonical-json-sort-keys-compact','hashes':{k:hh(v) for k,v in objs.items()},'preseal_pass':audit['pass'],'semantic_change_from_v218':False,'v217_sealed_rerun':False,'v218_sealed_rerun':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_219_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
rec={'candidate':'V8.3.219','phase':'preseal-freeze-v1','run_id':int(os.environ.get('GITHUB_RUN_ID','0')),'validated_development_head_sha':DEV,'semantic_base_sha':SEM,'semantic_authority':'QCEvidenceExtractorV5X -> QCSemanticCoreV97','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':audit['internal_max_similarity'],'internal_max_pair':pair,'external_max_similarity':audit['external_max_similarity'],'external_cases_at_or_above_0_75':ge,'exact_external_duplicates':exdup,'semantic_fingerprint_exact_duplicates':fd,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success' if audit['pass'] else 'failure'};(O/'V8_3_219_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(rec,indent=2)+'\n')
st=R/'V8_3_219_PRESEAL_CHECKPOINT';shutil.rmtree(st,ignore_errors=True);st.mkdir()
for p in O.glob('V8_3_219_*.json'):shutil.copy2(p,st/p.name)
(st/'SHA256_MANIFEST.txt').write_text(''.join(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}\n' for p in sorted(st.iterdir()) if p.is_file()))
z=R/'PSC_V8_3_219_V1_PRESEAL_CHECKPOINT.zip'
if z.exists():z.unlink()
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED) as q:
 for p in sorted(st.iterdir()):q.write(p,p.name)
(R/'PSC_V8_3_219_V1_PRESEAL_CHECKPOINT_SHA256.txt').write_text(f'{hashlib.sha256(z.read_bytes()).hexdigest()}  {z.name}\n')
print(json.dumps(rec,indent=2));raise SystemExit(0 if audit['pass'] else 1)
