import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83229-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='c0a28b22f49a0186dfea8babfe477a78f4bf7cf7';SEM='QCEvidenceExtractorV5AF -> QCSemanticCoreV105'
C=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral'];D=['money','relationship','career','family','workplace','other']
E={'clarification':('input:clarification-required',[],0),'decision':('input:decision-request',[],0),'hypothetical':('input:hypothetical-or-example',[],0),'third':('input:third-party-only',[],0),'prediction':('input:prediction',[],0),'freeze':('input:self-lived',['freeze'],0),'ignore':('input:self-lived',['ignore'],0),'slow':('input:self-lived',['slow'],0),'sequence':('input:self-lived',['slow'],1),'neutral':('input:self-lived',[],0)}
EN={
'clarification':['It was a real event and I can describe what led up to the ending, but the specific action I took at that ending is not in the account.','This happened to me; the circumstances are concrete, yet my own observable final response has not been provided.','The lived episode is clear apart from one missing fact: what I personally did immediately before it concluded.','I have given the real situation and its sequence, but not the behaviour that came from me at the closing point.','The event is not hypothetical and its context is known; only my actual endpoint action remains absent.','Everything around the lived situation is described except the last concrete thing I myself did.'],
'decision':['Make the choice itself for me and let that selection become my final option.','I am asking you to decide the outcome of the choice, not to coach me through making it.','Choose which route I should take so your call substitutes for mine.','Take over the final selection instead of leaving decision ownership with me.','Use your judgement to pick the option that becomes my decision.','I want the final call made by you on my behalf rather than by me.'],
'hypothetical':['I wrote this as made-up assessment material; it is unrelated to any event I lived through.','This scenario exists only as artificial test input and is not autobiographical.','The example was invented for validation and does not report something that happened to me.','Nothing here is a personal event; this is a constructed practice case.','The scenario is fictional evaluation text rather than evidence from my life.','I deliberately created this example for testing, with no real experience behind it.'],
'third':['Describe what the other person privately believes even though they have shown no observable behaviour or statement supporting it.','Tell me someone else’s concealed conclusion when there is no outward evidence from that person.','Infer the hidden view inside the other person despite no words or conduct that establish it.','Work out their private thought without any observable action from them that would justify the inference.','State what someone else secretly thinks even though their behaviour gives no basis for it.','Give me the other person’s internal conclusion when nothing they said or did supports that conclusion.'],
'prediction':['When the future point I specified arrives, will the result I want be there?','By the future deadline I named, will the situation have ended in my preferred way?','At that stated future milestone, will I have obtained the outcome I am hoping for?','Will the desired result exist by the future date I gave?','Looking to the future checkpoint I named, will things resolve the way I want?','Once that future boundary is reached, will the outcome be in my favour?'],
'freeze':['I had a small step I could easily reverse, but I kept broadening the alternatives until I never began.','A low-cost trial move was available with a clear way back; I added more choices instead of starting it.','There was a reversible opening action, yet comparison kept widening and I stayed inactive.','I could have tested one contained first move and undone it, but option growth replaced initiation.','The first action carried little commitment and was reversible; I kept generating possibilities and did not start.','A bounded starter step had an easy exit, but I expanded the choice set until no move was made.'],
'ignore':['The issue that mattered still required something from me, but I put my effort into side activity that could not answer it.','A central responsibility was waiting for my response while I spent time on peripheral work.','The important matter remained unresolved because I redirected attention to secondary tasks.','My response was still needed on the main issue, yet I kept myself occupied with work that did not address it.','The core obligation required action from me, but I diverted into less relevant tasks instead.','Something consequential remained unanswered while I used side work to avoid dealing with it.'],
'slow':['I allowed one time-limited pause, made one check, responded, and then stopped reviewing the matter.','I delayed within a single boundary, reviewed once, answered, and considered the issue closed.','There was one contained interval and one review pass before my response; after that I did not reopen it.','I took a finite pause, checked the matter a single time, replied, and ended the review process.','Before answering I used one bounded delay and one review, then treated the decision process as finished.','I paused once inside a defined limit, checked once, gave my response, and left the matter closed.'],
'sequence':['I advanced toward taking the action, withdrew, then arrived back at the same judgement without any new facts.','I moved close to execution, stepped back, and repeated the earlier reasoning although nothing had changed.','I approached the practical move, retreated, then returned to the same conclusion with no additional evidence.','I nearly acted, pulled away, and cycled back to my prior assessment while the information stayed identical.','I moved toward doing it, reversed course, and repeated the same judgement in the absence of new information.','I came close to execution, backed out, then revisited the same reasoning even though no new evidence appeared.'],
'neutral':['I made the final choice myself, carried it out, and left the matter closed afterward.','Decision ownership stayed with me; I completed what I chose and moved on.','I retained final agency, executed the action, and did not reopen the issue once done.','The final call remained mine through completion; afterward I treated the situation as settled.','I chose for myself, finished the action, and did not return to the decision process.','I kept ownership of the decision, completed it, and left the issue resolved.']}
VI={
'clarification':['Đây là event thật và tôi mô tả được những gì dẫn tới ending, nhưng specific action tôi làm tại ending đó chưa có trong account.','Chuyện này xảy ra với tôi; circumstances concrete nhưng observable final response của chính tôi chưa được cung cấp.','Lived episode đã rõ trừ một fact: chính tôi đã làm gì ngay trước khi nó conclude.','Tôi đã đưa real situation và sequence nhưng chưa nêu behaviour đến từ tôi ở closing point.','Event không hypothetical và context đã biết; chỉ actual endpoint action của tôi còn absent.','Mọi thứ quanh lived situation đã mô tả trừ concrete thing cuối mà chính tôi làm.'],
'decision':['Hãy make choice luôn cho tôi và để selection đó thành final option của tôi.','Tôi yêu cầu bạn decide outcome của choice chứ không coach tôi tự quyết.','Chọn route tôi nên đi để call của bạn substitute cho call của tôi.','Take over final selection thay vì để decision ownership ở tôi.','Dùng judgement của bạn pick option trở thành decision của tôi.','Tôi muốn final call do bạn make on my behalf chứ không phải tôi.'],
'hypothetical':['Tôi viết đoạn này như made-up assessment material; nó không liên quan event nào tôi trải qua.','Scenario chỉ tồn tại như artificial test input và không autobiographical.','Example được invent để validation và không report chuyện xảy ra với tôi.','Không có personal event nào ở đây; đây là constructed practice case.','Scenario là fictional evaluation text chứ không phải evidence từ đời tôi.','Tôi deliberately tạo example để testing, không có real experience phía sau.'],
'third':['Mô tả điều người kia privately believes dù họ không cho observable behaviour hay statement nào support.','Nói concealed conclusion của người khác khi không outward evidence nào từ người đó.','Suy ra hidden view bên trong người kia dù không words hay conduct nào establish.','Xác định private thought của họ khi không observable action nào justify inference.','Nói người khác secretly nghĩ gì dù behaviour của họ không cho basis.','Cho tôi internal conclusion của người kia khi không điều họ nói hay làm support conclusion đó.'],
'prediction':['Khi future point tôi specify tới, result tôi muốn có ở đó không?','Đến future deadline tôi nêu, situation có end theo preferred way của tôi không?','Tại future milestone đó, tôi có obtain outcome mình hy vọng không?','Desired result có tồn tại trước future date tôi đưa không?','Nhìn tới future checkpoint đã nêu, mọi thứ có resolve theo cách tôi muốn không?','Khi future boundary đó tới, outcome có in my favour không?'],
'freeze':['Tôi có small step dễ reverse, nhưng cứ broaden alternative tới mức không bao giờ begin.','Có low-cost trial move với đường quay lại rõ; tôi thêm choice thay vì start.','Có reversible opening action, nhưng comparison cứ widen và tôi inactive.','Tôi có thể test contained first move rồi undo, nhưng option growth thay thế initiation.','First action ít commitment và reversible; tôi cứ generate possibility rồi không start.','Bounded starter step có easy exit, nhưng tôi expand choice set tới mức không move.'],
'ignore':['Issue quan trọng vẫn require something từ tôi, nhưng tôi đổ effort vào side activity không thể answer nó.','Central responsibility đang chờ response của tôi trong khi tôi dành thời gian cho peripheral work.','Important matter vẫn unresolved vì tôi redirect attention sang secondary task.','Response của tôi vẫn needed ở main issue, nhưng tôi occupy với work không address nó.','Core obligation require action từ tôi, nhưng tôi divert sang task ít relevant hơn.','Một consequential matter vẫn unanswered khi tôi dùng side work để avoid dealing with it.'],
'slow':['Tôi cho một time-limited pause, check một lần, response rồi stop reviewing matter.','Tôi delay trong single boundary, review một lần, answer rồi xem issue closed.','Có một contained interval và one review pass trước response; sau đó tôi không reopen.','Tôi lấy finite pause, check một lần, reply rồi end review process.','Trước khi answer tôi dùng bounded delay và one review rồi xem decision process finished.','Tôi pause một lần trong defined limit, check một lần, response rồi để matter closed.'],
'sequence':['Tôi advance toward action, withdraw rồi quay lại same judgement khi không có new facts.','Tôi move gần execution, step back rồi lặp earlier reasoning dù không gì changed.','Tôi approach practical move, retreat rồi return same conclusion khi không additional evidence.','Tôi nearly acted, pull away rồi cycle về prior assessment khi information identical.','Tôi move toward doing it, reverse course rồi repeat same judgement khi không new information.','Tôi gần execution, back out rồi revisit same reasoning dù không new evidence.'],
'neutral':['Tôi tự make final choice, carry it out rồi để matter closed.','Decision ownership ở tôi; tôi complete điều đã chọn rồi move on.','Tôi retain final agency, execute action và không reopen issue khi done.','Final call ở tôi tới completion; sau đó tôi xem situation settled.','Tôi tự choose, finish action và không quay lại decision process.','Tôi giữ ownership của decision, complete nó và để issue resolved.']}
CTXE=['A leather studio logged edge tools and thread cards by drawer.','A choir library indexed score sleeves and pencil boxes by shelf.','A bicycle classroom tracked torque keys and tyre levers by station.','A greenhouse lab recorded mist nozzles and plant tags by bay.','A ceramics store catalogued sponge trays and glaze notes by cabinet.','A photo archive logged negative sleeves and clip bags by case.','A bakery room indexed dough cards and scraper bins by bench.','A kayaking shed tracked buckle kits and paddle rings by rack.','A theatre archive recorded cue folders and prop labels by locker.','A sewing school catalogued bobbin cases and pattern clips by table.','A telescope club logged eyepiece caps and mount screws by case.','A map room indexed tube tags and paper weights by drawer.','A sound booth tracked cable straps and headset pads by cabinet.','A herbarium lab recorded specimen cards and blotter sheets by shelf.','A rowing workshop catalogued seat runners and oar collars by board.','A dance store logged costume tags and shoe bags by rail.','A repair hub indexed socket trays and parts labels by bench.','A cooking school tracked utensil bins and pantry cards by shelf.']
CTXV=['Leather studio ghi edge tool và thread card theo drawer.','Choir library lập index score sleeve và pencil box theo shelf.','Bicycle classroom theo dõi torque key và tyre lever theo station.','Greenhouse lab ghi mist nozzle và plant tag theo bay.','Ceramics store catalog sponge tray và glaze note theo cabinet.','Photo archive ghi negative sleeve và clip bag theo case.','Bakery room lập index dough card và scraper bin theo bench.','Kayaking shed theo dõi buckle kit và paddle ring theo rack.','Theatre archive ghi cue folder và prop label theo locker.','Sewing school catalog bobbin case và pattern clip theo table.','Telescope club ghi eyepiece cap và mount screw theo case.','Map room lập index tube tag và paper weight theo drawer.','Sound booth theo dõi cable strap và headset pad theo cabinet.','Herbarium lab ghi specimen card và blotter sheet theo shelf.','Rowing workshop catalog seat runner và oar collar theo board.','Dance store ghi costume tag và shoe bag theo rail.','Repair hub lập index socket tray và parts label theo bench.','Cooking school theo dõi utensil bin và pantry card theo shelf.']
TAIL_E=['That inventory detail is incidental setting, not evidence of the response.','The storage note is logistical background and cannot establish the mechanism.','That equipment reference has no authority over the semantic classification.','The filing record supplies context only, not behavioural proof.','That physical detail sits outside the response evidence.','The administrative record cannot determine the mechanism under review.']
TAIL_V=['Inventory detail đó chỉ là incidental setting chứ không phải response evidence.','Storage note là logistical background và không establish mechanism.','Equipment reference không có authority lên semantic classification.','Filing record chỉ supply context chứ không behavioural proof.','Physical detail đó nằm ngoài response evidence.','Administrative record không thể determine mechanism đang review.']
cases=[]
for ci,c in enumerate(C):
 for j in range(18):
  lang='EN' if j<9 else 'VI';k=(ci*2+j*5)%6;core=(EN if lang=='EN' else VI)[c][k];ctx=(CTXE if lang=='EN' else CTXV)[(ci*7+j*11)%18];tail=(TAIL_E if lang=='EN' else TAIL_V)[(ci*5+j)%6];parts=[core,ctx,tail];rot=(2*ci+2*j)%3;parts=parts[rot:]+parts[:rot];surface=' '.join(parts);route,fam,seq=E[c];cases.append({'case_id':f'V229-S{ci:02d}-{j:02d}','category':c,'language':lang,'domain':D[(ci*4+j)%6],'surface':surface,'expected':{'route':route,'families':fam,'sequence':bool(seq)}})
assert len(cases)==180 and len({x['surface'] for x in cases})==180
selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V229-S{ci:02d}-{j:02d}' for j in [0,3,7,10,15,17]];selected+=ids;A+=ids[:3];B+=ids[3:]
assert len(selected)==60 and len(A)==30 and len(B)==30 and set(A).isdisjoint(B)
cm={x['case_id']:x for x in cases};fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 ta,tb=toks(a),toks(b);return len(ta&tb)/len(ta|tb) if ta|tb else 1.0
internal=(0,None)
for i in range(len(cases)):
 for j in range(i):
  q=sim(cases[i]['surface'],cases[j]['surface'])
  if q>internal[0]:internal=(q,(cases[j]['case_id'],cases[i]['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228]:
 br=f'v83{v}-v1-sealed-validation';p=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  z=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{p}'],text=True));prior+=z.get('cases',[])
 except Exception:pass
ext=(0,None);at75=0;exact=0;prior_sur={x.get('surface','') for x in prior}
for x in cases:
 if x['surface'] in prior_sur:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:at75+=1
  if q>ext[0]:ext=(q,(x['case_id'],y.get('case_id')))
fps=[(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface'])))) for x in cases];fpdup=len(fps)-len(set(fps))
assert internal[0]<.75 and ext[0]<.75 and at75==0 and exact==0 and fpdup==0
def dump(n,o):(O/n).write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
def canon(o):return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def ho(o):return hashlib.sha256(canon(o)).hexdigest()
bank={'authority':'V8.3.229 PRESEAL CANDIDATE BANK','cases':cases};selection={'authority':'V8.3.229 SEALED SELECTION','selected':selected,'batch_a':A,'batch_b':B};fix={'authority':'V8.3.229 SEALED FIXTURE','cases':fixture};g={'authority':'V8.3.229 INDEPENDENT GOLD','cases':gold};membership={'authority':'V8.3.229 SEALED MEMBERSHIP','selected':selected,'batch_a':A,'batch_b':B};audit={'candidate':'V8.3.229','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(ext[0],6),'external_max_pair':ext[1],'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True}
for n,o in [('V8_3_229_PRESEAL_CANDIDATE_BANK_V1.json',bank),('V8_3_229_SEALED_SELECTION_V1.json',selection),('V8_3_229_SEALED_FIXTURE_V1.json',fix),('V8_3_229_INDEPENDENT_GOLD_V1.json',g),('V8_3_229_SEALED_MEMBERSHIP_V1.json',membership),('V8_3_229_PRESEAL_DIVERSITY_AUDIT_V1.json',audit)]:dump(n,o)
hashes={'candidate_bank':ho(bank),'selection':ho(selection),'fixture':ho(fix),'independent_gold':ho(g),'membership':ho(membership),'preseal_audit':ho(audit)};auth={'candidate':'V8.3.229','validated_development_head_sha':DEV,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'semantic_runtime_executed':False,'batch_a_executed':False,'batch_b_executed':False};dump('V8_3_229_SEALED_AUTHORITY_V1.json',auth)
receipt={'candidate':'V8.3.229','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(ext[0],6),'external_cases_at_or_above_0_75':at75,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};dump('V8_3_229_PRESEAL_RUN_RECEIPT.json',receipt);print(json.dumps(receipt))
