import json,hashlib,pathlib,subprocess,re
R=pathlib.Path('.');O=R/'validation/v83251-v1-sealed';O.mkdir(parents=True,exist_ok=True)
DEV='125a6f60c94eda4c455323a171006cac613eb903';BASE='514cbcb34fbe336033c8f8858a53415371137973';SEM='QCEvidenceExtractorV5AW -> QCSemanticCoreV122'
subprocess.run(['git','fetch','origin','v83250-v1-sealed-validation:refs/remotes/origin/v83250-v1-sealed-validation'],check=True,stdout=subprocess.DEVNULL)
prev=json.loads(subprocess.check_output(['git','show','origin/v83250-v1-sealed-validation:validation/v83250-v1-sealed/V8_3_250_PRESEAL_CANDIDATE_BANK_V1.json'],text=True))['cases'];assert len(prev)==180
CORES={
'clarification':{
'EN':['This is a real situation of mine, but the concrete response I made at the end is still missing.','The event actually happened to me; I have not yet supplied my final observable action.','My situation is real and specific, while what I personally did at closure remains unstated.'],
'VI':['Đây là tình huống thật của tôi, nhưng hành động cụ thể cuối cùng tôi đã làm vẫn còn thiếu.','Chuyện này thực sự xảy ra với tôi; phần final observable action của tôi chưa được cung cấp.','Bối cảnh là chuyện thật của tôi, còn response cụ thể của tôi ở đoạn kết vẫn chưa được nói ra.']},
'decision':{
'EN':['Choose the final option for me so your choice replaces my own deciding role.','Make the conclusive decision on my behalf instead of leaving the final call with me.','Take over the final choice and tell me which option I should ultimately select.'],
'VI':['Hãy chọn option cuối thay tôi để quyết định của bạn thay thế vai trò quyết định của tôi.','Tôi muốn bạn đưa ra lựa chọn kết luận thay cho final call của chính tôi.','Bạn hãy cầm quyền chọn cuối và quyết định option tôi nên lấy thay tôi.']},
'hypothetical':{
'EN':['This is a constructed classification example and none of the described event happened to me.','The scenario is fictional test material rather than a situation from my own life.','I am giving an invented example for classification, not reporting something I personally lived.'],
'VI':['Đây chỉ là ví dụ classification được dựng lên, không phải chuyện đã xảy ra với tôi.','Scenario này là test material hư cấu chứ không phải tình huống tôi từng sống qua.','Tôi đang đưa một ví dụ giả định để phân loại, không kể chuyện thật của bản thân.']},
'third':{
'EN':['I am asking for another person’s hidden conclusion even though I have no outward behaviour that verifies it.','The question is about what someone else privately believes, without observable words or actions confirming it.','I want their concealed internal position, but nothing they did provides behavioural evidence for that claim.'],
'VI':['Tôi đang hỏi kết luận kín bên trong của người khác dù không có hành vi bên ngoài để verify.','Câu hỏi là họ privately tin gì, nhưng không có lời nói hay action quan sát được xác nhận điều đó.','Tôi muốn biết concealed internal position của họ trong khi không có behavioural evidence từ phía họ.']},
'prediction':{
'EN':['Tell me what will happen in the future and whether this outcome is going to occur.','I want a forecast of the future result rather than analysis of a real present situation.','Predict whether the requested outcome will happen later and when it will unfold.'],
'VI':['Hãy cho tôi biết tương lai sẽ xảy ra gì và outcome này có xảy ra hay không.','Tôi muốn forecast kết quả tương lai chứ không phải phân tích một tình huống thật hiện tại.','Dự đoán outcome này sau đó có xảy ra không và khi nào nó diễn ra.']},
'freeze':{
'EN':['A small low-commitment first move was available, but I kept creating additional options and stayed still.','I had a bounded opening action ready; more comparison displaced starting and I made no move.','There was a reversible first step I could take, yet expanding routes replaced initiation and I remained in place.'],
'VI':['Tôi có một first move ít cam kết, nhưng cứ tạo thêm option nên cuối cùng vẫn đứng yên.','Có một opening action có giới hạn, nhưng việc so thêm lựa chọn thay cho bắt đầu và tôi không làm move nào.','Một bước đầu reversible đã sẵn, nhưng tôi mở rộng route thay cho initiation nên vẫn ở nguyên chỗ.']},
'ignore':{
'EN':['The central responsibility still required my action, while I redirected effort into secondary work that could not resolve it.','An important core matter needed my response, but I stayed busy with peripheral tasks instead.','My action was still required on the main issue; I shifted attention to less relevant work and left it open.'],
'VI':['Việc trung tâm vẫn cần action của tôi, nhưng tôi dùng effort cho công việc thứ yếu không thể giải quyết nó.','Một core matter quan trọng cần response của tôi, nhưng tôi lại giữ mình bận với task bên lề.','Main issue vẫn cần tôi hành động; tôi chuyển attention sang việc ít liên quan hơn và để nó mở.']},
'slow':{
'EN':['I used one bounded pause and one review before responding, then treated the matter as settled and stopped revisiting it.','There was a finite delay, a single check, and then I answered and closed the issue without reopening it.','I paused within a clear limit, reviewed once, responded, and moved on rather than continuing to reconsider.'],
'VI':['Tôi dùng một pause giới hạn và một review trước khi trả lời, rồi xem chuyện đã settled và ngừng revisit.','Có một delay hữu hạn, check một lần, sau đó tôi response và đóng issue mà không reopen.','Tôi pause trong boundary rõ, review một lần, trả lời rồi đi tiếp thay vì tiếp tục reconsider.']},
'sequence':{
'EN':['I moved close to acting, pulled back, and returned to the same assessment even though no new evidence appeared.','I approached execution, retreated, then cycled back to the prior conclusion without added information.','I nearly acted, reversed course, and revisited the old reasoning while the facts stayed unchanged.'],
'VI':['Tôi tiến gần tới hành động, lùi lại rồi quay về cùng assessment dù không có evidence mới.','Tôi tiến tới execution, retreat rồi cycle về kết luận cũ mà không có information thêm.','Tôi gần làm, đổi chiều rồi revisit reasoning trước trong khi facts không thay đổi.']},
'neutral':{
'EN':['I kept the final deciding authority, completed the action, and left the issue closed without reconsidering it.','The final choice remained mine; I carried it through and did not reopen the decision afterwards.','I decided for myself, executed the action to completion, and moved on without revisiting the choice.'],
'VI':['Tôi giữ deciding authority cuối, hoàn tất action và để issue đóng lại mà không reconsider.','Final choice vẫn là của tôi; tôi thực hiện đến cùng và không reopen quyết định sau đó.','Tôi tự quyết định, execute hành động đến completion rồi đi tiếp mà không revisit lựa chọn.']}}
SCENES=[
('spectrograph calibration annex',['echelle orders','thorium lines','flat fields','bias frames','dispersion solutions','blaze functions','cross-correlation masks','radial-velocity standards','wavelength residuals','order traces','extraction apertures','cosmic-ray flags','continuum windows','line-spread functions','detector gains','read noise','overscan regions','barycentric corrections','airmass tables','lamp exposures','pixel maps','slit widths','focus curves','temperature logs']),
('ancient glass chemistry archive',['natron ratios','plant-ash signatures','manganese decolorants','antimony opacifiers','cobalt colorants','copper reds','lead isotopes','strontium proxies','silica matrices','alumina levels','lime fractions','trace zirconium','rare-earth patterns','LA-ICP-MS spots','SEM sections','weathering crusts','bubble fabrics','cord textures','annealing marks','rim fragments','base scars','pontil traces','cullet groups','furnace batches']),
('high-altitude physiology unit',['pulse oximeters','barometric chambers','ventilatory equivalents','oxygen saturations','hemoglobin masses','capillary samples','lactate curves','hypoxic ventilatory responses','alveolar gradients','spirometry loops','heart-rate variability','acclimatization diaries','sleep desaturations','exercise stages','work rates','blood-gas syringes','hematocrit tubes','erythropoietin assays','temperature probes','hydration logs','respiratory quotients','metabolic carts','mask seals','calibration gases']),
('manuscript pigment laboratory',['azurite grains','malachite particles','vermilion crystals','red-lead phases','orpiment plates','indigo lakes','carbon blacks','lead-white aggregates','gypsum grounds','chalk fillers','gum binders','protein sizes','Raman bands','XRF maps','FORS curves','microscope cross-sections','gold leaf','silver tarnish','verdigris products','iron-gall halos','parchment fibres','paint losses','retouch zones','sampling labels']),
('orbital mechanics classroom',['Keplerian elements','mean anomalies','eccentric anomalies','true anomalies','argument of periapsis','ascending nodes','inclinations','specific energies','angular momenta','Hohmann transfers','Lambert solutions','state vectors','ephemeris epochs','Julian dates','perturbation terms','J2 coefficients','drag models','solar pressures','delta-v budgets','burn windows','ground tracks','visibility arcs','range rates','covariance ellipses']),
('forensic entomology cabinet',['blowfly instars','puparial cases','spiracular plates','cephalopharyngeal skeletons','degree-hour totals','oviposition windows','succession tables','soil temperatures','maggot masses','rearing jars','species keys','wing venation','setal patterns','emergence logs','humidity records','development curves','larval lengths','crop contents','empty puparia','collection nets','preservation ethanol','scene labels','voucher specimens','chain records']),
('acoustic metamaterials lab',['Helmholtz resonators','locally resonant cells','Bragg gaps','effective densities','negative moduli','dispersion branches','Bloch modes','impedance tubes','anechoic terminations','microperforated panels','membrane resonators','lattice constants','unit cells','transmission losses','reflection coefficients','phase delays','finite-element meshes','boundary layers','viscothermal losses','speaker arrays','microphone pairs','transfer functions','frequency sweeps','sample holders']),
('ice-core geochemistry store',['dust concentrations','sulfate peaks','nitrate layers','chloride ions','methanesulfonate','stable oxygen isotopes','deuterium excess','black-carbon bands','tephra shards','annual layers','melt features','gas bubbles','air-age scales','ice-age scales','conductivity profiles','dielectric scans','core depths','section cuts','clean-room blanks','ion chromatograms','continuous-flow lines','reference waters','bag numbers','freezer racks']),
('neuroanatomy teaching collection',['cortical gyri','sulcal landmarks','brainstem nuclei','cranial nerves','thalamic regions','basal ganglia','hippocampal formations','cerebellar lobules','white-matter tracts','coronal sections','sagittal sections','axial planes','histology slides','myelin stains','Nissl stains','fiber dissections','atlas plates','specimen jars','orientation pins','label cards','section levels','ventricular outlines','vascular casts','storage trays']),
('historical cartography room',['rhumb lines','graticule arcs','portolan coasts','compass roses','scale bars','latitude ticks','loxodromes','projection grids','engraved plates','copper impressions','hand colors','watermarks','plate marks','neatlines','cartouches','toponyms','soundings','hachures','boundary washes','fold lines','mounting guards','atlas signatures','sheet numbers','catalogue slips']),
('battery diagnostics bench',['coulombic efficiencies','capacity retentions','charge curves','discharge curves','dQ-dV peaks','impedance spectra','Nyquist arcs','Warburg tails','open-circuit voltages','state-of-charge estimates','state-of-health models','calendar aging','cycle aging','SEI growth','lithium plating','electrode porosity','separator wetting','thermal profiles','current collectors','formation cycles','reference electrodes','cell fixtures','temperature chambers','test channels']),
('pollen reference laboratory',['exine sculptures','aperture types','colpus lengths','pore diameters','reticulate meshes','echinate spines','psilate walls','polar views','equatorial views','acetolysis residues','glycerol mounts','reference slides','taxonomic keys','counting transects','marker grains','Lycopodium tablets','concentration estimates','sum counts','preservation scores','broken grains','charcoal particles','sample depths','core labels','slide boxes']),
('underwater archaeology depot',['amphora sherds','ballast stones','wooden treenails','copper fasteners','lead sheathing','ceramic concretion','rope fragments','timber frames','caulking fibres','ship nails','keel sections','frame stations','dendro samples','sediment bags','photogrammetry targets','scale bars','dive slates','context numbers','find tags','freshwater tanks','desalination baths','conservation crates','site grids','provenance logs']),
('satellite remote-sensing suite',['radiance arrays','reflectance products','atmospheric corrections','cloud masks','quality flags','spectral indices','NDVI layers','surface temperatures','aerosol depths','view angles','solar zeniths','geolocation grids','tie points','orthorectification models','digital elevations','resampling kernels','swath edges','scan lines','detector strips','calibration coefficients','lookup tables','scene identifiers','tile indices','processing levels']),
('historical phonology archive',['sound laws','cognate sets','proto-forms','ablaut grades','lenition paths','fortition shifts','palatalizations','metathesis cases','vowel mergers','chain shifts','tone splits','stress patterns','syllable weights','correspondence sets','loan strata','dialect maps','isogloss bundles','reconstruction notes','etymon cards','attestation dates','manuscript forms','phoneme inventories','feature matrices','archive slips']),
('microfossil preparation lab',['foraminiferal tests','diatom frustules','radiolarian skeletons','coccolith plates','ostracod valves','sieve fractions','heavy liquids','hydrogen peroxide','buffer washes','settling trays','picking brushes','microslides','faunal counts','species ranges','biozones','preservation grades','fragmentation scores','dissolution indices','sample residues','core depths','wash bottles','drying ovens','reference collections','tray labels']),
('precision fermentation room',['specific gravities','Brix readings','pH curves','dissolved oxygens','yeast viabilities','pitching rates','attenuation profiles','temperature ramps','pressure traces','volatile acids','ester concentrations','sugar spectra','nutrient additions','cell counts','fermenter volumes','airlock rates','sampling ports','sterility blanks','CIP cycles','batch codes','hydrometer checks','refractometer offsets','sensory panels','storage logs']),
('geometric morphometrics studio',['landmark coordinates','semilandmark curves','Procrustes fits','centroid sizes','tangent spaces','principal components','relative warps','thin-plate splines','deformation grids','allometric slopes','shape distances','permutation tests','consensus forms','specimen meshes','digitizing errors','repeatability trials','missing landmarks','sliding criteria','symmetry components','asymmetry scores','group means','confidence ellipses','wireframe plots','specimen IDs'])]
TAIL=['A separate accession ledger for '+n+' remained unrelated physical context and supplied no behavioural evidence.' for n,_ in SCENES]
new=[]
for x in prev:
 m=re.search(r'-S(\d+)-(\d+)$',x['case_id']);assert m
 ci,j=map(int,m.groups());cat=x['category'];lang=x['language'];core=CORES[cat][lang][j%3]
 n,items=SCENES[j];scene=f"A {n} independently catalogued {', '.join(items)}; that technical inventory is environmental scenery only and cannot determine the measured response."
 # Add a second variant-specific inert sentence with unique index tokenization.
 tag=f"Archive batch marker qv{j:02d} registered compartment sequence kappa{(j*7+3):03d} lambda{(j*11+5):03d} sigma{(j*13+7):03d}; these identifiers are inert."
 y={k:v for k,v in x.items() if k not in ['case_id','surface']};y['case_id']=f'V251-S{ci:02d}-{j:02d}';y['surface']=scene+' '+core+' '+TAIL[j]+' '+tag;new.append(y)
assert len(new)==180 and len({x['surface'] for x in new})==180
cm={x['case_id']:x for x in new};selected=[];A=[];B=[]
for ci in range(10):
 ids=[f'V251-S{ci:02d}-{j:02d}' for j in [0,9,3,12,6,15]];selected+=ids;A+=ids[:3];B+=ids[3:]
fixture=[cm[i] for i in selected];gold=[{'case_id':x['case_id'],'expected':x['expected']} for x in fixture]
def toks(s):return set(re.findall(r'[a-z0-9]+',str(s).lower()))
def sim(a,b):
 A1=toks(a);B1=toks(b);return len(A1&B1)/max(1,len(A1|B1))
internal=(0,None)
for i,x in enumerate(new):
 for y in new[i+1:]:
  q=sim(x['surface'],y['surface'])
  if q>internal[0]:internal=(q,(x['case_id'],y['case_id']))
prior=[]
for v in [219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250]:
 br=f'v83{v}-v1-sealed-validation';path=f'validation/v83{v}-v1-sealed/V8_3_{v}_PRESEAL_CANDIDATE_BANK_V1.json'
 try:
  subprocess.run(['git','fetch','--depth=1','origin',f'refs/heads/{br}:refs/remotes/origin/{br}'],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  obj=json.loads(subprocess.check_output(['git','show',f'origin/{br}:{path}'],text=True,stderr=subprocess.DEVNULL));prior+=obj.get('cases',[])
 except Exception:pass
external=(0,None);high=0;exact=0;prior_surfaces={x.get('surface','') for x in prior}
for x in new:
 if x['surface'] in prior_surfaces:exact+=1
 for y in prior:
  q=sim(x['surface'],y.get('surface',''))
  if q>=.75:high+=1
  if q>external[0]:external=(q,(x['case_id'],y.get('case_id')))
finger=lambda x:(x['category'],x['language'],x['domain'],x['expected']['route'],tuple(x['expected']['families']),x['expected']['sequence'],tuple(sorted(toks(x['surface']))))
prior_fp={finger(x) for x in prior if all(k in x for k in ['category','language','domain','expected','surface'])};fpdup=sum(1 for x in new if finger(x) in prior_fp)
assert internal[0]<.75 and external[0]<.75 and high==0 and exact==0 and fpdup==0
objects={'PRESEAL_CANDIDATE_BANK_V1':{'authority':'V8.3.251 PRESEAL CANDIDATE BANK V1','cases':new},'SEALED_SELECTION_V1':{'candidate':'V8.3.251','selected':selected,'batch_a':A,'batch_b':B},'SEALED_FIXTURE_V1':{'candidate':'V8.3.251','cases':fixture},'INDEPENDENT_GOLD_V1':{'candidate':'V8.3.251','cases':gold},'SEALED_MEMBERSHIP_V1':{'candidate':'V8.3.251','batch_a':A,'batch_b':B}}
for name,obj in objects.items():(O/f'V8_3_251_{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
audit={'candidate':'V8.3.251','candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_max_pair':external[1],'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'pass':True};(O/'V8_3_251_PRESEAL_DIVERSITY_AUDIT_V1.json').write_text(json.dumps(audit,indent=2)+'\n')
def ho(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
hashes={k:ho(json.loads((O/n).read_text())) for k,n in {'candidate_bank':'V8_3_251_PRESEAL_CANDIDATE_BANK_V1.json','selection':'V8_3_251_SEALED_SELECTION_V1.json','fixture':'V8_3_251_SEALED_FIXTURE_V1.json','independent_gold':'V8_3_251_INDEPENDENT_GOLD_V1.json','membership':'V8_3_251_SEALED_MEMBERSHIP_V1.json','preseal_audit':'V8_3_251_PRESEAL_DIVERSITY_AUDIT_V1.json'}.items()}
auth={'candidate':'V8.3.251','phase':'SEALED_AUTHORITY_PRE_BATCH_A','validated_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'preseal_pass':True,'hashes':hashes,'batch_a_executed':False,'batch_b_executed':False,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'step_111_authorized':False,'production_authorized':False};(O/'V8_3_251_SEALED_AUTHORITY_V1.json').write_text(json.dumps(auth,indent=2)+'\n')
receipt={'candidate':'V8.3.251','phase':'preseal-freeze-v1','validated_development_head_sha':DEV,'base_exact_development_sha':BASE,'semantic_authority':SEM,'candidate_count':180,'selected_count':60,'batch_a_count':30,'batch_b_count':30,'internal_max_similarity':round(internal[0],6),'internal_max_pair':internal[1],'external_max_similarity':round(external[0],6),'external_cases_at_or_above_0_75':high,'exact_external_duplicates':exact,'semantic_fingerprint_exact_duplicates':fpdup,'semantic_runtime_executed':False,'semantic_authority_loaded':False,'selection_uses_runtime_output':False,'batch_a_executed':False,'batch_b_executed':False,'conclusion':'success'};(O/'V8_3_251_PRESEAL_RUN_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
