const VERSION='v8.3.13-micro-pattern-grounding';
const UPSTREAM='https://quiet-clarity-pattern-signal-check-3lux9quay.vercel.app';
const ELIGIBLE=['A','B','C','D','F','G','H'];

const CLUSTERS={
 A:[{id:'A_AVOID',ids:['A1','A2','A3','A4']},{id:'A_TOLERATE',ids:['A5','A6','A7','A8']}],
 B:[{id:'B_SELF_PRESSURE',ids:['B1','B2','B3','B4']},{id:'B_OVER_UNDERSTAND',ids:['B5','B6','B7','B8']}],
 C:[{id:'C_TIME_DRIFT',ids:['C1','C2','C3','C4']},{id:'C_TUNNEL',ids:['C5','C6','C7','C8']}],
 D:[{id:'D_DELAY',ids:['D1','D2','D3','D4']},{id:'D_COMMITMENT',ids:['D5','D6','D7','D8']}],
 F:[{id:'F_ROLE_WEIGHT',ids:['F1','F2','F3','F4']},{id:'F_OVER_PERSPECTIVE',ids:['F5','F6','F7','F8']}],
 G:[{id:'G_THOUGHT_FUSION',ids:['G1','G2','G3','G4']},{id:'G_OVER_CHECKING',ids:['G5','G6','G7','G8']}],
 H:[{id:'H_MISALIGNMENT',ids:['H1','H2','H3','H4']},{id:'H_VALUE_RIGIDITY',ids:['H5','H6','H7','H8']}]
};

const AREA_HINTS={
 work:['D_DELAY','B_SELF_PRESSURE','H_MISALIGNMENT'],business:['D_DELAY','D_COMMITMENT','H_MISALIGNMENT'],money:['H_MISALIGNMENT','D_COMMITMENT'],
 romantic:['B_OVER_UNDERSTAND','F_OVER_PERSPECTIVE','A_TOLERATE'],family:['B_OVER_UNDERSTAND','F_ROLE_WEIGHT','A_TOLERATE'],friends:['B_OVER_UNDERSTAND','F_OVER_PERSPECTIVE'],
 home:['A_TOLERATE','D_DELAY'],daily:['D_DELAY','H_MISALIGNMENT'],wellbeing:['A_TOLERATE','G_OVER_CHECKING'],direction:['H_MISALIGNMENT','D_DELAY','G_OVER_CHECKING'],repeating:['G_OVER_CHECKING','F_OVER_PERSPECTIVE','A_TOLERATE']
};

const COPY={
 vi:{
  A_AVOID:{p:'Điều nổi bật hơn cả là bạn có xu hướng làm giảm tiếp xúc với sự khó chịu trước khi xử lý trọn phần đang cần được nhìn thẳng.',pc:'Bạn vẫn có khả năng nhìn thực tế và xử lý việc khó; phần shadow nằm ở những lúc bạn cần giảm bớt cảm giác khó chịu trước, khiến việc đối diện trực tiếp bị chậm thêm một nhịp.',f:'Nếu pattern này tiếp tục, những việc cần được xử lý đúng lúc có thể tiếp tục bị dời đến khi phạm vi lựa chọn thực tế hẹp hơn.'},
  A_TOLERATE:{p:'Điều nổi bật hơn cả là khả năng chịu đựng và giữ bình tĩnh của bạn đôi khi khiến bạn nhận ra giới hạn của tình huống muộn hơn mức cần thiết.',pc:'Bạn vẫn chịu được áp lực và giữ bình tĩnh khá tốt; phần shadow nằm ở chỗ chính khả năng đó đôi khi làm tín hiệu “đã đủ rồi” đến với bạn muộn hơn.',f:'Nếu pattern này tiếp tục, bạn có thể tiếp tục ở trong một tình huống lâu hơn trước khi nhận ra rằng phạm vi lựa chọn thực tế đã hẹp đi.'},
  B_SELF_PRESSURE:{p:'Điều nổi bật hơn cả là bạn có xu hướng đặt tiêu chuẩn lên chính mình cao hơn mức tình huống thực tế đang đòi hỏi.',pc:'Bạn vẫn có khả năng tự chịu trách nhiệm và làm việc ở tiêu chuẩn cao; phần shadow nằm ở những lúc tiêu chuẩn đó tiếp tục siết lên mình ngay cả khi bạn đã làm đủ để xử lý tình huống hợp lý.',f:'Nếu pattern này tiếp tục, thời gian và năng lượng có thể tiếp tục bị dùng để sửa hoặc chứng minh thêm ở những chỗ thực tế đã đủ tốt để đi tiếp.'},
  B_OVER_UNDERSTAND:{p:'Điều nổi bật hơn cả là bạn thường dành sự thấu hiểu cho hoàn cảnh hoặc lý do của người khác trước khi đặt đủ trọng lượng vào tác động thực tế đang rơi lên chính mình.',pc:'Bạn vẫn có khả năng thấu hiểu người khác và giữ ranh giới; phần shadow nằm ở những lúc sự thấu hiểu đi trước, khiến tác động lên chính bạn được đưa vào quyết định muộn hơn.',f:'Nếu pattern này tiếp tục, những quyết định hoặc giới hạn quan trọng có thể tiếp tục được đặt muộn hơn mức tình huống thực tế đang cần.'},
  C_TIME_DRIFT:{p:'Điều nổi bật hơn cả là quá khứ hoặc những khả năng phía trước đôi khi nhận nhiều trọng lượng hơn dữ kiện đang có ngay lúc này.',pc:'Bạn vẫn phân biệt được hiện tại với quá khứ và dự đoán; phần shadow nằm ở những lúc thông tin cũ hoặc khả năng chưa xảy ra được giữ trong quyết định lâu hơn trọng lượng thực tế của chúng.',f:'Nếu pattern này tiếp tục, những lựa chọn cần dựa trên hiện tại có thể tiếp tục bị làm chậm hoặc lệch bởi thông tin không còn cùng trọng lượng.'},
  C_TUNNEL:{p:'Điều nổi bật hơn cả là một việc đang cấp bách hoặc ở ngay trước mắt có thể chiếm quá nhiều sự chú ý so với bức tranh dài hơn.',pc:'Bạn vẫn nhìn chi tiết và xử lý việc trước mắt khá tốt; phần shadow nằm ở những lúc chính độ tập trung đó thu hẹp tầm nhìn và đẩy những ưu tiên quan trọng khác sang sau.',f:'Nếu pattern này tiếp tục, những phần quan trọng nhưng ít cấp bách hơn có thể tiếp tục bị đẩy xuống cho tới khi chúng trở thành vấn đề mới.'},
  D_DELAY:{p:'Điều nổi bật hơn cả là khoảng cách giữa việc bạn đã biết đủ để hành động và thời điểm bạn thực sự bắt đầu hoặc chốt bước tiếp theo.',pc:'Bạn vẫn có khả năng bắt đầu và điều chỉnh khi dữ kiện đã đủ; phần shadow nằm ở những lúc bạn vẫn chờ thêm một chút chắc chắn, chuẩn bị hoặc phân tích sau khi bước hợp lý đã khá rõ.',f:'Nếu pattern này tiếp tục, những cơ hội phụ thuộc vào thời điểm có thể đi qua trước khi một lựa chọn được chốt hoặc đưa vào hành động.'},
  D_COMMITMENT:{p:'Điều nổi bật hơn cả là bạn có xu hướng giữ một hướng đã đầu tư hoặc cam kết lâu hơn, ngay cả khi dữ kiện mới đã bắt đầu làm thay đổi mức độ phù hợp của nó.',pc:'Bạn vẫn có khả năng cam kết và theo đuổi một hướng bền bỉ; phần shadow nằm ở những lúc chính sự bền bỉ đó làm việc dừng, giảm hoặc đổi hướng đến muộn hơn.',f:'Nếu pattern này tiếp tục, thêm thời gian, công sức hoặc nguồn lực có thể tiếp tục đi vào một hướng đã không còn phù hợp như lúc đầu.'},
  F_ROLE_WEIGHT:{p:'Điều nổi bật hơn cả là một vai trò hoặc phần trách nhiệm quen thuộc của bạn có thể nhận quá nhiều trọng lượng khi bạn đánh giá tình huống.',pc:'Bạn vẫn có khả năng nhìn nhiều phía và giữ trách nhiệm; phần shadow nằm ở những lúc vai trò quen thuộc như người giải quyết, người giữ ổn định hoặc người phải làm đúng khiến phần không thuộc về bạn khó được tách ra đủ sớm.',f:'Nếu pattern này tiếp tục, bạn có thể tiếp tục mang hoặc xử lý những phần trách nhiệm mà thực tế không cần nằm hoàn toàn ở phía mình.'},
  F_OVER_PERSPECTIVE:{p:'Điều nổi bật hơn cả là việc nhìn quá nhiều góc đôi khi làm quan điểm dựa trên trải nghiệm trực tiếp của chính bạn bị đặt nhẹ hơn.',pc:'Bạn vẫn có khả năng nhìn nhiều góc và cân nhắc công bằng; phần shadow nằm ở những lúc việc tiếp tục tìm thêm góc nhìn làm lập trường đã có đủ dữ kiện của bạn mất trọng lượng.',f:'Nếu pattern này tiếp tục, một quyết định đã có đủ cơ sở có thể tiếp tục bị giữ mở lâu hơn mức hữu ích.'},
  G_THOUGHT_FUSION:{p:'Điều nổi bật hơn cả là một suy nghĩ, dự đoán hoặc quy tắc lặp lại có thể bắt đầu ảnh hưởng tới lựa chọn gần như thể nó đã là dữ kiện chắc chắn.',pc:'Bạn vẫn có khả năng kiểm tra suy nghĩ bằng dữ kiện; phần shadow nằm ở những lúc một dự đoán hoặc quy tắc lặp đủ nhiều để nhận thêm trọng lượng trước khi được kiểm chứng đầy đủ.',f:'Nếu pattern này tiếp tục, một số lựa chọn có thể tiếp tục được định hình bởi khả năng hoặc quy tắc chưa có cùng trọng lượng với dữ kiện thực tế.'},
  G_OVER_CHECKING:{p:'Điều nổi bật hơn cả là bạn có xu hướng kiểm tra lại nhận định thêm nhiều lần ngay cả khi dữ kiện đã đủ để chốt một kết luận hợp lý.',pc:'Bạn vẫn có khả năng kiểm chứng suy nghĩ và tin vào nhận định khi dữ kiện đã đủ; phần shadow nằm ở những lúc việc kiểm tra kéo dài thêm một vòng và giữ quyết định mở lâu hơn.',f:'Nếu pattern này tiếp tục, các quyết định có thể tiếp tục bị giữ mở đủ lâu để làm mất đi một phần tính kịp thời của chúng.'},
  H_MISALIGNMENT:{p:'Điều nổi bật hơn cả là cách thời gian, năng lượng hoặc lựa chọn gần đây của bạn chưa phản ánh đầy đủ điều bạn nói là quan trọng nhất.',pc:'Bạn vẫn biết khá rõ điều gì quan trọng với mình; phần shadow nằm ở những lúc áp lực trước mắt hoặc quán tính thực tế khiến nguồn lực tiếp tục đi theo một hướng khác với ưu tiên đã rõ.',f:'Nếu pattern này tiếp tục, nguồn lực có thể tiếp tục đi theo một hướng khác với điều bạn thực sự muốn ưu tiên.'},
  H_VALUE_RIGIDITY:{p:'Điều nổi bật hơn cả là một giá trị hoặc nguyên tắc quan trọng có thể được giữ quá chặt đến mức những giá trị và điều kiện thực tế khác bị đặt nhẹ hơn.',pc:'Bạn vẫn có khả năng sống theo giá trị của mình; phần shadow nằm ở những lúc một giá trị đúng với bạn nhận quá nhiều trọng lượng và làm cách áp dụng nó kém linh hoạt hơn hoàn cảnh đang cần.',f:'Nếu pattern này tiếp tục, một ưu tiên đúng nhưng quá nổi trội có thể tiếp tục đẩy những nhu cầu hoặc giá trị quan trọng khác xuống sau.'}
 },
 en:{
  A_AVOID:{p:'What stands out most is a tendency to reduce contact with discomfort before fully dealing with what needs to be faced.',pc:'You can still see reality and handle difficult things; the shadow appears when you need to lower the discomfort first, delaying direct engagement by one more step.',f:'If this pattern continues, matters that need timely handling may keep being deferred until the practical range of options becomes narrower.'},
  A_TOLERATE:{p:'What stands out most is that your ability to tolerate discomfort and stay composed can sometimes make you notice the limit of a situation later than is useful.',pc:'You still tolerate pressure and stay composed well; the shadow is that this strength can make the “enough” signal arrive later.',f:'If this pattern continues, you may remain in a situation longer before noticing that the practical range of options has narrowed.'},
  B_SELF_PRESSURE:{p:'What stands out most is a tendency to hold yourself to a higher standard than the situation actually requires.',pc:'You can still take responsibility and work to a high standard; the shadow appears when that standard keeps tightening even after you have done enough to handle the situation reasonably.',f:'If this pattern continues, time and energy may keep going into correcting or proving more in places that are already sufficient to move forward.'},
  B_OVER_UNDERSTAND:{p:'What stands out most is a tendency to give another person’s circumstances or reasons weight before giving equal weight to the practical effect on you.',pc:'You can still understand other people and keep boundaries; the shadow appears when understanding comes first and the effect on you enters the decision later.',f:'If this pattern continues, important decisions or limits may keep being set later than the situation actually calls for.'},
  C_TIME_DRIFT:{p:'What stands out most is the past or future possibilities sometimes carrying more weight than the evidence available now.',pc:'You can still distinguish the present from the past and from prediction; the shadow appears when old information or unrealised possibilities stay in the decision longer than their current weight warrants.',f:'If this pattern continues, choices that need to rest on the present may keep being delayed or distorted by information that no longer carries equal weight.'},
  C_TUNNEL:{p:'What stands out most is an urgent or immediate issue taking up too much attention relative to the longer picture.',pc:'You can still handle detail and immediate demands well; the shadow appears when that focus narrows the field and pushes other important priorities behind it.',f:'If this pattern continues, important but less urgent parts may keep being deferred until they become new problems.'},
  D_DELAY:{p:'What stands out most is the gap between already knowing enough to act and the point at which you actually begin or settle the next step.',pc:'You can still begin and adjust when the evidence is sufficient; the shadow appears when you wait for a little more certainty, preparation or analysis after a reasonable step is already clear.',f:'If this pattern continues, time-sensitive opportunities may pass before a choice is settled or put into action.'},
  D_COMMITMENT:{p:'What stands out most is a tendency to hold on to a direction you have already invested in even after new evidence starts to change how well it fits.',pc:'You can still commit and persist strongly; the shadow appears when that persistence makes stopping, reducing or changing direction arrive later.',f:'If this pattern continues, more time, effort or resources may keep going into a direction that no longer fits as well as it once did.'},
  F_ROLE_WEIGHT:{p:'What stands out most is a familiar role or responsibility carrying too much weight when you assess the situation.',pc:'You can still take multiple perspectives and hold responsibility; the shadow appears when a familiar role such as fixer, stabiliser or responsible one makes it harder to separate what does not actually belong to you.',f:'If this pattern continues, you may keep carrying or handling parts of the responsibility that do not need to sit entirely with you.'},
  F_OVER_PERSPECTIVE:{p:'What stands out most is taking so many perspectives that your own evidence-based position can become underweighted.',pc:'You can still consider different perspectives fairly; the shadow appears when continuing to seek more angles weakens a position that already has enough evidence behind it.',f:'If this pattern continues, a sufficiently supported decision may remain open longer than is useful.'},
  G_THOUGHT_FUSION:{p:'What stands out most is a repeated thought, prediction or rule beginning to influence choices almost as if it were established evidence.',pc:'You can still check thoughts against evidence; the shadow appears when a prediction or rule repeats enough to gain extra weight before it has been fully tested.',f:'If this pattern continues, some choices may keep being shaped by possibilities or rules that do not carry the same weight as current evidence.'},
  G_OVER_CHECKING:{p:'What stands out most is a tendency to recheck your judgement even after the evidence is already sufficient for a reasonable conclusion.',pc:'You can still test your thinking and trust a judgement when the evidence is sufficient; the shadow appears when checking takes one extra round and keeps the decision open longer.',f:'If this pattern continues, decisions may remain open long enough to lose some of their timeliness.'},
  H_MISALIGNMENT:{p:'What stands out most is that recent use of time, energy or choice is not fully reflecting what you say matters most.',pc:'You still know fairly clearly what matters to you; the shadow appears when immediate pressure or practical momentum keeps resources moving in a different direction from a priority that is already clear.',f:'If this pattern continues, resources may keep moving in a different direction from what you genuinely want to prioritise.'},
  H_VALUE_RIGIDITY:{p:'What stands out most is one important value or principle being held tightly enough that other values and practical conditions receive less weight.',pc:'You can still live by your values; the shadow appears when one value that is right for you receives too much weight and makes its application less flexible than the situation requires.',f:'If this pattern continues, one valid but over-weighted priority may keep pushing other important needs or values behind it.'}
 }
};

const EVIDENCE_PHRASE={
 vi:{B1:'phản ứng đầu tiên của bạn thường quay về phần mình đã làm sai',B2:'bạn đòi hỏi ở mình nhiều hơn mức bạn sẽ đòi hỏi ở người khác',B3:'việc nghỉ hoặc giảm tải dễ mang cảm giác “vẫn chưa đủ”',B4:'những gì chưa tốt thường giữ sự chú ý lâu hơn phần đã xử lý ổn',B5:'bạn có thể hiểu hoàn cảnh người khác đến mức tác động lên mình xuống sau',B6:'khi lý do của người khác có thể hiểu được, bạn dễ cho tình huống thêm cơ hội',B7:'việc đặt giới hạn có thể đến muộn vì bạn không muốn trở nên quá cứng',B8:'bạn có thể trấn an hoặc bỏ qua vấn đề trước khi phần trách nhiệm được nhìn đủ rõ',D1:'bước tiếp theo khá rõ nhưng việc bắt đầu vẫn chậm hơn',D3:'bạn vẫn muốn thêm chắc chắn dù đã có một bước hợp lý',D4:'chuẩn bị và phân tích có thể kéo dài hơn phần hành động',G6:'bạn có thể nghi ngờ cả một nhận định đã có khá nhiều bằng chứng',G7:'bạn kiểm tra lại suy nghĩ nhiều lần và giữ quyết định mở lâu hơn',H5:'một nguyên tắc đúng có thể được giữ chặt hơn mức hoàn cảnh cần',H6:'một giá trị quan trọng có thể lấn phần của những giá trị khác'},
 en:{B1:'your first reaction often returns to what you may have done wrong',B2:'you expect more from yourself than you would from someone else',B3:'rest or reducing the load can still feel like “not enough”',B4:'what went wrong can hold attention longer than what you handled well',B5:'you can understand another person’s circumstances enough that the effect on you comes second',B6:'when another person’s reasons are understandable, you tend to give the situation more chances',B7:'a boundary can arrive later because you do not want to be too harsh',B8:'you can reassure or move past the issue before responsibility is fully clear',D1:'the next step can be clear while beginning still arrives later',D3:'you can still seek more certainty after a reasonable next step already exists',D4:'preparation and analysis can last longer than action',G6:'you can doubt even a judgement that already has fairly good evidence',G7:'you recheck your thinking and keep a decision open longer',H5:'a valid principle can be held more tightly than the situation requires',H6:'one important value can crowd out other important values'}
};

function parseBody(req){try{return typeof req.body==='string'?JSON.parse(req.body):req.body||{}}catch{return {}}}
function shadowIds(body,f){const a=Array.isArray(body.responses?.[f])?body.responses[f].map(String):[];return a.filter(id=>new RegExp(`^${f}[1-8]$`).test(id));}
function adaptive(body,f){return Array.isArray(body.responses?.[f])&&body.responses[f].map(String).includes(`${f}9`);}
function chooseCluster(f,ids,area){const cs=CLUSTERS[f]||[];let best=null;for(const c of cs){const count=ids.filter(id=>c.ids.includes(id)).length;const hint=(AREA_HINTS[area]||[]).includes(c.id)?0.25:0;const score=count+hint;if(!best||score>best.score)best={...c,score,count};}return best?.count?best:null;}
function anchorPhrase(lang,ids,cluster){const map=EVIDENCE_PHRASE[lang]||{};const ordered=ids.filter(id=>cluster.ids.includes(id));for(const id of ordered){if(map[id])return map[id];}return ''}
function microResult(body,result){if(result?.status!=='dominant_pattern'||!result.primary_pattern?.family)return result;const f=result.primary_pattern.family,ids=shadowIds(body,f);if(!ids.length)return result;const area=String(body.intake?.main_area||''),cluster=chooseCluster(f,ids,area);if(!cluster)return result;const lang=body.language==='en'?'en':'vi',copy=COPY[lang][cluster.id];if(!copy)return result;const hasAdaptive=adaptive(body,f);let statement=hasAdaptive?copy.pc:copy.p;const phrase=anchorPhrase(lang,ids,cluster);if(phrase){statement+=lang==='vi'?` Trong các tín hiệu bạn chọn, điểm cụ thể nhất là ${phrase}.`:` In the signals you selected, the clearest specific edge is that ${phrase}.`;}
 result.primary_pattern.statement=statement;result.future_consequence={statement:copy.f};result.confidence=ids.length>=3?'high':ids.length>=2?'moderate':'limited';
 if(hasAdaptive){const base=result.adaptive_capacity?.statement;result.adaptive_capacity={show:true,statement:base|| (lang==='vi'?'Bạn vẫn có năng lực thích ứng rõ trong chính khu vực này; pattern không xoá phần đang vận hành tốt.':'You still show clear adaptive capacity in this same area; the pattern does not erase what is already functioning well.')};}
 result._micro_pattern=cluster.id;return result;}
async function upstream(req,pathOverride){const path=pathOverride??String(req.query?.path||'');const q=new URLSearchParams();for(const [k,v] of Object.entries(req.query||{})){if(k==='path')continue;if(Array.isArray(v))v.forEach(x=>q.append(k,String(x)));else if(v!==undefined&&v!==null)q.set(k,String(v));}let url=UPSTREAM+'/'+path.replace(/^\/+/, '');if(q.toString())url+=(url.includes('?')?'&':'?')+q.toString();const init={method:req.method,headers:{}};if(!['GET','HEAD'].includes(req.method)){init.headers['content-type']='application/json';init.body=JSON.stringify(parseBody(req));}const r=await fetch(url,init);return r;}
function copyHeaders(r,res){for(const [k,v] of r.headers){if(['content-length','transfer-encoding','content-encoding','connection'].includes(k.toLowerCase()))continue;res.setHeader(k,v);}res.setHeader('x-qc-version',VERSION);res.setHeader('x-robots-tag','noindex');}
async function selftest(res){const base={language:'vi',impact:{choice_action:2,adjustability:2,spillover:1},intake:{main_area:'romantic',current_situation:'Tôi thường hiểu lý do của người khác trước rồi mới nghĩ tới tác động lên mình.',clarity_need:'what'},other_text:{},responses:{A:[],B:['B5','B7','B9'],C:[],D:[],E:[],F:[],G:[],H:[]}};const fake={status:'dominant_pattern',primary_pattern:{family:'B',statement:'x'},impact:{level:'friction'},adaptive_capacity:{show:true,statement:'adaptive'},future_consequence:{statement:'x'},confidence:'moderate'};const a=microResult(base,structuredClone(fake));const b=microResult({...base,intake:{...base.intake,main_area:'work'},responses:{...base.responses,B:['B1','B2','B3']}},structuredClone(fake));const pass=a._micro_pattern==='B_OVER_UNDERSTAND'&&/tác động lên chính mình|tác động lên mình/.test(a.primary_pattern.statement)&&!a.primary_pattern.statement.includes('tiêu chuẩn của mình hoặc')&&b._micro_pattern==='B_SELF_PRESSURE'&&/tiêu chuẩn/.test(b.primary_pattern.statement);return res.status(pass?200:500).json({version:VERSION,pass,cases:[a,b]});}

export default async function handler(req,res){try{const op=String(req.query?.op||'');if(op==='selftest8313'&&req.method==='GET')return selftest(res);if(op==='analyse'&&req.method==='POST'){const body=parseBody(req);const r=await fetch(UPSTREAM+'/?op=analyse',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const text=await r.text();copyHeaders(r,res);if(!r.ok)return res.status(r.status).send(text);let obj;try{obj=JSON.parse(text)}catch{return res.status(502).json({error:'analysis_unavailable'})}obj=microResult(body,obj);delete obj._micro_pattern;return res.status(200).json(obj);}const r=await upstream(req);const ab=await r.arrayBuffer();copyHeaders(r,res);return res.status(r.status).send(Buffer.from(ab));}catch(e){console.error('v8313_app_error',String(e?.stack||e));return res.status(500).json({error:'preview_unavailable'});}}
