import { getVercelOidcToken } from '@vercel/oidc';

const VERSION='v8.3.12-competence-shadow';
const UPSTREAM='https://quiet-clarity-pattern-signal-check-5lmmmx9te.vercel.app';
const ELIGIBLE=['A','B','C','D','F','G','H'];
const MICRO={
 A1:'delays facing discomfort',A2:'waits to feel better first',A3:'distracts from the feeling',A4:'fixes too quickly before clarity',A5:'notices limits late because tolerance is high',A6:'turns acceptance into resignation',A7:'stays too long because tolerance masks the stopping signal',A8:'stays calm enough to underweight what discomfort is signalling',
 B1:'assumes personal fault first',B2:'holds the self to a stricter standard',B3:'struggles to rest because it never feels enough',B4:'weights mistakes more than what went well',B5:'understands others enough to deprioritise the effect on self',B6:'gives too many chances because reasons are understandable',B7:'delays a boundary to avoid seeming harsh',B8:'reassures or forgives before responsibility is clear',
 C1:'rechecks the past repeatedly',C2:'weights future possibilities without enough evidence',C3:'responds from old data after reality changed',C4:'misses current signals because attention is elsewhere',C5:'lets the immediate issue outweigh the longer view',C6:'lets things unfold instead of preparing when preparation is possible',C7:'lets urgency crowd out other important things',C8:'tracks detail but loses overall direction',
 D1:'knows a reasonable next step but has not begun',D2:'returns to the old way before a change stabilises',D3:'waits for more certainty despite enough evidence for a next step',D4:'prepares or analyses more than acts',D5:'continues mainly because of prior commitment',D6:'finds it hard to stop after investing time effort or money',D7:'keeps doing more when reality calls for pause or review',D8:'holds a plan too tightly after circumstances change',
 F1:'stays in the same viewpoint too long',F2:'gets held in a familiar role such as fixer or responsible one',F3:'blurs personal responsibility with what belongs elsewhere',F4:'gives one factor too much weight',F5:'sees so many perspectives that a personal stance becomes hard to choose',F6:'weights another person’s viewpoint above direct evidence',F7:'keeps seeking perspectives after enough evidence exists',F8:'observes the self from outside enough to underweight direct experience',
 G1:'treats a feared possibility almost as certain',G2:'repeats the same thought without new evidence',G3:'lets rigid must/cannot rules control choices',G4:'trusts a thought more because it repeats',G5:'dismisses a warning too quickly as just a thought',G6:'doubts evidence-based judgement from fear of bias',G7:'rechecks thinking and keeps decisions open',G8:'seeks perfect objectivity and distrusts sufficiently clear observations',
 H1:'choices do not fully reflect what matters',H2:'continues a direction that is becoming less aligned',H3:'allocates time money or energy away from stated priorities',H4:'sacrifices long-term importance to short-term pressure',H5:'applies a value too rigidly',H6:'lets one value crowd out other important values',H7:'protects an old priority after priorities changed',H8:'applies a value so ideally that real-life use becomes impractical'
};
const COMPETENCE={
 vi:{
  A:'Bạn vẫn có khả năng ở lại với sự khó chịu và nhìn thực tế khá rõ; phần shadow nằm ở ngưỡng mà khả năng chịu đựng hoặc giữ bình tĩnh bắt đầu kéo dài hơn mức có ích.',
  B:'Bạn vẫn có khả năng giữ sự tử tế, trách nhiệm và ranh giới; phần shadow nằm ở những lúc sự thấu hiểu hoặc tiêu chuẩn cao nhận thêm trọng lượng trước tác động thực tế lên chính bạn.',
  C:'Bạn vẫn có khả năng phân biệt hiện tại với quá khứ và dự đoán; phần shadow nằm ở những lúc sự chú ý bị giữ quá lâu ở thông tin không còn cần cùng một trọng lượng.',
  D:'Bạn vẫn có khả năng bắt đầu và điều chỉnh khi dữ kiện đã đủ; phần shadow nằm ở những lúc nhu cầu chắc chắn, chuẩn bị thêm hoặc cam kết với hướng cũ giữ hành động chậm hơn điều bạn đã biết.',
  F:'Bạn vẫn có khả năng nhìn nhiều phía và giữ trách nhiệm, giới hạn khá rõ; phần shadow nằm ở những lúc một vai trò quen thuộc hoặc việc cân nhắc thêm góc nhìn bắt đầu nhận quá nhiều trọng lượng.',
  G:'Bạn vẫn có khả năng kiểm chứng suy nghĩ và tin vào nhận định khi dữ kiện đã đủ; phần shadow nằm ở những lúc việc kiểm tra đó kéo dài thêm một vòng và giữ quyết định mở lâu hơn.',
  H:'Bạn vẫn biết khá rõ điều gì quan trọng với mình và có thể linh hoạt cách sống nó; phần shadow nằm ở những lúc một giá trị hoặc ưu tiên nhận quá nhiều trọng lượng so với phần còn lại.'
 },
 en:{
  A:'You can still stay with discomfort and keep a fairly clear view of reality; the shadow appears at the point where tolerance or composure lasts beyond what is useful.',
  B:'You still show kindness, accountability and boundaries; the shadow appears when understanding or high standards receive extra weight before the practical effect on you does.',
  C:'You can still distinguish present evidence from the past and from prediction; the shadow appears when attention stays too long with information that no longer deserves equal weight.',
  D:'You can still begin and adjust when the evidence is sufficient; the shadow appears when the wish for more certainty, more preparation, or loyalty to an existing commitment keeps action behind what you already know.',
  F:'You can still take multiple perspectives while keeping responsibility and limits fairly clear; the shadow appears when a familiar role or continued perspective-taking starts to carry too much weight.',
  G:'You can still test your thinking and trust a judgement when the evidence is sufficient; the shadow appears when checking takes one extra round and keeps a supported decision open longer.',
  H:'You still know what matters and can adapt how you live it; the shadow appears when one value or priority receives more weight than the rest of the value field.'
 }
};
const banned=[/bạn nên/iu,/bạn cần phải/iu,/hãy thử/iu,/nguyên nhân là/iu,/bắt nguồn từ/iu,/you should/iu,/you need to/iu,/the reason is/iu,/this comes from/iu];
function parsed(req){try{return typeof req.body==='string'?JSON.parse(req.body):req.body||{}}catch{return {}}}
function evidence(body){const responses=body.responses||{},scores={};for(const f of ELIGIBLE){const a=Array.isArray(responses[f])?responses[f].map(String):[];scores[f]={adaptive:a.includes(`${f}9`),shadowIds:a.filter(id=>new RegExp(`^${f}[1-8]$`).test(id))};}return {scores,totalShadow:ELIGIBLE.reduce((n,f)=>n+scores[f].shadowIds.length,0)};}
async function baseline(body){const r=await fetch(`${UPSTREAM}/?op=analyse`,{method:'POST',redirect:'manual',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});let payload=null;try{payload=await r.json()}catch{}return {statusCode:r.status,body:payload};}
async function proxy(req,res){let path=String(req.query?.path||'').replace(/^\/+/, '');const q=new URLSearchParams();for(const [k,v] of Object.entries(req.query||{})){if(k==='path')continue;if(Array.isArray(v))v.forEach(x=>q.append(k,String(x)));else if(v!==undefined)q.set(k,String(v));}const url=`${UPSTREAM}/${path}${q.toString()?`?${q}`:''}`;const headers={};if(req.headers?.['content-type'])headers['content-type']=req.headers['content-type'];let body;if(!['GET','HEAD'].includes(req.method||'GET'))body=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});const r=await fetch(url,{method:req.method||'GET',headers,body,redirect:'manual',signal:AbortSignal.timeout(15000)});for(const h of ['content-type','cache-control','location']){const v=r.headers.get(h);if(v)res.setHeader(h,v)}res.setHeader('x-qc-version',VERSION);const buf=Buffer.from(await r.arrayBuffer());return res.status(r.status).send(buf);}
async function token(){if(process.env.AI_GATEWAY_API_KEY)return process.env.AI_GATEWAY_API_KEY;try{return await getVercelOidcToken()}catch{}return process.env.VERCEL_OIDC_TOKEN||null;}
function safe(x,max=800){return typeof x==='string'&&x.trim()&&x.length<=max&&!/[<>\r\n]/.test(x)&&!banned.some(r=>r.test(x));}
async function refine(body,result,e){
 const family=result.primary_pattern?.family;if(!ELIGIBLE.includes(family))throw new Error('invalid_primary_family');
 const shadowIds=e.scores[family].shadowIds;if(!shadowIds.length)throw new Error('primary_without_shadow_evidence');
 const adaptive=e.scores[family].adaptive,lang=body.language==='en'?'en':'vi',gateway=await token();
 if(!gateway){if(adaptive)result.primary_pattern.statement=COMPETENCE[lang][family];return result;}
 const schema={name:'competence_shadow_refinement',strict:true,schema:{type:'object',additionalProperties:false,properties:{statement:{type:'string'},future_consequence:{type:'string'},grounding_ids:{type:'array',items:{type:'string'},minItems:1,maxItems:3}},required:['statement','future_consequence','grounding_ids']}};
 const evidenceList=shadowIds.map(id=>({id,meaning:MICRO[id]}));
 const language=lang==='vi'?'natural Vietnamese':'natural UK English';
 const system=`Refine one already-selected primary pattern for Quiet Clarity. The chosen family is fixed and must not change. The result must create an evidence-earned recognition moment: a person may be strong, self-aware and functional while still carrying a real shadow pattern. Surprise must come from precision, not exaggeration.\n\nIf ADAPTIVE_PRESENT=true, the statement MUST explicitly preserve demonstrated competence and then locate the shadow at the threshold where a strength is overextended, delayed, applied unevenly, or given too much weight. Never write as if the person lacks the whole skill. If ADAPTIVE_PRESENT=false, do not invent competence.\n\nUse 1-3 GROUNDING_IDS only from SELECTED_SHADOW_EVIDENCE. The statement must directly make sense from those signals plus the current situation. Do not infer causes, childhood, trauma, motives, diagnosis, or another person's inner state. No advice or solutions. Keep one current pattern only. Future consequence: exactly one broad conditional downstream consequence if the pattern continues. Use ${language}. Return JSON only.`;
 const user=`FAMILY: ${family}\nADAPTIVE_PRESENT: ${adaptive}\nSELECTED_SHADOW_EVIDENCE: ${JSON.stringify(evidenceList)}\nCURRENT_BASELINE_STATEMENT: ${result.primary_pattern.statement}\nCURRENT_BASELINE_CONSEQUENCE: ${result.future_consequence?.statement||''}\nMAIN_AREA: ${String(body.intake?.main_area||'').slice(0,250)}\nCURRENT_SITUATION: ${String(body.intake?.current_situation||'').slice(0,1600)}\nCLARITY_NEED: ${String(body.intake?.clarity_need||'').slice(0,250)}\nOTHER_TEXT: ${JSON.stringify(body.other_text||{})}`;
 const models=['inclusionai/ling-3.0-flash','openai/gpt-5.6-sol'];let last;
 for(const model of models){try{const r=await fetch('https://ai-gateway.vercel.sh/v1/chat/completions',{method:'POST',signal:AbortSignal.timeout(9000),headers:{'content-type':'application/json','authorization':`Bearer ${gateway}`},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:0.1,max_tokens:500,response_format:{type:'json_schema',json_schema:schema}})});if(!r.ok)throw new Error(`refine_${model}_${r.status}`);const data=await r.json(),obj=JSON.parse(data.choices?.[0]?.message?.content||'{}'),ids=Array.isArray(obj.grounding_ids)?obj.grounding_ids:[];if(!safe(obj.statement)||!safe(obj.future_consequence)||!ids.length||ids.some(id=>!shadowIds.includes(id)))throw new Error('refine_validation_failed');result.primary_pattern.statement=obj.statement;result.future_consequence={statement:obj.future_consequence};return result;}catch(err){last=err;}}
 if(adaptive){result.primary_pattern.statement=COMPETENCE[lang][family];return result;}
 console.warn('v8312_refine_fallback',String(last?.message||last));return result;
}
async function analyseBody(body){const e=evidence(body),base=await baseline(body);if(base.statusCode!==200||!base.body)throw new Error(`baseline_${base.statusCode||500}`);const result=base.body;if(result.status==='dominant_pattern')return refine(body,result,e);if(e.totalShadow>0)throw new Error('shadow_present_but_no_primary_pattern');return {status:'no_dominant_pattern',primary_pattern:null,impact:{level:'light'},adaptive_capacity:{show:false,statement:null},future_consequence:null,confidence:'limited'};}
function versioned(res){const set=res.setHeader.bind(res);res.setHeader=(k,v)=>set(k,String(k).toLowerCase()==='x-qc-version'?VERSION:v);}
function blank(){return {A:[],B:[],C:[],D:[],E:[],F:[],G:[],H:[]};}
function tb(responses,situation,impact={choice_action:2,adjustability:2,spillover:1}){return {language:'vi',responses:{...blank(),...responses},impact,intake:{main_area:'direction',current_situation:situation,clarity_need:'what',other_clarity_need:''},other_text:{}};}
async function selftest(res){const cases=[];const one=await analyseBody(tb({D:['D1','D9']},'Tôi thường xử lý mọi việc khá ổn và biết mình cần làm gì, nhưng có vài quyết định tôi vẫn để chậm hơn dù bước tiếp theo đã khá rõ.'));cases.push({name:'competent_person_still_gets_pattern',pass:one.status==='dominant_pattern'&&one.primary_pattern?.family==='D'&&one.adaptive_capacity?.show===true,result:one});const tie=await analyseBody(tb({A:['A1','A5','A9'],B:['B5','B7','B9'],G:['G2','G7','G9']},'Tôi nhìn chung quyết định khá tốt và giữ được ranh giới, nhưng trước khi chốt một chuyện tôi thường kiểm tra lại suy nghĩ nhiều lần dù dữ kiện đã khá đủ.'));cases.push({name:'strong_tie_still_resolves_one',pass:tie.status==='dominant_pattern'&&Boolean(tie.primary_pattern?.family)&&tie.adaptive_capacity?.show===true,result:tie});const none=await analyseBody(tb({A:['A9'],B:['B9'],C:['C9'],D:['D9'],F:['F9'],G:['G9'],H:['H9']},'Tôi đang vận hành khá ổn.',{choice_action:3,adjustability:0,spillover:3}));cases.push({name:'zero_shadow_cannot_claim_clear_impact',pass:none.status==='no_dominant_pattern'&&none.impact?.level==='light',result:none});return res.status(cases.every(x=>x.pass)?200:500).json({version:VERSION,pass:cases.every(x=>x.pass),cases});}

export default async function handler(req,res){versioned(res);const op=String(req.query?.op||'');if(op==='selftest8312'&&req.method==='GET')return selftest(res);if(op!=='analyse')return proxy(req,res);try{return res.status(200).json(await analyseBody(parsed(req)));}catch(err){console.error('v8312_competence_shadow_error',String(err?.message||err));return res.status(503).json({error:'analysis_unavailable'});}}
