const VERSION='v8.3.12.1-resilient-tie';
const UPSTREAM='https://quiet-clarity-pattern-signal-check-o4hfo48zv.vercel.app';
const ELIGIBLE=['A','B','C','D','F','G','H'];
const COPY={
vi:{
A:{p:'Điều đang nổi bật hơn cả lúc này là xu hướng trì hoãn, chịu đựng hoặc làm nhẹ việc phải đối diện với sự khó chịu, ngay cả khi tình huống đã cần một phản ứng rõ hơn.',c:'Bạn vẫn có khả năng ở lại với sự khó chịu và nhìn thực tế khá rõ; phần shadow nằm ở ngưỡng mà khả năng chịu đựng hoặc giữ bình tĩnh bắt đầu kéo dài hơn mức có ích.',a:'Đồng thời, bạn vẫn cho thấy khả năng ở lại với cảm giác khó chịu mà không hoàn toàn mất đi khả năng nhìn thực tế.',f:'Nếu pattern này tiếp tục, những việc cần được xử lý đúng lúc có thể tiếp tục bị dời đến khi phạm vi lựa chọn thực tế hẹp hơn.'},
B:{p:'Điều đang nổi bật hơn cả lúc này là xu hướng dành nhiều độ rộng cho tiêu chuẩn của mình hoặc cho người khác hơn là cho tác động thực tế đang rơi lên chính bạn.',c:'Bạn vẫn có khả năng giữ sự tử tế, trách nhiệm và ranh giới; phần shadow nằm ở những lúc sự thấu hiểu hoặc tiêu chuẩn cao nhận thêm trọng lượng trước tác động thực tế lên chính bạn.',a:'Đồng thời, bạn vẫn cho thấy khả năng giữ sự tử tế mà không hoàn toàn đánh mất trách nhiệm và ranh giới.',f:'Nếu pattern này tiếp tục, phần tác động lên chính bạn có thể tiếp tục bị đặt sau nhu cầu giữ mọi thứ hợp lý hoặc dễ chấp nhận.'},
C:{p:'Điều đang nổi bật hơn cả lúc này là sự chú ý dễ rời khỏi dữ kiện hiện tại, khiến quá khứ, dự đoán hoặc điều cấp bách nhất thời nhận nhiều trọng lượng hơn mức cần thiết.',c:'Bạn vẫn có khả năng phân biệt hiện tại với quá khứ và dự đoán; phần shadow nằm ở những lúc sự chú ý bị giữ quá lâu ở thông tin không còn cần cùng một trọng lượng.',a:'Đồng thời, bạn vẫn có khả năng phân biệt dữ kiện hiện tại với điều thuộc về quá khứ hoặc dự đoán.',f:'Nếu pattern này tiếp tục, những lựa chọn cần dựa trên dữ kiện hiện tại có thể tiếp tục bị làm chậm hoặc lệch bởi thông tin không còn cùng trọng lượng.'},
D:{p:'Điều đang nổi bật hơn cả lúc này là khoảng cách giữa điều bạn đã biết đủ để bắt đầu và việc thực sự đưa lựa chọn đó thành hành động hoặc điều chỉnh đúng lúc.',c:'Bạn vẫn có khả năng bắt đầu và điều chỉnh khi dữ kiện đã đủ; phần shadow nằm ở những lúc nhu cầu chắc chắn, chuẩn bị thêm hoặc cam kết với hướng cũ giữ hành động chậm hơn điều bạn đã biết.',a:'Đồng thời, bạn vẫn cho thấy khả năng bắt đầu khi bằng chứng đã đủ và điều chỉnh khi thực tế thay đổi.',f:'Nếu pattern này tiếp tục, những cơ hội phụ thuộc vào thời điểm có thể đi qua trước khi một lựa chọn được chốt hoặc điều chỉnh.'},
F:{p:'Điều đang nổi bật hơn cả lúc này là một góc nhìn hoặc vai trò quen thuộc đang giữ quá nhiều trọng lượng, làm những giới hạn và dữ kiện khác khó được đặt ngang hàng.',c:'Bạn vẫn có khả năng nhìn nhiều phía và giữ trách nhiệm, giới hạn khá rõ; phần shadow nằm ở những lúc một vai trò quen thuộc hoặc việc cân nhắc thêm góc nhìn bắt đầu nhận quá nhiều trọng lượng.',a:'Đồng thời, bạn vẫn có khả năng đổi góc nhìn mà không hoàn toàn đánh mất trách nhiệm, giới hạn và dữ kiện.',f:'Nếu pattern này tiếp tục, các quyết định có thể tiếp tục được hình thành từ một phần của bức tranh trong khi những giới hạn quan trọng khác chưa được đặt ngang hàng.'},
G:{p:'Điều đang nổi bật hơn cả lúc này là việc kiểm tra và xem xét lại suy nghĩ đang giữ tình huống mở lâu hơn, ngay cả khi đã có đủ dữ kiện để hình thành một nhận định tạm thời.',c:'Bạn vẫn có khả năng kiểm chứng suy nghĩ và tin vào nhận định khi dữ kiện đã đủ; phần shadow nằm ở những lúc việc kiểm tra đó kéo dài thêm một vòng và giữ quyết định mở lâu hơn.',a:'Đồng thời, bạn vẫn có khả năng xem suy nghĩ như một giả thuyết và tin vào nhận định khi bằng chứng đã đủ.',f:'Nếu pattern này tiếp tục, các quyết định có thể tiếp tục bị giữ mở đủ lâu để làm mất đi tính kịp thời của chúng.'},
H:{p:'Điều đang nổi bật hơn cả lúc này là khoảng cách giữa điều bạn coi trọng và cách thời gian, năng lượng hoặc lựa chọn gần đây đang thực sự được phân bổ.',c:'Bạn vẫn biết khá rõ điều gì quan trọng với mình và có thể linh hoạt cách sống nó; phần shadow nằm ở những lúc một giá trị hoặc ưu tiên nhận quá nhiều trọng lượng so với phần còn lại.',a:'Đồng thời, bạn vẫn cho thấy khả năng giữ điều cốt lõi quan trọng với mình trong khi linh hoạt cách sống nó.',f:'Nếu pattern này tiếp tục, nguồn lực có thể tiếp tục đi theo một hướng khác với điều bạn đang muốn ưu tiên trong thực tế.'}
},
en:{
A:{p:'What stands out most right now is a tendency to delay, tolerate, or soften contact with discomfort even when the situation is already asking for a clearer response.',c:'You can still stay with discomfort and keep a fairly clear view of reality; the shadow appears at the point where tolerance or composure lasts beyond what is useful.',a:'At the same time, you still show some capacity to stay with discomfort without completely losing sight of reality.',f:'If this pattern continues, matters that need timely handling may keep being deferred until the practical range of options becomes narrower.'},
B:{p:'What stands out most right now is a tendency to give more room to your own standards or to other people than to the practical effect the situation is having on you.',c:'You still show kindness, accountability and boundaries; the shadow appears when understanding or high standards receive extra weight before the practical effect on you does.',a:'At the same time, you still show some capacity to remain kind without completely losing accountability and boundaries.',f:'If this pattern continues, the effect on you may keep being placed behind the need to keep things understandable or acceptable.'},
C:{p:'What stands out most right now is attention moving away from present evidence, allowing the past, prediction, or immediate urgency to carry more weight than it needs to.',c:'You can still distinguish present evidence from the past and from prediction; the shadow appears when attention stays too long with information that no longer deserves equal weight.',a:'At the same time, you still show some capacity to distinguish present evidence from the past or from prediction.',f:'If this pattern continues, choices that need to rest on current evidence may keep being delayed or distorted by information that no longer carries the same weight.'},
D:{p:'What stands out most right now is the gap between already knowing enough to begin and actually turning that choice into action or adjusting it in time.',c:'You can still begin and adjust when the evidence is sufficient; the shadow appears when the wish for more certainty, more preparation, or loyalty to an existing commitment keeps action behind what you already know.',a:'At the same time, you still show some capacity to begin when the evidence is sufficient and adjust when reality changes.',f:'If this pattern continues, time-sensitive opportunities may pass before a choice is settled or adjusted.'},
F:{p:'What stands out most right now is a familiar viewpoint or role carrying too much weight, making other limits and evidence harder to hold alongside it.',c:'You can still take multiple perspectives while keeping responsibility and limits fairly clear; the shadow appears when a familiar role or continued perspective-taking starts to carry too much weight.',a:'At the same time, you still show some capacity to shift perspective without completely losing responsibility, limits, and evidence.',f:'If this pattern continues, decisions may keep being formed from only part of the picture while other important limits remain underweighted.'},
G:{p:'What stands out most right now is repeated checking of your thinking keeping the situation open longer even when there is already enough evidence for a provisional judgement.',c:'You can still test your thinking and trust a judgement when the evidence is sufficient; the shadow appears when checking takes one extra round and keeps a supported decision open longer.',a:'At the same time, you still show some capacity to treat thoughts as hypotheses and trust a judgement when the evidence is sufficient.',f:'If this pattern continues, decisions may remain open long enough to lose some of their timeliness.'},
H:{p:'What stands out most right now is a gap between what matters to you and how time, energy, or recent choices are actually being allocated.',c:'You still know what matters and can adapt how you live it; the shadow appears when one value or priority receives more weight than the rest of the value field.',a:'At the same time, you still show some capacity to keep hold of what matters while adapting how you live it in practice.',f:'If this pattern continues, resources may keep moving in a different direction from what you are trying to prioritise in practice.'}
}};
const TERMS={A:['khó chịu','chịu đựng','chấp nhận','bình tĩnh','né','tránh','discomfort','tolerat','accept','calm','avoid'],B:['ranh giới','người khác','trách nhiệm','lỗi','tử tế','cảm thông','boundary','other people','responsib','fault','kind','compassion'],C:['quá khứ','tương lai','dự đoán','hiện tại','cấp bách','past','future','predict','current','urgent'],D:['bắt đầu','hành động','chuẩn bị','chắc chắn','cam kết','đầu tư','kế hoạch','start','action','prepare','certainty','commit','invest','plan'],F:['góc nhìn','vai trò','quan điểm','trách nhiệm của mình','perspective','viewpoint','role','my responsibility'],G:['suy nghĩ','nghĩ','kiểm tra','nhận định','khách quan','thiên vị','quyết định','thinking','thought','check','judgement','objective','bias','decision'],H:['giá trị','ưu tiên','thời gian','năng lượng','tiền bạc','quan trọng','value','priority','time','energy','money','important']};
const BOOST={work:{D:3,H:2,G:1},business:{D:3,H:2,G:1},money:{H:3,D:2,G:1},direction:{H:3,D:2,G:1},romantic:{B:3,F:2,G:1,A:1},family:{B:3,F:2,A:1,G:1},friends:{B:3,F:2,G:1},home:{A:2,D:2,H:2},daily:{A:2,H:2,G:1,C:1},wellbeing:{A:3,G:2,C:1},repeating:{G:2,C:2,D:2,F:1}};
function parse(req){try{return typeof req.body==='string'?JSON.parse(req.body):req.body||{}}catch{return {}}}
function ev(body){const scores={};for(const f of ELIGIBLE){const a=Array.isArray(body.responses?.[f])?body.responses[f].map(String):[];const ids=a.filter(id=>new RegExp(`^${f}[1-8]$`).test(id));scores[f]={n:ids.length,adaptive:a.includes(`${f}9`)};}const ranked=ELIGIBLE.map(f=>({f,n:scores[f].n})).sort((a,b)=>b.n-a.n||ELIGIBLE.indexOf(a.f)-ELIGIBLE.indexOf(b.f));return {scores,ranked,top:ranked[0]?.n||0,total:ranked.reduce((s,x)=>s+x.n,0)};}
function impact(body){const x=body.impact||{},sum=Number(x.choice_action||0)+Number(x.adjustability||0)+Number(x.spillover||0);return sum<=2?'light':sum<=5?'friction':'clear';}
function choose(body,e){const candidates=e.ranked.filter(x=>x.n>=Math.max(1,e.top-1)&&x.n>0).map(x=>x.f),text=[body.intake?.current_situation,body.intake?.other_clarity_need,...Object.values(body.other_text||{})].filter(Boolean).join(' ').toLowerCase(),area=String(body.intake?.main_area||'');let best;for(const f of candidates){let score=e.scores[f].n*10+(BOOST[area]?.[f]||0);for(const t of TERMS[f]||[])if(text.includes(t))score+=3;const z={f,score,n:e.scores[f].n};if(!best||z.score>best.score||z.score===best.score&&z.n>best.n||z.score===best.score&&z.n===best.n&&ELIGIBLE.indexOf(z.f)<ELIGIBLE.indexOf(best.f))best=z;}return best?.f||candidates[0]||null;}
function local(body){const e=ev(body);if(!e.total)return {status:'no_dominant_pattern',primary_pattern:null,impact:{level:'light'},adaptive_capacity:{show:false,statement:null},future_consequence:null,confidence:'limited'};const f=choose(body,e),lang=body.language==='en'?'en':'vi',a=e.scores[f].adaptive,c=COPY[lang][f];return {status:'dominant_pattern',primary_pattern:{family:f,statement:a?c.c:c.p},impact:{level:impact(body)},adaptive_capacity:a?{show:true,statement:c.a}:{show:false,statement:null},future_consequence:{statement:c.f},confidence:e.top>=3?'high':e.top>=2?'moderate':'limited'};}
async function upstreamAnalyse(body){const r=await fetch(`${UPSTREAM}/?op=analyse`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),redirect:'manual',signal:AbortSignal.timeout(20000)});let b=null;try{b=await r.json()}catch{}return {status:r.status,body:b};}
async function analyse(body){let up;try{up=await upstreamAnalyse(body)}catch{}if(up?.status===200&&up.body?.status==='dominant_pattern')return up.body;if(up?.status===200&&up.body?.status==='no_dominant_pattern'&&ev(body).total===0)return {...up.body,impact:{level:'light'},future_consequence:null};if(up?.status&&up.status<500)return up.body||{error:'invalid_payload'};return local(body);}
async function proxy(req,res){let path=String(req.query?.path||'').replace(/^\/+/,''),q=new URLSearchParams();for(const [k,v] of Object.entries(req.query||{})){if(k==='path')continue;if(Array.isArray(v))v.forEach(x=>q.append(k,String(x)));else if(v!==undefined)q.set(k,String(v));}const url=`${UPSTREAM}/${path}${q.toString()?`?${q}`:''}`,headers={};if(req.headers?.['content-type'])headers['content-type']=req.headers['content-type'];let body;if(!['GET','HEAD'].includes(req.method||'GET'))body=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});const r=await fetch(url,{method:req.method||'GET',headers,body,redirect:'manual',signal:AbortSignal.timeout(20000)});for(const h of ['content-type','cache-control','location']){const v=r.headers.get(h);if(v)res.setHeader(h,v)}res.setHeader('x-qc-version',VERSION);return res.status(r.status).send(Buffer.from(await r.arrayBuffer()));}
function blank(){return {A:[],B:[],C:[],D:[],E:[],F:[],G:[],H:[]};}function tb(responses,situation,impactObj={choice_action:2,adjustability:2,spillover:1}){return {language:'vi',responses:{...blank(),...responses},impact:impactObj,intake:{main_area:'direction',current_situation:situation,clarity_need:'what',other_clarity_need:''},other_text:{}};}
async function selftest(res){const cases=[];const one=await analyse(tb({D:['D1','D9']},'Tôi thường xử lý mọi việc khá ổn và biết mình cần làm gì, nhưng có vài quyết định tôi vẫn để chậm hơn dù bước tiếp theo đã khá rõ.'));cases.push({name:'competent_person_still_gets_pattern',pass:one.status==='dominant_pattern'&&one.primary_pattern?.family==='D'&&one.adaptive_capacity?.show===true,result:one});const tie=await analyse(tb({A:['A1','A5','A9'],B:['B5','B7','B9'],G:['G2','G7','G9']},'Tôi nhìn chung quyết định khá tốt và giữ được ranh giới, nhưng trước khi chốt một chuyện tôi thường kiểm tra lại suy nghĩ nhiều lần dù dữ kiện đã khá đủ.'));cases.push({name:'strong_tie_still_resolves_one',pass:tie.status==='dominant_pattern'&&tie.primary_pattern?.family==='G'&&tie.adaptive_capacity?.show===true,result:tie});const none=await analyse(tb({A:['A9'],B:['B9'],C:['C9'],D:['D9'],F:['F9'],G:['G9'],H:['H9']},'Tôi đang vận hành khá ổn.',{choice_action:3,adjustability:0,spillover:3}));cases.push({name:'zero_shadow_cannot_claim_clear_impact',pass:none.status==='no_dominant_pattern'&&none.impact?.level==='light',result:none});return res.status(cases.every(x=>x.pass)?200:500).json({version:VERSION,pass:cases.every(x=>x.pass),cases});}
export default async function handler(req,res){const op=String(req.query?.op||'');if(op==='selftest83121'&&req.method==='GET')return selftest(res);if(op==='analyse'&&req.method==='POST'){try{res.setHeader('x-qc-version',VERSION);return res.status(200).json(await analyse(parse(req)))}catch(e){console.error('v83121_analyse_error',String(e?.message||e));return res.status(503).json({error:'analysis_unavailable'})}}return proxy(req,res);}
