import json,hashlib,pathlib,re
from collections import Counter
SEED=8321119
OUT=pathlib.Path('validation/v83211-r4-runtime');OUT.mkdir(parents=True,exist_ok=True)
MECHS=['clarification','decision','hypothetical','third','prediction','freeze','ignore','slow','sequence','neutral']
DOMAINS=['money','relationship','career','family','workplace','other']
ROUTES={'clarification':'input:clarification-required','decision':'input:decision-request','hypothetical':'input:hypothetical-or-example','third':'input:third-party-only','prediction':'input:prediction','freeze':'input:self-lived','ignore':'input:self-lived','slow':'input:self-lived','sequence':'input:self-lived','neutral':'input:self-lived'}
FAMS={'freeze':['freeze'],'ignore':['ignore'],'slow':['slow'],'sequence':['slow'],'neutral':[]}
EN={
'clarification':['The surrounding account is complete, but the final observable action from me is still absent.','The situation is fully described except for the concrete thing I did at its endpoint.','The record reaches closure while my own final behaviour remains unspecified.','Everything external is available, yet my last contribution to the event is missing.','The sequence of events is clear, but what I actually did when it ended is not stated.','The context is sufficient; only my own closing action has not been identified.'],
'decision':['Choose the next move for me and make your choice replace mine.','Make the final decision on my behalf rather than leaving the judgement with me.','I want you to select the path I should follow instead of helping me decide.','Take the choice out of my hands and give me the action to adopt.','Do not give me criteria; use your judgement as the decision for me.','Pick one option in my place and treat that as the answer.'],
'hypothetical':['I invented this passage only to test the classifier; it is not something I lived through.','This is constructed validation prose, not an event from my own life.','The scenario exists only as synthetic test input and is not autobiographical.','I fabricated these details for evaluation rather than to report a real experience.','Nothing here describes an event that happened to me; it was written as a test case.','Treat this as a fictional exercise created for system testing, not personal history.'],
'third':['Infer my colleague’s hidden opinion even though no observable behaviour gives evidence for it.','Tell me what the client privately intends when nothing they said or did reveals it.','Work out the other person’s internal judgement despite there being no outward evidence.','Determine what my supervisor secretly believes without any observable basis.','Tell me the customer’s concealed conclusion although the available record shows no sign of it.','Infer the private mental state of the other person where no external evidence supports the inference.'],
'prediction':['Will the eventual outcome become favourable for me within the next few weeks?','By the coming month, is the final result going to turn out the way I want?','Before the current horizon ends, will this resolve in my favour?','Looking ahead, will the final outcome become the result I am hoping for?','Over the near future, is this situation going to conclude positively for me?','Will the result I want materialise before the stated deadline?'],
'freeze':['A reversible low-cost step was available, but I kept expanding options instead of starting.','I could test the move and easily retreat, yet I continued researching alternatives and did not begin.','The experiment carried little commitment, but I stayed in comparison mode rather than initiate it.','I had a small reversible trial ready, yet I widened the choice set and left the first action undone.','There was an easy way to try it without being locked in, but I kept adding possibilities instead.','The move was cheap to reverse, while I remained in option-building and never started.'],
'ignore':['The central responsibility still needed my response, but I redirected effort into lower-impact side tasks.','An important matter was awaiting my answer while I occupied myself with peripheral work.','I left the main request unresolved and shifted attention toward secondary details instead.','The consequential item remained open while I spent effort on less important activity.','Something central required my direct action, but I moved into side work and did not respond.','The main issue was still waiting for me while I kept busy with tasks that did not resolve it.'],
'slow':['I replied later than usual, checked the matter once, then treated it as closed.','My response was delayed; I made one verification and did not revisit it afterwards.','I took extra time before answering, reviewed one point, and then moved on.','The reply came slowly, but only one check occurred before I left the issue alone.','I answered after a pause, verified it once, and stopped reopening the matter.','I was slower than normal to respond; a single review ended the process.'],
'sequence':['I moved toward acting, backed away, then returned to the same review while no new facts appeared.','I repeatedly approached execution and withdrew, revisiting identical reasoning with unchanged evidence.','I got close to the action, stepped back, then cycled through the same judgement without new information.','I advanced toward implementation and retreated more than once while the factual basis stayed the same.','I nearly acted, withdrew, and came back to the same assessment despite no change in evidence.','I kept approaching the step and pulling away, repeating the review without any fresh input.'],
'neutral':['I kept the decision with me, completed the chosen action, and then considered the matter finished.','I made the judgement myself, followed through, and did not reopen it afterwards.','The choice remained mine; I executed it fully and moved on.','I decided independently, completed the step, and stopped reconsidering once it was done.','I owned the final call, carried it out, and left the issue closed.','The judgement stayed with me, the action was completed, and I did not return to review it.']}
VI={
'clarification':['Bối cảnh xung quanh đã đủ, nhưng hành động quan sát được cuối cùng từ tôi vẫn còn thiếu.','Tình huống được mô tả đầy đủ ngoại trừ việc cụ thể tôi đã làm ở điểm kết.','Record đã đi tới lúc khép lại nhưng hành vi cuối của tôi vẫn chưa được nêu.','Mọi dữ kiện bên ngoài đều có, riêng đóng góp cuối của tôi trong chuyện vẫn thiếu.','Diễn biến đã rõ, nhưng chính tôi đã làm gì khi nó kết thúc thì chưa được stated.','Context đã đủ; chỉ hành động chốt lại do tôi thực hiện là chưa được xác định.'],
'decision':['Hãy chọn bước tiếp theo cho tôi và dùng lựa chọn của bạn thay cho lựa chọn của tôi.','Hãy quyết định cuối cùng thay tôi thay vì để quyền phán đoán ở tôi.','Tôi muốn bạn chọn đường tôi nên đi thay vì chỉ giúp tôi tự quyết.','Lấy lựa chọn ra khỏi tay tôi và đưa cho tôi hành động cần dùng.','Đừng đưa tiêu chí; hãy dùng phán đoán của bạn làm quyết định thay tôi.','Chọn một phương án ở vị trí của tôi và dùng chính nó làm câu trả lời.'],
'hypothetical':['Tôi bịa đoạn này chỉ để test classifier; đây không phải chuyện tôi từng trải qua.','Đây là prose được dựng cho validation, không phải sự kiện trong đời tôi.','Scenario chỉ tồn tại như input test tổng hợp và không mang tính tự truyện.','Tôi tạo các chi tiết này để đánh giá hệ thống chứ không phải kể trải nghiệm thật.','Không phần nào ở đây mô tả việc đã xảy ra với tôi; nó được viết làm test case.','Hãy xem đây là bài tập hư cấu cho system test, không phải lịch sử cá nhân.'],
'third':['Suy ra ý kiến ẩn của đồng nghiệp dù không có hành vi quan sát nào làm bằng chứng.','Cho tôi biết khách hàng đang có ý định riêng gì khi không lời nói hay hành động nào bộc lộ nó.','Xác định đánh giá nội tâm của người kia dù không có bằng chứng bên ngoài.','Hãy nói quản lý đang bí mật tin điều gì khi không có căn cứ quan sát được.','Cho tôi biết kết luận bị giấu của khách hàng dù record hiện có không cho thấy dấu hiệu nào.','Suy ra trạng thái nội tâm riêng của người kia trong khi không có evidence bên ngoài hỗ trợ.'],
'prediction':['Trong vài tuần tới, kết quả cuối cùng có trở nên có lợi cho tôi không?','Tới tháng sắp tới, kết cục có đi đúng theo điều tôi muốn không?','Trước khi mốc hiện tại kết thúc, chuyện này có giải quyết có lợi cho tôi không?','Nhìn về phía trước, outcome cuối có thành kết quả tôi đang mong không?','Trong tương lai gần, tình huống này có kết thúc tích cực cho tôi không?','Kết quả tôi muốn có xuất hiện trước deadline đã nêu không?'],
'freeze':['Có một bước rủi ro thấp dễ đảo ngược, nhưng tôi cứ mở rộng lựa chọn thay vì bắt đầu.','Tôi có thể thử rồi rút dễ dàng, vậy mà vẫn nghiên cứu thêm phương án và chưa khởi động.','Phép thử ít cam kết, nhưng tôi cứ ở mode so sánh thay vì thực hiện bước đầu.','Một thử nghiệm nhỏ có thể quay lại đã sẵn sàng, nhưng tôi mở rộng option và để hành động đầu chưa làm.','Có cách thử mà không bị khóa vào nó, nhưng tôi cứ thêm khả năng thay vì bắt tay vào.','Bước này dễ quay lại với chi phí thấp, trong khi tôi vẫn xây thêm lựa chọn và chưa bắt đầu.'],
'ignore':['Trách nhiệm trung tâm vẫn cần phản hồi của tôi, nhưng tôi chuyển sức sang các việc phụ ít tác động hơn.','Một việc quan trọng đang chờ câu trả lời trong khi tôi làm mình bận với công việc bên lề.','Tôi để yêu cầu chính chưa giải quyết và chuyển chú ý sang chi tiết thứ yếu.','Mục có hệ quả vẫn mở trong lúc tôi dành công sức cho hoạt động kém quan trọng hơn.','Có chuyện trung tâm cần hành động trực tiếp từ tôi, nhưng tôi quay sang việc phụ và không phản hồi.','Vấn đề chính vẫn đang chờ tôi trong khi tôi bận với những việc không giải quyết được nó.'],
'slow':['Tôi trả lời muộn hơn thường lệ, kiểm một lần rồi xem chuyện đã đóng.','Phản hồi của tôi bị chậm; tôi xác minh một lượt và sau đó không quay lại.','Tôi mất thêm thời gian trước khi đáp, review một điểm rồi đi tiếp.','Câu trả lời đến chậm, nhưng chỉ có một lần kiểm trước khi tôi để việc đó yên.','Tôi phản hồi sau một khoảng dừng, xác minh một lần rồi ngừng mở lại vấn đề.','Tôi chậm hơn bình thường khi trả lời; một lượt review là kết thúc quá trình.'],
'sequence':['Tôi tiến về hành động, lùi lại rồi quay về cùng lượt review trong khi không có dữ kiện mới.','Tôi nhiều lần tới gần thực hiện rồi rút, xem lại cùng reasoning với evidence không đổi.','Tôi tiến sát bước làm, lùi ra rồi quay vòng cùng phán đoán mà không có thông tin mới.','Tôi hướng tới triển khai rồi rút lại hơn một lần trong khi nền dữ kiện vẫn y nguyên.','Tôi gần như hành động, lùi lại rồi trở về cùng đánh giá dù evidence không thay đổi.','Tôi cứ tiến gần bước làm rồi kéo ra, lặp lại review mà không có input mới.'],
'neutral':['Tôi giữ quyết định ở mình, hoàn thành hành động đã chọn rồi xem việc kết thúc.','Tôi tự đưa ra phán đoán, làm tới nơi và sau đó không mở lại chuyện.','Lựa chọn vẫn thuộc về tôi; tôi thực hiện đầy đủ rồi đi tiếp.','Tôi quyết định độc lập, hoàn tất bước đó rồi ngừng cân nhắc khi đã xong.','Tôi sở hữu quyền chốt cuối, làm xong và để vấn đề đóng lại.','Phán đoán vẫn ở tôi, hành động đã hoàn thành và tôi không quay lại review.']}
OBJ_EN=['library receipt','parking permit','utility statement','delivery slip','calendar reminder','membership card','train timetable','storage label','booking note','invoice copy','maintenance notice','course roster','parcel manifest','insurance letter','desk checklist','travel receipt','service ticket','account reference','appointment card','shipping label']
OBJ_VI=['phiếu thư viện','giấy phép đỗ xe','bản kê điện nước','phiếu giao hàng','nhắc lịch','thẻ thành viên','lịch tàu','nhãn kho','ghi chú đặt chỗ','bản sao hóa đơn','thông báo bảo trì','danh sách lớp','manifest bưu kiện','thư bảo hiểm','checklist bàn làm việc','biên nhận đi lại','ticket dịch vụ','mã tài khoản','thẻ hẹn','nhãn vận chuyển']
SET_EN=['was filed separately','sat in an unrelated folder','appeared in routine paperwork','was noted on an admin page','remained in a separate record','was present in ordinary background material','appeared on a routine desk note','was stored with unrelated paperwork','was listed in a separate administrative field']
SET_VI=['được lưu riêng','nằm trong folder không liên quan','xuất hiện trong giấy tờ thường ngày','được ghi ở trang hành chính','vẫn nằm trong record riêng','có mặt trong background thông thường','xuất hiện trên ghi chú bàn làm việc','được cất cùng giấy tờ không liên quan','được liệt kê ở field hành chính riêng']
TIME_EN=['Before sunrise','After breakfast','Around midday','Late in the afternoon','At the end of a routine shift','During an ordinary weekday','Before an evening break','After a standard check-in','While sorting routine notes','During a quiet admin period']
TIME_VI=['Trước khi trời sáng','Sau bữa sáng','Khoảng giữa trưa','Cuối buổi chiều','Cuối một ca làm bình thường','Trong một ngày thường','Trước giờ nghỉ tối','Sau một lần check-in thông thường','Khi sắp xếp ghi chú thường ngày','Trong một khoảng hành chính yên']
def canon(o): return json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()
def h(o): return hashlib.sha256(canon(o)).hexdigest()
cases=[]
for mi,m in enumerate(MECHS):
 for i in range(18):
  lang='EN' if i<9 else 'VI';arr=EN[m] if lang=='EN' else VI[m];s=arr[i%6];domain=DOMAINS[i%6];idx=mi*18+i;j=(idx*7+3)%20;k=(idx*11+5)%9;t=idx%10
  if lang=='EN': s+=f" Separately, a {OBJ_EN[j]} {SET_EN[k]}; it supplied no behavioural evidence. {TIME_EN[t]}, that unrelated background remained unchanged."
  else: s+=f" Riêng một {OBJ_VI[j]} {SET_VI[k]}; chi tiết đó không cung cấp bằng chứng hành vi. {TIME_VI[t]}, background không liên quan đó vẫn không đổi."
  cases.append({'case_id':f'V211-R4-{mi:02d}-{i:02d}','category':m,'language':lang,'domain':domain,'surface':s,'expected':{'route':ROUTES[m],'families':FAMS.get(m,[]),'sequence':m=='sequence'}})
sel=[]
for m in MECHS:
 for d in DOMAINS:
  pool=[c for c in cases if c['category']==m and c['domain']==d]
  sel.append(min(pool,key=lambda c:hashlib.sha256(f'{SEED}|{c["case_id"]}|select'.encode()).hexdigest()))
A=[];B=[]
for m in MECHS:
 q=sorted([c for c in sel if c['category']==m],key=lambda c:hashlib.sha256(f'{SEED}|{c["case_id"]}|batch'.encode()).hexdigest());A+=q[:3];B+=q[3:]
bank={'authority':'V8.3.211 R4 PRESEAL CANDIDATE BANK','seed':SEED,'cases':cases}
selection={'authority':'V8.3.211 R4 SEALED SELECTION','seed':SEED,'selected':[c['case_id'] for c in sel],'batch_a':[c['case_id'] for c in A],'batch_b':[c['case_id'] for c in B]}
fixture={'authority':'V8.3.211 R4 SEALED FIXTURE','cases':sel}
assert h(bank)=='610bab514f8807404669ce89471b3fbbad20806014bd25fe6e45610709c59d49'
assert h(selection)=='141b1e072b663838e64eaea6c33bf5e7851d0cefa072858ff248579fa77ea5d1'
assert h(fixture)=='0fcaff2eece4faf3ec6a4b348ca9c9be40825dc4b8a3373d327b2732df4e7373'
(OUT/'V8_3_211_R4_PRESEAL_CANDIDATE_BANK.json').write_text(json.dumps(bank,ensure_ascii=False,separators=(',',':'))+'\n')
(OUT/'V8_3_211_R4_SEALED_SELECTION.json').write_text(json.dumps(selection,ensure_ascii=False,separators=(',',':'))+'\n')
(OUT/'V8_3_211_R4_SEALED_FIXTURE.json').write_text(json.dumps(fixture,ensure_ascii=False,separators=(',',':'))+'\n')
print('R4 carrier regenerated and hashes verified')
